### ISSUE TITLE
Align JDK packages

### ISSUE THREAD

**Issue by taku0** [NixOS/nixpkgs#106716]
We have several JDK packages with slightly different features and library dependencies. We should align them and review the library dependencies.

## Package Features

|                                                       | `openjdk`        | `adoptopenjdk-bin`   | `zulu`       | `graalvm11-ce` |
|-------------------------------------------------------|------------------|----------------------|--------------|----------------|
| has `jre` output (\*1)                                | 8 only           | yes (via `passthru`) | no           | no             |
| exports `passthru.home` (\*2)                         | yes              | yes                  | yes          | yes            |
| sets `JAVA_HOME`                                      | yes              | yes                  | yes          | yes            |
| sets `ClASSPATH`                                      | yes              | no                   | no           | yes            |
| runs Swing app (\*3)                                  | yes              | yes                  | no           | no             |
| supports GTK+ Look and Feel (\*4)                     | yes              | no                   | no           | no             |
| has `demo` folder                                     | no               | no                   | yes          | no             |
| has broken japanese man pages (\*5)                   | no               | no                   | yes          | no             |
| has man pages                                         | yes              | yes                  | yes          | no             |
| has `include/jni_md.h` (not `include/linux/jni_md.h`) | yes              | no                   | no           | no             |
| uses `autoPatchelfHook`                               | (source package) | yes                  | no           | no             |
| runs JavaFX apps                                      | no               | (not tested)         | (not tested) | (not tested)   |

- \*1: `nix-instantiate --eval -E '"${(import <nixpkgs> {}).openjdk.jre}"'`
- \*2: `nix-instantiate --eval -E '"${(import <nixpkgs> {}).openjdk.home}"'`
- \*3: `java -jar zulu/demo/jfc/SwingSet2/SwingSet2.jar`
- \*4: `java -jar zulu/demo/jfc/SwingSet2/SwingSet2.jar` → `Look & Feel` → `GTK Style Look & Feel`
- \*5: `share/man/ja_JP.UTF-8` or `lib/man/ja_JP.UTF-8`

Aligning with `openjdk` package would be reasonable.

## Library Dependencies

Many libraries are optional and loaded lazily if available.

|                  | `openjdk` | `adoptopenjdk-bin` | `zulu` | `graalvm11-ce` | CentOS 8 `java-11-openjdk` (\*6) (for reference) |
|------------------|-----------|--------------------|--------|----------------|--------------------------------------------|
| `GConf`          | yes       | no                 | no     | no             | no                                         |
| `alsaLib`        | yes       | yes                | yes    | no             | yes                                        |
| `atk`            | no        | no                 | yes    | no             | no                                         |
| `cairo`          | no        | no                 | yes    | no             | no                                         |
| `cups`           | yes       | no                 | yes    | no             | yes                                        |
| `ffmpeg_3`       | no        | no                 | yes    | no             | no                                         |
| `fontconfig`     | yes       | yes                | yes    | no             | yes                                        |
| `freetype`       | yes       | yes                | yes    | no             | yes                                        |
| `gdk-pixbuf`     | no        | no                 | yes    | no             | no                                         |
| `giflib`         | yes       | no                 | no     | no             | yes                                        |
| `glib`           | yes       | no                 | yes    | no             | no                                         |
| `gnome_vfs`      | yes       | no                 | no     | no             | no                                         |
| `gtk2`           | no        | no                 | yes    | no             | no                                         |
| `gtk3`           | yes       | no                 | no     | no             | no                                         |
| `lcms2`          | yes       | no                 | no     | no             | yes                                        |
| `libXcomposite`  | no        | no                 | no     | no             | yes                                        |
| `libGL`          | no        | no                 | yes    | no             | no                                         |
| `libICE`         | yes       | yes                | no     | no             | no                                         |
| `libX11`         | yes       | yes                | no     | no             | yes                                        |
| `libXcursor`     | yes       | no                 | yes    | no             | no                                         |
| `libXext`        | yes       | yes                | yes    | no             | yes                                        |
| `libXi`          | yes       | yes                | yes    | no             | yes                                        |
| `libXinerama`    | yes       | no                 | no     | no             | no                                         |
| `libXp`          | no        | no                 | yes    | no             | no                                         |
| `libXrandr`      | yes       | no                 | no     | no             | no                                         |
| `libXrender`     | yes       | yes                | yes    | no             | yes                                        |
| `libXt`          | yes       | no                 | yes    | no             | no                                         |
| `libXtst`        | yes       | yes                | yes    | no             | yes                                        |
| `libXxf86vm`     | no        | no                 | yes    | no             | no                                         |
| `libav_0_8`      | no        | no                 | yes    | no             | no                                         |
| `libjpeg`        | yes       | no                 | no     | no             | yes                                        |
| `libpng`         | yes       | no                 | no     | no             | yes                                        |
| `libxml2`        | no        | no                 | yes    | no             | no                                         |
| `libxslt`        | no        | no                 | yes    | no             | no                                         |
| `pango`          | no        | no                 | yes    | no             | no                                         |
| `stdenv.cc.cc`   | no        | no                 | yes    | no             | yes? (`libstdc++.so`)                      |
| `stdenv.cc.libc` | no        | no                 | yes    | yes            | yes                                        |
| `zlib`           | yes       | yes                | yes    | yes            | yes                                        |

- \*6:
  - https://centos.pkgs.org/8/centos-appstream-x86_64/java-11-openjdk-11.0.9.11-0.el8_2.x86_64.rpm.html
  - https://centos.pkgs.org/8/centos-appstream-x86_64/java-11-openjdk-headless-11.0.9.11-0.el8_2.x86_64.rpm.html

### Library Usage

- `GConf`: used to read proxy settings if GSettings is not available: 
  - [Networking Properties](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/doc-files/net-properties.html)
  - [`DefaultProxySelector.c`](https://github.com/openjdk/jdk11u/blob/master/src/java.base/unix/native/libnet/DefaultProxySelector.c)
  - [`DefaultProxySelector.java`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.base/share/classes/sun/net/spi/DefaultProxySelector.java)
- `glib`: used to read proxy settings. Also used by GTK+ 2/3.
  - [`gtk3_interface.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/gtk3_interface.c)
- `cairo`: used by GTK+ 3
  - [`gtk3_interface.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/gtk3_interface.c)
- `cups`: used by AWT:
  - [`CUPSfuncs.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/common/awt/CUPSfuncs.c)
- `ffmpeg_3`: not used?
- `gdk-pixbuf`: not used?
- `gnome_vfs`: not used anymore:
  - [8129633: (fs) Investigate removing the GNOME-based FileTypeDetector from the Linux and Solaris implementations](https://github.com/openjdk/jdk11u/commit/ba6e733ede28533b3775dbe578e85c81f6445e6d)
- `lcms2`: bundled?
- `libXcomposite`: used by `java.awt.Robot`:
  - [`awt_Robot.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/awt_Robot.c)
- `libGL`: used by Java2D
  - [`GLXGraphicsConfig.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/common/java2d/opengl/GLXGraphicsConfig.c)
  - [`OGLFuncs_md.h`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/common/java2d/opengl/OGLFuncs_md.h)
- `libICE`: not used? Noted in [building.md](https://github.com/openjdk/jdk11u/blob/2b4cfd277663f68a8d3d0c120eaf7afc0d7613dc/doc/building.md). 
- `libXcursor`: not used?
- `libXinerama`: used by AWT:
  - [`awt_GraphicsEnv.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/awt_GraphicsEnv.c)
- `libXp`: not used?
- `libXrandr`: used by AWT:
  - [`awt_GraphicsEnv.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/awt_GraphicsEnv.c)
- `libXrender`: used by AWT:
  - [`awt_GraphicsEnv.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/awt_GraphicsEnv.c)
- `libXt`: not used?
- `libXxf86vm`: not used?
- `libav_0_8`: not used?
- `libxml2`: not used?
- `libxslt`: not uesd?
- `pango`: used indirectly?
  - [`gtk3_interface.c`](https://github.com/openjdk/jdk11u/blob/727ddb06fd780ecba80dd31db0700a0005ffedda/src/java.desktop/unix/native/libawt_xawt/awt/gtk3_interface.c)

Should we drop dependencies with GNOME 2 libraries like `GConf` and `gnome_vfs`? Related: #73407, #73246.

Does anyone know about those libraries marked as "not used?"?

## TODO

- [ ] Set `CLASSPATH` in `adoptopenjdk-bin` and `zulu`.
- [ ] Add libraries to run Swing app for `zulu` and `graalvm11-ce`.
- [ ] Add libraries to suuport GTK+ Look and Feel for `adoptopenjdk-bin`, `zulu`, and `graalvm11-ce`.
- [ ] Remove `demo` folder from `zulu`.
- [ ] Remove broken man pages from `zulu`.
- [ ] Add man pages to `graalvm11-ce` (can we do this?).
- [ ] Link `jni_md.h` to `include` folder.
- [ ] Remove unused libraries from `openjdk`.
- [ ] Support JavaFX.
- [ ] Test with Eclipse, InteliJ IDEA, and NetBeans.
- [ ] Test with network servers (Tomcat or something else).

**Comment by gebner** [comment]
> runs JavaFX apps	 no

openjdk versions >= 11 support javafx (just tried with openjdk14).

**Comment by taku0** [comment]
@gebner yes it runs simple JavaFX apps but it fails with `MediaPlayer`.  I have updated the table.

**Comment by taku0** [comment]
I have found that `pkgs/development/compilers/openjdk/darwin` is actually Zulu binary distribution. We should unify them.

Note: we don't need `ZuluJCEPolicies.zip` anymore.
https://docs.azul.com/zulu/zulurelnotes-archive/ZuluReleaseNotes/RunningZulu.htm

**Comment by Gaelan** [comment]
Actually, why do we even have so many JDK builds in the first place? Aren't they just all builds of the same source? What advantage do the third-party binaries have over the normal Nix-built ones?

**Comment by jerith666** [comment]
I think one of the chief advantages is that the zulu (Azul) binaries have passed [the JCK](https://openjdk.java.net/groups/conformance/JckAccess/) (aka the TCK), which the builds from source in nixpkgs have not.  My understanding (from brief slack conversations w/ AdoptOpenJDK contributors) is that those tests are, on occasion, sensitive to compiler flags etc.  (Though note that at the moment, AdoptOpenJDK [does not have access to the JCK](https://adoptopenjdk.net/quality.html).)

So it's possible in principle that the nix expressions for openjdk might have those things wrong and thus be producing JDK binaries that would not pass the JCK.

That said, I've been using nix builds of openjdk for several years in my development environment and never encountered a problem; I would feel safe recommending that my employer use nix openjdk builds in production, though for various reasons we don't do that now.

**Comment by taku0** [comment]
In general (not limited to OpenJDK), binary packages tend to be updated with less problems.  When a new version is released, we may delay several weeks or months to update source packages.

**Comment by taku0** [comment]
#107784 is merged :tada:. Now we can run AWS/Swing apps with Zulu and GraalVM.

**Comment by taku0** [comment]
#106737 is merged :tada:.

**Comment by taku0** [comment]
#110567 has been merged :tada:.
