### ISSUE TITLE
Meta issue for zoom-us

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nixpkgs#107495]
## Issue description

- [ ] Outdated: https://github.com/NixOS/nixpkgs/pull/105979
- [ ] Segfaults when launching a file explorer: [`6fcf95e` (#105979)](https://github.com/NixOS/nixpkgs/pull/105979/commits/6fcf95efff9530dcc3ee6dc0527d46e4561cfd22)
- [x] Update script fix [`0e3e969` (#105979)](https://github.com/NixOS/nixpkgs/pull/105979/commits/0e3e96926ad40292a7aa936458f77ea0f8fe1e08)
- [ ] Possible workaround for gnome / wayland screen sharing? https://github.com/NixOS/nixpkgs/issues/107233
- [ ] Pulseaudio sinks switch https://github.com/NixOS/nixpkgs/issues/80042
- [ ] SSO sign in https://github.com/NixOS/nixpkgs/issues/73532
- [ ] Doesn't work on non nixos? https://github.com/NixOS/nixpkgs/issues/94958
- [ ] Latest versions don't work at all due to opengl related issues a bit like the above and like in https://github.com/NixOS/nixpkgs/issues/52498 and similar to what I experience when I try to update it in https://github.com/NixOS/nixpkgs/pull/105979 .
- [ ] Wrong Qt version used? Upstream's bundled qt libraries seem like they intend it to be used with qt5.12.9 which is updated from 5.12.7 at https://github.com/NixOS/nixpkgs/pull/107483 .

Ccing everyone involved in all issues mentioned above who use Zoom and might be able to help.

@tadfisher @danbst @lambdafu @3noch @romildo @worldofpeace @lovesegfault @mkg20001 @kennyballou @samuela @katsar0v @knarrff @ConnorNovak @felixgolcher @svalaskevicius @eethann @jameysharp .

**Comment by tadfisher** [comment]
Re: Qt version, we should link against the version of qt5 in nixpkgs as Qt is ABI-compatible within major versions. I believe that if there are issues with using Qt from nixpkgs, we should identify and fix them, as there is no fundamental reason why our Qt shouldn't work beyond us breaking something with patches.

**Comment by doronbehar** [comment]
What's most bothering is that there is not much of a difference between the tarball of the working derivation i.e the previous version and the next:

```
[A]=/home/doron/downloads/zoom-working
[B]=/home/doron/downloads/zoom-latest
Usage:   <Enter>/'o'=open,'s'=sync,'q'=quit
Options: 'u'=update,'x'=set excludes,'i'=set ignore,'a'=set args, 'h'=hex mode, 'w'=wrap mode
Diff Args: -r --brief

    Files [A]/translations/de.qm and [B]/translations/de.qm differ
    Files [A]/translations/es.qm and [B]/translations/es.qm differ
    Files [A]/translations/fr.qm and [B]/translations/fr.qm differ
    Files [A]/translations/it.qm and [B]/translations/it.qm differ
    Files [A]/translations/jp.qm and [B]/translations/jp.qm differ
    Files [A]/translations/ko.qm and [B]/translations/ko.qm differ
    Files [A]/translations/ptg.qm and [B]/translations/ptg.qm differ
    Files [A]/translations/ru.qm and [B]/translations/ru.qm differ
    Files [A]/translations/vi.qm and [B]/translations/vi.qm differ
    Files [A]/translations/zh_CN.qm and [B]/translations/zh_CN.qm differ
    Files [A]/translations/zh_TW.qm and [B]/translations/zh_TW.qm differ
==> Files [A]/version.txt and [B]/version.txt differ
    Files [A]/zoom and [B]/zoom differ
    Files [A]/ZoomLauncher and [B]/ZoomLauncher differ
    Only in [A]: config-dump.sh
    Only in [A]: libQt5WaylandCompositor.so
    Only in [A]: libQt5WaylandCompositor.so.5
    Only in [A]: libQt5WaylandCompositor.so.5.12
    Only in [A]: libQt5WaylandCompositor.so.5.12.9
    Only in [A]: zcacert.pem
    Only in [A]: zoom.sh
    Only in [B]: all-libs-for-main-files.txt
    Only in [B]: libfdkaac2.so
    Only in [B]: libQt5QuickControls2.so
    Only in [B]: libQt5QuickControls2.so.5
    Only in [B]: libQt5QuickControls2.so.5.12
    Only in [B]: libQt5QuickControls2.so.5.12.9
    Only in [B]: libQt5QuickTemplates2.so
    Only in [B]: libQt5QuickTemplates2.so.5
    Only in [B]: libQt5QuickTemplates2.so.5.12
    Only in [B]: libQt5QuickTemplates2.so.5.12.9
```

**Comment by 3noch** [comment]
Zoom and Zoom Launcher differ. That sounds significant to me.

**Comment by lovesegfault** [comment]
I've found that I need to force `QT_QPA_PLATFORM=xcb` for zoom to run at all now.

**Comment by doronbehar** [comment]
> I've found that I need to force `QT_QPA_PLATFORM=xcb` for zoom to run at all now.

@lovesegfault is it possible that you have (by default) `QT_QPA_PLATFORM` set to `wayland`? I don't experience this issue with the version of zoom-us that's currently in nixpkgs.

**Comment by felixgolcher** [comment]
(That might be not very specific and helpful, but a lot of the above reminds me of problems I experienced these days with RStudio. Those, in the end, where rooted in the boost library, version 1.75)

**Comment by yorickvP** [comment]
I can confirm that it works better with `QT_QPA_PLATFORM=xcb`, now I have a bigger list of wayland bugs:
- segfault on connect
- right click context menu's don't close
- window management issues (welcome window on top of call window, fullscreening failures)

**Comment by Mic92** [comment]
I was able to run it by not providing qt libaries but just their dependencies. See https://github.com/Mic92/nix-ld/blob/main/examples/zoom.nix

**Comment by miniBill** [comment]
zoom-5.4.57862.0110 shows an empty "Participants" list, it used to work on zoom-us-5.3.469451.0927

**Comment by doronbehar** [comment]
> zoom-5.4.57862.0110 shows an empty "Participants" list, it instead works in zoom-us-5.3.469451.0927

I don't experience the issue, just checked. Using Gnome here with xorg.

**Comment by miniBill** [comment]
KDE with xorg, might it be a theme issue?

**Comment by doronbehar** [comment]
> KDE with xorg, might it be a theme issue?

Could be Could you share a screenshot?

**Comment by miniBill** [comment]
![image](https://user-images.githubusercontent.com/191825/105383874-e02a4c80-5c11-11eb-9aa9-488aa78344de.png)

**Comment by Mic92** [comment]
> ![image](https://user-images.githubusercontent.com/191825/105383874-e02a4c80-5c11-11eb-9aa9-488aa78344de.png)

To narrow the problem down. Does the issue also appear if you do?

```
nix-shell --pure -p zoom-us --run zoom-us
```

In a pure nix-shell you won't be able to do SSL unless you also unset `SSL_CERT_FILE` and `NIX_SSL_CERT_FILE`: https://github.com/nix-community/nix-direnv/blob/dff7b0bfe9028378dfbe4043c328418d5242b92e/direnvrc#L31

**Comment by miniBill** [comment]
Using a pure shell [unsetting `SSL_CERT_FILE` and `NIX_SSL_CERT_FILE` before running zoom-us] did indeed fix it

**Comment by Mic92** [comment]
> Using a `--pure` `nix-shell` [and unsetting `SSL_CERT_FILE` and `NIX_SSL_CERT_FILE` before running `zoom-us`] did indeed make it show correctly

Ok now you can check the output of `env` until unset stuff until it no longer breaks.

**Comment by brcha** [comment]
On my system (under KDE, NixOS 20.09) zoom doesn't show the main window at all. But, it works in --pure shell, and I managed to make it work by unsetting QML2_IMPORT_PATH. Perhaps unsetting that in the wrapper would fix zoom.

**Comment by yorickvP** [comment]
Still relevant

**Comment by adam248** [comment]
I believe this is not stale.

Also, emojis are not working. It seems to try to download it separately while running the app.

**Comment by sdht0** [comment]
I'm getting the following errors when starting Zoom:
```
Can't loadsdh/.config/zoomus.conf
sh: line 1: pactl: command not found                                                                                                                                                                                                                                                                                           
[1017/132356.504977:ERROR:context.cc(151)] The cache_path directory (/nix/store/h7aqjplx1xgac9821zgmkmjgdp5h1ka1-zoom-5.16.1.8561/opt/zoom/sdh/.zoom/data/cefcache) could not be created.
```

Sigin and basic calls still work. However, screen sharing gives an error: pulseaudio required. Also, signin state and presumably other settings are not being saved since it can't find my home folder.

Anyone knows what's up?
