### ISSUE TITLE
Remove wlroots_0_12 (tracking issue)

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#118838]
We've temporarily introduced `wlroots_0_12` as part of #116544 to avoid breaking some reverse dependencies. The affected attributes should switch to `wlroots` when possible (usually a new upstream release). There's no hurry but let's use this issue to track the current progress.

`wlroots_0_12`:
- [ ] phoc #151519
- [x] cage (https://github.com/Hjdskes/cage/pull/174): #119615
- [x] hikari (https://hub.darcs.net/raichoo/hikari/patch/43e289a3d2974c2347c65ae2a0882892e687e93f and https://hub.darcs.net/raichoo/hikari/patch/736754fcf88bebcabb5dccb2801cb384dbc7588d): #120985
- [x] waybox (https://github.com/wizbright/waybox/commit/309ccd2faf08079e698104b19eff32b3a255b947): #123013
- [x] wayfire (supported since https://github.com/WayfireWM/wayfire/commit/b377906b8fd7f01d482db88cfb06a81c3ebe66a7): #121110
- [x] wio (~~nothing so far~~, turns out the pending patches on the ML should fix the build with wlroots 0.13): #123014
- [x] cagebreak (https://github.com/project-repo/cagebreak/commit/b989fe50f08d77245b73790f52ea2cc730b94b4e and additional commits): ~~#119963~~ #121652 (~~TODO: Fix VM test~~)

`wlroots_0_13`:
- [x] sway: #128036
- [x] hikari (downstream patches: https://cgit.freebsd.org/ports/diff/x11-wm/hikari/files/patch-wlroots-0.14?id=f2820b6cc2170feef17989c422f2cf46644a5b57): #128122
- [x] wio (https://git.sr.ht/~primeos/wio/commit/9d5093c019f6966b8ee0dba1da3361a761d04bcc, send via git-send-email to @AndersonTorres, https://github.com/primeos/nixpkgs/commit/68acf441853f95cc148c0bef7e7b1da5e7025f8c): #128220

**Comment by Synthetica9** [comment]
cage: https://github.com/Hjdskes/cage/pull/174 was just merged, do we want to:

1. Wait until a next release
2. Patch it using the now-merged patch
3. Use the latest version from master

**Comment by primeos** [comment]
I think waiting for the next release is the best option for now (we're in no hurry). For some other packages that are already based on commits instead of releases there's no need to wait if the package maintainers deem a newer version stable (in that case I'd leave it up to the package maintainers).

**Comment by Synthetica9** [comment]
https://github.com/NixOS/nixpkgs/pull/119615

**Comment by Synthetica9** [comment]
https://github.com/project-repo/cagebreak/releases/tag/1.7.0

**Comment by Synthetica9** [comment]
https://github.com/NixOS/nixpkgs/pull/119963

**Comment by Synthetica9** [comment]
https://github.com/NixOS/nixpkgs/pull/120985

**Comment by alyssais** [comment]
https://github.com/NixOS/nixpkgs/pull/121110

**Comment by Synthetica9** [comment]
https://github.com/NixOS/nixpkgs/pull/121652

(kinda flew under the radar for me, but it happened!)

**Comment by Synthetica9** [comment]
Don't we want to split this issue up per version? It seems like we're always gonna have a handful of wlroots versions around, would be nice if we could close those issues individually instead of having one perpetually open issue

**Comment by primeos** [comment]
I thought about that too but I was hoping we can close this before the next wlroots release. `phoc` is the main blocker, `wlroots_0_13` should be fairly easy to drop (I'm waiting for `hikari` patches and, if necessary, I might be able to patch `wio` again but I might also mark it as broken instead (until there's a maintained fork) as I don't intend to do that every release).

**Comment by AndersonTorres** [comment]
I have merely made a new fork outside SourceHut, but me myself do not plan to maintain it alone.

**Comment by primeos** [comment]
@AndersonTorres in that case we should eventually drop it from Nixpkgs, at least IMO. I had some time yesterday so I've sent you a patch for wlroots 0.14 (https://git.sr.ht/~primeos/wio/commit/9d5093c019f6966b8ee0dba1da3361a761d04bcc, tested with https://github.com/primeos/nixpkgs/commit/68acf441853f95cc148c0bef7e7b1da5e7025f8c).

**Comment by AndersonTorres** [comment]
I will mark it as broken for now.

**Comment by AndersonTorres** [comment]
I have patched it!

**Comment by zhaofengli** [comment]
Phoc 0.11.0 was released targeting wlroots 0.14.0 (#151519), so this can finally be closed.
