### ISSUE TITLE
Tracking Issue: transfer essential repositories to haskellPackages infra to the NixOS organisation

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#125980]
There are a few haskell packages released on hackage and being managed in GitHub repositories in @peti's account which are tightly coupled with `cabal2nix` and/or the haskell infrastructure in nixpkgs. Future development for our haskell infrastructure in nixpkgs will require touching those repositories and releasing new versions to hackage. Such changes would be implementing changes to the package set generation (<https://github.com/NixOS/cabal2nix/issues/499>, <https://github.com/NixOS/cabal2nix/issues/497>) or adding a new platform (like `aarch64-darwin` in the near future).

The repos in question are (feel free to add any I've missed):

* [x] <https://github.com/peti/distribution-nixpkgs> (hackage: <https://hackage.haskell.org/package/distribution-nixpkgs>)
* [x] <https://github.com/peti/jailbreak-cabal> which is used for all `doJailbreak` overrides (hackage: <https://hackage.haskell.org/package/jailbreak-cabal>)
* [x] <https://github.com/peti/language-nix> (hackage: <https://hackage.haskell.org/package/language-nix>)
* [x] <https://github.com/peti/hackage-db> (hackage: <https://hackage.haskell.org/package/hackage-db>)
* [x] <https://github.com/peti/package-list>

I don't think we *currently* would need access to all of the repositories, but I think it'd be a good idea to give @NixOS/haskell access to them, so we won't have to bother @peti whenever we have to change something for day-to-day nixpkgs operation.

As for what should be done I think it is a case of:

* Adding the members of the haskell team as maintainers for the respective packages on hackage. Unfortunately we can't create an equivalent of the team there, so these lists will have to be updated manually. For that purpose we'll need to collect the hackage usernames of everyone involved.
* Enable the haskell team to commit to the respective repositories either by
  * forking them into the NixOS organisation and using them as a new upstream or
  * transferring the repositories to the NixOS organisation.

Any comments and concerns are welcome!

cc @NixOS/haskell

**Comment by maralorn** [comment]
Hey @peti, I hope you are happy about what we did in the last weeks and that we didn‘t step too much on your toes. Would be great if you could transfer those packages so that we don‘t need to bother you in the future. Of course any input you have will always be greatly appreciated.

**Comment by cdepillabout** [comment]
I emailed Peter today to ask if he could take a look at this issue.

**Comment by peti** [comment]
I have moved all of those repositories to the NixOS organization and transferred maintainer rights to the `cabal2nix-owners` and `haskell` teams. I've also added @cdepillabout as a maintainer for those packages an Hackage where applicable. I believe this gives Dennis the ability to add more maintainers as required. I would have added @maralorn and @sternenseemann, too, but I could not figure out your Hackage user names quickly. I hope this allows you guys to move forward without me blocking progress.

**Comment by cdepillabout** [comment]
Thanks a lot @peti!

--------------------------------------------------------------------------

@maralorn @sternenseemann and @expipiplus1, if you guys let me know your Hackage usernames, I can add you as maintainers to all the relevant packages on Hackage.

**Comment by cdepillabout** [comment]
I've added maralorn, sternenseemann, and expipiplus1 as maintainers on Hackage for:

- https://hackage.haskell.org/package/hackage-db
- https://hackage.haskell.org/package/language-nix
- https://hackage.haskell.org/package/jailbreak-cabal
- https://hackage.haskell.org/package/distribution-nixpkgs

However, @sternenseemann noticed that I am not a maintainer for cabal2nix on Hackage, so I will reach out to peti for that.

**Comment by cdepillabout** [comment]
I've added maralorn, sternenseemann, and expipiplus1 as maintainers on Hackage for https://hackage.haskell.org/package/cabal2nix as well.

That should be all the libraries needed, so I will go ahead and close this issue.
