### ISSUE TITLE
RFC42 tracking issue

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#144575]
[RFC42](https://github.com/NixOS/rfcs/blob/master/rfcs/0042-config-option.md) is the future, let's migrate to it

###### List generated with `grep -rn "extraConfig\|extraOptions" nixos/modules | grep "=" | sed -r "s|(.*.nix):.+|\1|g" | sed "s|nixos/modules/|- [ ] |g" | grep -v pl | grep -v xml | uniq`

- [ ] testing/test-instrumentation.nix
- [ ] system/boot/networkd.nix
- [ ] system/boot/initrd-ssh.nix
- [ ] system/boot/loader/grub/grub.nix
- [ ] system/boot/binfmt.nix
- [ ] system/boot/timesyncd.nix
- [ ] system/boot/resolved.nix
- [ ] system/boot/systemd.nix
- [ ] tasks/snapraid.nix
- [ ] tasks/filesystems/nfs.nix
- [ ] virtualisation/azure-agent.nix
- [ ] virtualisation/lxc-container.nix
- [ ] virtualisation/nixos-containers.nix
- [ ] virtualisation/docker.nix
- [ ] virtualisation/oci-containers.nix
- [ ] virtualisation/azure-common.nix
- [ ] virtualisation/xen-dom0.nix
- [ ] virtualisation/qemu-vm.nix
- [ ] virtualisation/virtualbox-host.nix
- [ ] virtualisation/amazon-image.nix
- [ ] virtualisation/libvirtd.nix
- [ ] programs/msmtp.nix
- [ ] programs/ccache.nix
- [ ] programs/xss-lock.nix
- [ ] programs/tmux.nix
- [ ] programs/ssh.nix
- [ ] programs/sway.nix
- [ ] programs/tsm-client.nix
- [ ] programs/zsh/zsh-autosuggestions.nix
- [ ] installer/cd-dvd/installation-cd-graphical-base.nix
- [ ] installer/cd-dvd/system-tarball-pc.nix
- [ ] hardware/corectrl.nix
- [ ] hardware/video/amdgpu-pro.nix
- [ ] hardware/network/ath-user-regd.nix
- [ ] config/terminfo.nix
- [ ] config/ldap.nix
- [ ] config/resolvconf.nix
- [ ] config/krb5/default.nix
- [ ] config/pulseaudio.nix
- [ ] security/polkit.nix
- [ ] security/google_oslogin.nix
- [ ] security/sudo.nix
- [ ] security/duosec.nix
- [ ] security/doas.nix
- [ ] services/printing/cupsd.nix
- [ ] services/development/jupyterhub/default.nix
- [ ] services/development/bloop.nix
- [ ] services/web-servers/lighttpd/default.nix
- [ ] services/web-servers/lighttpd/cgit.nix
- [ ] services/web-servers/lighttpd/collectd.nix
- [ ] services/web-servers/lighttpd/gitweb.nix
- [ ] services/web-servers/caddy/default.nix
- [ ] services/web-servers/caddy/vhost-options.nix
- [ ] services/web-servers/hitch/default.nix
- [ ] services/web-servers/apache-httpd/default.nix
- [ ] services/web-servers/apache-httpd/vhost-options.nix
- [ ] services/web-servers/apache-httpd/location-options.nix
- [ ] services/web-servers/tomcat.nix
- [ ] services/web-servers/shellinabox.nix
- [x] services/web-servers/phpfpm/default.nix
- [ ] services/web-servers/nginx/default.nix
- [ ] services/web-servers/nginx/vhost-options.nix
- [ ] services/web-servers/nginx/location-options.nix
- [ ] services/web-servers/nginx/gitweb.nix
- [ ] services/mail/mlmmj.nix
- [ ] services/mail/rspamd.nix
- [ ] services/mail/mailman.nix:283:          "/".extraConfig = "uwsgi_pass unix
- [ ] services/mail/postfixadmin.nix
- [ ] services/mail/dspam.nix
- [ ] services/mail/roundcube.nix
- [ ] services/mail/postfix.nix
- [ ] services/mail/dovecot.nix
- [ ] services/mail/sympa.nix
- [ ] services/databases/cassandra.nix
- [ ] services/databases/memcached.nix
- [x] services/databases/mysql.nix
- [ ] services/databases/mongodb.nix
- [ ] services/databases/riak.nix
- [ ] services/databases/couchdb.nix
- [ ] services/databases/victoriametrics.nix
- [ ] services/databases/influxdb.nix
- [ ] services/databases/aerospike.nix
- [ ] services/x11/redshift.nix
- [ ] services/x11/xautolock.nix
- [ ] services/x11/desktop-managers/cinnamon.nix
- [ ] services/x11/desktop-managers/cde.nix
- [ ] services/x11/unclutter-xfixes.nix
- [ ] services/x11/xserver.nix
- [ ] services/x11/unclutter.nix
- [ ] services/monitoring/alerta.nix
- [ ] services/monitoring/kapacitor.nix
- [ ] services/monitoring/graphite.nix
- [x] services/monitoring/grafana-image-renderer.nix
- [ ] services/monitoring/cadvisor.nix
- [ ] services/monitoring/scollector.nix
- [x] services/monitoring/grafana.nix
- [ ] services/monitoring/nagios.nix
- [ ] services/monitoring/bosun.nix
- [ ] services/monitoring/munin.nix
- [ ] services/monitoring/datadog-agent.nix
- [ ] services/monitoring/smartd.nix
- [ ] services/monitoring/prometheus/exporters/dovecot.nix
- [ ] services/monitoring/fusion-inventory.nix
- [ ] services/monitoring/statsd.nix
- [ ] services/monitoring/collectd.nix
- [ ] services/monitoring/telegraf.nix
- [ ] services/network-filesystems/ceph.nix
- [ ] services/network-filesystems/samba-wsdd.nix
- [ ] services/network-filesystems/nfsd.nix
- [ ] services/network-filesystems/diod.nix
- [ ] services/network-filesystems/cachefilesd.nix
- [x] services/network-filesystems/davfs2.nix
- [ ] services/network-filesystems/xtreemfs.nix
- [ ] services/network-filesystems/orangefs/client.nix
- [ ] services/network-filesystems/orangefs/server.nix
- [x] services/network-filesystems/ipfs.nix
- [ ] services/network-filesystems/samba.nix
- [ ] services/audio/alsa.nix
- [ ] services/audio/mpd.nix
- [ ] services/audio/jack.nix
- [ ] services/audio/mopidy.nix
- [ ] services/torrent/opentracker.nix
- [x] services/torrent/magnetico.nix
- [ ] services/games/teeworlds.nix
- [ ] services/games/quake3-server.nix
- [ ] services/backup/restic.nix
- [ ] services/backup/bacula.nix
- [ ] services/backup/rsnapshot.nix
- [ ] services/ttys/kmscon.nix
- [ ] services/networking/pdnsd.nix
- [ ] services/networking/monero.nix
- [ ] services/networking/dnsdist.nix
- [ ] services/networking/iodine.nix
- [ ] services/networking/gnunet.nix
- [ ] services/networking/ntp/ntpd.nix
- [ ] services/networking/ntp/openntpd.nix
- [ ] services/networking/ntp/chrony.nix
- [ ] services/networking/dhcpd.nix
- [ ] services/networking/powerdns.nix
- [ ] services/networking/kresd.nix  https://github.com/NixOS/nixpkgs/pull/154610
- [ ] services/networking/strongswan-swanctl/module.nix
- [ ] services/networking/babeld.nix
- [ ] services/networking/murmur.nix
- [ ] services/networking/minidlna.nix
- [ ] services/networking/mtprotoproxy.nix
- [ ] services/networking/zerobin.nix
- [ ] services/networking/blockbook-frontend.nix
- [ ] services/networking/xinetd.nix
- [ ] services/networking/hans.nix
- [ ] services/networking/tinc.nix
- [ ] services/networking/dnsmasq.nix
- [ ] services/networking/lxd-image-server.nix
- [ ] services/networking/mxisd.nix
- [ ] services/networking/tox-bootstrapd.nix
- [ ] services/networking/3proxy.nix
- [ ] services/networking/nghttpx/nghttpx-options.nix
- [ ] services/networking/iscsi/initiator.nix
- [ ] services/networking/iscsi/root-initiator.nix
- [ ] services/networking/vsftpd.nix
- [ ] services/networking/asterisk.nix
- [ ] services/networking/xandikos.nix
- [ ] services/networking/smokeping.nix
- [ ] services/networking/avahi-daemon.nix
- [ ] services/networking/ddclient.nix
- [ ] services/networking/atftpd.nix
- [ ] services/networking/syncthing-relay.nix
- [ ] services/networking/x2goserver.nix
- [ ] services/networking/shadowsocks.nix
- [ ] services/networking/nixops-dns.nix
- [ ] services/networking/thelounge.nix
- [ ] services/networking/coturn.nix
- [ ] services/networking/htpdate.nix
- [ ] services/networking/ntopng.nix
- [x] services/networking/ssh/sshd.nix
- [ ] services/networking/cntlm.nix
- [ ] services/networking/cjdns.nix
- [ ] services/networking/znc/default.nix
- [ ] services/networking/znc/options.nix
- [ ] services/networking/skydns.nix
- [ ] services/networking/keepalived/vrrp-script-options.nix
- [ ] services/networking/keepalived/default.nix
- [ ] services/networking/keepalived/vrrp-instance-options.nix
- [ ] services/networking/consul.nix
- [ ] services/networking/knot.nix
- [ ] services/networking/syncthing.nix
- [ ] services/networking/multipath.nix
- [ ] services/networking/bitcoind.nix
- [ ] services/networking/zeronet.nix
- [ ] services/networking/bind.nix
- [ ] services/networking/connman.nix
- [ ] services/networking/dnscrypt-wrapper.nix
- [ ] services/networking/soju.nix
- [ ] services/networking/squid.nix
- [ ] services/networking/networkmanager.nix
- [x] services/networking/hostapd.nix
- [ ] services/networking/polipo.nix
- [ ] services/networking/prayer.nix
- [ ] services/networking/dhcpcd.nix
- [ ] services/networking/nsd.nix
- [ ] services/networking/prosody.nix
- [ ] services/networking/stubby.nix
- [ ] services/computing/slurm/slurm.nix
- [ ] services/web-apps/zabbix.nix
- [ ] services/web-apps/mattermost.nix
- [ ] services/web-apps/limesurvey.nix
- [ ] services/web-apps/lemmy.nix
- [ ] services/web-apps/wordpress.nix
- [ ] services/web-apps/trilium.nix
- [ ] services/web-apps/moinmoin.nix
- [ ] services/web-apps/mediawiki.nix
- [ ] services/web-apps/keycloak.nix
- [ ] services/web-apps/hledger-web.nix
- [ ] services/web-apps/bookstack.nix
- [ ] services/web-apps/jitsi-meet.nix
- [ ] services/web-apps/discourse.nix
- [ ] services/web-apps/mastodon.nix
- [ ] services/web-apps/dokuwiki.nix
- [ ] services/web-apps/fluidd.nix
- [ ] services/web-apps/matomo.nix
- [ ] services/web-apps/vikunja.nix
- [ ] services/web-apps/jirafeau.nix
- [ ] services/web-apps/youtrack.nix
- [ ] services/web-apps/restya-board.nix
- [ ] services/web-apps/tt-rss.nix
- [ ] services/web-apps/sogo.nix
- [ ] services/web-apps/ihatemoney/default.nix
- [ ] services/web-apps/engelsystem.nix
- [ ] services/web-apps/grocy.nix
- [ ] services/web-apps/icingaweb2/icingaweb2.nix
- [ ] services/web-apps/rss-bridge.nix
- [ ] services/web-apps/nextcloud.nix
- [ ] services/web-apps/selfoss.nix
- [ ] services/web-apps/moodle.nix
- [ ] services/web-apps/pgpkeyserver-lite.nix
- [ ] services/editors/infinoted.nix
- [ ] services/hardware/sane.nix
- [ ] services/hardware/triggerhappy.nix
- [ ] services/hardware/actkbd.nix
- [ ] services/hardware/lcd.nix
- [ ] services/hardware/tlp.nix
- [ ] services/hardware/rasdaemon.nix
- [ ] services/hardware/throttled.nix
- [ ] services/continuous-integration/hercules-ci-agent/common.nix
- [ ] services/continuous-integration/gocd-server/default.nix
- [ ] services/continuous-integration/buildkite-agents.nix
- [ ] services/continuous-integration/gocd-agent/default.nix
- [ ] services/continuous-integration/buildbot/master.nix
- [ ] services/continuous-integration/hydra/default.nix
- [ ] services/continuous-integration/jenkins/default.nix
- [ ] services/security/oauth2_proxy.nix
- [ ] services/security/vault.nix
- [ ] services/security/privacyidea.nix
- [ ] services/security/oauth2_proxy_nginx.nix
- [ ] services/logging/syslogd.nix
- [ ] services/logging/syslog-ng.nix
- [ ] services/logging/graylog.nix
- [ ] services/logging/rsyslogd.nix
- [ ] services/logging/awstats.nix
- [x] services/logging/logrotate.nix
- [ ] services/logging/SystemdJournal2Gelf.nix
- [ ] services/logging/journalbeat.nix
- [ ] services/logging/journalwatch.nix
- [ ] services/logging/heartbeat.nix
- [ ] services/misc/dwm-status.nix
- [ ] services/misc/gammu-smsd.nix
- [ ] services/misc/errbot.nix
- [ ] services/misc/gollum.nix
- [ ] services/misc/octoprint.nix
- [ ] services/misc/gitlab.nix
- [ ] services/misc/docker-registry.nix
- [ ] services/misc/bepasty.nix
- [ ] services/misc/gogs.nix
- [x] services/misc/home-assistant.nix #157213
- [ ] services/misc/paperless-ng.nix
- [ ] services/misc/snapper.nix
- [ ] services/misc/zoneminder.nix
- [ ] services/misc/sourcehut/hg.nix
- [ ] services/misc/sourcehut/git.nix
- [x] services/misc/gitea.nix
- [ ] services/misc/nix-ssh-serve.nix
- [ ] services/misc/bees.nix
- [x] services/misc/matrix-synapse.nix #158605 
- [ ] services/misc/siproxd.nix
- [ ] services/misc/nix-daemon.nix
- [ ] services/misc/gitweb.nix
- [ ] services/misc/parsoid.nix
- [x] services/networking/yggdrasil.nix #185584
- [ ] misc/crashdump.nix

**Comment by polykernel** [comment]
I think some of the modules in the list are false positives, some already implement structural settings but provide `extraConfig` as a fallback or use `extraConfig` from another module. The list is a helpful reference nonetheless.

**Comment by ShamrockLee** [comment]
With PR #139075 merged, we're going to have `nix.settings`!

**Comment by pingiun** [comment]
Logrotate can be checked as it was done in https://github.com/NixOS/nixpkgs/commit/e92c05349c6053df22cf21eb9f424251ba2b114f

**Comment by peterhoeg** [comment]
NFS is in progress, https://github.com/NixOS/nixpkgs/pull/177601

**Comment by KFearsoff** [comment]
Grafana is done.

**Comment by peterhoeg** [comment]
The big one is all the programs under the systemd project umbrella. It should be probably be done piecemeal but it requires a fair amount of work.

**Comment by matthiasbeyer** [comment]
`services/network-filesystems/ipfs.nix` is done (in https://github.com/NixOS/nixpkgs/pull/197104)

**Comment by Yarny0** [comment]
Now that https://github.com/NixOS/nixpkgs/pull/253428 got merged, the "programs/tsm-client.nix" checkbox may be ticked.

**Comment by SigmaSquadron** [comment]
**virtualisation/xen-dom0.nix** is partially done with #324911. There's still the `xl` configuration, which is non-trivial and will happen later, alongside a declarative VM builder.

**Comment by RafaelKr** [comment]
I'd like to mention that PHP (not the phpfpm module) also uses extraConfig. There it also would make sense to migrate to RFC42.
See https://github.com/NixOS/nixpkgs/blob/a9478ce4d0378dce2f672bae392fb67afaae4158/pkgs/development/interpreters/php/generic.nix

**Comment by vacy** [comment]
isn't haproxy part of this? but it is not listed here.
services/networking/haproxy.nix: [services.haproxy.config](https://search.nixos.org/options?channel=26.05&query=haproxy#show=option%253Aservices.haproxy.config)
maintainer: @vifino
