### ISSUE TITLE
Remove wlroots_0_14 (tracking issue)

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#151311]
~~Note: This is WIP / only a draft. https://github.com/NixOS/nixpkgs/pull/151234 isn't even merged yet.~~

The affected packages should switch to the latest wlroots release when possible (usually a new upstream release). There's no hurry (everything is still in `staging`) but let's use this issue to track the current progress.

Packages:
- [ ] cage (https://github.com/Hjdskes/cage/pull/197)
- [ ] cagebreak (no patches yet: https://github.com/project-repo/cagebreak/tree/development)
- [x] dwl (https://github.com/djpohly/dwl/tree/wlroots-next; **released**: https://github.com/djpohly/dwl/releases/tag/v0.2.2): https://github.com/NixOS/nixpkgs/pull/157593
- [ ] hikari (https://hub.darcs.net/raichoo/hikari/patch/1dbeab7561c1f86815cbacdbbd4a8a8b2ec13b3e)
- [x] labwc (https://github.com/labwc/labwc/commit/c9312edf0b05162b49032828837370e168a010d8; https://github.com/labwc/labwc/issues/121): https://github.com/NixOS/nixpkgs/pull/157065
- [x] python3.8-pywlroots python3.9-pywlroots (https://github.com/flacjacket/pywlroots/issues/52 and https://github.com/flacjacket/pywlroots/pull/51; **released**: https://github.com/flacjacket/pywlroots/releases/tag/v0.15.0): https://github.com/NixOS/nixpkgs/pull/156671
  - [x] qtile (https://github.com/qtile/qtile; only depends on pywlroots): https://github.com/NixOS/nixpkgs/pull/156671
- [x] river (**released**: https://github.com/riverwm/river/releases/tag/v0.1.1): https://github.com/NixOS/nixpkgs/pull/156086
- [x] sway sway-unwrapped (https://github.com/swaywm/sway/commit/c53ef023850fcdc4b3dfeee2992cdaa7f0cee1ac; https://github.com/swaywm/sway/issues/6729): https://github.com/NixOS/nixpkgs/pull/151902
  - nwg-panel (only depends on Sway)
  - [x] waybar (https://github.com/Alexays/Waybar; depends on wlroots and Sway)
- [ ] waybox-unstable (unmaintained: https://github.com/wizbright/waybox/issues/27)
- [ ] wayfire wayfire wcm wcm wf-shell (https://github.com/WayfireWM/wayfire/commit/c690ad8d699978ec5f9fe2925a661a104c479e8a and https://github.com/WayfireWM/wayfire/issues/1386)
- [ ] wio (basically unmaintained)
- [ ] phoc (https://gitlab.gnome.org/World/Phosh/phoc/-/merge_requests/284)

No changes required / unaffected:
- [x] fnott (https://codeberg.org/dnkl/fnott)
- [x] qt-video-wlr (unmaintained?: https://github.com/xdavidwu/qt-video-wlr)
- [x] wlroots tinywl

Previous issue: https://github.com/NixOS/nixpkgs/issues/118838

**Comment by wineee** [comment]
- [ ] waybox https://github.com/NixOS/nixpkgs/pull/220277
- [ ] hikari https://github.com/NixOS/nixpkgs/pull/219693
- [ ] wayfire https://github.com/NixOS/nixpkgs/pull/220714
- [ ] cage https://github.com/cage-kiosk/cage/issues/232
- [ ] wio (still basically unmaintained)
