### ISSUE TITLE
Regressions due to a boost bump

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#151469]
The default boost version has been bumped from 1.69 (or 1.75) to 1.77. This is a notice for maintainers that **the following packages are now failing to build**:

 - [ ] [libpointmatcher](https://hydra.nixos.org/job/nixpkgs/staging-next/libpointmatcher.x86_64-linux) @cryptix
 - [ ] [masari](https://hydra.nixos.org/job/nixpkgs/staging-next/masari.x86_64-linux) @fpletz
 - [ ] [libtorrent-rasterbar-1_1_x](https://hydra.nixos.org/job/nixpkgs/staging-next/libtorrent-rasterbar-1_1_x.x86_64-linux) @phreedom
 - [x] [monotone](https://hydra.nixos.org/job/nixpkgs/staging-next/monotone.x86_64-linux) @7c6f434c #152208
 - [x] [arc_unpacker](https://hydra.nixos.org/job/nixpkgs/staging-next/arc_unpacker.x86_64-linux) @midchildan #152370
 - [x] [swiften](https://hydra.nixos.org/job/nixpkgs/staging-next/swiften.x86_64-linux) @Twey https://github.com/NixOS/nixpkgs/pull/152145
 - [ ] [pivxd](https://hydra.nixos.org/job/nixpkgs/staging-next/pivxd.x86_64-linux) @wucke13
 - [x] [cpp-netlib](https://hydra.nixos.org/job/nixpkgs/staging-next/cpp-netlib.x86_64-linux) - #151202
 - [ ] [particl-core](https://hydra.nixos.org/job/nixpkgs/staging-next/particl-core.x86_64-linux) @demyanrogozhin
 - [x] [nova-filters](https://hydra.nixos.org/job/nixpkgs/staging-next/nova-filters.x86_64-linux) @magnetophon #151732
 - [x] [powerdns](https://hydra.nixos.org/job/nixpkgs/staging-next/powerdns.x86_64-linux) @mic92 @disassembler - #151202
 - [ ] [uhd3_5](https://hydra.nixos.org/job/nixpkgs/staging-next/uhd3_5.x86_64-linux) @bjornfor @fpletz @tomberek
 - [ ] [namecoind](https://hydra.nixos.org/job/nixpkgs/staging-next/namecoind.x86_64-linux) @infinisil
 - [x] [libbitcoin](https://hydra.nixos.org/job/nixpkgs/staging-next/libbitcoin.x86_64-linux) - #151202
 - [x] [ndn-tools](https://hydra.nixos.org/job/nixpkgs/staging-next/ndn-tools.x86_64-linux) @bertof #152721
 - [x] [nfd](https://hydra.nixos.org/job/nixpkgs/staging-next/nfd.x86_64-linux) @bertof #152721
 - [x] [rethinkdb](https://hydra.nixos.org/job/nixpkgs/staging-next/rethinkdb.x86_64-linux) @thoughtpolice @bluescreen303 https://github.com/NixOS/nixpkgs/pull/153639
 - [ ] [litecoind](https://hydra.nixos.org/job/nixpkgs/staging-next/litecoind.x86_64-linux) @offlinehacker
 - [x] [wt3](https://hydra.nixos.org/job/nixpkgs/staging-next/wt3.x86_64-linux) @juliendehos @willibutz #152128
 - [x] [mozart2](https://hydra.nixos.org/job/nixpkgs/staging-next/mozart2.x86_64-linux) @layus #151576
 - [x] [librecad](https://hydra.nixos.org/job/nixpkgs/staging-next/librecad.x86_64-linux) @Kiwi @viric - #151202
 - [x] [ycmd](https://hydra.nixos.org/job/nixpkgs/staging-next/ycmd.x86_64-linux) @rasendubi @cstrahan @lnl7 597743cf9c62c21ec55a6d2ad64cdf062f117aaa
 - [ ] [namecoin](https://hydra.nixos.org/job/nixpkgs/staging-next/namecoin.x86_64-linux) @infinisil
 - [x] [emulationstation](https://hydra.nixos.org/job/nixpkgs/staging-next/emulationstation.x86_64-linux) @edwtjo #172196
 - [x] [python39Packages.graph-tool](https://hydra.nixos.org/job/nixpkgs/staging-next/python39Packages.graph-tool.x86_64-linux) @joelmo #151638
 - [ ] [opendungeons](https://hydra.nixos.org/job/nixpkgs/staging-next/opendungeons.x86_64-linux) 
 - [ ] [litecoin](https://hydra.nixos.org/job/nixpkgs/staging-next/litecoin.x86_64-linux) @offlinehacker
 - [x] [colobot](https://hydra.nixos.org/job/nixpkgs/staging-next/colobot.x86_64-linux) @freezeboy #153130
 - [x] [snapcast](https://hydra.nixos.org/job/nixpkgs/staging-next/snapcast.x86_64-linux) @fpletz
 - [x] [gnuradio3_8Packages.gnuradio](https://hydra.nixos.org/job/nixpkgs/staging-next/gnuradio3_8Packages.gnuradio.x86_64-linux) @doronbehar @bjornfor @fpletz #151864
 - [x] [sourcetrail](https://hydra.nixos.org/job/nixpkgs/staging-next/sourcetrail.x86_64-linux) @midchildan #152375
 - [ ] [dashpay](https://hydra.nixos.org/job/nixpkgs/staging-next/dashpay.x86_64-linux) 
 - [x] [digikam](https://hydra.nixos.org/job/nixpkgs/staging-next/digikam.x86_64-linux) - https://github.com/NixOS/nixpkgs/pull/151388
 - [x] [gnuradio3_8Minimal](https://hydra.nixos.org/job/nixpkgs/staging-next/gnuradio3_8Minimal.x86_64-linux) @doronbehar @bjornfor @fpletz
 - [x] [freecad](https://hydra.nixos.org/job/nixpkgs/staging-next/freecad.x86_64-linux) @viric @gebner @AndersonTorres #151741
 - [x] [opentoonz](https://hydra.nixos.org/job/nixpkgs/staging-next/opentoonz.x86_64-linux) @chkno #151500
 - [x] [sdrangel](https://hydra.nixos.org/job/nixpkgs/staging-next/sdrangel.x86_64-linux) @Alkeryn https://github.com/NixOS/nixpkgs/pull/153316
 - [x] [pokerth-server](https://hydra.nixos.org/job/nixpkgs/staging-next/pokerth-server.x86_64-linux) @obadz @yegortimoshenko  #157088
 - [x] [python39Packages.roboschool](https://hydra.nixos.org/job/nixpkgs/staging-next/python39Packages.roboschool.x86_64-linux) @timokau - #154998
 - [x] [python39Packages.scikit-survival](https://hydra.nixos.org/job/nixpkgs/staging-next/python39Packages.scikit-survival.x86_64-linux)
 - [x] [foundationdb61](https://hydra.nixos.org/job/nixpkgs/staging-next/foundationdb61.x86_64-linux) @thoughtpolice #157967
 - [x] [pokerth](https://hydra.nixos.org/job/nixpkgs/staging-next/pokerth.x86_64-linux) @obadz @yegortimoshenko  #157088
 - [x] [python38Packages.graph-tool](https://hydra.nixos.org/job/nixpkgs/staging-next/python38Packages.graph-tool.x86_64-linux) @joelmo - https://github.com/NixOS/nixpkgs/pull/151638
 - [x] [python38Packages.roboschool](https://hydra.nixos.org/job/nixpkgs/staging-next/python38Packages.roboschool.x86_64-linux) @timokau - #154998
 - [x] [bombono](https://hydra.nixos.org/job/nixpkgs/staging-next/bombono.x86_64-linux) @symphorien #151574
 - [x] [musikcube](https://hydra.nixos.org/job/nixpkgs/staging-next/musikcube.x86_64-linux) @aanderse
 - [x] [gplates](https://hydra.nixos.org/job/nixpkgs/staging-next/gplates.x86_64-linux) - https://github.com/NixOS/nixpkgs/pull/151505
 - [x] [mapnik](https://hydra.nixos.org/job/nixpkgs/staging-next/mapnik.x86_64-linux) @hrdinka @erictapen - #151202
 - [ ] [pivx](https://hydra.nixos.org/job/nixpkgs/staging-next/pivx.x86_64-linux) @wucke13
 - [x] [mirtk](https://hydra.nixos.org/job/nixpkgs/staging-next/mirtk.x86_64-linux) @bcdarwin #151596
 - [x] [slic3r](https://hydra.nixos.org/job/nixpkgs/staging-next/slic3r.x86_64-linux) @bjornfor #153276
 - [x] [arrayfire](https://hydra.nixos.org/job/nixpkgs/staging-next/arrayfire.x86_64-linux) @chessai
 - [x] [ethminer-free](https://hydra.nixos.org/job/nixpkgs/staging-next/ethminer-free.x86_64-linux) @Atemu #151989
 - [x] cryfs #152817

A typical fix would involve pinning the package to a specific version (e.g. see #151202)

**Comment by layus** [comment]
My fix in https://github.com/NixOS/nixpkgs/pull/151576 is not the same as #151202. Is there a very good reason to prefer one over the other ?

**Comment by vcunat** [comment]
Well, I like trying to keep it away from the huge top-level file.  (which is e.g. harder to use in git)

**Comment by wucke13** [comment]
Re. pivx, I think we should mark it broken. Our current version is very old (and therefore useless), and the new version includes a rust build. I don't have the capacity to fix this ATM.

**Comment by doronbehar** [comment]
In my case, what broke it was the update from boost175 to boost177. Fix is in https://github.com/NixOS/nixpkgs/pull/151864 .

**Comment by vcunat** [comment]
It's in the `master` branch now, so please target any further fixes there as well (unless they're a mass rebuild, etc.)

**Comment by c0bw3b** [comment]
colobot fixed with #153130

**Comment by bcc32** [comment]
FYI, ledger has some broken behavior with the new boost version, although it curiously doesn't cause a test failure: ledger/ledger#2075.

**Comment by vcunat** [comment]
Our `ledger` expression does not attempt to run tests.

**Comment by bcc32** [comment]
Ah, that would be why, thanks.  Nevertheless, the binary exhibits the same problem described in that issue in interactive use.
