### ISSUE TITLE
CUDA in 22.05

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nixpkgs#167068]
## Issue description

This is a aggregate issue to track (the selected subset of) that state of CUDA in master before the 22-05 release.
It's concern is the world evaluated with `{ config.cudaSupport = true; config.allowUnfree = true; }` 

- The release will see the following changes that affect how we package and use cuda:
  - [x] The new scope-based interface for consuming cuda-related packages, introduced together with the redistributable cuda packages in https://github.com/NixOS/nixpkgs/pull/167016/
  - [x] cudnn drops its `propagatedBuildInputs` which used to include `cudatoolkit` and cause a lot of obscure errors. Happens in: https://github.com/NixOS/nixpkgs/pull/168748
- We currently have the following failures (we might not fix them before the release, but back-port later) 
  
  - [x] As of (at least) 2022-04-11 jax is failing on master, cf. [jax: tests/test_sparse.py](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F53190dyjcf00cl0rja4ficaghlxn8ab9-python3.9-jax-0.3.5.drv/log?via-job=f167030f-e041-4191-95b7-74c71afd5aad)
    - [x] `test_sparse.py` has been fixed upstream, but blocked in nixpkgs because of: https://github.com/NixOS/nixpkgs/issues/169148
  
  - [ ] [catboost](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Flj1np2w0gmwnr45aq20lbf7dwjqmg3va-python3.10-catboost-0.24.4.drv/log?via-job=f167030f-e041-4191-95b7-74c71afd5aad)
  
  - [x] As of (at least) 2022-04-11, [tensorflow-datasets is failing](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Fsw770kmi645jczmwi21x5h9k16ara6nd-python3.9-tensorflow-datasets-4.5.2.drv/log?via-job=f167030f-e041-4191-95b7-74c71afd5aad), cf. https://github.com/NixOS/nixpkgs/issues/167445
  
  - [x] [`xgboost`](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F87l72vpbkaxh1zixmrzd56lw4a6j9m80-xgboost-1.5.2.drv/log?via-job=ab473808-fd27-43d3-aa86-1e82235718e0)
    
    ```
    CMake Error at CMakeLists.txt:140 (message):
    `BUILD_WITH_CUDA_CUB` should be set to `ON` for CUDA >= 11.4
    ```
  
    ...and now it's https://github.com/NixOS/nixpkgs/issues/167931
  
  - [x] `python39Packages.mxnet`
    CMake configurePhase [fails](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F6l39w83hvhr4y78dhv1v50y5ixjvk2vd-mxnet-1.8.0.drv/log?via-job=930fc1c2-1577-48e1-b532-c9252621fe60)
  
    Likely will be fixed in: https://github.com/NixOS/nixpkgs/pull/167250
  - [ ] `cholmod-extra`
    
    Tests [fail](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F46nw0nv4gr1q747rxpgkf2nhyc6lvxjf-cholmod-extra-1.2.0.drv/log?via-job=930fc1c2-1577-48e1-b532-c9252621fe60): too large residuals
  
  - [x] `python3*Packages.chainer`
    
    Complains about [cupy version](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2Fgwfj4vnzag4lqrggg033pdggzyai1737-python3.9-chainer-7.8.1.drv/log?via-job=8db14681-ab92-465d-8355-575c55c32e12)
  
    Marked as broken in: https://github.com/NixOS/nixpkgs/pull/167250
  - [x] `python310Packages.caffe`
    
    CMake configurePhase [fails](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F27crqg6g0z173cr380qcid5c8mrv0m87-caffe-1.0.drv/log?via-job=8db14681-ab92-465d-8355-575c55c32e12)
  - [x] `python39Packages.caffe`
  
    Fixed by: https://github.com/NixOS/nixpkgs/pull/166784/
  
  - [x] `blender`: failing dependency (opensubdiv)
    
  - [x] `opensubdiv`: [fails at cmake configurePhase](https://hercules-ci.com/accounts/github/SomeoneSerge/derivations/%2Fnix%2Fstore%2F6q4a99a0ww0vzll8q6212xzrsbipp76z-opensubdiv-3.4.4.drv/log?via-job=930fc1c2-1577-48e1-b532-c9252621fe60)
  
    Likely will be fixed in: https://github.com/NixOS/nixpkgs/pull/167250
  
  - [x] Pytorch
    
    Cmake error: https://github.com/NixOS/nixpkgs/issues/166403
    Build error: https://github.com/NixOS/nixpkgs/issues/161843
    Fixed by: https://github.com/NixOS/nixpkgs/pull/166784/

cc @NixOS/cuda-maintainers

**Comment by samuela** [comment]
I think we may just need to mark some of these as broken. For example, `chainer` is requesting a truly ancient version of cupy: `cupy>=7.7.0,<8.0.0`. Latest stable cupy is v10.3.0.

cc'ing some maintainers:
* blender: @cillianderoiste @veprbl 
* opensubdiv: @edolstra 
* cholmod-extra: @jluttine 
* python3Packages.chainer: @hyphon81 
* python310Packages.caffe: @jb55

**Comment by SomeoneSerge** [comment]
The state of things at the time of the release landing:
![image](https://user-images.githubusercontent.com/9720532/171177214-28c4591b-d584-40e5-b9b3-6d3718b12d9d.png)

I believe it would be still justifiable to backport some incremental improvements, fixes, and extensions as we make them. In particular, in the release we still
- [ ] haven't finished migrating downstream expressions to the redistributable `cudaPackages`, even the fundamental packages like 
  - [ ] `pytorch`,
  - [ ]  `jax`,
  - [ ]  or `tensorflow`;
- [ ] don't have a good control of the closure size, e.g. when building docker images with deep learning packages: https://github.com/NixOS/nixpkgs/issues/173462
- ..?
