### ISSUE TITLE
aeson 1.5 tracking issue

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#167859]
We are still building some packages with `aeson` 1.5 which is a slight annoyance, so let's make a list and migrate them to 2.0 one by one!

Packages still using `aeson` 1.5:

* [x] `niv`
* [x] `nix-linter`
* [x] `vaultenv`
* [x] `stack`
* [x] `descriptive`
* [x] `mattermost-api`, `matterhorn`
* [x] `elmPackages`
* [x] `spago`, `bower-json`
* [ ] `ghcjs`

Packages that are failing because they don't support `aeson` 2.0 (but also haven't been overridden to use 1.5):

* [x] `ghcjs` #166553
* [x] `jl`
* [x] `hasura-graphql-engine` (because of `haskellPackages.graphql-parser`)

cc @NixOS/haskell

**Comment by AleXoundOS** [comment]
`nix-linter` is still using aeson 1.5:

```
$ NIXPKGS_ALLOW_BROKEN=1 nix shell --impure github:nixos/nixpkgs#nix-linter
error: builder for '/nix/store/iry15ddwhh1nxk68bnxl3641m1alsr6f-aeson-1.5.6.0.drv' failed with exit code 1;
       last 10 log lines:
       >     Ambiguous occurrence ‘scientific’
       >     It could refer to
       >        either ‘B.scientific’,
       >               imported from ‘Data.ByteString.Builder’ at src/Data/Aeson/Encoding/Builder.hs:45:1-35
       >               (and originally defined in ‘Data.ByteString.Builder.RealFloat’)
       >            or ‘Data.Aeson.Encoding.Builder.scientific’,
       >               defined at src/Data/Aeson/Encoding/Builder.hs:138:1
       >    |
       > 68 | encodeToBuilder (Number n) = scientific n
       >    |                              ^^^^^^^^^^
       For full logs, run 'nix log /nix/store/iry15ddwhh1nxk68bnxl3641m1alsr6f-aeson-1.5.6.0.drv'.
error: 1 dependencies of derivation '/nix/store/pnlhysmk7l30vb59rcq5zmklhnsbi5cn-nix-linter-0.2.0.4.drv' failed to build
```

**Comment by sternenseemann** [comment]
#305970

**Comment by ysangkok** [comment]
How can I easily discover the packages that are still using aeson-1.5?

**Comment by maralorn** [comment]
You can grep nixpkgs for `aeson_1_`.
