### ISSUE TITLE
Enable `config.strictDepsByDefault = true` by default

### ISSUE THREAD

**Issue by trofi** [NixOS/nixpkgs#178468]
`strictDeps` helps keeping cleaner `PATH`s for cross-compiled packages. But it's also useful to have for native builds: it helps writing nix derivations that have better chance of working when cross-compiled later.

A bunch of packages will need to sort out their `buildInputs / nativeBuildInputs` depends. Or more precise `depsBuildBuild & co.` finer grained equivalents.

https://github.com/NixOS/nixpkgs/blob/913ee4f295c6a0cc801effd3c72906639a31fdb0/pkgs/stdenv/generic/make-derivation.nix#L345-L346

**Comment by erdnaxe** [comment]
libxml2 seems to break with `config.strictDepsByDefault = true`. Adding `python` in `nativeBuildInputs` fixes the issue.
I am not really confident to propose this as a patch as I don't understand why this exists: `pythonSupport ? enableShared && stdenv.buildPlatform == stdenv.hostPlatform`.

**Comment by Artturin** [comment]
> libxml2 seems to break with `config.strictDepsByDefault = true`. Adding `python` in `nativeBuildInputs` fixes the issue. I am not really confident to propose this as a patch as I don't understand why this exists: `pythonSupport ? enableShared && stdenv.buildPlatform == stdenv.hostPlatform` (in pkgs/development/libraries/libxml2/default.nix).

python is probably being disabled because cross-compilation enables strictDeps and so breaks the python detection

i'll fix it

**Comment by erdnaxe** [comment]
There seems to be a similar issue to libxml2 with libxslt.

I am building a aarch64-linux NixOS system from master using `config.strictDepsByDefault = true`. I will update the following list with the files in which I had to add `strictDeps = false;` to get a working system:

 * [ ] pkgs/development/libraries/libxml2/default.nix
 * [ ] pkgs/development/libraries/libxslt/default.nix
 * [ ] pkgs/os-specific/linux/kmod/default.nix

**Comment by Artturin** [comment]
libxml2, libxslt: https://github.com/NixOS/nixpkgs/pull/194941

**Comment by Artturin** [comment]
perlPackages.{Po4a,AlienLibxml2},kmod,liblouis https://github.com/NixOS/nixpkgs/pull/218503

**Comment by AndersonTorres** [comment]
Ward because I need to learn this.

**Comment by infinisil** [comment]
Since nobody mentioned this before, we should only do this for Nixpkgs, not third-parties, at least not without a proper warning first. Otherwise we break package builds for thousands of users.

**Comment by trofi** [comment]
What are third parties exactly? Are (for example) users of `.override`, `.overrideAttrs` and `overlays = []` considered to be third-parties? I wonder if `nixpkgs` even provides a way to distinguish internal from external users.

I had an impression that external users are expected to pin to a particular revision of `nixpkgs` to get a reasonable build result. Otherwise users have to constantly adapt to internal changes like `gcc` updates, parameter additions and removals, package removal/deprecation and `.nix` file moves. Largest breakages are usually covered by release notes.

**Comment by infinisil** [comment]
Overlays make this a bit tricky because it's how Nixpkgs defines its packages internally, but third-parties can also provide overlays. So I think it's fine to treat overlays as Nixpkgs code.

But other than that, anything using the resulting `import <nixpkgs> {}` value instead of going through overlays should be considered third-party code. And it's possible to implement code that can distinguish that (it'll have to touch the core of Nixpkgs though).

> I had an impression that external users are expected to pin to a particular revision of `nixpkgs` to get a reasonable build result. Otherwise users have to constantly adapt to internal changes like `gcc` updates, parameter additions and removals, package removal/deprecation and `.nix` file moves. Largest breakages are usually covered by release notes.

While we don't yet have a clear guideline on API stability guarantees, my take on it is that we should guarantee stability for the code that we control. This includes all the Nix code in Nixpkgs, including e.g. the passthru attributes of packages. We are responsible for that code and should take care to not break it.

But this doesn't include the contents of the packages: If upstream of a package happens to break for all users, we aren't responsible for that, it's upstream that should get the complaints. We can still include a note on that in the release notes as a courtesy, but it's not required.

**Comment by AndersonTorres** [comment]
Is extra-cmake-modules affected by `strictDeps = true`?

**Comment by paparodeo** [comment]
note that cmake effectively puts buildInputs in the search path and before PATH when strictDeps is true and should probably get fixed before strictDeps becomes the default. one attempt to fix this is here https://github.com/NixOS/nixpkgs/pull/318226 but it is still a WIP.

**Comment by uninsane** [comment]
FYI we're 15 packages away from having `strictDeps = true` along the entire path of deriving `stdenv` (on x86_64-linux). it's a fun milestone to target, and it would _significantly_ reduce the rebuild count of applying `strictDepsByDefault = true`. ordered earliest -> last in the stdenv bootstrap path:
- [x] [gnu-config](https://github.com/NixOS/nixpkgs/pull/483771)
- [ ] bison
- [ ] libxcrypt
- [ ] libidn2
- [ ] attr
- [ ] gzip
- [ ] gnused
- [x] acl
- [ ] coreutils
- [x] gnumake
- [x] [lzip](https://github.com/NixOS/nixpkgs/pull/483833)
- [x] [gnutar](https://github.com/NixOS/nixpkgs/pull/503199)
- [x] [gnupatch](https://github.com/NixOS/nixpkgs/pull/531562) (a.k.a. `patch`)
- [ ] findutils
- [ ] diffutils

**Comment by Eveeifyeve** [comment]
Could someone provide an updated list to what needs to be worked on?
