### ISSUE TITLE
Use of $NIX_BUILD_TOP considered harmful

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixpkgs#189691]
### Describe the bug
Nix expressions that rely on `$NIX_BUILD_TOP` may break under `nix-shell` (or when using `nativeBuildInputs = [ keepBuildTree ]`), so let's try to avoid it.

### Steps To Reproduce
1. Find a package that uses `$NIX_BUILD_TOP`, e.g. `spotifyd` via cargo setup hook: `nix-shell -A spotifyd`
2. Run `genericBuild` inside the shell.
3. Watch it fail trying to work with files inside `$NIX_BUILD_TOP` (when the files actually are in `$PWD`).

### Expected behavior
Builds work both with `nix-build` _and_ `nix-shell` (not fail in the latter case).

### Additional context
A workaround for the `nix-shell` breakage could be exporting `$NIX_BUILD_TOP` before invoking any build code. (`nix develop` has code for that?) But it wouldn't fix the `keepBuildTree` case.

### TODO list
* [x] cargo setup hook: https://github.com/NixOS/nixpkgs/issues/138554
* [ ] `writableTmpDirAsHome` setup hook: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/setup-hooks/writable-tmpdir-as-home.sh
* [ ] [buildBazelPackage](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/build-bazel-package/default.nix)
* [ ] Most other packages referring to `$NIX_BUILD_TOP`. (Some are harmless, need to check them.)

**Comment by bjornfor** [comment]
CC bazel and cargo setup hook people: @abbradar @danieldk.

Do you agree with the issue? Who else need to be aware of this issue before we start removing `$NIX_BUILD_TOP` from nixpkgs?

**Comment by bjornfor** [comment]
Another fix here: https://github.com/NixOS/nixpkgs/pull/266723

**Comment by ConnorBaker** [comment]
Following up on this, is there a consistent way to get the build directory other than `NIX_BUILD_TOP`? For example, is `TMPDIR` always equivalent?
