### ISSUE TITLE
Bug Fix Round 2

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#19075]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities since our [last hunt](https://github.com/NixOS/nixpkgs/issues/18856).

## Notes on the list
1. Some of these were probably resolved the last hunt, as I believe 10 of the issues got dropped at some point. I don't know how, but I'm thinking this list will go quickly. 19 of these issues are new.
2. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
3. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
4. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

Without further ado...

### Assorted (26 issues)
 - [x] [`#701931`](https://lwn.net/Vulnerabilities/701931/) ([search](http://search.nix.gsc.io/?q=nss&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nss+in%3Apath&type=Code))  mozilla: denial of service
 - [x] [`#647618`](https://lwn.net/Vulnerabilities/647618/) ([search](http://search.nix.gsc.io/?q=python-tornado&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-tornado+in%3Apath&type=Code))  python-tornado: side-channel attack
 - [x] [`#679619`](https://lwn.net/Vulnerabilities/679619/) ([search](http://search.nix.gsc.io/?q=OpenVPN&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=OpenVPN+in%3Apath&type=Code))  OpenVPN: multiple vulnerabilities
 - [x] [`#701926`](https://lwn.net/Vulnerabilities/701926/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities
 - [x] [`#701920`](https://lwn.net/Vulnerabilities/701920/) ([search](http://search.nix.gsc.io/?q=mactelnet&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mactelnet+in%3Apath&type=Code))  mactelnet: code execution
 - [x] [`#701727`](https://lwn.net/Vulnerabilities/701727/) ([search](http://search.nix.gsc.io/?q=wordpress&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wordpress+in%3Apath&type=Code))  wordpress: multiple vulnerabilities
 - [x] [`#701931`](https://lwn.net/Vulnerabilities/701931/) ([search](http://search.nix.gsc.io/?q=firefox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firefox+in%3Apath&type=Code))  mozilla: denial of service
 - [x] [`#684319`](https://lwn.net/Vulnerabilities/684319/) ([search](http://search.nix.gsc.io/?q=systemd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=systemd+in%3Apath&type=Code))  systemd: two vulnerabilities
 - [x] [`#701999`](https://lwn.net/Vulnerabilities/701999/) ([search](http://search.nix.gsc.io/?q=python-django&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-django+in%3Apath&type=Code))  python-django: cross-site request forgery
 - [x] [`#702118`](https://lwn.net/Vulnerabilities/702118/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [x] [`#701923`](https://lwn.net/Vulnerabilities/701923/) ([search](http://search.nix.gsc.io/?q=bash&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bash+in%3Apath&type=Code))  bash: code execution
 - [x] [`#701921`](https://lwn.net/Vulnerabilities/701921/) ([search](http://search.nix.gsc.io/?q=policycoreutils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=policycoreutils+in%3Apath&type=Code))  policycoreutils: sandbox escape
 - [x] [`#616041`](https://lwn.net/Vulnerabilities/616041/) ([search](http://search.nix.gsc.io/?q=rubygem-bundler&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rubygem-bundler+in%3Apath&type=Code))  rubygem-bundler: installs malicious gem files
 - [x] [`#633546`](https://lwn.net/Vulnerabilities/633546/) ([search](http://search.nix.gsc.io/?q=cups&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=cups+in%3Apath&type=Code))  cups: buffer overflow
 - [x] [`#701739`](https://lwn.net/Vulnerabilities/701739/) ([search](http://search.nix.gsc.io/?q=shiro&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=shiro+in%3Apath&type=Code))  shiro: access control bypass
 - [x] [`#701734`](https://lwn.net/Vulnerabilities/701734/) ([search](http://search.nix.gsc.io/?q=openvas-libraries&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openvas-libraries+in%3Apath&type=Code))  openvas-libraries: multiple vulnerabilities
 - [x] [`#675696`](https://lwn.net/Vulnerabilities/675696/) ([search](http://search.nix.gsc.io/?q=nghttp2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nghttp2+in%3Apath&type=Code))  nghttp2: denial of service
 - [x] [`#680462`](https://lwn.net/Vulnerabilities/680462/) ([search](http://search.nix.gsc.io/?q=putty&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=putty+in%3Apath&type=Code))  putty: code execution
 - [x] [`#701735`](https://lwn.net/Vulnerabilities/701735/) ([search](http://search.nix.gsc.io/?q=openvas-scanner&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openvas-scanner+in%3Apath&type=Code))  openvas-scanner: denial of service
 - [x] [`#676795`](https://lwn.net/Vulnerabilities/676795/) ([search](http://search.nix.gsc.io/?q=poco&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=poco+in%3Apath&type=Code))  poco: SSL server spoofing
 - [x] [`#701917`](https://lwn.net/Vulnerabilities/701917/) ([search](http://search.nix.gsc.io/?q=imagemagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=imagemagick+in%3Apath&type=Code))  imagemagick: code execution
 - [x] [`#683853`](https://lwn.net/Vulnerabilities/683853/) ([search](http://search.nix.gsc.io/?q=postgresql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=postgresql+in%3Apath&type=Code))  postgresql: two vulnerabilities
 - [x] [`#701918`](https://lwn.net/Vulnerabilities/701918/) ([search](http://search.nix.gsc.io/?q=dwarfutils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dwarfutils+in%3Apath&type=Code))  dwarfutils: two vulnerabilities
 - [x] [`#698651`](https://lwn.net/Vulnerabilities/698651/) ([search](http://search.nix.gsc.io/?q=borgbackup&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=borgbackup+in%3Apath&type=Code))  borgbackup: directory traversal
 - [x] [`#680795`](https://lwn.net/Vulnerabilities/680795/) ([search](http://search.nix.gsc.io/?q=proftpd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=proftpd+in%3Apath&type=Code))  proftpd: weak key usage
 - [x] [`#701997`](https://lwn.net/Vulnerabilities/701997/) ([search](http://search.nix.gsc.io/?q=wireshark-cli&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wireshark-cli+in%3Apath&type=Code))  wireshark: denial of service

### freerdp (2 issues) Note: triage indicates Gentoo is running 1.1.0 beta? 1.0.2 doesn't seem to have a fix.
 - [x] [`#702121`](https://lwn.net/Vulnerabilities/702121/) ([search](http://search.nix.gsc.io/?q=freerdp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=freerdp+in%3Apath&type=Code))  freerdp: denial of service
 - [x] [`#604034`](https://lwn.net/Vulnerabilities/604034/) ([search](http://search.nix.gsc.io/?q=freerdp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=freerdp+in%3Apath&type=Code))  freerdp: two vulnerabilities

### openssl (2 issues)
 - [x] [`#702000`](https://lwn.net/Vulnerabilities/702000/) ([search](http://search.nix.gsc.io/?q=openssl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openssl+in%3Apath&type=Code))  openssl: denial of service
 - [x] [`#701729`](https://lwn.net/Vulnerabilities/701729/) ([search](http://search.nix.gsc.io/?q=openssl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openssl+in%3Apath&type=Code))  openssl: multiple vulnerabilities

**Comment by grahamc** [comment]
This one took under an hour :)

**Comment by Mic92** [comment]
openvpn: 
- unstable has 2.3.12
- stable has 2.3.10
- the cve report talks update an update to openvpn-2.3.4
- openvpn 2.3.11: says "Fixed port-share bug with DoS potential" -> so this upgrade might be worse

**Comment by grahamc** [comment]
Thanks, @Mic92! 16.03 has 2.3.10? we should probably backport that. Would you like to do the honors?

**Comment by Mic92** [comment]
Upgrade straight to 2.3.12? Mostly bug fixes in this version.

**Comment by aneeshusa** [comment]
@grahamc, do you know if there is an RSS/Atom feed for the LWN vulnerabilities? I couldn't find one.

**Comment by grahamc** [comment]
@aneeshusa I don't think there is one. if you want to chat more, I'd rather talk about it over IRC? gchristensen

**Comment by grahamc** [comment]
@Mic92 yep, straight to 2.3.12.

**Comment by Mic92** [comment]
done: https://github.com/NixOS/nixpkgs/commit/1abec08343e6ec11c31ffe9a1844d80b098ef98d
