### ISSUE TITLE
Vulnerability Roundup 3

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#19253]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our last [hunt](https://github.com/NixOS/nixpkgs/issues/19075).

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

Without further ado...

### Assorted (15 issues)
 - [x] [`#702222`](https://lwn.net/Vulnerabilities/702222/) ([search](http://search.nix.gsc.io/?q=vfrnav&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=vfrnav+in%3Apath&type=Code))  vrfnav: unspecified
 - [x] [`#702312`](https://lwn.net/Vulnerabilities/702312/) ([search](http://search.nix.gsc.io/?q=python-twisted-web&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-twisted-web+in%3Apath&type=Code))  python-twisted-web: HTTP proxy redirect
 - [x] [`#702317`](https://lwn.net/Vulnerabilities/702317/) ([search](http://search.nix.gsc.io/?q=openjpeg&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg+in%3Apath&type=Code))  openjpeg: denial of service
 - [x] [`#702553`](https://lwn.net/Vulnerabilities/702553/) ([search](http://search.nix.gsc.io/?q=libcryptopp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libcryptopp+in%3Apath&type=Code))  libcryptopp: information disclosure
 - [x] [`#702224`](https://lwn.net/Vulnerabilities/702224/) ([search](http://search.nix.gsc.io/?q=clamav&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=clamav+in%3Apath&type=Code))  clamav: three code execution flaws
 - [x] [`#702552`](https://lwn.net/Vulnerabilities/702552/) ([search](http://search.nix.gsc.io/?q=freerdp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=freerdp+in%3Apath&type=Code))  freerdp: denial of service
 - [x] [`#702551`](https://lwn.net/Vulnerabilities/702551/) ([search](http://search.nix.gsc.io/?q=libdbd-mysql-perl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libdbd-mysql-perl+in%3Apath&type=Code))  libdbd-mysql-perl: denial of service
 - [x] [`#702477`](https://lwn.net/Vulnerabilities/702477/) ([search](http://search.nix.gsc.io/?q=openssh&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openssh+in%3Apath&type=Code))  openssh: null pointer dereference
 - [x] [`#702474`](https://lwn.net/Vulnerabilities/702474/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities
 - [x] [`#702476`](https://lwn.net/Vulnerabilities/702476/) ([search](http://search.nix.gsc.io/?q=community-mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=community-mysql+in%3Apath&type=Code))  community-mysql: unspecified
 - [x] [`#702225`](https://lwn.net/Vulnerabilities/702225/) ([search](http://search.nix.gsc.io/?q=systemd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=systemd+in%3Apath&type=Code))  systemd: denial of service
 - [x] [`#702314`](https://lwn.net/Vulnerabilities/702314/) ([search](http://search.nix.gsc.io/?q=c-ares&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=c-ares+in%3Apath&type=Code))  c-ares: code execution
 - [x] [`#702475`](https://lwn.net/Vulnerabilities/702475/) ([search](http://search.nix.gsc.io/?q=bash&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bash+in%3Apath&type=Code))  bash: code execution
 - [x] [`#702315`](https://lwn.net/Vulnerabilities/702315/) ([search](http://search.nix.gsc.io/?q=chicken&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chicken+in%3Apath&type=Code))  chicken: two vulnerabilities
 - [x] [`#702316`](https://lwn.net/Vulnerabilities/702316/) ([search](http://search.nix.gsc.io/?q=php-adodb&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php-adodb+in%3Apath&type=Code))  php-adodb: SQL injection

**Comment by danbst** [comment]
> #702225 (search, files) systemd: denial of service

this should be in master https://github.com/NixOS/nixpkgs/commit/8b09ba32d3d42392480c9691f0964dfc934de730

**Comment by grahamc** [comment]
We should try removing the ancient version of Twisted.

**Comment by Mic92** [comment]
bash in stable will be fixed by: https://github.com/NixOS/nixpkgs/pull/19274
for master I would propose an update to 4.4

**Comment by grahamc** [comment]
@fpletz Could you take a look at openssh? I'm not sure we're vulnerable...

**Comment by FRidh** [comment]
@grahamc which ancient Twisted are you referring to? We only have the latest version in Nixpkgs (except for ancient version used as example in the docs).

**Comment by grahamc** [comment]
@FRidh We seem to have `twisted_11` (which is secretly Twisted 13.)

**Comment by FRidh** [comment]
@grahamc indeed, thanks. It seems it's used only by Kippo. For now I will move that version of twisted into the Kippo package, and leave it to the maintainer, @tomberek , to update or not.

**Comment by grahamc** [comment]
Sounds great, thank you so much, @FRidh!

**Comment by tomberek** [comment]
Last time I looked, Kippo cannot be updated and is tied to that older
version. I'm dont know if the cve impacts kippo or not.

**Comment by grahamc** [comment]
Not sure. FWIW it looks like Kippo has a more active fork: https://github.com/micheloosterhof/cowrie ?

**Comment by tomberek** [comment]
Good catch. Is there interest in simply moving to Cowrie and deprecating
Kippo? Is there a way to tell if Kippo itself is used in the NixOS
community?

**Comment by fpletz** [comment]
@grahamc We can skip the openssh issue IMHO. We are vulnerable but it's just a denial of service, nothing critical. We can wait until the next patch or major release or for a CVE if there's a bigger issue hidden underneath. I'll monitor the Fedora issue.

**Comment by grahamc** [comment]
@fpletz oops, I already sent a patch ^ should we not apply / port it? also: I want to leave this open until bash gets merged to release-16.09 and master is fully resolved.
