### ISSUE TITLE
Vulnerability Roundup 4

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#19481]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last hunt](https://github.com/NixOS/nixpkgs/issues/19253).

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

Without further ado...

### Assorted (3 issues)
 - [x] [`#703123`](https://lwn.net/Vulnerabilities/703123/) ([search](http://search.nix.gsc.io/?q=graphicsmagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=graphicsmagick+in%3Apath&type=Code))  graphicsmagick: multiple vulnerabilities
 - [x] [`#702897`](https://lwn.net/Vulnerabilities/702897/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: unintended access
 - [x] [`#703105`](https://lwn.net/Vulnerabilities/703105/) ([search](http://search.nix.gsc.io/?q=messagelib&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=messagelib+in%3Apath&type=Code))  messagelib: two vulnerabilities

---
## Total remaining: 3

---
<details>
<summary><strong>Triaged and Resolved Issues</strong></summary>
### Assorted (29 issues)
 - [x] [`#703104`](https://lwn.net/Vulnerabilities/703104/) ([search](http://search.nix.gsc.io/?q=kcoreaddons&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kcoreaddons+in%3Apath&type=Code))  kcoreaddons: HTML injection
 - [x] [`#703243`](https://lwn.net/Vulnerabilities/703243/) ([search](http://search.nix.gsc.io/?q=tomcat&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat+in%3Apath&type=Code))  tomcat: privilege escalation
 - [x] [`#702896`](https://lwn.net/Vulnerabilities/702896/) ([search](http://search.nix.gsc.io/?q=nodejs4&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nodejs4+in%3Apath&type=Code))  nodejs4: two vulnerabilities
 - [x] [`#703241`](https://lwn.net/Vulnerabilities/703241/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: stack corruption
 - [x] [`#703246`](https://lwn.net/Vulnerabilities/703246/) ([search](http://search.nix.gsc.io/?q=mujs&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mujs+in%3Apath&type=Code))  mujs: two vulnerabilities
 - [x] [`#610419`](https://lwn.net/Vulnerabilities/610419/) ([search](http://search.nix.gsc.io/?q=jinja&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jinja+in%3Apath&type=Code))  jinja: privilege escalation
 - [x] [`#702898`](https://lwn.net/Vulnerabilities/702898/) ([search](http://search.nix.gsc.io/?q=chromium&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium+in%3Apath&type=Code))  oxide-qt: denial of service
 - [x] [`#703106`](https://lwn.net/Vulnerabilities/703106/) ([search](http://search.nix.gsc.io/?q=mat&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mat+in%3Apath&type=Code))  mat: information leak
 - [x] [`#702889`](https://lwn.net/Vulnerabilities/702889/) ([search](http://search.nix.gsc.io/?q=apache&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=apache+in%3Apath&type=Code))  apache: denial of service
 - [x] [`#703122`](https://lwn.net/Vulnerabilities/703122/) ([search](http://search.nix.gsc.io/?q=python-pillow&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-pillow+in%3Apath&type=Code))  python-pillow: memory disclosure
 - [x] [`#702787`](https://lwn.net/Vulnerabilities/702787/) ([search](http://search.nix.gsc.io/?q=zendframework&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=zendframework+in%3Apath&type=Code))  zendframework: SQL injection
 - [x] [`#702898`](https://lwn.net/Vulnerabilities/702898/) ([search](http://search.nix.gsc.io/?q=oxide-qt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=oxide-qt+in%3Apath&type=Code))  oxide-qt: denial of service
 - [x] [`#703244`](https://lwn.net/Vulnerabilities/703244/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: three vulnerabilities
 - [x] [`#703103`](https://lwn.net/Vulnerabilities/703103/) ([search](http://search.nix.gsc.io/?q=imagemagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=imagemagick+in%3Apath&type=Code))  imagemagick: two vulnerabilities
 - [x] [`#702789`](https://lwn.net/Vulnerabilities/702789/) ([search](http://search.nix.gsc.io/?q=ffmpeg&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ffmpeg+in%3Apath&type=Code))  ffmpeg: not well specified
 - [x] [`#651766`](https://lwn.net/Vulnerabilities/651766/) ([search](http://search.nix.gsc.io/?q=groovy&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=groovy+in%3Apath&type=Code))  groovy: code execution
 - [x] [`#702623`](https://lwn.net/Vulnerabilities/702623/) ([search](http://search.nix.gsc.io/?q=links&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=links+in%3Apath&type=Code))  links: anonymity leak
 - [x] [`#703121`](https://lwn.net/Vulnerabilities/703121/) ([search](http://search.nix.gsc.io/?q=libXvMC&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXvMC+in%3Apath&type=Code))  libXvMC: insufficient validation
 - [x] [`#702889`](https://lwn.net/Vulnerabilities/702889/) ([search](http://search.nix.gsc.io/?q=httpd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=httpd+in%3Apath&type=Code))  apache: denial of service
 - [x] [`#703109`](https://lwn.net/Vulnerabilities/703109/) ([search](http://search.nix.gsc.io/?q=libdwarf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libdwarf+in%3Apath&type=Code))  libdwarf: out-of-bounds read
 - [x] [`#703120`](https://lwn.net/Vulnerabilities/703120/) ([search](http://search.nix.gsc.io/?q=libXv&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXv+in%3Apath&type=Code))  libXv: insufficient validation
 - [x] [`#703125`](https://lwn.net/Vulnerabilities/703125/) ([search](http://search.nix.gsc.io/?q=systemd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=systemd+in%3Apath&type=Code))  systemd: denial of service
 - [x] [`#703245`](https://lwn.net/Vulnerabilities/703245/) ([search](http://search.nix.gsc.io/?q=irssi&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=irssi+in%3Apath&type=Code))  irssi: information disclosure
 - [x] [`#703117`](https://lwn.net/Vulnerabilities/703117/) ([search](http://search.nix.gsc.io/?q=libXrender&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXrender+in%3Apath&type=Code))  libXrender: insufficient validation
 - [x] [`#703113`](https://lwn.net/Vulnerabilities/703113/) ([search](http://search.nix.gsc.io/?q=libXi&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXi+in%3Apath&type=Code))  libXi: insufficient validation
 - [x] [`#703119`](https://lwn.net/Vulnerabilities/703119/) ([search](http://search.nix.gsc.io/?q=libXtst&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXtst+in%3Apath&type=Code))  libXtst: insufficient validation
 - [x] [`#703114`](https://lwn.net/Vulnerabilities/703114/) ([search](http://search.nix.gsc.io/?q=libXrandr&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXrandr+in%3Apath&type=Code))  libXrandr: insufficient validation
 - [x] [`#703111`](https://lwn.net/Vulnerabilities/703111/) ([search](http://search.nix.gsc.io/?q=libXfixes&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libXfixes+in%3Apath&type=Code))  libXfixes: integer overflow
 - [x] [`#702790`](https://lwn.net/Vulnerabilities/702790/) ([search](http://search.nix.gsc.io/?q=ntp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntp+in%3Apath&type=Code))  ntp: privilege escalation

### freeimage (2 issues)
 - [x] [`#702786`](https://lwn.net/Vulnerabilities/702786/) ([search](http://search.nix.gsc.io/?q=freeimage&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=freeimage+in%3Apath&type=Code))  freeimage: code execution
 - [x] [`#656894`](https://lwn.net/Vulnerabilities/656894/) ([search](http://search.nix.gsc.io/?q=freeimage&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=freeimage+in%3Apath&type=Code))  freeimage: integer overflow

### libav (2 issues)
 - [x] [`#702622`](https://lwn.net/Vulnerabilities/702622/) ([search](http://search.nix.gsc.io/?q=libav&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libav+in%3Apath&type=Code))  libav: buffer overflow
 - [x] [`#702621`](https://lwn.net/Vulnerabilities/702621/) ([search](http://search.nix.gsc.io/?q=libav&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libav+in%3Apath&type=Code))  libav: multiple vulnerabilities

</details>
---

**Comment by Mic92** [comment]
ntp had a ubuntu specific security issue due packaging a vulnerable cronjob script.

**Comment by grahamc** [comment]
@ttuegel we need to patch kcoreaddons with https://quickgit.kde.org/?p=kcoreaddons.git&a=commitdiff&h=96e562d9138c100498da38e4c5b4091a226dde12&o=plain

see: https://www.kde.org/info/security/advisory-20161006-1.txt

I'm not sure how to apply this patch. Could you send in a PR?

**Comment by ttuegel** [comment]
I'll prepare a PR, but this shouldn't affect us because we don't package KMail.

**Comment by ttuegel** [comment]
This is fixed for KDE 5 in 8b7f04c25a37ed416e986a3a635d5d120706d75f. We still need to find our KDE 4 maintainer to fix this vulnerability in kdepimlibs.

**Comment by grahamc** [comment]
@ttuegel I see, okay. Cool -- thank you!

Should we also backport it anyway? It seems the problem could affect other software too.

**Comment by vcunat** [comment]
The X ones were fixed in f755299.

**Comment by grahamc** [comment]
- [ ] X fixes need backporting.

**Comment by grahamc** [comment]
Ack, sorry @ttuegel -- looks like two more:

 - https://www.kde.org/info/security/advisory-20161006-2.txt
 - https://www.kde.org/info/security/advisory-20161006-3.txt

includes that messagelib vuln is related.

**Comment by ttuegel** [comment]
@grahamc We don't have KMail 5 or messagelib.

**Comment by grahamc** [comment]
X updates were pushed to staging-16.09 in  https://github.com/NixOS/nixpkgs/commit/53612bb0f5511d1c1c4b27bcffc2484ea7c44b89 , still needs merging back to release.

**Comment by grahamc** [comment]
X fixes were backported in https://github.com/NixOS/nixpkgs/commit/24dc3f203618c588057afeeebc03ba4adfb56673

**Comment by grahamc** [comment]
Last fix is Xen. I think the following needs to happen:

1. Drop support for xen_4_5_0 ... why do we even have that? Even on 16.09 if possible.
2. Rename xen_4_5_2 to just xen_4_5
3. Upgrade xen_4_5 to 4.5.5

It would also be good to packageXen 4.7 and maybe, 4.6 and remove 4.5 in unstable, see: https://wiki.xen.org/wiki/Xen_Project_Release_Features
