### ISSUE TITLE
Kolide launcher

### ISSUE THREAD

**Issue by znewman01** [NixOS/nixpkgs#195965]
For work, I (and many others) are required to install [Kolide](https://www.kolide.com/) for endpoint security. This is the least-bad endpoint security solution I've ever used. Getting this to work on NixOS is the difference between me using NixOS at work, and switching to another distro[^1]. I imagine other folks are in the same situation. Here's my goal:

[^1]: I *also* need this installed on my laptop (macOS). While I'd love to manage it via Nixpkgs, this is a lower priority for me, as the normal install works fine. Let me know in the comments if macOS support matters to you.

- I can install the [Kolide launcher](https://github.com/kolide/launcher) (MIT license) from Nixpkgs.
- I can get it running in systemd via a NixOS module (maybe a nix-darwin module too?).
- Kolide depends on [osquery](https://osquery.io/) (dual-licensed:  Apache-2.0 and GPL-2.0); I should be able to provide it with an osquery binary using a `osqueryPackage` configuration parameter in the NixOS module.

Because I need this for work, I'm willing to invest a fair bit of effort here (though help is appreciated), including being a maintainer for osquery and kolide-launcher in Nixpkgs.

### Osquery

Kolide relies very heavily on [osquery](https://osquery.io/). It [ships](https://github.com/kolide/launcher#secure-osquery-autoupdater) a ([not statically linked](https://github.com/kolide/launcher/issues/770)) copy of the official osquery releases.

osquery *used to be* in Nixpkgs, but [was removed because it broke frequently and there was no maintainer](https://github.com/NixOS/nixpkgs/pull/74081). There are a couple requests to reinstate it (https://github.com/NixOS/nixpkgs/issues/121745, https://github.com/NixOS/nixpkgs/issues/193673) but interest has been low.

### Auto-updater

Kolide has its own autoupdater for osquery (and Kolide itself, IIUC). It relies on [The Update Framework (TUF)](https://theupdateframework.com/) for package signing and metadata distribution. This isn't going to work if we install via Nix :smile: But how do we handle it? How easy will this be to disable? Maintainers should be checking signatures (maybe? if we're building from source, perhaps not). Is there any way to give some of these benefits downstream? So can we check in the Nixpkgs test suite, or even add a checkPhase to the package itself?

I actually happen to know TUF pretty well so if that winds up being an issue here I can help out.

### Building

The launcher has [its own build tooling](https://github.com/kolide/launcher/blob/main/cmd/make/make.go). It's relatively simple, but still somewhat nonstandard. There's a couple issues with it when building in Nix:

- doesn't use [trimpath](https://pkg.go.dev/cmd/go) (so embeds local paths in the binary; not reproducible)
- runs Git to get the current revision (no way to override)

### Running other binaries

Kolide winds up shelling out to a lot of other tools to query the state of your system. When it does so, it doesn't respect your `$PATH`; instead, most paths to binaries are hardcoded. This is [by design]
(https://github.com/kolide/launcher/issues/833). On NixOS, we don't have ZFS in `/usr/bin` so the ZFS checks break.

### OS-specific stuff

One of the big value-adds of Kolide is that it tracks the installed packages on your OS. However, [on NixOS, it doesn't](https://github.com/kolide/launcher/issues/868).

This is pretty subtle, actually. What counts as an installed package? In your current system profile? Current user profile? In `/nix/store` at all? In the store, but pointed to by any GC root?

## How I got it kind-of working (warning: terrible hacks)

1. [Install osquery from .deb](https://github.com/znewman01/kolide-launcher/commit/30050866be6521ab07c0ef421e12d3fa3e95a6fe).
2. Fork the launcher: https://github.com/znewman01/kolide-launcher
   1. Manually check in a (now outdated) [copy of the package update metadata](https://github.com/znewman01/kolide-launcher/commit/35a26c63a795ce4249498ec51c4d8fba78dcbb85).
   2. Patch the builder for [reproducibility and building in Nix](https://github.com/znewman01/kolide-launcher/commit/f37b02b070665a652c5de5351c919af1072d7768).
   3. Patch the [hardcoded paths to other tools](https://github.com/znewman01/kolide-launcher/commit/c48b577d814c17a3aaeb1b89288c9c1509b87cf9).
   3. Write [a flake](https://github.com/znewman01/kolide-launcher/commit/2bf0ee22860ffc560f1e2e9b4e7cd37f75366b01) for local dev and building the package.
3. Write a [module to run it in systemd](https://github.com/znewman01/kolide-launcher/commit/30050866be6521ab07c0ef421e12d3fa3e95a6fe#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R45).

   There's a minor subtlety in that you need an "enrollment secret." This is out-of-scope for any NixOS module IMO. I just stuck it in a long-lived directory on my machine; a better solution might use one of the [NixOS secret managers](https://nixos.wiki/wiki/Comparison_of_secret_managing_schemes).
4. Enable it in [my NixOS config](https://github.com/znewman01/dotfiles/commit/4826df5205c43ad32b3652ed429acab1ff2992e1). This was really easy, after the above work!

You *should* be able to get that setup working for you. Let me know if you need help, though I'd prefer to focus efforts on a long-term solution.

There's one final caveat. Presumably your workplace is making you install Kolide so that it can run a bunch of Osquery checks on your machine. NixOS is *weird*, and many very standard checks are going to fire because of the way NixOS works. I'm very fortunate to have a friendly and flexible security/compliance manager at my company who is willing to work with me on allow-listing certain NixOS behaviors. If you *aren't* in that situation, YMMV.

## Action plan

- [ ] [Coordinate with the Kolide folks](https://github.com/kolide/launcher/issues/896), who are very helpful! 
- [ ] I need to make update to my fork, including a newer osquery binary.
- [ ] Get osquery back into Nixpkgs: https://github.com/NixOS/nixpkgs/issues/193673
- [ ] Upstream fix: [send PR for hardcoded paths](https://github.com/kolide/launcher/issues/833)
- [ ] Upstream fix: copy some of [my build patches](https://github.com/znewman01/kolide-launcher/commit/f37b02b070665a652c5de5351c919af1072d7768)
- [ ] Write a Nixpkgs package for the launcher
- [ ] Write a Nixpkgs module for the launcher
- [ ] Figure out the autoupdater situation (bonus)

## How you can help!

CC @patflynn @danderson @terlar @joncoll (sorry for the random ping, you're all the folks I could find based on GH issues who care)

- GitHub thumbs-ups to let me know if you're interested:
  - This issue, if this would be helpful to you!
  - [Tracking issue](https://github.com/kolide/launcher/issues/896) for Kolide to support NixOS
  - [issue for adding osquery back]()
- Volunteer to co-maintain with me! This shouldn't be very much work, mostly reviewing/testing PRs and letting me know when things break.
  - [osquery](https://github.com/NixOS/nixpkgs/issues/121745)
  - Kolide launcher (this issue)
- Help figure out open questions:
  - [How should NixOS track installed packages](https://github.com/kolide/launcher/issues/868)?
  - What should we do about the autoupdater?
- Volunteer for some of the items in the action plan

**Comment by peterhoeg** [comment]
I suggest having a look at how dropbox is handled in NixOS - that would probably be similar to what you need.

**Comment by x10an14** [comment]
I am definitely interested in getting osquery back into nixpkgs for the purposes of kolide, so while my current capacity is reduced, I'm for sure interested in helping out/figuring it out/becoming a maintainer!

Thanks to @ngerstle who pointed me to this issue!

**Comment by 06kellyjac** [comment]
cc @Taneb 

https://github.com/NixOS/nixpkgs/issues/193673#issuecomment-1279013344

**Comment by sjdrc** [comment]
Kolide now has official support for Nix https://github.com/kolide/nix-agent

See: https://github.com/kolide/launcher/issues/896#issuecomment-1964533616
