### ISSUE TITLE
libxcrypt tracking issue for Haskell

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#196378]
* [x] Initial adjustments for packages depending on `libcrypt` (https://github.com/NixOS/nixpkgs/pull/181764)
* [x] Test and merge `libNixName` resolver update for `cabal2nix` (https://github.com/NixOS/cabal2nix/pull/576)
* [x] Regenerate package set and drop `libxcrypt` overrides after `staging-next` is merged (#195862)
* [x] Release updated `cabal2nix`, so that it'll be shipped with 22.11 (but do not backport to 22.05)
* [x] Ship cabal2nix 2.19.1 in nixpkgs

cc @NixOS/haskell
