### ISSUE TITLE
Vulnerability Roundup 5

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#19678]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last hunt](https://github.com/NixOS/nixpkgs/issues/19481).

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [ ] Update https://github.com/NixOS/nixpkgs/issues/13515 with a
    summary.

Without further ado...

### Assorted (5 issues)
 - [x] [`#703329`](https://lwn.net/Vulnerabilities/703329/) ([search](http://search.nix.gsc.io/?q=kde-cli-tools5&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kde-cli-tools5+in%3Apath&type=Code))  kde-cli-tools5: code execution
 - [ ] [`#703767`](https://lwn.net/Vulnerabilities/703767/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities
 - [x] [`#559200`](https://lwn.net/Vulnerabilities/559200/) ([search](http://search.nix.gsc.io/?q=python-suds&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-suds+in%3Apath&type=Code))  python-suds: symbolic link attack
 - [x] [`#703330`](https://lwn.net/Vulnerabilities/703330/) ([search](http://search.nix.gsc.io/?q=tracker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tracker+in%3Apath&type=Code))  tracker: denial of service
 - [x] [`#703467`](https://lwn.net/Vulnerabilities/703467/) ([search](http://search.nix.gsc.io/?q=tiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tiff+in%3Apath&type=Code))  tiff: denial of service

---
## Total remaining: 5

---
<details>
<summary><strong>Triaged and Resolved Issues</strong></summary>
### Assorted (15 issues)
 - [x] [`#703868`](https://lwn.net/Vulnerabilities/703868/) ([search](http://search.nix.gsc.io/?q=quagga&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=quagga+in%3Apath&type=Code))  quagga: stack overrun
 - [x] [`#703325`](https://lwn.net/Vulnerabilities/703325/) ([search](http://search.nix.gsc.io/?q=nsd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nsd+in%3Apath&type=Code))  nsd: denial of service
 - [x] [`#703862`](https://lwn.net/Vulnerabilities/703862/) ([search](http://search.nix.gsc.io/?q=atomic-openshift&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=atomic-openshift+in%3Apath&type=Code))  atomic-openshift: authentication bypass
 - [x] [`#658202`](https://lwn.net/Vulnerabilities/658202/) ([search](http://search.nix.gsc.io/?q=unzip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=unzip+in%3Apath&type=Code))  unzip: two vulnerabilities
 - [x] [`#703866`](https://lwn.net/Vulnerabilities/703866/) ([search](http://search.nix.gsc.io/?q=libarchive&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libarchive+in%3Apath&type=Code))  libarchive: three vulnerabilities
 - [x] [`#703328`](https://lwn.net/Vulnerabilities/703328/) ([search](http://search.nix.gsc.io/?q=libgd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgd+in%3Apath&type=Code))  libgd: denial of service
 - [x] [`#703466`](https://lwn.net/Vulnerabilities/703466/) ([search](http://search.nix.gsc.io/?q=ruby&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ruby+in%3Apath&type=Code))  ruby: encrypted ciphertext duplication
 - [x] [`#703461`](https://lwn.net/Vulnerabilities/703461/) ([search](http://search.nix.gsc.io/?q=libass&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libass+in%3Apath&type=Code))  libass: three vulnerabilities
 - [x] [`#703869`](https://lwn.net/Vulnerabilities/703869/) ([search](http://search.nix.gsc.io/?q=ffmpeg&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ffmpeg+in%3Apath&type=Code))  ffmpeg: multiple vulnerabilities
 - [x] [`#703326`](https://lwn.net/Vulnerabilities/703326/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [x] [`#703607`](https://lwn.net/Vulnerabilities/703607/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: information leak/corruption
 - [x] [`#703606`](https://lwn.net/Vulnerabilities/703606/) ([search](http://search.nix.gsc.io/?q=dbus&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dbus+in%3Apath&type=Code))  dbus: code execution
 - [x] [`#703609`](https://lwn.net/Vulnerabilities/703609/) ([search](http://search.nix.gsc.io/?q=derby&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=derby+in%3Apath&type=Code))  derby: information leak
 - [x] [`#703324`](https://lwn.net/Vulnerabilities/703324/) ([search](http://search.nix.gsc.io/?q=ghostscript&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ghostscript+in%3Apath&type=Code))  ghostscript: multiple vulnerabilities
 - [x] [`#703769`](https://lwn.net/Vulnerabilities/703769/) ([search](http://search.nix.gsc.io/?q=guile&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=guile+in%3Apath&type=Code))  guile: two vulnerabilities

### mpg123 (2 issues)
 - [x] [`#703771`](https://lwn.net/Vulnerabilities/703771/) ([search](http://search.nix.gsc.io/?q=mpg123&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mpg123+in%3Apath&type=Code))  mpg123: denial of service
 - [x] [`#586336`](https://lwn.net/Vulnerabilities/586336/) ([search](http://search.nix.gsc.io/?q=mpg123&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mpg123+in%3Apath&type=Code))  mpg123: denial of service

</details>
---

**Comment by grahamc** [comment]
Libtiff: I get the impression SUSE has about 9 patches to libtiff, based on openSUSE's `-9` version number. Would somebody look in to 4.0.6 and patches we may need to apply? There hasn't been a release in over a year.

**Comment by grahamc** [comment]
Libtiff: I get the impression SUSE has about 9 patches to libtiff, based on openSUSE's `-9` version number. Would somebody look in to 4.0.6 and patches we may need to apply? There hasn't been a release in over a year.

**Comment by grahamc** [comment]
@DamienCassou Is it okay to update Tracker to 1.10.1? https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/desktops/gnome-3/3.20/core/tracker/src.nix

**Comment by grahamc** [comment]
Suds: We have it, we are vulnerable. We should consider upgrading to 0.4.1 and apply the 5-or-so patches from Ubuntu.

**Comment by DamienCassou** [comment]
@grahamc ok for me. Should I do it myself? /cc @lethalman @groxxda

**Comment by grahamc** [comment]
If you wouldn't mind :) we should also backport to 16.09 if that is OK.

**Comment by NeQuissimus** [comment]
#19565 has my attempt at chromium from a few days ago. I could not figure out what was going on and quit. But it will at least give somebody a place to start :)

**Comment by grahamc** [comment]
@NeQuissimus I wonder about only upgrading stable (that one worked ok, right?) and holding off on the other two, in order to get it out. @aszlig?

**Comment by NeQuissimus** [comment]
I think I must have done something wrong. Trying it again, even the updated stable does not build, with the same issue I mentioned in the PR.

**Comment by aszlig** [comment]
The problem here is that Chromium is transitioning to GN and are phasing out GYP, so the newer versions come with a pretty broken GYP build. I've pushed a WIP branch a few days ago to https://github.com/aszlig/nixpkgs/tree/chromium-gn, but haven't picked up on it because I'm currently moving. Cc: @bendlas

**Comment by grahamc** [comment]
@aszlig I don't really know anything about chromium, gyp, or gn, and so don't feel brave enough to take on the project of upgrading chromium in this case. Thank you for having maintained Chromium this whole time. Unless someone else steps up, I'm going to leave chromium unchecked on this issue, knowing you're on it :)

**Comment by grahamc** [comment]
re KDE: https://github.com/NixOS/nixpkgs/commit/9cd8b4e2d7846d897787963d5a2e11d3c12f30e1

**Comment by NeQuissimus** [comment]
Just came across this. I think we should include Oracle JDK and MySQL

http://www.oracle.com/technetwork/security-advisory/cpuoct2016-2881722.html

**Comment by grahamc** [comment]
Agreed @NeQuissimus. Can you post comments here summarizing the issues / any assigned CVEs / affected packages?

**Comment by NeQuissimus** [comment]
I'll even send PRs if you can wait until tonight :-)

**Comment by NeQuissimus** [comment]
Java SE:
http://www.oracle.com/technetwork/security-advisory/cpuoct2016-2881722.html#AppendixJAVA

_Fixed CVEs_
- CVE-2016-5556
- CVE-2016-5568
- CVE-2016-5582
- CVE-2016-5573
- CVE-2016-5597
- CVE-2016-5554
- CVE-2016-5542

**Comment by NeQuissimus** [comment]
MySQL:
http://www.oracle.com/technetwork/security-advisory/cpuoct2016-2881722.html#AppendixMSQL

_Fixed CVEs_

- CVE-2016-6304
- CVE-2016-6662
- CVE-2016-5617
- CVE-2016-5616
- CVE-2016-5625
- CVE-2016-5609
- CVE-2016-5612
- CVE-2016-5624
- CVE-2016-5626
- CVE-2016-5627
- CVE-2016-3492
- CVE-2016-7440
- CVE-2016-5628
- CVE-2016-5629
- CVE-2016-3495
- CVE-2016-5630
- CVE-2016-5507
- CVE-2016-5631
- CVE-2016-5632
- CVE-2016-5633
- CVE-2016-5634
- CVE-2016-5635
- CVE-2016-8289
- CVE-2016-8287
- CVE-2016-8290
- CVE-2016-5584
- CVE-2016-8283
- CVE-2016-8288
- CVE-2016-8286
- CVE-2016-8284

**Comment by NeQuissimus** [comment]
There you go :)

**Comment by grahamc** [comment]
pythonPackages.suds: mark as broken in 58e46e2 / 7145fec.

**Comment by grahamc** [comment]
Thank you, everyone, for these patches :) remaining questions: KDE, Chromium, tracker porting to unstable, and the libtiff merge.
