### ISSUE TITLE
Vulnerability Roundup 6

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#19884]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last hunt](https://github.com/NixOS/nixpkgs/issues/19678).

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Update https://github.com/NixOS/nixpkgs/issues/13515 with a
    summary.

Without further ado...

### Assorted (7 issues)
 - [x] [`#703983`](https://lwn.net/Vulnerabilities/703983/) ([search](http://search.nix.gsc.io/?q=epiphany&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=epiphany+in%3Apath&type=Code))  epiphany: unspecified
 - [x] [`#704470`](https://lwn.net/Vulnerabilities/704470/) ([search](http://search.nix.gsc.io/?q=libX11&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libX11+in%3Apath&type=Code))  libX11: insufficient validation
 - [x] [`#704249`](https://lwn.net/Vulnerabilities/704249/) ([search](http://search.nix.gsc.io/?q=openslp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openslp+in%3Apath&type=Code))  openslp: code execution
 - [x] [`#703983`](https://lwn.net/Vulnerabilities/703983/) ([search](http://search.nix.gsc.io/?q=webkitgtk4&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=webkitgtk4+in%3Apath&type=Code))  epiphany: unspecified
 - [ ] [`#703767`](https://lwn.net/Vulnerabilities/703767/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities
 - [x] [`#703987`](https://lwn.net/Vulnerabilities/703987/) ([search](http://search.nix.gsc.io/?q=asterisk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=asterisk+in%3Apath&type=Code))  asterisk: denial of service
 - [x] [`#703975`](https://lwn.net/Vulnerabilities/703975/) ([search](http://search.nix.gsc.io/?q=java-1.8.0-openjdk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=java-1.8.0-openjdk+in%3Apath&type=Code))  java-1.8.0-openjdk: multiple vulnerabilities

### kernel (2 issues)
 - [x] [`#704120`](https://lwn.net/Vulnerabilities/704120/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: multiple vulnerabilities
 - [x] [`#704469`](https://lwn.net/Vulnerabilities/704469/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service

---
## Total remaining: 9

---
<details>
<summary><strong>Triaged and Resolved Issues</strong></summary>
### Assorted (10 issues)
 - [x] [`#704466`](https://lwn.net/Vulnerabilities/704466/) ([search](http://search.nix.gsc.io/?q=php&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php+in%3Apath&type=Code))  php: multiple vulnerabilities
 - [x] [`#704467`](https://lwn.net/Vulnerabilities/704467/) ([search](http://search.nix.gsc.io/?q=php-pecl-zip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php-pecl-zip+in%3Apath&type=Code))  php-pecl-zip: multiple vulnerabilities
 - [x] [`#704248`](https://lwn.net/Vulnerabilities/704248/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [x] [`#704589`](https://lwn.net/Vulnerabilities/704589/) ([search](http://search.nix.gsc.io/?q=mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql+in%3Apath&type=Code))  mysql: multiple unspecified vulnerabilities
 - [x] [`#703978`](https://lwn.net/Vulnerabilities/703978/) ([search](http://search.nix.gsc.io/?q=dwarfutils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dwarfutils+in%3Apath&type=Code))  dwarfutils: three vulnerabilities
 - [x] [`#704586`](https://lwn.net/Vulnerabilities/704586/) ([search](http://search.nix.gsc.io/?q=virtualbox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=virtualbox+in%3Apath&type=Code))  virtualbox: multiple unspecified vulnerabilities
 - [x] [`#704468`](https://lwn.net/Vulnerabilities/704468/) ([search](http://search.nix.gsc.io/?q=kdump&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kdump+in%3Apath&type=Code))  kdump: denial of service
 - [x] [`#703977`](https://lwn.net/Vulnerabilities/703977/) ([search](http://search.nix.gsc.io/?q=tor&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tor+in%3Apath&type=Code))  tor: denial of service
 - [x] [`#703979`](https://lwn.net/Vulnerabilities/703979/) ([search](http://search.nix.gsc.io/?q=libgd2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgd2+in%3Apath&type=Code))  libgd2: two vulnerabilities
 - [x] [`#703984`](https://lwn.net/Vulnerabilities/703984/) ([search](http://search.nix.gsc.io/?q=libgit2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgit2+in%3Apath&type=Code))  libgit2: two vulnerabilities

### qemu (2 issues)
 - [x] [`#704471`](https://lwn.net/Vulnerabilities/704471/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: denial of service
 - [x] [`#703985`](https://lwn.net/Vulnerabilities/703985/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: three vulnerabilities

</details>
---

**Comment by grahamc** [comment]
5456d8f00729a5591d66208bd175cee24bd6fb59 0f42ee7c8893cf62d9a15402ad32f58d5c381e1b were ported in 732930b and bd2568a (php upgrades) to 16.09

**Comment by grahamc** [comment]
cc people who participated in the last one: @DamienCassou @NeQuissimus @aszlig @jgeerds.

**Comment by grahamc** [comment]
Firefox updates by @edolstra (thank you for backporting) https://github.com/NixOS/nixpkgs/compare/bd2568a2f927...0195ab84607a

**Comment by NeQuissimus** [comment]
I'll take care of the kernel notifications. We need to update 4.1.x

**Comment by grahamc** [comment]
Thank you :) Looks like 4.9 is out of date (rc2?) -- could you also look to see if the other kernels are seriously out of date, and just make a note here?

**Comment by NeQuissimus** [comment]
I think qemu is covered by what we have.

**Comment by NeQuissimus** [comment]
The OpenJDK one is definitely covered, I updated that yesterday

**Comment by grahamc** [comment]
I was just dreading that update :)

**Comment by grahamc** [comment]
I just collapsed the done items to make the rest easier to find.

**Comment by grahamc** [comment]
Whoa, I didn't actually expect updates on all the kernels! :100: :trophy:

**Comment by NeQuissimus** [comment]
Might as well :D
I let each of them go beyond the asking for modules, which is generally where they fail if anything is wrong. I don't have the time to build 5 full kernels right now :D

**Comment by grahamc** [comment]
I'll do a merge and build them all on my build box today.

**Comment by NeQuissimus** [comment]
It would take me a while:

```
▶ cat /proc/cpuinfo | grep 'model name' | head -1
model name      : Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz
```

**Comment by NeQuissimus** [comment]
You have the same epiphany notice twice and I would think it is not covered. But it seems to be part of GNOME 3.20/3.22 and I know there are a few PRs for that right now. Not sure if we'd break something... The epiphany files are auto-generated. (currently 3.20.3, needs 3.20.4)

**Comment by grahamc** [comment]
I usually ping @DamienCassou about Gnome issues (is @DamienCassou the one for that? :))

**Comment by NeQuissimus** [comment]
And I can't find libX11 in nixpkgs. I am not very familiar with X, so it might be in some other file but I am not sure where to look.

**Comment by grahamc** [comment]
Not sure who to ping on X11. I bet @vcunat knows?

**Comment by grahamc** [comment]
---

**Comment by grahamc** [comment]
https://github.com/NixOS/nixpkgs/commit/9db03c1cf18e215ca9559e8f8a629dc6b1ad5385 should probably be backported.

**Comment by FRidh** [comment]
libX11 is at https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/x11/xorg/default.nix#L682

**Comment by vcunat** [comment]
That X advisory was fixed weeks ago in 53612bb0f.

**Comment by vcunat** [comment]
For future reference, I do seem to be the most active in updating basic X packages, and I do watch their announcement ML.

**Comment by grahamc** [comment]
@NeQuissimus re epiphany being listed twice, the second search is for webkitgtk.

**Comment by grahamc** [comment]
OK FWIW everything in the list (except Chromium) has a PR in for it. I'm running builds for the remaining PRs now and will hopefully have most of them done by morning, where we'll merge. OpenJDK hasn't been backported because the patch doesn't apply cleanly. I'm hoping Tim will check that out.

**Comment by grahamc** [comment]
Thank you everyone, for your great help!
