### ISSUE TITLE
Vulnerability Roundup 7

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#20078]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last hunt](https://github.com/NixOS/nixpkgs/issues/19884).

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Update https://github.com/NixOS/nixpkgs/issues/13515 with a
    summary.

Without further ado...

### Assorted (21 issues)
 - [x] [`#705119`](https://lwn.net/Vulnerabilities/705119/) ([search](http://search.nix.gsc.io/?q=cairo&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=cairo+in%3Apath&type=Code))  cairo: denial of service
 - [x] [`#704699`](https://lwn.net/Vulnerabilities/704699/) ([search](http://search.nix.gsc.io/?q=nss&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nss+in%3Apath&type=Code))  nspr, nss: information disclosure
 - [x] [`#705125`](https://lwn.net/Vulnerabilities/705125/) ([search](http://search.nix.gsc.io/?q=ImageMagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ImageMagick+in%3Apath&type=Code))  imagemagick: multiple vulnerabilities
 - [ ] [`#705216`](https://lwn.net/Vulnerabilities/705216/) ([search](http://search.nix.gsc.io/?q=tar&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tar+in%3Apath&type=Code))  tar: file overwrite
 - [x] [`#705214`](https://lwn.net/Vulnerabilities/705214/) ([search](http://search.nix.gsc.io/?q=memcached&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=memcached+in%3Apath&type=Code))  memcached: code execution
 - [x] [`#704699`](https://lwn.net/Vulnerabilities/704699/) ([search](http://search.nix.gsc.io/?q=nspr&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nspr+in%3Apath&type=Code))  nspr, nss: information disclosure
 - [x] [`#704698`](https://lwn.net/Vulnerabilities/704698/) ([search](http://search.nix.gsc.io/?q=nginx&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nginx+in%3Apath&type=Code))  nginx: privilege escalation
 - [x] [`#704922`](https://lwn.net/Vulnerabilities/704922/) ([search](http://search.nix.gsc.io/?q=nodejs-tough-cookie&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nodejs-tough-cookie+in%3Apath&type=Code))  nodejs-tough-cookie: denial of service
 - [x] [`#705213`](https://lwn.net/Vulnerabilities/705213/) ([search](http://search.nix.gsc.io/?q=libxml2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libxml2+in%3Apath&type=Code))  libxml2: code execution
 - [ ] [`#703767`](https://lwn.net/Vulnerabilities/703767/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities
 - [x] [`#704924`](https://lwn.net/Vulnerabilities/704924/) ([search](http://search.nix.gsc.io/?q=tre&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tre+in%3Apath&type=Code))  tre: code execution
 - [x] [`#704712`](https://lwn.net/Vulnerabilities/704712/) ([search](http://search.nix.gsc.io/?q=seamonkey&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=seamonkey+in%3Apath&type=Code))  mozilla: two vulnerabilities
 - [x] [`#704702`](https://lwn.net/Vulnerabilities/704702/) ([search](http://search.nix.gsc.io/?q=perl-Image-Info&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=perl-Image-Info+in%3Apath&type=Code))  perl-Image-Info: information disclosure
 - [x] [`#705124`](https://lwn.net/Vulnerabilities/705124/) ([search](http://search.nix.gsc.io/?q=chromium&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium+in%3Apath&type=Code))  chromium: denial of service
 - [x] [`#704834`](https://lwn.net/Vulnerabilities/704834/) ([search](http://search.nix.gsc.io/?q=openstack-manila-ui&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openstack-manila-ui+in%3Apath&type=Code))  openstack-manila-ui: cross-site scripting
 - [x] [`#705120`](https://lwn.net/Vulnerabilities/705120/) ([search](http://search.nix.gsc.io/?q=qemu-kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu-kvm+in%3Apath&type=Code))  qemu-kvm: multiple vulnerabilities
 - [x] [`#668545`](https://lwn.net/Vulnerabilities/668545/) ([search](http://search.nix.gsc.io/?q=libpng&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libpng+in%3Apath&type=Code))  libpng: read underflow
 - [x] [`#620056`](https://lwn.net/Vulnerabilities/620056/) ([search](http://search.nix.gsc.io/?q=sssd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sssd+in%3Apath&type=Code))  sssd: restriction bypass
 - [x] [`#704701`](https://lwn.net/Vulnerabilities/704701/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: three vulnerabilities
 - [x] [`#704697`](https://lwn.net/Vulnerabilities/704697/) ([search](http://search.nix.gsc.io/?q=asterisk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=asterisk+in%3Apath&type=Code))  asterisk: two vulnerabilities
 - [x] [`#704712`](https://lwn.net/Vulnerabilities/704712/) ([search](http://search.nix.gsc.io/?q=firefox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firefox+in%3Apath&type=Code))  mozilla: two vulnerabilities

### graphicsmagick (3 issues)
 - [x] [`#704703`](https://lwn.net/Vulnerabilities/704703/) ([search](http://search.nix.gsc.io/?q=graphicsmagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=graphicsmagick+in%3Apath&type=Code))  graphicsmagick: three vulnerabilities
 - [x] [`#704711`](https://lwn.net/Vulnerabilities/704711/) ([search](http://search.nix.gsc.io/?q=graphicsmagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=graphicsmagick+in%3Apath&type=Code))  graphicsmagick: multiple vulnerabilities
 - [x] [`#704704`](https://lwn.net/Vulnerabilities/704704/) ([search](http://search.nix.gsc.io/?q=graphicsmagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=graphicsmagick+in%3Apath&type=Code))  graphicsmagick: multiple vulnerabilities

### kernel (2 issues)
 - [x] [`#704737`](https://lwn.net/Vulnerabilities/704737/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: local privilege escalation (Dirty COW)
 - [x] [`#704714`](https://lwn.net/Vulnerabilities/704714/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: three vulnerabilities

### mariadb (2 issues)
 - [x] [`#705212`](https://lwn.net/Vulnerabilities/705212/) ([search](http://search.nix.gsc.io/?q=mariadb&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mariadb+in%3Apath&type=Code))  mysql: unspecified vulnerability
 - [x] [`#705211`](https://lwn.net/Vulnerabilities/705211/) ([search](http://search.nix.gsc.io/?q=mariadb&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mariadb+in%3Apath&type=Code))  mariadb: multiple unspecified vulnerabilities

### mysql (2 issues)
 - [x] [`#705212`](https://lwn.net/Vulnerabilities/705212/) ([search](http://search.nix.gsc.io/?q=mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql+in%3Apath&type=Code))  mysql: unspecified vulnerability
 - [x] [`#705211`](https://lwn.net/Vulnerabilities/705211/) ([search](http://search.nix.gsc.io/?q=mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql+in%3Apath&type=Code))  mariadb: multiple unspecified vulnerabilities

### potrace (2 issues)
 - [x] [`#704700`](https://lwn.net/Vulnerabilities/704700/) ([search](http://search.nix.gsc.io/?q=potrace&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=potrace+in%3Apath&type=Code))  potrace: multiple vulnerabilities
 - [x] [`#639578`](https://lwn.net/Vulnerabilities/639578/) ([search](http://search.nix.gsc.io/?q=potrace&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=potrace+in%3Apath&type=Code))  potrace: denial of service

**Comment by grahamc** [comment]
cc @FRidh, @fpletz, @NeQuissimus, @vcunat who participated last time.

Also: 

 - [ ] Backport 11 curl patch to 16.09: 1e1609da6ad87fe828973f17f1f175b3de841383

**Comment by rycee** [comment]
The `perl-Image-Info` package is vulnerable. I will push an updated version shortly.

**Comment by grahamc** [comment]
@rycee Thank you for the patches and what-not! When you push a commit to a branch, can you add a comment on this issue with the package, and the sha that you fixed it in? that'll help me do the summary at the end.

**Comment by grahamc** [comment]
perl-Image-Info: https://github.com/NixOS/nixpkgs/commit/68f2bc8fb351065fda55c8a7b1ee6d74ba64a9a0 /

**Comment by rycee** [comment]
@grahamc Sorry, I missed that. I'll make sure to include the commit hashes in the future.

**Comment by fpletz** [comment]
Django (not yet on LWN): 6ad14d42569ffbf214ee301aaa9f47370bc5555d, 58ad105cd43356e3de024fbf7df2d34f10d696df, b806e14a3ced762ec2b0ce162c75d400f312e897

https://www.djangoproject.com/weblog/2016/nov/01/security-releases/

We should remove Django 1.5 and 1.6 as they're not maintained upstream anymore.  One of the users of Django 1.6 in nixpks, reviewboard, is maintaining a version with security patches, maybe switch to this: https://www.reviewboard.org/news/2016/11/01/new-django-1-6-11-5-security-releases/

I'm currently investigating and will open a PR shortly if all goes well.

**Comment by NeQuissimus** [comment]
I just took a quick look at `gnutar` and it needs to be changed to pull from git. But something is wrong with `fetchgit`, it complains about an issue in `cpio` of all things. Not really sure what to do.

**Comment by NeQuissimus** [comment]
`nginx` is up-to-date. I think the vulnerability is Debian-specific

**Comment by vcunat** [comment]
@NeQuissimus: tar may pose problems due to being involved in bootstrapping.

**Comment by NeQuissimus** [comment]
@vcunat This is how far I got:
https://gist.github.com/NeQuissimus/9a01a2215fffba1ce789ca598486fa46

1) Changed the `fetchurl` to `fetchgit`
2) `nix-build` complains about a chain of things, which lead me back to `fetchurl/boot.nix`
3) Added a `, ...` argument to the function there "fixes" the issue
4) C build does not work; and I have no idea about C builds :)

**Comment by grahamc** [comment]
@vcunat can you help me out with fixing the tar issue? I'd love to understand how that process works.

**Comment by grahamc** [comment]
BTW thank you everyone for help with this roundup. I've had an incredibly busy week, and regret not being more involved. I'll do a summary on this one shortly.

**Comment by grahamc** [comment]
I'm closing out this issue for now, but it is important to note hydra hasn't passed in some time: https://hydra.nixos.org/build/43025591 can someone diagnose this issue and try and get a fix in?

Also, we really need to get this tar issue fixed. @vcunat If not you, who could show me the process here?

**Comment by shlevy** [comment]
@grahamc What's the issue with tar? I can help.

**Comment by shlevy** [comment]
@grahamc fix for the nss issue https://github.com/NixOS/nixpkgs/commit/80cbb8acf17cd128e834d4a11f8270b9a5197166

**Comment by grahamc** [comment]
Thank you for the nss patch, @shlevy! Regarding tar, it is mishandling  `..` in archives: https://lwn.net/Vulnerabilities/705216/ which @NeQuissimus was trying to patch: https://gist.github.com/NeQuissimus/9a01a2215fffba1ce789ca598486fa46

**Comment by shlevy** [comment]
Testing a fix

**Comment by shlevy** [comment]
https://github.com/NixOS/nixpkgs/commit/ac59e2f184fe0beeec2920dc9d6d9830813d9212
https://github.com/NixOS/nixpkgs/commit/674ebc241dde3b747e8c47a5ca1b5825cba95c38

**Comment by shlevy** [comment]
Will link to jobsets shortly...

**Comment by shlevy** [comment]
Well, I wanted to link to evals but the loop is taking too long ( @edolstra @rbvermaa everyting good with hydra?) http://hydra.nixos.org/jobset/nixos/staging http://hydra.nixos.org/jobset/nixos/staging-16.09 I'll check back in the morning.

**Comment by vcunat** [comment]
It does compilation during eval! http://hydra.nixos.org/jobset/nixos/staging#tabs-errors

**Comment by vcunat** [comment]
Using git would complicate the bootstrapping process and make it longer, so it's nicer to avoid that like shlevy did.

**Comment by vcunat** [comment]
I can post a few lines about (linux stdenv) bootstrapping here/somewhere, if you're still interested.

**Comment by grahamc** [comment]
Yes please!

**Comment by shlevy** [comment]
The build-during-eval is due to the cjdns test...
