### ISSUE TITLE
Vulnerability Roundup 8

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#20274]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last hunt](https://github.com/NixOS/nixpkgs/issues/20078).

cc @rycee @fpletz @NeQuissimus @vcunat @shlevy @FRidh who were involved in the last one.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Update https://github.com/NixOS/nixpkgs/issues/13515 with a
    summary.

Without further ado...

### Assorted (31 issues)
 - [x] [`#705578`](https://lwn.net/Vulnerabilities/705578/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities
 - [x] [`#705370`](https://lwn.net/Vulnerabilities/705370/) ([search](http://search.nix.gsc.io/?q=mailman&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mailman+in%3Apath&type=Code))  mailman: cross-site request forgery
 - [x] [`#667153`](https://lwn.net/Vulnerabilities/667153/) ([search](http://search.nix.gsc.io/?q=LibRaw&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=LibRaw+in%3Apath&type=Code))  libraw: two vulnerabilities
 - [x] [`#705372`](https://lwn.net/Vulnerabilities/705372/) ([search](http://search.nix.gsc.io/?q=oxide-qt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=oxide-qt+in%3Apath&type=Code))  oxide-qt: information disclosure
 - [x] [`#705560`](https://lwn.net/Vulnerabilities/705560/) ([search](http://search.nix.gsc.io/?q=389-ds-base&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=389-ds-base+in%3Apath&type=Code))  389-ds-base: two vulnerabilities
 - [x] [`#705579`](https://lwn.net/Vulnerabilities/705579/) ([search](http://search.nix.gsc.io/?q=spip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=spip+in%3Apath&type=Code))  spip: multiple vulnerabilities
 - [x] [`#705581`](https://lwn.net/Vulnerabilities/705581/) ([search](http://search.nix.gsc.io/?q=nvidia-graphics-drivers-367&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nvidia-graphics-drivers-367+in%3Apath&type=Code))  nvidia-graphics-drivers-367: privilege escalation
 - [x] [`#705580`](https://lwn.net/Vulnerabilities/705580/) ([search](http://search.nix.gsc.io/?q=openjpeg2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg2+in%3Apath&type=Code))  openjpeg2: code execution
 - [x] [`#705822`](https://lwn.net/Vulnerabilities/705822/) ([search](http://search.nix.gsc.io/?q=tomcat&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat+in%3Apath&type=Code))  tomcat: multiple vulnerabilities
 - [x] [`#705373`](https://lwn.net/Vulnerabilities/705373/) ([search](http://search.nix.gsc.io/?q=python-django&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-django+in%3Apath&type=Code))  python-django: two vulnerabilities
 - [x] [`#705568`](https://lwn.net/Vulnerabilities/705568/) ([search](http://search.nix.gsc.io/?q=libvirt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libvirt+in%3Apath&type=Code))  libvirt: privilege escalation
 - [x] [`#705361`](https://lwn.net/Vulnerabilities/705361/) ([search](http://search.nix.gsc.io/?q=java&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=java+in%3Apath&type=Code))  java: unspecified vulnerability
 - [x] [`#705574`](https://lwn.net/Vulnerabilities/705574/) ([search](http://search.nix.gsc.io/?q=subscription-manager&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=subscription-manager+in%3Apath&type=Code))  subscription-manager: information disclosure
 - [x] [`#705915`](https://lwn.net/Vulnerabilities/705915/) ([search](http://search.nix.gsc.io/?q=ansible&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ansible+in%3Apath&type=Code))  ansible: two vulnerabilities
 - [x] [`#705566`](https://lwn.net/Vulnerabilities/705566/) ([search](http://search.nix.gsc.io/?q=libreswan&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libreswan+in%3Apath&type=Code))  libreswan: denial of service
 - [x] [`#639784`](https://lwn.net/Vulnerabilities/639784/) ([search](http://search.nix.gsc.io/?q=powerpc-utils-python&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=powerpc-utils-python+in%3Apath&type=Code))  powerpc-utils-python: code execution
 - [x] [`#705917`](https://lwn.net/Vulnerabilities/705917/) ([search](http://search.nix.gsc.io/?q=java-1.8.0-openjdk-aarch32&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=java-1.8.0-openjdk-aarch32+in%3Apath&type=Code))  java-1.8.0-openjdk-aarch32: multiple vulnerabilities
 - [x] [`#705572`](https://lwn.net/Vulnerabilities/705572/) ([search](http://search.nix.gsc.io/?q=resteasy-base&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=resteasy-base+in%3Apath&type=Code))  resteasy-base: code execution
 - [x] [`#705672`](https://lwn.net/Vulnerabilities/705672/) ([search](http://search.nix.gsc.io/?q=oracle-jre-bin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=oracle-jre-bin+in%3Apath&type=Code))  oracle-jre-bin: unspecified vulnerability
 - [x] [`#705671`](https://lwn.net/Vulnerabilities/705671/) ([search](http://search.nix.gsc.io/?q=libwebp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libwebp+in%3Apath&type=Code))  libwebp: integer overflows
 - [x] [`#705363`](https://lwn.net/Vulnerabilities/705363/) ([search](http://search.nix.gsc.io/?q=libwmf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libwmf+in%3Apath&type=Code))  libwmf: denial of service
 - [x] [`#705913`](https://lwn.net/Vulnerabilities/705913/) ([search](http://search.nix.gsc.io/?q=python-imaging&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-imaging+in%3Apath&type=Code))  python-imaging: two vulnerabilities
 - [x] [`#705575`](https://lwn.net/Vulnerabilities/705575/) ([search](http://search.nix.gsc.io/?q=sudo&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sudo+in%3Apath&type=Code))  sudo: information disclosure
 - [x] [`#705366`](https://lwn.net/Vulnerabilities/705366/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  libtiff: denial of service
 - [x] [`#705362`](https://lwn.net/Vulnerabilities/705362/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [x] [`#703767`](https://lwn.net/Vulnerabilities/703767/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities
 - [x] [`#705823`](https://lwn.net/Vulnerabilities/705823/) ([search](http://search.nix.gsc.io/?q=chromium&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium+in%3Apath&type=Code))  chromium: memory leak
 - [x] [`#705216`](https://lwn.net/Vulnerabilities/705216/) ([search](http://search.nix.gsc.io/?q=tar&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tar+in%3Apath&type=Code))  tar: file overwrite
 - [x] [`#625494`](https://lwn.net/Vulnerabilities/625494/) ([search](http://search.nix.gsc.io/?q=rpm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rpm+in%3Apath&type=Code))  rpm: code execution
 - [x] [`#705815`](https://lwn.net/Vulnerabilities/705815/) ([search](http://search.nix.gsc.io/?q=libxslt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libxslt+in%3Apath&type=Code))  libxslt: code execution
 - [x] [`#633086`](https://lwn.net/Vulnerabilities/633086/) ([search](http://search.nix.gsc.io/?q=dbus&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dbus+in%3Apath&type=Code))  dbus: denial of service
### curl (2 issues)
 - [x] [`#705367`](https://lwn.net/Vulnerabilities/705367/) ([search](http://search.nix.gsc.io/?q=curl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=curl+in%3Apath&type=Code))  curl: multiple vulnerabilities
 - [x] [`#705577`](https://lwn.net/Vulnerabilities/705577/) ([search](http://search.nix.gsc.io/?q=curl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=curl+in%3Apath&type=Code))  curl: insufficient validation
### jasper (2 issues)
 - [x] [`#705824`](https://lwn.net/Vulnerabilities/705824/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: multiple vulnerabilities
 - [x] [`#705673`](https://lwn.net/Vulnerabilities/705673/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: multiple vulnerabilities
### kernel (2 issues)
 - [x] [`#705918`](https://lwn.net/Vulnerabilities/705918/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#705565`](https://lwn.net/Vulnerabilities/705565/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: three vulnerabilities
### pacemaker (2 issues)
 - [x] [`#705571`](https://lwn.net/Vulnerabilities/705571/) ([search](http://search.nix.gsc.io/?q=pacemaker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pacemaker+in%3Apath&type=Code))  pacemaker: privilege escalation
 - [x] [`#705570`](https://lwn.net/Vulnerabilities/705570/) ([search](http://search.nix.gsc.io/?q=pacemaker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pacemaker+in%3Apath&type=Code))  pacemaker: denial of service
### tiff (2 issues)
 - [x] [`#705364`](https://lwn.net/Vulnerabilities/705364/) ([search](http://search.nix.gsc.io/?q=tiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tiff+in%3Apath&type=Code))  tiff: multiple vulnerabilities
 - [x] [`#635993`](https://lwn.net/Vulnerabilities/635993/) ([search](http://search.nix.gsc.io/?q=tiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tiff+in%3Apath&type=Code))  tiff: multiple vulnerabilities

**Comment by grahamc** [comment]
Chromium was patched in master with this merge: https://github.com/NixOS/nixpkgs/commit/c67a7ee73156796187894c63386b1a78e5902ea5 (note: don't cherry-pick merges!) and is waiting a successful build before going to 16.09.

**Comment by grahamc** [comment]
Libtiff: https://github.com/NixOS/nixpkgs/commit/d9db3208890b805569a9a85fe15fff624010fa99 plus many other commits around this issue.

**Comment by grahamc** [comment]
We're good against the current jasper issues reported here, but there are two more releases since our last update: https://github.com/mdadams/jasper/releases

**Comment by grahamc** [comment]
Ported sudo patches:

```
[release-16.09 cb35b0c] sudo: 1.8.17p1 -> 1.8.18
 Author: Alexander Ried <ried@mytum.de>
 Date: Fri Sep 23 02:01:57 2016 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
[release-16.09 6443b40] sudo: 1.8.18 -> 1.8.18p1
 Author: mimadrid <mimadrid@ucm.es>
 Date: Sun Oct 23 17:57:16 2016 +0200
 1 file changed, 2 insertions(+), 2 deletions(-)
```

**Comment by FRidh** [comment]
python-imaging (pillow) is fixed in https://github.com/NixOS/nixpkgs/commit/20d16f86cc4798b03c7ca9cd6e628964348143a1

**Comment by NeQuissimus** [comment]
All the java stuff is covered by what we have

**Comment by fpletz** [comment]
#705915 ansible: two vulnerabilities

We already have ansible 2.2.x.

**Comment by fpletz** [comment]
#705566 libreswan: denial of service

CVE-2016-5361 was misissued because this is a protocol flaw. See http://www.openwall.com/lists/oss-security/2016/06/13/1.

**Comment by fpletz** [comment]
#705671 libwebp: integer overflows

Vulnerable code (examples/giflib.c) is not present in our version of libwebp. https://chromium-review.googlesource.com/#/c/396007/

**Comment by fpletz** [comment]
#705568 libvirt: privilege escalation

Debian considers CVE-2015-5160 as a minor issue: https://security-tracker.debian.org/tracker/CVE-2015-5160

There were already patches on the qemu ML in 2011: https://www.redhat.com/archives/libvir-list/2011-November/msg00853.html. Not sure if it has been fixed in current versions, but there is no clear fix available.

**Comment by fpletz** [comment]
#705672 oracle-jre-bin: unspecified vulnerability

We have Oracle JRE/JDK > 8u102.

**Comment by NeQuissimus** [comment]
We are good for the two kernel issues, our kernels are up-to-date

**Comment by fpletz** [comment]
#667153 libraw: two vulnerabilities

Fix is in our version of libraw (0.17.1): https://github.com/LibRaw/LibRaw/commit/89d065424f09b788f443734d44857289489ca9e2

**Comment by fpletz** [comment]
#705560 389-ds-base: two vulnerabilities

CVE-2016-5405: No fix available?
CVE-2016-5416: Fixed with patch from https://fedorahosted.org/389/ticket/48354

**Comment by NeQuissimus** [comment]
I don't think qemu has anything available, it would have to be manual patching

**Comment by fpletz** [comment]
#705373 python-django: two vulnerabilities

We have the fixes already: https://www.djangoproject.com/weblog/2016/nov/01/security-releases/

**Comment by fpletz** [comment]
#705580 openjpeg2: code execution

Fix is in openjpeg 2.1.2, which we already have.

**Comment by grahamc** [comment]
Thank you all! Here is a bit of an update on my position: I moved very recently, and have been spending most of my spare time dealing with that.  Due to that, I haven't been able to help in the same capacity. That should be coming back to normal within the next couple weeks. Thank you all for stepping up and getting these done :)

**Comment by joepie91** [comment]
Commenting here for potential involvement in a future roundup :)
