### ISSUE TITLE
Vulnerability Roundup 9

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#20462]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last hunt](https://github.com/NixOS/nixpkgs/issues/20078)

cc: @FRidh, @fpletz, @rasendubi, @NeQuissimus, and @joepie91.

_Note:_ The list of people CC'd on this issue participated in the last
hunt. If you participate on this hunt, I'll cc you on the next one. If
you don't participate in the next one, you won't be CC'd on the one
after that. If you would like to be CC'd on the next hunt. If you
would like to be CC'd on the next hunt, add a comment to the most
recent vulnerability roundup. If you would like to be CC'd on _all_
hunts, leave a comment and tell @grahamc so.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [ ] Review commits since last hunt for backport candidates
 - [ ] Update https://github.com/NixOS/nixpkgs/issues/13515 with a
 summary.

Without further ado...
### Assorted (42 issues)
 - [ ] [`#705560`](https://lwn.net/Vulnerabilities/705560/) ([search](http://search.nix.gsc.io/?q=389-ds-base&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=389-ds-base+in%3Apath&type=Code))  389-ds-base: two vulnerabilities
 - [ ] [`#667153`](https://lwn.net/Vulnerabilities/667153/) ([search](http://search.nix.gsc.io/?q=LibRaw&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=LibRaw+in%3Apath&type=Code))  libraw: two vulnerabilities
 - [ ] [`#705915`](https://lwn.net/Vulnerabilities/705915/) ([search](http://search.nix.gsc.io/?q=ansible&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ansible+in%3Apath&type=Code))  ansible: two vulnerabilities
 - [ ] [`#705362`](https://lwn.net/Vulnerabilities/705362/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [ ] [`#705823`](https://lwn.net/Vulnerabilities/705823/) ([search](http://search.nix.gsc.io/?q=chromium&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium+in%3Apath&type=Code))  chromium: memory leak
 - [ ] [`#633086`](https://lwn.net/Vulnerabilities/633086/) ([search](http://search.nix.gsc.io/?q=dbus&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dbus+in%3Apath&type=Code))  dbus: denial of service
 - [ ] [`#706114`](https://lwn.net/Vulnerabilities/706114/) ([search](http://search.nix.gsc.io/?q=dracut&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dracut+in%3Apath&type=Code))  dracut: information disclosure
 - [ ] [`#705361`](https://lwn.net/Vulnerabilities/705361/) ([search](http://search.nix.gsc.io/?q=java&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=java+in%3Apath&type=Code))  java: unspecified vulnerability
 - [ ] [`#705917`](https://lwn.net/Vulnerabilities/705917/) ([search](http://search.nix.gsc.io/?q=java-1.8.0-openjdk-aarch32&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=java-1.8.0-openjdk-aarch32+in%3Apath&type=Code))  java-1.8.0-openjdk-aarch32: multiple vulnerabilities
 - [ ] [`#706478`](https://lwn.net/Vulnerabilities/706478/) ([search](http://search.nix.gsc.io/?q=libgit2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgit2+in%3Apath&type=Code))  libgit2: unspecified
 - [ ] [`#705566`](https://lwn.net/Vulnerabilities/705566/) ([search](http://search.nix.gsc.io/?q=libreswan&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libreswan+in%3Apath&type=Code))  libreswan: denial of service
 - [ ] [`#705366`](https://lwn.net/Vulnerabilities/705366/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  libtiff: denial of service
 - [ ] [`#705671`](https://lwn.net/Vulnerabilities/705671/) ([search](http://search.nix.gsc.io/?q=libwebp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libwebp+in%3Apath&type=Code))  libwebp: integer overflows
 - [ ] [`#705363`](https://lwn.net/Vulnerabilities/705363/) ([search](http://search.nix.gsc.io/?q=libwmf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libwmf+in%3Apath&type=Code))  libwmf: denial of service
 - [ ] [`#705815`](https://lwn.net/Vulnerabilities/705815/) ([search](http://search.nix.gsc.io/?q=libxslt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libxslt+in%3Apath&type=Code))  libxslt: code execution
 - [ ] [`#705370`](https://lwn.net/Vulnerabilities/705370/) ([search](http://search.nix.gsc.io/?q=mailman&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mailman+in%3Apath&type=Code))  mailman: cross-site request forgery
 - [ ] [`#706021`](https://lwn.net/Vulnerabilities/706021/) ([search](http://search.nix.gsc.io/?q=mariadb&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mariadb+in%3Apath&type=Code))  mariadb: unspecified vulnerability
 - [ ] [`#706399`](https://lwn.net/Vulnerabilities/706399/) ([search](http://search.nix.gsc.io/?q=monit&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=monit+in%3Apath&type=Code))  monit: cross-site request forgery
 - [ ] [`#706021`](https://lwn.net/Vulnerabilities/706021/) ([search](http://search.nix.gsc.io/?q=mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql+in%3Apath&type=Code))  mariadb: unspecified vulnerability
 - [ ] [`#706401`](https://lwn.net/Vulnerabilities/706401/) ([search](http://search.nix.gsc.io/?q=mysql-community-server&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql-community-server+in%3Apath&type=Code))  mysql-community-server: multiple unspecified vulnerabilities
 - [ ] [`#705581`](https://lwn.net/Vulnerabilities/705581/) ([search](http://search.nix.gsc.io/?q=nvidia-graphics-drivers-367&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nvidia-graphics-drivers-367+in%3Apath&type=Code))  nvidia-graphics-drivers-367: privilege escalation
 - [ ] [`#705580`](https://lwn.net/Vulnerabilities/705580/) ([search](http://search.nix.gsc.io/?q=openjpeg2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg2+in%3Apath&type=Code))  openjpeg2: code execution
 - [ ] [`#706402`](https://lwn.net/Vulnerabilities/706402/) ([search](http://search.nix.gsc.io/?q=opera&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=opera+in%3Apath&type=Code))  opera: multiple vulnerabilties
 - [ ] [`#705672`](https://lwn.net/Vulnerabilities/705672/) ([search](http://search.nix.gsc.io/?q=oracle-jre-bin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=oracle-jre-bin+in%3Apath&type=Code))  oracle-jre-bin: unspecified vulnerability
 - [ ] [`#705372`](https://lwn.net/Vulnerabilities/705372/) ([search](http://search.nix.gsc.io/?q=oxide-qt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=oxide-qt+in%3Apath&type=Code))  oxide-qt: information disclosure
 - [ ] [`#639784`](https://lwn.net/Vulnerabilities/639784/) ([search](http://search.nix.gsc.io/?q=powerpc-utils-python&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=powerpc-utils-python+in%3Apath&type=Code))  powerpc-utils-python: code execution
 - [ ] [`#706400`](https://lwn.net/Vulnerabilities/706400/) ([search](http://search.nix.gsc.io/?q=python-cryptography&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-cryptography+in%3Apath&type=Code))  python-cryptography: returns empty byte-string
 - [ ] [`#705373`](https://lwn.net/Vulnerabilities/705373/) ([search](http://search.nix.gsc.io/?q=python-django&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-django+in%3Apath&type=Code))  python-django: two vulnerabilities
 - [ ] [`#705913`](https://lwn.net/Vulnerabilities/705913/) ([search](http://search.nix.gsc.io/?q=python-imaging&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-imaging+in%3Apath&type=Code))  python-imaging: two vulnerabilities
 - [ ] [`#706117`](https://lwn.net/Vulnerabilities/706117/) ([search](http://search.nix.gsc.io/?q=qemu-kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu-kvm+in%3Apath&type=Code))  qemu: multiple vulnerabilities
 - [ ] [`#705572`](https://lwn.net/Vulnerabilities/705572/) ([search](http://search.nix.gsc.io/?q=resteasy-base&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=resteasy-base+in%3Apath&type=Code))  resteasy-base: code execution
 - [ ] [`#706475`](https://lwn.net/Vulnerabilities/706475/) ([search](http://search.nix.gsc.io/?q=rh-mysql56-mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rh-mysql56-mysql+in%3Apath&type=Code))  rh-mysql56-mysql: privilege escalation
 - [ ] [`#625494`](https://lwn.net/Vulnerabilities/625494/) ([search](http://search.nix.gsc.io/?q=rpm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rpm+in%3Apath&type=Code))  rpm: code execution
 - [ ] [`#658311`](https://lwn.net/Vulnerabilities/658311/) ([search](http://search.nix.gsc.io/?q=shutter&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=shutter+in%3Apath&type=Code))  shutter: code execution
 - [ ] [`#705579`](https://lwn.net/Vulnerabilities/705579/) ([search](http://search.nix.gsc.io/?q=spip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=spip+in%3Apath&type=Code))  spip: multiple vulnerabilities
 - [ ] [`#705574`](https://lwn.net/Vulnerabilities/705574/) ([search](http://search.nix.gsc.io/?q=subscription-manager&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=subscription-manager+in%3Apath&type=Code))  subscription-manager: information disclosure
 - [ ] [`#705216`](https://lwn.net/Vulnerabilities/705216/) ([search](http://search.nix.gsc.io/?q=tar&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tar+in%3Apath&type=Code))  tar: file overwrite
 - [ ] [`#706397`](https://lwn.net/Vulnerabilities/706397/) ([search](http://search.nix.gsc.io/?q=terminology&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=terminology+in%3Apath&type=Code))  terminology: command execution
 - [ ] [`#619813`](https://lwn.net/Vulnerabilities/619813/) ([search](http://search.nix.gsc.io/?q=tnftp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tnftp+in%3Apath&type=Code))  tnftp: command execution
 - [ ] [`#705822`](https://lwn.net/Vulnerabilities/705822/) ([search](http://search.nix.gsc.io/?q=tomcat&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat+in%3Apath&type=Code))  tomcat: multiple vulnerabilities
 - [ ] [`#706479`](https://lwn.net/Vulnerabilities/706479/) ([search](http://search.nix.gsc.io/?q=tre&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tre+in%3Apath&type=Code))  tre: code execution
 - [ ] [`#569768`](https://lwn.net/Vulnerabilities/569768/) ([search](http://search.nix.gsc.io/?q=xinetd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xinetd+in%3Apath&type=Code))  xinetd: privilege escalation/code execution

### chromium-browser (2 issues)
 - [ ] [`#706473`](https://lwn.net/Vulnerabilities/706473/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities
 - [ ] [`#703767`](https://lwn.net/Vulnerabilities/703767/) ([search](http://search.nix.gsc.io/?q=chromium-browser&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium-browser+in%3Apath&type=Code))  chromium-browser: multiple vulnerabilities

### curl (2 issues)
 - [ ] [`#705577`](https://lwn.net/Vulnerabilities/705577/) ([search](http://search.nix.gsc.io/?q=curl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=curl+in%3Apath&type=Code))  curl: insufficient validation
 - [ ] [`#705367`](https://lwn.net/Vulnerabilities/705367/) ([search](http://search.nix.gsc.io/?q=curl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=curl+in%3Apath&type=Code))  curl: multiple vulnerabilities

### jasper (2 issues)
 - [ ] [`#705673`](https://lwn.net/Vulnerabilities/705673/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: multiple vulnerabilities
 - [ ] [`#705824`](https://lwn.net/Vulnerabilities/705824/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: multiple vulnerabilities

### kernel (3 issues)
 - [ ] [`#706116`](https://lwn.net/Vulnerabilities/706116/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [ ] [`#705918`](https://lwn.net/Vulnerabilities/705918/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [ ] [`#705565`](https://lwn.net/Vulnerabilities/705565/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: three vulnerabilities

### libvirt (2 issues)
 - [ ] [`#669529`](https://lwn.net/Vulnerabilities/669529/) ([search](http://search.nix.gsc.io/?q=libvirt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libvirt+in%3Apath&type=Code))  libvirt: path traversal
 - [ ] [`#705568`](https://lwn.net/Vulnerabilities/705568/) ([search](http://search.nix.gsc.io/?q=libvirt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libvirt+in%3Apath&type=Code))  libvirt: privilege escalation

### ntp (4 issues)
 - [ ] [`#656982`](https://lwn.net/Vulnerabilities/656982/) ([search](http://search.nix.gsc.io/?q=ntp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntp+in%3Apath&type=Code))  ntp: multiple vulnerabilities
 - [ ] [`#661765`](https://lwn.net/Vulnerabilities/661765/) ([search](http://search.nix.gsc.io/?q=ntp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntp+in%3Apath&type=Code))  ntp: multiple vulnerabilities
 - [ ] [`#673451`](https://lwn.net/Vulnerabilities/673451/) ([search](http://search.nix.gsc.io/?q=ntp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntp+in%3Apath&type=Code))  ntp: missing check for zero originate timestamp
 - [ ] [`#674069`](https://lwn.net/Vulnerabilities/674069/) ([search](http://search.nix.gsc.io/?q=ntp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntp+in%3Apath&type=Code))  ntp: multiple vulnerabilities

### pacemaker (2 issues)
 - [ ] [`#705571`](https://lwn.net/Vulnerabilities/705571/) ([search](http://search.nix.gsc.io/?q=pacemaker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pacemaker+in%3Apath&type=Code))  pacemaker: privilege escalation
 - [ ] [`#705570`](https://lwn.net/Vulnerabilities/705570/) ([search](http://search.nix.gsc.io/?q=pacemaker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pacemaker+in%3Apath&type=Code))  pacemaker: denial of service

### qemu (2 issues)
 - [ ] [`#706117`](https://lwn.net/Vulnerabilities/706117/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities
 - [ ] [`#705578`](https://lwn.net/Vulnerabilities/705578/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities

### sudo (3 issues)
 - [ ] [`#706476`](https://lwn.net/Vulnerabilities/706476/) ([search](http://search.nix.gsc.io/?q=sudo&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sudo+in%3Apath&type=Code))  sudo: privilege escalation
 - [ ] [`#706398`](https://lwn.net/Vulnerabilities/706398/) ([search](http://search.nix.gsc.io/?q=sudo&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sudo+in%3Apath&type=Code))  sudo: privilege escalation
 - [ ] [`#705575`](https://lwn.net/Vulnerabilities/705575/) ([search](http://search.nix.gsc.io/?q=sudo&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sudo+in%3Apath&type=Code))  sudo: information disclosure

### tiff (2 issues)
 - [ ] [`#705364`](https://lwn.net/Vulnerabilities/705364/) ([search](http://search.nix.gsc.io/?q=tiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tiff+in%3Apath&type=Code))  tiff: multiple vulnerabilities
 - [ ] [`#635993`](https://lwn.net/Vulnerabilities/635993/) ([search](http://search.nix.gsc.io/?q=tiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tiff+in%3Apath&type=Code))  tiff: multiple vulnerabilities

**Comment by FRidh** [comment]
We have pillow 3.4.2 on master and stable so
> #705913 (search, files) python-imaging: two vulnerabilities
is irrelevant.

**Comment by FRidh** [comment]
77cdbb9e3af9fcdd6edafa74695f6b00bdd89748 and ca250267989c68bead978615809c1cf9d05d00e5 fix

>  #706400 (search, files) python-cryptography: returns empty byte-string

**Comment by grahamc** [comment]
Fixed jasper in https://github.com/NixOS/nixpkgs/pull/20466

**Comment by grahamc** [comment]
Curl seems to been fixed already.

**Comment by grahamc** [comment]
kmicu pointed out I failed to exclude vulnerability roundup 8's list, fixing... please hold.

**Comment by joepie91** [comment]
@grahamc Hereby requesting a CC for the next roundup and every one after that :)

**Comment by grahamc** [comment]
Fixed the list, the things which had been checked off (due to already being fixed) have been removed from this list.

**Comment by grahamc** [comment]
Sudo was addressed already.

**Comment by NeQuissimus** [comment]
With the latest kernels, we have those vulnerabilities covered.

**Comment by NeQuissimus** [comment]
qemu has a `2.8.0-rc0`, which fixed the vulns, do we want an RC?

**Comment by grahamc** [comment]
mariadb needs updates for

```
Fixes for the following security vulnerabilities:

    CVE-2016-7440
    CVE-2016-5584
```

https://mariadb.com/kb/en/mariadb/mariadb-10119-release-notes/

**Comment by NeQuissimus** [comment]
done xD

**Comment by NeQuissimus** [comment]
I marked off `rh-mysql56-mysql` because we don't have 5.6

**Comment by grahamc** [comment]
> qemu has a 2.8.0-rc0, which fixed the vulns, do we want an RC?

Probably not, especially since it is -> `.8`. Is there a patch other distros are shipping?

**Comment by NeQuissimus** [comment]
We are good for `ntp`.

For qemu, I am not sure, I just went and checked their website.

**Comment by NeQuissimus** [comment]
Chromium is fine, we have the version that fixed the vuln.

**Comment by grahamc** [comment]
Patch for xinetd incoming.

**Comment by grahamc** [comment]
Shutter patch in my rollup

**Comment by grahamc** [comment]
@rickynils do we need to be upgrading our libvirt to cover this issue? https://lwn.net/Vulnerabilities/669529/

**Comment by grahamc** [comment]
@fpletz can you take a look at the qemu vulns? there is a big list of CVEs now.

**Comment by grahamc** [comment]
@Mic92 how do you want to handle this monit issue? backport the patch, or backport an upgrade to monit?

**Comment by rickynils** [comment]
@grahamc We have libvirt 2.2.0 both in `master` and `release-16.09` and it includes the fix for CVE-2015-5313 (https://github.com/libvirt/libvirt/commit/034e47c338b13a95cf02106a3af912c1c5f818d7), so we should be fine.

**Comment by grahamc** [comment]
Thank you for checking in to that, @rickynils -- it wasn't so clear to me. Checked it as done!

**Comment by fpletz** [comment]
For qemu, only CVE-2016-7994 & CVE-2016-8668 had to be fixed.

Done in f4a318b528cacdd5c960bf66662131ecbdb2536f. Testing build on 16.09 right now and will push when finished.

**Comment by grahamc** [comment]
@fpletz can you comment and CC me when you've backported the qemu fix? I have an advisory ready to post when you do. Thank you!

**Comment by phanimahesh** [comment]
Requesting a cc on next hunt

**Comment by fpletz** [comment]
@grahamc Went to sleep too soon. :) Pushed to release-16.09.
