### ISSUE TITLE
Vulnerability Roundup 11

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#20814]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/20647)

cc: @fpletz, @phanimahesh, @NeQuissimus, @vcunat.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup.
If you would like to be CC'd on the next roundup, add a comment to the
most recent vulnerability roundup. If you would like to be CC'd on
_all_ roundups, leave a comment and tell @grahamc so.

Permanent CC's: @joepie91, @NixOS/security-notifications
(if you no longer want to be CC'd, ask to be removed from this list)

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [ ] Run the issue through `reformat` one last time
 - [ ] Review commits since last roundup for backport candidates
 - [ ] Update https://github.com/NixOS/nixpkgs/issues/13515 with a
 summary.
 - [ ] Update the database at https://github.com/NixOS/security

Without further ado...
### Assorted (5 issues)
 - [x] [`#707496`](https://lwn.net/Vulnerabilities/707496/) ([search](http://search.nix.gsc.io/?q=bzip2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bzip2+in%3Apath&type=Code))  bzip2: denial of service
 - [ ] [`#707363`](https://lwn.net/Vulnerabilities/707363/) ([search](http://search.nix.gsc.io/?q=kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kvm+in%3Apath&type=Code))  kvm: denial of service
 - [x] [`#707357`](https://lwn.net/Vulnerabilities/707357/) ([search](http://search.nix.gsc.io/?q=libgc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgc+in%3Apath&type=Code))  libgc: code execution
 - [x] [`#657992`](https://lwn.net/Vulnerabilities/657992/) ([search](http://search.nix.gsc.io/?q=rpcbind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rpcbind+in%3Apath&type=Code))  rpcbind: denial of service
 - [x] [`#707214`](https://lwn.net/Vulnerabilities/707214/) ([search](http://search.nix.gsc.io/?q=testdisk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=testdisk+in%3Apath&type=Code))  testdisk: code execution

### icu (2 issues)
 - [x] [`#707489`](https://lwn.net/Vulnerabilities/707489/) ([search](http://search.nix.gsc.io/?q=icu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=icu+in%3Apath&type=Code))  icu: code execution
 - [x] [`#707360`](https://lwn.net/Vulnerabilities/707360/) ([search](http://search.nix.gsc.io/?q=icu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=icu+in%3Apath&type=Code))  icu: code execution

---
## 7 remaining, 18 completed

<details><summary><strong>
    CLICK TO EXPAND Show all 18 triaged and resolved issues
  </strong></summary>

### Assorted (16 issues)
 - [x] [`#707215`](https://lwn.net/Vulnerabilities/707215/) ([search](http://search.nix.gsc.io/?q=dovecot22&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dovecot22+in%3Apath&type=Code))  dovecot22: information disclosure
 - [x] [`#707364`](https://lwn.net/Vulnerabilities/707364/) ([search](http://search.nix.gsc.io/?q=lxc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=lxc+in%3Apath&type=Code))  lxc: directory traversal
 - [x] [`#707494`](https://lwn.net/Vulnerabilities/707494/) ([search](http://search.nix.gsc.io/?q=python-tornado&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-tornado+in%3Apath&type=Code))  python-tornado: XSRF protection bypass
 - [x] [`#707356`](https://lwn.net/Vulnerabilities/707356/) ([search](http://search.nix.gsc.io/?q=tomcat6&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat6+in%3Apath&type=Code))  tomcat: two vulnerabilities
 - [x] [`#707211`](https://lwn.net/Vulnerabilities/707211/) ([search](http://search.nix.gsc.io/?q=vim&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=vim+in%3Apath&type=Code))  vim: code execution
 - [x] [`#707499`](https://lwn.net/Vulnerabilities/707499/) ([search](http://search.nix.gsc.io/?q=wireshark&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wireshark+in%3Apath&type=Code))  wireshark: denial of service
 - [x] [`#707359`](https://lwn.net/Vulnerabilities/707359/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: multiple vulnerabilities
 - [x] [`#707218`](https://lwn.net/Vulnerabilities/707218/) ([search](http://search.nix.gsc.io/?q=gst-plugins-good0.10&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-good0.10+in%3Apath&type=Code))  gst-plugins-good: code execution
 - [x] [`#707218`](https://lwn.net/Vulnerabilities/707218/) ([search](http://search.nix.gsc.io/?q=gst-plugins-good1.0&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-good1.0+in%3Apath&type=Code))  gst-plugins-good: code execution
 - [x] [`#707497`](https://lwn.net/Vulnerabilities/707497/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: code execution
 - [x] [`#658823`](https://lwn.net/Vulnerabilities/658823/) ([search](http://search.nix.gsc.io/?q=libemail-address-perl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libemail-address-perl+in%3Apath&type=Code))  libemail-address-perl: denial of service
 - [x] [`#707491`](https://lwn.net/Vulnerabilities/707491/) ([search](http://search.nix.gsc.io/?q=libsoap-lite-perl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libsoap-lite-perl+in%3Apath&type=Code))  libsoap-lite-perl: XML expansion
 - [x] [`#707493`](https://lwn.net/Vulnerabilities/707493/) ([search](http://search.nix.gsc.io/?q=mcabber&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mcabber+in%3Apath&type=Code))  mcabber: roster push attack
 - [x] [`#707361`](https://lwn.net/Vulnerabilities/707361/) ([search](http://search.nix.gsc.io/?q=mujs&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mujs+in%3Apath&type=Code))  mujs: multiple vulnerabilities
 - [x] [`#707217`](https://lwn.net/Vulnerabilities/707217/) ([search](http://search.nix.gsc.io/?q=ntp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntp+in%3Apath&type=Code))  ntp: multiple vulnerabilities
 - [x] [`#707362`](https://lwn.net/Vulnerabilities/707362/) ([search](http://search.nix.gsc.io/?q=perl-DBD-MySQL&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=perl-DBD-MySQL+in%3Apath&type=Code))  perl-DBD-MySQL: out of bounds read

### libtiff (2 issues)
 - [x] [`#707488`](https://lwn.net/Vulnerabilities/707488/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  libtiff: multiple vulnerabilities
 - [x] [`#707212`](https://lwn.net/Vulnerabilities/707212/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  tiff: buffer overflow

</details>

**Comment by grahamc** [comment]
libgc is this: https://github.com/NixOS/nixpkgs/blob/release-16.09/pkgs/development/libraries/boehm-gc/default.nix

**Comment by FRidh** [comment]
We already have the latest version of Tornado, 4.4.2, in both stable and master.

**Comment by vcunat** [comment]
I forgot to comment that vim is OK now (so it got unticked by someone again, I suppose).

**Comment by fpletz** [comment]
We already have the fixes for lxc and wireshark. The dovecot22 vulnerability is specific to RedHat packaging.

**Comment by grahamc** [comment]
One thing to keep in mind is we're on a pretty old version of Xen, and we should consider an update. Just from a quick look, though, it doesn't look like it'll be real easy.

**Comment by grahamc** [comment]
All our tomcats needed updating, and the updates are in my rollup.

**Comment by grahamc** [comment]
I'm unable to find a patch for testdisk.

**Comment by grahamc** [comment]
Just kidding, I'm pretty sure we're covered on testdisk.

**Comment by grahamc** [comment]
Last one is `kvm`. I merged all my patches and am putting together a notice. This is just a heads up, since I won't be able to put out the notice for a few more hours.

**Comment by grahamc** [comment]
Oh ... also -- I mucked up some cherry-picking and had to revert a few reverts. I feel pretty terrible about that, it makes things look pretty sketchy. I think it should be okay though. Let me know if something is wrong, please.

**Comment by grahamc** [comment]
I'm going to go ahead and close this out for this week, and we'll revisit the kvm issue next week.

**Comment by phanimahesh** [comment]
I was travelling, missed out on this one too. :(
@grahamc please cc me on next roundup
