### ISSUE TITLE
Vulnerability Roundup 12

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#20972]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/20814)

cc: @FRidh @fpletz @vcunat @phanimahesh.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup.
If you would like to be CC'd on the next roundup, add a comment to the
most recent vulnerability roundup. If you would like to be CC'd on
_all_ roundups, leave a comment and tell @grahamc so.

Permanent CC's: @joepie91, @NixOS/security-notifications
(if you no longer want to be CC'd, ask to be removed from this list)

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple packages.
   For example, there are sometimes problems that impact thunderbird,
   and firefox. LWN might report in one vulnerability "thunderbird
   firefox". These names have been split to make sure both packages get
   addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [x] Send an update e-mail to the nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (27 issues)
 - [x] [`#708243`](https://lwn.net/Vulnerabilities/708243/) ([search](http://search.nix.gsc.io/?q=GraphicsMagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=GraphicsMagick+in%3Apath&type=Code))  GraphicsMagick: non-null null pointer
 - [x] [`#708137`](https://lwn.net/Vulnerabilities/708137/) ([search](http://search.nix.gsc.io/?q=chromium&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chromium+in%3Apath&type=Code))  chromium: multiple vulnerabilities
 - [x] [`#707696`](https://lwn.net/Vulnerabilities/707696/) ([search](http://search.nix.gsc.io/?q=hdf5&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=hdf5+in%3Apath&type=Code))  hdf5: multiple vulnerabilities
 - [x] [`#707363`](https://lwn.net/Vulnerabilities/707363/) ([search](http://search.nix.gsc.io/?q=kvm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kvm+in%3Apath&type=Code))  kvm: denial of service
 - [x] [`#708242`](https://lwn.net/Vulnerabilities/708242/) ([search](http://search.nix.gsc.io/?q=virtualbox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=virtualbox+in%3Apath&type=Code))  virtualbox: code execution
 - [x] [`#708152`](https://lwn.net/Vulnerabilities/708152/) ([search](http://search.nix.gsc.io/?q=busybox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=busybox+in%3Apath&type=Code))  busybox: two vulnerabilities
 - [x] [`#598856`](https://lwn.net/Vulnerabilities/598856/) ([search](http://search.nix.gsc.io/?q=cifs-utils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=cifs-utils+in%3Apath&type=Code))  cifs-utils: code execution
 - [x] [`#568668`](https://lwn.net/Vulnerabilities/568668/) ([search](http://search.nix.gsc.io/?q=davfs2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=davfs2+in%3Apath&type=Code))  davfs2: privilege escalation
 - [x] [`#707705`](https://lwn.net/Vulnerabilities/707705/) ([search](http://search.nix.gsc.io/?q=jenkins-remoting&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jenkins-remoting+in%3Apath&type=Code))  jenkins-remoting: code execution
 - [x] [`#708000`](https://lwn.net/Vulnerabilities/708000/) ([search](http://search.nix.gsc.io/?q=libtcnative-1-0&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtcnative-1-0+in%3Apath&type=Code))  libctnative: SSL improvements
 - [x] [`#708140`](https://lwn.net/Vulnerabilities/708140/) ([search](http://search.nix.gsc.io/?q=openafs&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openafs+in%3Apath&type=Code))  openafs: information leak
 - [x] [`#707698`](https://lwn.net/Vulnerabilities/707698/) ([search](http://search.nix.gsc.io/?q=p7zip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=p7zip+in%3Apath&type=Code))  p7zip: denial of service
 - [x] [`#708148`](https://lwn.net/Vulnerabilities/708148/) ([search](http://search.nix.gsc.io/?q=phpMyAdmin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=phpMyAdmin+in%3Apath&type=Code))  phpMyAdmin: multiple vulnerabilities
 - [x] [`#668130`](https://lwn.net/Vulnerabilities/668130/) ([search](http://search.nix.gsc.io/?q=pygments&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pygments+in%3Apath&type=Code))  pygments: shell injection
 - [x] [`#707700`](https://lwn.net/Vulnerabilities/707700/) ([search](http://search.nix.gsc.io/?q=teeworlds&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=teeworlds+in%3Apath&type=Code))  teeworlds: code execution
 - [x] [`#707703`](https://lwn.net/Vulnerabilities/707703/) ([search](http://search.nix.gsc.io/?q=vagrant&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=vagrant+in%3Apath&type=Code))  vagrant: nfs export insertion
 - [x] [`#708149`](https://lwn.net/Vulnerabilities/708149/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: multiple vulnerabilities
 - [x] [`#639393`](https://lwn.net/Vulnerabilities/639393/) ([search](http://search.nix.gsc.io/?q=arj&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=arj+in%3Apath&type=Code))  arj: multiple vulnerabilities
 - [x] [`#708138`](https://lwn.net/Vulnerabilities/708138/) ([search](http://search.nix.gsc.io/?q=libdwarf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libdwarf+in%3Apath&type=Code))  libdwarf: multiple vulnerabilities
 - [x] [`#664646`](https://lwn.net/Vulnerabilities/664646/) ([search](http://search.nix.gsc.io/?q=libsndfile&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libsndfile+in%3Apath&type=Code))  libsndfile: buffer overflow
 - [x] [`#624610`](https://lwn.net/Vulnerabilities/624610/) ([search](http://search.nix.gsc.io/?q=util-linux&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=util-linux+in%3Apath&type=Code))  util-linux: command injection
 - [x] [`#707997`](https://lwn.net/Vulnerabilities/707997/) ([search](http://search.nix.gsc.io/?q=calamares&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=calamares+in%3Apath&type=Code))  calamares: encryption bypass
 - [x] [`#665921`](https://lwn.net/Vulnerabilities/665921/) ([search](http://search.nix.gsc.io/?q=dpkg&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dpkg+in%3Apath&type=Code))  dpkg: code execution
 - [x] [`#707838`](https://lwn.net/Vulnerabilities/707838/) ([search](http://search.nix.gsc.io/?q=firefox-esr&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firefox-esr+in%3Apath&type=Code))  firefox: code execution
 - [x] [`#708239`](https://lwn.net/Vulnerabilities/708239/) ([search](http://search.nix.gsc.io/?q=gstreamer1-plugins-good&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gstreamer1-plugins-good+in%3Apath&type=Code))  gstreamer1-plugins-good: buffer overflow
 - [x] [`#669403`](https://lwn.net/Vulnerabilities/669403/) ([search](http://search.nix.gsc.io/?q=nghttp2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nghttp2+in%3Apath&type=Code))  nghttp2: code execution
 - [x] [`#708154`](https://lwn.net/Vulnerabilities/708154/) ([search](http://search.nix.gsc.io/?q=patch&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=patch+in%3Apath&type=Code))  patch: denial of service

### firefox (3 issues)
 - [x] [`#708241`](https://lwn.net/Vulnerabilities/708241/) ([search](http://search.nix.gsc.io/?q=firefox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firefox+in%3Apath&type=Code))  mozilla: file overwrites
 - [x] [`#707838`](https://lwn.net/Vulnerabilities/707838/) ([search](http://search.nix.gsc.io/?q=firefox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firefox+in%3Apath&type=Code))  firefox: code execution
 - [x] [`#707854`](https://lwn.net/Vulnerabilities/707854/) ([search](http://search.nix.gsc.io/?q=firefox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firefox+in%3Apath&type=Code))  firefox: same-origin bypass

### imagemagick (2 issues)
 - [x] [`#708243`](https://lwn.net/Vulnerabilities/708243/) ([search](http://search.nix.gsc.io/?q=imagemagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=imagemagick+in%3Apath&type=Code))  GraphicsMagick: non-null null pointer
 - [x] [`#707857`](https://lwn.net/Vulnerabilities/707857/) ([search](http://search.nix.gsc.io/?q=imagemagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=imagemagick+in%3Apath&type=Code))  imagemagick: code execution

### kernel (4 issues)
 - [x] [`#708246`](https://lwn.net/Vulnerabilities/708246/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: code execution
 - [x] [`#708245`](https://lwn.net/Vulnerabilities/708245/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#708240`](https://lwn.net/Vulnerabilities/708240/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#707859`](https://lwn.net/Vulnerabilities/707859/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: privilege escalation

### thunderbird (2 issues)
 - [x] [`#708241`](https://lwn.net/Vulnerabilities/708241/) ([search](http://search.nix.gsc.io/?q=thunderbird&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=thunderbird+in%3Apath&type=Code))  mozilla: file overwrites
 - [x] [`#707838`](https://lwn.net/Vulnerabilities/707838/) ([search](http://search.nix.gsc.io/?q=thunderbird&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=thunderbird+in%3Apath&type=Code))  firefox: code execution

**Comment by grahamc** [comment]
ImageMagick fixed in my rollup.

**Comment by grahamc** [comment]
We should just delete Calamares: "LUKS accepts every WRONG password after install".

**Comment by grahamc** [comment]
gstreamer needs updating / backporting to 1.10.2 and is ABI-safe according to https://abi-laboratory.pro/tracker/, see also https://github.com/NixOS/nixpkgs/commit/7a6185d9a1eb18fa09892fdef01a5193968cf704 for info on how.

**Comment by grahamc** [comment]
I have an incoming patch for gstreamer

**Comment by NeQuissimus** [comment]
I do not think there are patched kernels for the remaining issue. Only the 4.9 RCs seem to have the commit so far.

**Comment by vcunat** [comment]
The util-linux problem [was reported in 2014](http://seclists.org/oss-sec/2014/q4/811) and our version is from 2016 (2.28.1 both on master and 16.09), so I don't think it's vulnerable anymore.

**Comment by vcunat** [comment]
Our `unarj` is `meta.broken` with notes about vulnerability, so I'm ticking that as well.

**Comment by vcunat** [comment]
`libsndfile`: the LWN link says versions <= 1.0.25 suffer from that vulnerability but we have 1.0.27 both on 16.09 and master.

**Comment by vcunat** [comment]
`libdwarf`: fixed up in master and 16.09, except that `darwin.dtrace` probably contains an embedded copy in it's code which I don't feel like digging in.

**Comment by grahamc** [comment]
Wow, great work, @vcunat. Thank you!

**Comment by grahamc** [comment]
Backported jenkins from 9575eeae108ca23f7af49f0a1566706feef83cb4 in 3573b6c.

**Comment by grahamc** [comment]
It isn't clear to me if virtualbox needs updating ...

**Comment by grahamc** [comment]
hdf5 backported from 16eb67ac9ca52d56ff13fb3cda2e4644df9f387b in b60ae78

**Comment by grahamc** [comment]
@NeQuissimus can you clarify? all the Kernel tasks are still marked not done. Do they all need to wait on releases from kernel.org?

**Comment by grahamc** [comment]
:raised_hands: they're all completed this week, except for the kernel tasks (see previous comment.) I'm letting my patch branch build for a few hours before merging in to master / release. Some bigger builds in there I'm not 100% sure about.

**Comment by Mic92** [comment]
How was arj solved? I was starting to fix the broken build?

**Comment by joachifm** [comment]
Re: the final kernel issue, grsec users are unaffected :)

**Comment by joachifm** [comment]
Oh, sorry, the first one, d'oh

**Comment by NeQuissimus** [comment]
OK, that is weird, I definitely checked off three of them yesterday... Anyways... According to SuSE we are good on that one as well, everything > 4.8.8 (or equivalent 4.4.x, etc.) is safe.

**Comment by grahamc** [comment]
Thank you, @NeQuissimus! I'll merge these patches soon and close this out.

**Comment by phanimahesh** [comment]
Wow. The roundup is done before I even noticed! That's awesome.
Too many github notifications to plough through. :(  I'll probably have to setup a mobile notification to not miss roundups.
To avoid repeated metoo comments on the roundups I miss, @grahamc, can you please add me to permanent ccs?

**Comment by grahamc** [comment]
:D Done! Thank you!
