### ISSUE TITLE
Vulnerability Roundup 13

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#21142]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/20972).

cc: @NeQuissimus @vcunat @joachifm.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.
If you would like to be CC'd on _all_ roundups, leave a comment and
tell @grahamc so.

Permanent CC's: @joepie91, @phanimahesh, @NixOS/security-notifications
(if you no longer want to be CC'd, ask to be removed from this list)

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [ ] Send an update e-mail to nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (36 issues)
 - [x] [`#708522`](https://lwn.net/Vulnerabilities/708522/) ([search](http://search.nix.gsc.io/?q=atomic-openshift&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=atomic-openshift+in%3Apath&type=Code))  atomic-openshift: information disclosure
 - [x] [`#708996`](https://lwn.net/Vulnerabilities/708996/) ([search](http://search.nix.gsc.io/?q=golang&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=golang+in%3Apath&type=Code))  golang: denial of service
 - [x] [`#708652`](https://lwn.net/Vulnerabilities/708652/) ([search](http://search.nix.gsc.io/?q=python-XStatic-jquery-ui&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-XStatic-jquery-ui+in%3Apath&type=Code))  python-XStatic-jquery-ui: cross-site scripting
 - [x] [`#709009`](https://lwn.net/Vulnerabilities/709009/) ([search](http://search.nix.gsc.io/?q=zabbix&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=zabbix+in%3Apath&type=Code))  zabbix: two vulnerabilities
 - [x] [`#708876`](https://lwn.net/Vulnerabilities/708876/) ([search](http://search.nix.gsc.io/?q=DBD-mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=DBD-mysql+in%3Apath&type=Code))  perl-DBD-MySQL: use after free
 - [x] [`#708883`](https://lwn.net/Vulnerabilities/708883/) ([search](http://search.nix.gsc.io/?q=subversion&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=subversion+in%3Apath&type=Code))  subversion: denial of service
 - [x] [`#708995`](https://lwn.net/Vulnerabilities/708995/) ([search](http://search.nix.gsc.io/?q=unzip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=unzip+in%3Apath&type=Code))  unzip: buffer overflows
 - [x] [`#709007`](https://lwn.net/Vulnerabilities/709007/) ([search](http://search.nix.gsc.io/?q=webkit-gtk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=webkit-gtk+in%3Apath&type=Code))  webkit-gtk: multiple vulnerabilities
 - [x] [`#708524`](https://lwn.net/Vulnerabilities/708524/) ([search](http://search.nix.gsc.io/?q=gst-plugins-bad0.10&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-bad0.10+in%3Apath&type=Code))  gst-plugins-bad: code execution
 - [x] [`#708525`](https://lwn.net/Vulnerabilities/708525/) ([search](http://search.nix.gsc.io/?q=gst-plugins-base0.10&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-base0.10+in%3Apath&type=Code))  gst-plugins-base: code execution
 - [x] [`#708873`](https://lwn.net/Vulnerabilities/708873/) ([search](http://search.nix.gsc.io/?q=gstreamer-plugins-bad-free&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gstreamer-plugins-bad-free+in%3Apath&type=Code))  gstreamer-plugins-bad-free: two vulnerabilities
 - [x] [`#708657`](https://lwn.net/Vulnerabilities/708657/) ([search](http://search.nix.gsc.io/?q=httpd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=httpd+in%3Apath&type=Code))  httpd: denial of service
 - [x] [`#708871`](https://lwn.net/Vulnerabilities/708871/) ([search](http://search.nix.gsc.io/?q=libgsf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgsf+in%3Apath&type=Code))  libgsf: denial of service
 - [x] [`#595998`](https://lwn.net/Vulnerabilities/595998/) ([search](http://search.nix.gsc.io/?q=libmms&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libmms+in%3Apath&type=Code))  libmms: code execution
 - [x] [`#708359`](https://lwn.net/Vulnerabilities/708359/) ([search](http://search.nix.gsc.io/?q=mapserver&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mapserver+in%3Apath&type=Code))  mapserver: information leak
 - [x] [`#708363`](https://lwn.net/Vulnerabilities/708363/) ([search](http://search.nix.gsc.io/?q=mingw-nsis&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mingw-nsis+in%3Apath&type=Code))  mingw-nsis: DLL hijacking
 - [x] [`#708528`](https://lwn.net/Vulnerabilities/708528/) ([search](http://search.nix.gsc.io/?q=openjpeg&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg+in%3Apath&type=Code))  openjpeg: code execution
 - [x] [`#708875`](https://lwn.net/Vulnerabilities/708875/) ([search](http://search.nix.gsc.io/?q=openjpeg2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg2+in%3Apath&type=Code))  openjpeg2: denial of service
 - [x] [`#588035`](https://lwn.net/Vulnerabilities/588035/) ([search](http://search.nix.gsc.io/?q=xstream&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xstream+in%3Apath&type=Code))  xstream: code execution
 - [x] [`#708523`](https://lwn.net/Vulnerabilities/708523/) ([search](http://search.nix.gsc.io/?q=and&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=and+in%3Apath&type=Code))  openstack-cinder, openstack-glance: denial of service
 - [x] [`#629686`](https://lwn.net/Vulnerabilities/629686/) ([search](http://search.nix.gsc.io/?q=coreutils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=coreutils+in%3Apath&type=Code))  coreutils: code execution
 - [x] [`#595046`](https://lwn.net/Vulnerabilities/595046/) ([search](http://search.nix.gsc.io/?q=elfutils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=elfutils+in%3Apath&type=Code))  elfutils: code execution
 - [x] [`#662905`](https://lwn.net/Vulnerabilities/662905/) ([search](http://search.nix.gsc.io/?q=exfat-utils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=exfat-utils+in%3Apath&type=Code))  exfat-utils: two vulnerabilities
 - [x] [`#708523`](https://lwn.net/Vulnerabilities/708523/) ([search](http://search.nix.gsc.io/?q=openstack-cinder&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openstack-cinder+in%3Apath&type=Code))  openstack-cinder, openstack-glance: denial of service
 - [x] [`#708365`](https://lwn.net/Vulnerabilities/708365/) ([search](http://search.nix.gsc.io/?q=pecl-http&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pecl-http+in%3Apath&type=Code))  pecl-http: code execution
 - [x] [`#709010`](https://lwn.net/Vulnerabilities/709010/) ([search](http://search.nix.gsc.io/?q=php&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php+in%3Apath&type=Code))  php: unknown
 - [x] [`#708527`](https://lwn.net/Vulnerabilities/708527/) ([search](http://search.nix.gsc.io/?q=php-php-gettext&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php-php-gettext+in%3Apath&type=Code))  php-php-gettext: code execution
 - [x] [`#708997`](https://lwn.net/Vulnerabilities/708997/) ([search](http://search.nix.gsc.io/?q=php-simplesamlphp-saml2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php-simplesamlphp-saml2+in%3Apath&type=Code))  php-simplesamlphp-saml2: incorrect signature verification
 - [x] [`#708993`](https://lwn.net/Vulnerabilities/708993/) ([search](http://search.nix.gsc.io/?q=php5&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php5+in%3Apath&type=Code))  php5: multiple vulnerabilities
 - [x] [`#658600`](https://lwn.net/Vulnerabilities/658600/) ([search](http://search.nix.gsc.io/?q=pixman&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pixman+in%3Apath&type=Code))  pixman: buffer overflow
 - [x] [`#664215`](https://lwn.net/Vulnerabilities/664215/) ([search](http://search.nix.gsc.io/?q=powerdns&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=powerdns+in%3Apath&type=Code))  powerdns: denial of service
 - [x] [`#708655`](https://lwn.net/Vulnerabilities/708655/) ([search](http://search.nix.gsc.io/?q=roundcube&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=roundcube+in%3Apath&type=Code))  roundcube: code execution
 - [x] [`#627589`](https://lwn.net/Vulnerabilities/627589/) ([search](http://search.nix.gsc.io/?q=sox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sox+in%3Apath&type=Code))  sox: code execution
 - [x] [`#708656`](https://lwn.net/Vulnerabilities/708656/) ([search](http://search.nix.gsc.io/?q=spip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=spip+in%3Apath&type=Code))  spip: cross-site scripting
 - [x] [`#708529`](https://lwn.net/Vulnerabilities/708529/) ([search](http://search.nix.gsc.io/?q=sqlite&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sqlite+in%3Apath&type=Code))  sqlite: code execution
 - [x] [`#529991`](https://lwn.net/Vulnerabilities/529991/) ([search](http://search.nix.gsc.io/?q=squashfs-tools&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=squashfs-tools+in%3Apath&type=Code))  squashfs-tools: two code execution flaws

### jasper (2 issues)
 - [x] [`#708870`](https://lwn.net/Vulnerabilities/708870/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: buffer overflow
 - [x] [`#708654`](https://lwn.net/Vulnerabilities/708654/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: multiple vulnerabilities

### kernel (8 issues)
 - [x] [`#708869`](https://lwn.net/Vulnerabilities/708869/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#708367`](https://lwn.net/Vulnerabilities/708367/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#708530`](https://lwn.net/Vulnerabilities/708530/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#708659`](https://lwn.net/Vulnerabilities/708659/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: multiple vulnerabilities
 - [x] [`#708532`](https://lwn.net/Vulnerabilities/708532/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#708531`](https://lwn.net/Vulnerabilities/708531/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: multiple vulnerabilities
 - [x] [`#708884`](https://lwn.net/Vulnerabilities/708884/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: privilege escalation
 - [x] [`#708874`](https://lwn.net/Vulnerabilities/708874/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities

### systemd (2 issues)
 - [x] [`#709006`](https://lwn.net/Vulnerabilities/709006/) ([search](http://search.nix.gsc.io/?q=systemd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=systemd+in%3Apath&type=Code))  systemd: denial of service
 - [x] [`#570330`](https://lwn.net/Vulnerabilities/570330/) ([search](http://search.nix.gsc.io/?q=systemd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=systemd+in%3Apath&type=Code))  systemd: multiple vulnerabilities

### xen (2 issues)
 - [x] [`#708886`](https://lwn.net/Vulnerabilities/708886/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: information disclosure
 - [x] [`#708533`](https://lwn.net/Vulnerabilities/708533/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: privilege escalation

**Comment by grahamc** [comment]
I've got a jasper update in the works. Checking to see if 2.0.6 is BC with 1.900.x or not.

**Comment by NeQuissimus** [comment]
kernel: [#708869](https://lwn.net/Vulnerabilities/708869/) (search, files) kernel: denial of service

This needs a patch from https://bugzilla.kernel.org/show_bug.cgi?id=189851
I am not home, so I can't do it until late tonight.

**Comment by grahamc** [comment]
Thank you, @NeQuissimus, I'll apply that patch.

**Comment by NeQuissimus** [comment]
Let's also mention #21135 in here, even though I don't see it on the list.

**Comment by grahamc** [comment]
Good idea, https://github.com/NixOS/nixpkgs/pull/21134 too.

**Comment by grahamc** [comment]
Hung up on https://github.com/NixOS/nixpkgs/issues/21145 which is blocking channels from moving forward.

**Comment by NeQuissimus** [comment]
Xen and SystemD are good.

**Comment by NeQuissimus** [comment]
Looks like `unzip` needs both the CVEs patched

**Comment by NeQuissimus** [comment]
I am going to send a PR for `subversion` once it has built on my machine.
It's a straight forward update.

**Comment by grahamc** [comment]
@domenkozar are you available to look in to upgrading our openstack components?

**Comment by grahamc** [comment]
Actually, @NeQuissimus, can you apply that kernel patch?

**Comment by grahamc** [comment]
@makefu can you look in to updating XStatic-jquery-ui?

**Comment by makefu** [comment]
@grahamc ^

**Comment by grahamc** [comment]
Thank you!

**Comment by phanimahesh** [comment]
I started looking at `atomic-openshift`. Both code and files searches failed to show any results. Past roundups mentioned `atomic-openshift` a few times, but I couldn't locate the corresponding commits/patches that fixed it.

The derivations for `openshift` and `rhc` are both simple. Should I be looking at their commits to see if the fixes have been included? Are they the right repos? How do I find out the corresponding repo and package, in general?

Pointers? How do I proceed?

**Comment by grahamc** [comment]
oh I don't think we have Atomic, and the one that says `cinder` is also for `glance` which we do have: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/openstack/glance.nix.

**Comment by domenkozar** [comment]
Updating openstack is quite some work as you need to bump all components. It's better to look into patching existing versions, if they're still supported upstream.

**Comment by bachp** [comment]
I think atomic-openshift refers to the package [`openshift`](https://github.com/NixOS/nixpkgs/blob/86ea23008b007c91a1b2f585072a073f0a0ad339/pkgs/applications/networking/cluster/openshift/default.nix). RHC is the old (OpenShiftv2) client utility. This is completly different from  `openshift` (OpenShift v3, aka OpenShift Container Platform).

As there is a version [1.3.2](https://github.com/openshift/origin/releases/tag/v1.3.2) available I think this would be the component to update.

**Comment by grahamc** [comment]
@bachp can you make that PR?

**Comment by grahamc** [comment]
@NeQuissimus bump on that kernel patch. Can you do it?

**Comment by grahamc** [comment]
I think my patches to release 16.09 are bad... will investigate in a few hours.

**Comment by grahamc** [comment]
I think my patches were good, but the nix / hydra issues are hurting us again.

**Comment by bachp** [comment]
@grahamc I might find some time to do it this weekend.

**Comment by NeQuissimus** [comment]
I bumped the kernels just now

**Comment by bachp** [comment]
@grahamc PR created #21216

**Comment by grahamc** [comment]
@bachp: Excellent, thank you!

@NeQuissimus Looks great, thank you!

@domenkozar That is part of what I feared, touching Openstack in general spooks me. It looks like there are patch releases within these major releases, 11.0.0 -> 11.0.2... 7.0.0 -> 7.0.2. Are these safe, do you think? Do they all need to go up in lock-step for these patch releases.

**Comment by grahamc** [comment]
I deleted this one from this week to close it out:

 - [ ] [`#708523`](https://lwn.net/Vulnerabilities/708523/) ([search](http://search.nix.gsc.io/?q=openstack-glance&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openstack-glance+in%3Apath&type=Code))  openstack-cinder, openstack-glance: denial of service

**Comment by domenkozar** [comment]
Minor bumps would work, but it's quite some python packages to update (sorry, I don't have time now).
