### ISSUE TITLE
Tracking Issue for `llvmPackages_15` changes

### ISSUE THREAD

**Issue by rrbutani** [NixOS/nixpkgs#213033]
This issue tracks the work left over from #194634.

### Fixes/missed patches for LLVM 15
  - [x] missing attrs: #213497 (thanks @Et7f3!)
  - [x] should be applied to LLVM 15: #207863
  - [x] need to apply #193636 after all; see [here](https://github.com/NixOS/nixpkgs/issues/191152#issuecomment-1429029003)
     + #217825
  - [x] #214524 (#216273)
  - [x] fix the license change: #217906
  - [x] #218657
  - [x] apply #212498: #218676
  - [x] #217042
  - [x] drop the `compiler-rt` sigtool codesigning patch: #218800

##### In-flight
 - [ ] #220520
 - [ ] #220595
 - [ ] #207325
 - [ ] #196006

### Unifying `llvmPackages_git` with `llvmPackages_15`
  - [x] #211225
  - [x] #217824
  - [x]  `compiler-rt` fixes: #217844
  - [x] use ninja: #218620
  - [x] #218657
  - [x] #218671
  - [x] #218799
  - [x] enable polly: #218806
  - [x] #218865
  - [x] `libcxx` stdenv change: #220527
  - [x] #218640
  - [x] enable `llvm` tests on darwin: #222220
  - [x] disable iOS simulator targets in `compiler-rt`: #223256
  - [x] misc `libcxx` changes: #223255
  - [x] #222901
  - [x] apply #205355: #222902
  - [x] openmp apply #197674: #222903
  - [x] apply #207863
  - [x] bump to LLVM 15: #222894

Tracking the current state of `llvmPackages_git` (i.e. all the PRs listed above applied) here: [`rrbutani/tracking/llvm-git-parity`](https://github.com/NixOS/nixpkgs/compare/master...rrbutani:nixpkgs:tracking/llvm-git-parity?expand=1)

### LLVM Package Set Updates
  - [ ] bump `llvmPackages_latest` (#213202)
  - [x] backport `llvmPackages_15` (#213092, #213093)

----

### Tests and additional coverage:
  - [ ] libcxx tests
    + [ ] `x86_64-darwin` (@Et7f3)
    + [ ] other platforms
  - [ ] [cc-wrapper tests for sanitizers](https://github.com/NixOS/nixpkgs/blob/86a387351acf96b7137f5f385d978bf3681c7239/pkgs/test/cc-wrapper/default.nix#L4-L8)
  - [ ] extra cc-wrapper tests for PGO, perhaps?
  - [ ] [stdenv tests](https://github.com/NixOS/nixpkgs/blob/3a2e5671843bd21ec71a8a29262a96b03bde2239/pkgs/top-level/release.nix#L218-L220) on other platforms
  - [ ] fix these: [1](https://github.com/NixOS/nixpkgs/blob/3a2e5671843bd21ec71a8a29262a96b03bde2239/pkgs/top-level/release.nix#L79-L86), [2](https://github.com/NixOS/nixpkgs/blob/3a2e5671843bd21ec71a8a29262a96b03bde2239/pkgs/top-level/release.nix#L114-L131), [3](https://github.com/NixOS/nixpkgs/blob/3a2e5671843bd21ec71a8a29262a96b03bde2239/pkgs/top-level/release.nix#L149) (either remove or decide that these *should* gate channel advancement)

### Issues/bugs:
  - [ ] fix use as a cross-compiler targeting FreeBSD (`libcxx` currently fails to build)
  - [ ] fix `pkgsStatic.llvmPackages_15`
  - [ ] follow up on the `armv7l` build (didn't finish building before #194634 was merged)
  - [ ] the [three failing `x86_64-darwin` LLVM tests](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179)
    + [ ] [one](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179#diff-e92a428f0a6f1217859727cec3f31212bd0bb5dbac461b87c30f52ebc513a8d6R157-R169): `roundevenf` isn't present on `x86_64-darwin`; unclear if this is expected or not
    + [ ] [two](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179#diff-e92a428f0a6f1217859727cec3f31212bd0bb5dbac461b87c30f52ebc513a8d6R171-R200): `sw_vers` on `aarch64-darwin` links against frameworks (`CoreFoundation`) outside the sandbox
    + [ ] [three](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179#diff-e92a428f0a6f1217859727cec3f31212bd0bb5dbac461b87c30f52ebc513a8d6R202-R204): crash in a `dsymutil` test

### Future Work/Wishlist

(not tracked by this issue; will point to issues here as we begin working on these things)

  - common LLVM function across the package sets
  - LLVM 16
  - updating `llvmPackages_git` to tip-of-tree
  - bumping `llvmPackages` to newer LLVM
  - MLIR
  - BOLT
  - auto updater
  - splitting `useLLVM`
  - expanding test coverage (i.e. enabling `doCheck` on more packages/platforms)
  - adding regression tests for the stdenv(s)
  - building LTO/PGO/bolt optimized binaries in the `llvmPackages` sets
  - reducing closure size of LLVM by splitting out the `.a` files in `lib` outputs? (but in a way that doesn't break users of LLVM static libs..)

**Comment by Et7f3** [comment]
Cool the PR is merged is their a Darwin task you are not working on ?

**Comment by rrbutani** [comment]
@Et7f3 I think, for now, I'm planning to focus on doing what I can to help bump `llvmPackages_latest` and then to bump `llvmPackages_git`.

I'm still gathering my notes to update the OP with but off the top of my head, for darwin:
  - I didn't _really_ get to the bottom of the three test failures, detailed in [this commit](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179)
    + [one](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179#diff-e92a428f0a6f1217859727cec3f31212bd0bb5dbac461b87c30f52ebc513a8d6R157-R169), [two](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179#diff-e92a428f0a6f1217859727cec3f31212bd0bb5dbac461b87c30f52ebc513a8d6R171-R200), [three](https://github.com/NixOS/nixpkgs/pull/194634/commits/eafb8fbd3215f0fe6b1d4a0360a9c4f761677179#diff-e92a428f0a6f1217859727cec3f31212bd0bb5dbac461b87c30f52ebc513a8d6R202-R204)
    + for the first one it probably makes sense to dig deeper into if/why the JIT test that links against `roundevenf` succeeds on `aarch64-darwin` (is the test actually running on `aarch64-darwin`? if so, where does that symbol come from, `libSystem`? is this an artifact of us seemingly using system frameworks – the second issue – on `aarch64-darwin`? etc)
    + the second one is pretty spooky (and the commit message linked above has more details about how to reproduce it) and probably involves digging into the `aarch64-darwin` stdenv and the build steps for `DarwinTools` to figure out why the system framework is getting linked
    + I haven't looked into the third one at all but verifying that that test case fails outside the sandbox too is probably a good place to start
  - Actually using the `llvmPackages_15` stdenv (as part of [this test script](https://gist.github.com/rrbutani/32db35ba9fe0f2183aab3d8f8410ce89) – note that `aarch64-darwin` and `x86_64-darwin` are commented out there in `systems`) leads to cycle errors on darwin
    + I don't have a good understanding of _why_; it seems like our stdenv gets used for some bootstrapping things, creating a cycle but it's not apparent to me why that doesn't affect the default (LLVM based) darwin stdenv
  - I wanted to maybe try enabling the tests for other packages in the set (`libcxx` and `clang` to start with)
    + this isn't strictly a darwin task but I'm sure we'll end up needing to spend time figuring out darwin/linux/etc specific fails as part of this 😃

If any of the above things sound interesting to you, let me know; I can update the OP accordingly and try to provide some more context.

None of the above are high priority or anything though; if there's something else you're interested in working on (i.e. getting cross-compiling LLVM to work in more configurations, experimenting with ways to share package definitions between the `llvmPackages_*` sets, etc) definitely feel free to pursue that instead!

**Comment by Et7f3** [comment]
In the other PR this technique was used for newer requirements https://github.com/NixOS/nixpkgs/pull/209536#issuecomment-1402777803 it use gcc on linux and not clang which might not be the default. This patch avoid mixing compiler, What do you think ?

I think I will try to enable test for libcxx on x86_64-darwin. I thought on enabling the test on all platforms and disabling those failing like https://github.com/NixOS/nixpkgs/blob/84eed3e542e7094d291da8fb50a9be13e4230f0f/pkgs/development/compilers/llvm/15/llvm/default.nix#L239-L243

So other works doesn't add regression and we can still keep progress.

**Comment by Et7f3** [comment]
Also linking a PR linked to these https://github.com/NixOS/nixpkgs/pull/213497

**Comment by rrbutani** [comment]
@Et7f3 Apologies for the late response.

> In the other PR this technique was used for newer requirements [#209536 (comment)](https://github.com/NixOS/nixpkgs/pull/209536#issuecomment-1402777803) it use gcc on linux and not clang which might not be the default. This patch avoid mixing compiler, What do you think ?

I believe it's okay for us to mix and match _compilers_ and that it's mixing C++ stdlib/libc impls that's cause for concern. For example, AIUI, `llvmPackages.stdenv` exists and defaults to the platform's C++ stdlib instead of always using `libc++` specifically so that some packages -- like [chromium](https://github.com/NixOS/nixpkgs/blob/587ee6ba8db49edee8a8b6c1e59e138f497548ed/pkgs/applications/networking/browsers/chromium/default.nix#L21) -- can use `clang` but can still link against other libraries compiled against `libstdc++` (default on linux targets).

In the case of `libc++`/`libc++-abi`, we aren't linking against a C++ stdlib impl anyways (and the [stdenv we use](https://github.com/NixOS/nixpkgs/pull/194634/files#diff-fb2f090fa2882cbe96de0e037fb9c1e570db8722774229ba352f095d329ba92dR261-R267) to build these packages is careful to use the platform's `libc`) so I _think_ this isn't a concern for us (those with more experience in this area should definitely feel free to weigh in or clarify).

Given that, I think using the `clang` that's built alongside `libcxx` is preferable; it mirrors how `libc++` is built in upstream LLVM and it lets us avoid having to maintain logic to select a new-enough gcc version, per-platform.

> I think I will try to enable test for libcxx on x86_64-darwin. 

That sounds great! I'll add an item for this in the OP; let me know if you open any issues or PRs and I can add them too.

**Comment by misuzu** [comment]
`llvmPackages_15.llvm` is currently [broken](https://hydra.armv7l.xyz/build/6935) on armv7l-linux: the test suite fails due to `MemoryError`.
At the same time `llvmPackages_git.llvm` [doesn't have](https://hydra.armv7l.xyz/build/6934) this issue.
It's really hard to bisect the exact cause of this `MemoryError` issue, if anyone has any ideas, please share.

**Comment by Artturin** [comment]
> should be applied to LLVM 15: https://github.com/NixOS/nixpkgs/pull/207863

fix in https://github.com/NixOS/nixpkgs/pull/230387

**Comment by pca006132** [comment]
I managed to get Bolt built in https://github.com/NixOS/nixpkgs/issues/176536#issuecomment-1949211795, not yet tested (will do in a few days). A lot of patching has to be done, should I open a PR or try to get something upstreamed first?
