### ISSUE TITLE
Some package requests

### ISSUE THREAD

**Issue by ghost** [NixOS/nixpkgs#213735]
FUP: https://github.com/NixOS/nixpkgs/issues/213678#issuecomment-1409720176

## TODO
- [ ] [QuickMedia](https://git.dec05eba.com/QuickMedia): A rofi inspired native client for web services supporting youtube, peertube, lbry, soundcloud, nyaa.si, manganelo, manganelos, mangatown, mangakatana, mangadex, readm, onimanga, 4chan, matrix, saucenao, hotexamples, anilist, dramacool and others. Also supports reading local manga and watching local anime.
- [ ] [hblock](https://github.com/hectorm/hblock): A POSIX-compliant shell script that gets a list of domains that serve ads, tracking scripts and malware from [multiple sources](https://github.com/hectorm/hblock/blob/master/SOURCES.md) and creates a [hosts file](https://en.wikipedia.org/wiki/Hosts_(file)), [among other formats](https://github.com/hectorm/hblock/blob/master/resources/alt-formats), that prevents one's system from connecting to them.
- [ ] [abaddon](https://github.com/uowuo/abaddon): An alternative Discord client made with C++/gtkmm.
- [ ] [BiglyBT](https://github.com/BiglySoftware/BiglyBT): A feature filled, open source, ad-free, bittorrent client. It is forked from the original project and is being maintained by two of the original developers as well as members of the community.
- [ ] [angrysearch](https://github.com/DoTheEvo/ANGRYsearch): A Linux file search instant results as you type.
- [ ] [hawck](https://github.com/snyball/Hawck): A Key-rebinding daemon for Linux. It intercepts key presses and lets one write Lua scripts to perform actions or modify keys depending on one's needs.
- [ ] [vnstat-client](https://github.com/Hulxv/vnstat-client): A beautiful gui client for vnStat.
- [ ] [enso](https://enso.org): An award-winning interactive programming language with dual visual and textual representations.
- [ ] [Cinelerra GG Infinity](https://www.cinelerra-gg.org) (See: https://github.com/NixOS/nixpkgs/issues/61371): A free and open source video editing software for Linux that handles rendering, compositing, motion tracking, video editing and much more.
- [ ] [vidcutter](https://github.com/ozmartian/vidcutter):  A modern yet simple multi-platform video cutter and joiner.
- [ ] [cabal-desktop](https://cabal.chat): Desktop client for Cabal, the p2p/decentralized/local-first chat platform.
- [ ] [revolt-desktop](https://github.com/revoltchat/desktop): A desktop application for Revolt built on Electron. Revolt is an open source user-first chat platform.
- [ ] [y-cruncher](http://www.numberworld.org/y-cruncher): A multi-threaded pi-program that can compute Pi and other constants to trillions of digits.
- [ ] [glint](https://glint.info): A Graphical interface for Git.
- [ ] [OneDriveGUI](https://github.com/bpozdena/OneDriveGUI): A simple GUI for OneDrive Linux client, with multi-account support.
- [ ] [portmaster](https://github.com/safing/portmaster): A FOSS firewall application with great UI that does the heavy lifting for you.
- [ ] [aether](https://getaether.net): A peer-to-peer network of independent, self-moderated communities.
- [ ] [gradience](https://gradienceteam.github.io): A tool for customizing Libadwaita applications and the adw-gtk3 theme.
- [ ] [bloop-desktop](https://bloop.ai): A fast code search engine written in Rust. 

## Metadata
| Name | Homepage URL                                            | Source URL                                             | License   | Platforms         |
|---------|---------------------------------------------------------|--------------------------------------------------------|-----------|-------------------|
| QuickMedia | [git.dec05eba.com/QuickMedia](https://git.dec05eba.com/QuickMedia) | [git.dec05eba.com/QuickMedia](https://git.dec05eba.com/QuickMedia) | gpl-3 | linux |
| hblock | [hectorm/hblock](https://github.com/hectorm/hblock) | [hectorm/hblock](https://github.com/hectorm/hblock) | mit | unix, linux, darwin |
| abaddon | [uowuo/abaddon](https://github.com/uowuo/abaddon) | [uowuo/abaddon](https://github.com/uowuo/abaddon) | gpl-3 | unix, linux, darwin, windows |
| BiglyBT | [BiglySoftware/BiglyBT](https://github.com/BiglySoftware/BiglyBT) | [BiglySoftware/BiglyBT](https://github.com/BiglySoftware/BiglyBT) | gpl-2 | unix, linux, darwin |
| angrysearch | [DoTheEvo/ANGRYsearch](https://github.com/DoTheEvo/ANGRYsearch) | [DoTheEvo/ANGRYsearch](https://github.com/DoTheEvo/ANGRYsearch) | gpl-2 | linux |
| hawck | [snyball/Hawck](https://github.com/snyball/Hawck) | [snyball/Hawck](https://github.com/snyball/Hawck) | bsd-2-clause | linux |
| vnstat-client | [Hulxv/vnstat-client](https://github.com/Hulxv/vnstat-client) | [Hulxv/vnstat-client](https://github.com/Hulxv/vnstat-client) | gpl-2 | linux |
| enso | https://enso.org | [enso-org/enso](https://github.com/enso-org/enso) | apache-2 | unix, linux, darwin
| Cinelerra GG Infinity | [cinelerra-gg.org](https://www.cinelerra-gg.org) | [cinelerra.git](https://git.cinelerra-gg.org/git/?p=goodguy/cinelerra.git), [cinelerra-gg.org/download/pkgs/src/](https://cinelerra-gg.org/download/pkgs/src/) | gpl-2 | linux
| vidcutter | [ozmartian/vidcutter](https://github.com/ozmartian/vidcutter) | [ozmartian/vidcutter](https://github.com/ozmartian/vidcutter) | gpl-3 | unix, linux, darwin
| cabal-desktop | [cabal.chat](https://cabal.chat) | [cabal-club/cabal-desktop](https://github.com/cabal-club/cabal-desktop) | agpl-3 | unix, linux, darwin
| revolt-desktop | [revolt.chat](https://revolt.chat) | [revoltchat/desktop](https://github.com/revoltchat/desktop) | agpl-3 | unix, linux, darwin
| y-cruncher | [numberworld.org/y-cruncher](http://www.numberworld.org/y-cruncher) | [numberworld.org/y-cruncher/#Download](http://www.numberworld.org/y-cruncher/#Download) | [license.html](http://www.numberworld.org/y-cruncher/license.html) | linux
| glint | [glint.info](https://glint.info) | [glint.info/download](https://glint.info/download) | [eula](https://glint.info/eula) | linux, darwin
| OneDriveGUI | [bpozdena/OneDriveGUI](https://github.com/bpozdena/OneDriveGUI) | [bpozdena/OneDriveGUI](https://github.com/bpozdena/OneDriveGUI) | gpl-3 | linux
| portmaster | [safing/portmaster](https://github.com/safing/portmaster) | [safing/portmaster](https://github.com/safing/portmaster) | agpl-3 | linux
| aether | [getaether.net](https://getaether.net) | [aether-app](https://github.com/aethereans/aether-app) | agpl-3 | linux, darwin
| gradience | [gradienceteam.github.io](https://gradienceteam.github.io) | [radienceTeam/Gradience](https://github.com/GradienceTeam/Gradience) | gpl-3 | linux
| bloop-desktop | [bloop.ai](https://bloop.ai) | [BloopAI/bloop](https://github.com/BloopAI/bloop) | apache-2 | unix, linux, darwin

**Comment by dit7ya** [comment]
`unison-ucm` already exists in nixpkgs - https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/compilers/unison/default.nix#L41. Is that what you are looking for or something else?

**Comment by dit7ya** [comment]
sniffnet is in nixpkgs - https://github.com/NixOS/nixpkgs/pull/204588 already.

**Comment by Aleksanaa** [comment]
abaddon  https://github.com/NixOS/nixpkgs/pull/227776

**Comment by Lord-Valen** [comment]
Portmaster: #227913

**Comment by hyperspace01** [comment]
Any developments for BiglyBT here? It looks like #129916 got closed because of a toxic contributor? Would it be possible to re-open the PR, maybe under a different contributor?

**Comment by AndersonTorres** [comment]
> Would it be possible to re-open the PR, maybe under a different contributor?

You can always open another PR with the same subject.
Given the sensitiveness of the issue, you (or any other person, for that matter) are free to not refer to that old PR.

**Comment by Nyabinary** [comment]
Same with Portmaster tbh (not toxic contributor but just died ig)

**Comment by ShalokShalom** [comment]
hblock is an amazing project. Due to ads not being downloaded, (opposite to traditional ad blockers) it increases the internet speed a lot. 

Definitely miss this on NixOS.

**Comment by FliegendeWurst** [comment]
> Definitely miss this on NixOS.

@ShalokShalom  [hostblocks](https://gaenserich.github.io/hostsblock/) is packaged and it does essentially the same thing when you supply it with the hosts lists used by hblock (https://github.com/hectorm/hblock/blob/bf882f22fe0715b170db95d2b2494c07ab4a12fe/hblock#L43-L87).

**Comment by ShalokShalom** [comment]
Oh nice, wonderful. I will try this. 👍🏻 
Could definitely be a bit more popular. 🙂

**Comment by Ashvith10** [comment]
Can we close this issue? The author has deleted their GitHub account, and the outdated top-comment is misleading.

**Comment by Nyabinary** [comment]
Closed because the original author deleted their account & the issue tracker is outdated anyways.
