### ISSUE TITLE
Vulnerability Roundup 15

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#21457]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/21289).

cc: @joachifm  @michalpalka @abbradar @bachp @LnL7 @the-kenny @Mic92 @FRidh @bjornfor @vcunat.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.
If you would like to be CC'd on _all_ roundups, leave a comment and
tell @grahamc so.

Permanent CC's: @joepie91, @phanimahesh, @NixOS/security-notifications
(if you no longer want to be CC'd, ask to be removed from this list)

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [x] Send an update e-mail to nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (17 issues)
 - [x] [`#710086`](https://lwn.net/Vulnerabilities/710086/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#710210`](https://lwn.net/Vulnerabilities/710210/) ([search](http://search.nix.gsc.io/?q=libcrypto++&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libcrypto+++in%3Apath&type=Code))  libcrypto++: denial of service
 - [x] [`#710082`](https://lwn.net/Vulnerabilities/710082/) ([search](http://search.nix.gsc.io/?q=openssh&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openssh+in%3Apath&type=Code))  openssh: multiple vulnerabilities
 - [x] [`#709844`](https://lwn.net/Vulnerabilities/709844/) ([search](http://search.nix.gsc.io/?q=ceph&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ceph+in%3Apath&type=Code))  ceph: denial of service
 - [x] [`#710085`](https://lwn.net/Vulnerabilities/710085/) ([search](http://search.nix.gsc.io/?q=gdk-pixbuf2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gdk-pixbuf2+in%3Apath&type=Code))  gdk-pixbuf2: unspecified
 - [x] [`#709987`](https://lwn.net/Vulnerabilities/709987/) ([search](http://search.nix.gsc.io/?q=GraphicsMagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=GraphicsMagick+in%3Apath&type=Code))  graphicsmagick: denial of service
 - [x] [`#709988`](https://lwn.net/Vulnerabilities/709988/) ([search](http://search.nix.gsc.io/?q=ImageMagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ImageMagick+in%3Apath&type=Code))  imagemagick: code execution
 - [x] [`#710084`](https://lwn.net/Vulnerabilities/710084/) ([search](http://search.nix.gsc.io/?q=botan&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=botan+in%3Apath&type=Code))  botan: integer overflow
 - [x] [`#710209`](https://lwn.net/Vulnerabilities/710209/) ([search](http://search.nix.gsc.io/?q=exim4&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=exim4+in%3Apath&type=Code))  exim4: information leak
 - [x] [`#710214`](https://lwn.net/Vulnerabilities/710214/) ([search](http://search.nix.gsc.io/?q=httpd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=httpd+in%3Apath&type=Code))  httpd: three vulnerabilities
 - [x] [`#709984`](https://lwn.net/Vulnerabilities/709984/) ([search](http://search.nix.gsc.io/?q=imagemagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=imagemagick+in%3Apath&type=Code))  imagemagick: code execution
 - [x] [`#709986`](https://lwn.net/Vulnerabilities/709986/) ([search](http://search.nix.gsc.io/?q=msgpuck&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=msgpuck+in%3Apath&type=Code))  msgpuck: two denial of service flaws
 - [x] [`#710212`](https://lwn.net/Vulnerabilities/710212/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: denial of service
 - [x] [`#671098`](https://lwn.net/Vulnerabilities/671098/) ([search](http://search.nix.gsc.io/?q=shellinabox&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=shellinabox+in%3Apath&type=Code))  shellinabox: DNS rebinding
 - [x] [`#710213`](https://lwn.net/Vulnerabilities/710213/) ([search](http://search.nix.gsc.io/?q=spip&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=spip+in%3Apath&type=Code))  spip: two vulnerabilities
 - [x] [`#710087`](https://lwn.net/Vulnerabilities/710087/) ([search](http://search.nix.gsc.io/?q=squid&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=squid+in%3Apath&type=Code))  squid: two vulnerabilities
 - [x] [`#709993`](https://lwn.net/Vulnerabilities/709993/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: two vulnerabilities

### gstreamer-plugins-good (2 issues)
 - [x] [`#318382`](https://lwn.net/Vulnerabilities/318382/) ([search](http://search.nix.gsc.io/?q=gstreamer-plugins-good&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gstreamer-plugins-good+in%3Apath&type=Code))  gstreamer-plugins-good: heap buffer overflows
 - [x] [`#709839`](https://lwn.net/Vulnerabilities/709839/) ([search](http://search.nix.gsc.io/?q=gstreamer-plugins-good&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gstreamer-plugins-good+in%3Apath&type=Code))  gstreamer-plugins-good: denial of service

**Comment by grahamc** [comment]
I tried updating botan with

```patch
commit 81879537edc27b40075563fff55a59ad06526d17
Author: Graham Christensen <graham@grahamc.com>
Date:   Wed Dec 28 07:08:13 2016 -0500

    botan: 1.10.13 -> 1.10.14
    
    CVE-2016-9132

diff --git a/pkgs/development/libraries/botan/default.nix b/pkgs/development/libraries/botan/default.nix
index 6e8a8cd..69e8f17 100644
--- a/pkgs/development/libraries/botan/default.nix
+++ b/pkgs/development/libraries/botan/default.nix
@@ -2,7 +2,7 @@
 
 callPackage ./generic.nix (args // {
   baseVersion = "1.10";
-  revision = "13";
-  sha256 = "144vl65z7bys43sxgb09mbisyf2nmh49wh0d957y0ksa9cyrgv13";
+  revision = "14";
+  sha256 = "072czy26vfjcqjww4qccsd29fzkb6mb8czamr4x76rdi9lwhpv8h";
   extraConfigureFlags = "--with-gnump";
 })
commit 25b0561037b986aeef9fbded100034df25348566
Author: Graham Christensen <graham@grahamc.com>
Date:   Wed Dec 28 07:08:27 2016 -0500

    botanUnstable: 1.11.32 -> 1.11.34

diff --git a/pkgs/development/libraries/botan/unstable.nix b/pkgs/development/libraries/botan/unstable.nix
index 71366ed..6ae151d 100644
--- a/pkgs/development/libraries/botan/unstable.nix
+++ b/pkgs/development/libraries/botan/unstable.nix
@@ -2,8 +2,8 @@
 
 callPackage ./generic.nix (args // {
   baseVersion = "1.11";
-  revision = "32";
-  sha256 = "0b4wgqyv6accsdh7fgr9as34r38f8r9024i6s3vhah6wiah7kddn";
+  revision = "34";
+  sha256 = "05hzffp0dxac7414a84z0fgv980cnfx55ch2y4vpg5nvin7m9bar";
   openssl = null;
   postPatch = "sed '1i#include <cmath>' -i src/tests/test_bigint.cpp";
 })

```

but get a build error:

```
In file included from src/asn1/ber_dec.cpp:11:0:
build/include/botan/internal/safeint.h: In constructor 'Botan::Integer_Overflow_Detected::Integer_Overflow_Detected(const string&, int)':
build/include/botan/internal/safeint.h:20:67: error: 'to_string' is not a member of 'std'
          Exception("Integer overflow detected at " + file + ":" + std::to_string(line))
                                                                   ^
build/include/botan/internal/safeint.h:20:67: note: suggested alternatives:
In file included from build/include/botan/exceptn.h:12:0,
                 from build/include/botan/asn1_int.h:12,
                 from build/include/botan/asn1_oid.h:11,
                 from build/include/botan/ber_dec.h:11,
                 from src/asn1/ber_dec.cpp:8:
build/include/botan/parsing.h:56:23: note:   'Botan::to_string'
 BOTAN_DLL std::string to_string(u64bit n, size_t min_len = 0);
                       ^
In file included from build/include/botan/asn1_oid.h:11:0,
                 from build/include/botan/ber_dec.h:11,
                 from src/asn1/ber_dec.cpp:8:
build/include/botan/asn1_int.h:94:13: note:   'Botan::ASN1::to_string'
 std::string to_string(const BER_Object& obj);
             ^
make: *** [Makefile:633: build/lib/asn1_ber_dec.o] Error 1
```

**Comment by the-kenny** [comment]
@grahamc Can you add me to the permanent-CC list please?

**Comment by grahamc** [comment]
Done, @the-kenny: https://github.com/NixOS/security/commit/686a57a690142de51d1c67df38eefad75d2654b5

**Comment by grahamc** [comment]
@wkennington second bump on Ceph, we're 2 major versions behind, 9.x hasn't seen an update in ages, and there don't seem to be any distros I can take the security patches from. I may mark as broken soon.

**Comment by 7c6f434c** [comment]
re: `botan`: fixed, stable version wasn't enforcing C++11 for some reason.

**Comment by grahamc** [comment]
Thank you, @7c6f434c!

**Comment by 7c6f434c** [comment]
`imagemagick`: I have updated to the latest repository release tag, no idea if it fixes all the vulnerabilities.

**Comment by grahamc** [comment]
image magick: https://github.com/NixOS/nixpkgs/compare/9ec867f59fba...de99dc50495e

**Comment by 7c6f434c** [comment]
Also updated `dovecot`

**Comment by grahamc** [comment]
dovecot: https://github.com/NixOS/nixpkgs/commit/35e3ea0966bcdf3483fc25e78a5e9e1887befe9b

**Comment by vcunat** [comment]
gdk-pixbuf: 421a7f37f and f3d383553e6.

**Comment by LnL7** [comment]
@vcunat any idea what's going wrong with the [openssh test](http://hydra.nixos.org/build/45500080)?

**Comment by vcunat** [comment]
No, I do not. That's why I had reverted that update.

**Comment by grahamc** [comment]
re SSH: I was able to reproduce the issue locally.

**Comment by nlewo** [comment]
qemu CVE-2016-9911 adressed by #21482.

**Comment by grahamc** [comment]
@vcunat, @LnL7 

applying:

```patch
diff --git a/nixos/modules/services/networking/ssh/sshd.nix b/nixos/modules/services/networking/ssh/sshd.nix
index 073391f..80659f1 100644
--- a/nixos/modules/services/networking/ssh/sshd.nix
+++ b/nixos/modules/services/networking/ssh/sshd.nix
@@ -264,8 +264,7 @@ in
                 StandardInput = "socket";
               } else {
                 Restart = "always";
-                Type = "forking";
-                PIDFile = "/run/sshd.pid";
+                Type = "simple";
               });
           };
 
@@ -322,8 +321,6 @@ in
 
     services.openssh.extraConfig = mkOrder 0
       ''
-        PidFile /run/sshd.pid
-
         Protocol 2
 
         UsePAM yes
```

has fixed it for me:

 - https://bugzilla.mindrot.org/attachment.cgi?id=2896&action=diff
 - https://bugzilla.mindrot.org/show_bug.cgi?id=2641

```
 * sshd(8): Improve handling of SIGHUP by checking to see if sshd is
   already daemonised at startup and skipping the call to daemon(3)
   if it is. This ensures that a SIGHUP restart of sshd(8) will
   retain the same process-ID as the initial execution. sshd(8) will
   also now unlink the PidFile prior to SIGHUP restart and re-create
   it after a successful restart, rather than leaving a stale file in
   the case of a configuration error. bz#2641
```

what do you think of this solution / backporting?

**Comment by vcunat** [comment]
I know little about this stuff. In master it'll be good to switch to `--with-systemd`, I guess, though that's not security-related. /cc openssh maintainer @aneeshusa. Context: previous comment and  661b5a9.

**Comment by grahamc** [comment]
@vcunat / @aneeshusa -- they don't create any sort of `--with-systemd` flag. That patch was rejected. The change they made makes it properly realize it is already backgrounded and not background itself if it is called by an init system. That is why my patch works, without adding a --with-systemd flag.

**Comment by LnL7** [comment]
That's also how I understood it, if simple also works with `services.openssh.startWhenNeeded` it should be fine.

**Comment by grahamc** [comment]
I marked ceph as broken.

**Comment by grahamc** [comment]
Thank you, everyone, for their work!
