### ISSUE TITLE
Vulnerability Roundup 16

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#21642]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/21457).

cc: @7c6f434c @LnL7 @nlewo @vcunat.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.

Permanent CC's: @joepie91, @phanimahesh, @the-kenny,
@NixOS/security-notifications
If you would like to be CC'd on _all_ roundups (or removed from the
list), open a PR editing
https://github.com/NixOS/security/blob/master/lwnvulns/src/bin/instructions.md.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [x] Send an update e-mail to nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (30 issues)
 - [x] [`#710484`](https://lwn.net/Vulnerabilities/710484/) ([search](http://search.nix.gsc.io/?q=bash&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bash+in%3Apath&type=Code))  bash: code execution
 - [x] [`#710286`](https://lwn.net/Vulnerabilities/710286/) ([search](http://search.nix.gsc.io/?q=openjpeg2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg2+in%3Apath&type=Code))  openjpeg2: multiple vulnerabilities
 - [x] [`#710478`](https://lwn.net/Vulnerabilities/710478/) ([search](http://search.nix.gsc.io/?q=python-crypto&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-crypto+in%3Apath&type=Code))  python-crypto: denial of service
 - [x] [`#710356`](https://lwn.net/Vulnerabilities/710356/) ([search](http://search.nix.gsc.io/?q=smack&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=smack+in%3Apath&type=Code))  smack: TLS bypass
 - [x] [`#710358`](https://lwn.net/Vulnerabilities/710358/) ([search](http://search.nix.gsc.io/?q=tracker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tracker+in%3Apath&type=Code))  tracker: adding sandboxing
 - [x] [`#710363`](https://lwn.net/Vulnerabilities/710363/) ([search](http://search.nix.gsc.io/?q=gstreamer-plugins-good&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gstreamer-plugins-good+in%3Apath&type=Code))  gstreamer-plugins-good: code execution
 - [x] [`#710480`](https://lwn.net/Vulnerabilities/710480/) ([search](http://search.nix.gsc.io/?q=cxf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=cxf+in%3Apath&type=Code))  cxf: two vulnerabilities
 - [x] [`#710486`](https://lwn.net/Vulnerabilities/710486/) ([search](http://search.nix.gsc.io/?q=cyassl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=cyassl+in%3Apath&type=Code))  cyassl: multiple vulnerabilities
 - [x] [`#710281`](https://lwn.net/Vulnerabilities/710281/) ([search](http://search.nix.gsc.io/?q=js-jquery&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=js-jquery+in%3Apath&type=Code))  js-jquery: cross-site scripting
 - [x] [`#710475`](https://lwn.net/Vulnerabilities/710475/) ([search](http://search.nix.gsc.io/?q=libphp-phpmailer&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libphp-phpmailer+in%3Apath&type=Code))  libphp-phpmailer: code execution
 - [x] [`#624315`](https://lwn.net/Vulnerabilities/624315/) ([search](http://search.nix.gsc.io/?q=mod-wsgi&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mod-wsgi+in%3Apath&type=Code))  mod-wsgi: privilege escalation
 - [x] [`#710282`](https://lwn.net/Vulnerabilities/710282/) ([search](http://search.nix.gsc.io/?q=nagios-plugins&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nagios-plugins+in%3Apath&type=Code))  nagios-plugins: multiple vulnerabilities
 - [x] [`#710482`](https://lwn.net/Vulnerabilities/710482/) ([search](http://search.nix.gsc.io/?q=php-zendframework-zend-mail&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php-zendframework-zend-mail+in%3Apath&type=Code))  php-zendframework-zend-mail: parameter injection
 - [x] [`#710477`](https://lwn.net/Vulnerabilities/710477/) ([search](http://search.nix.gsc.io/?q=postgresql-common&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=postgresql-common+in%3Apath&type=Code))  postgresql-common: file overwrites
 - [x] [`#710283`](https://lwn.net/Vulnerabilities/710283/) ([search](http://search.nix.gsc.io/?q=python-wikitcms&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-wikitcms+in%3Apath&type=Code))  python-wikitcms: code execution
 - [x] [`#710483`](https://lwn.net/Vulnerabilities/710483/) ([search](http://search.nix.gsc.io/?q=springframework&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=springframework+in%3Apath&type=Code))  springframework: directory traversal
 - [x] [`#710485`](https://lwn.net/Vulnerabilities/710485/) ([search](http://search.nix.gsc.io/?q=chicken&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=chicken+in%3Apath&type=Code))  chicken: two vulnerabilities
 - [x] [`#632571`](https://lwn.net/Vulnerabilities/632571/) ([search](http://search.nix.gsc.io/?q=e2fsprogs&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=e2fsprogs+in%3Apath&type=Code))  e2fsprogs: code execution
 - [x] [`#710285`](https://lwn.net/Vulnerabilities/710285/) ([search](http://search.nix.gsc.io/?q=firejail-lts&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firejail-lts+in%3Apath&type=Code))  firejail-lts: denial of service
 - [x] [`#710362`](https://lwn.net/Vulnerabilities/710362/) ([search](http://search.nix.gsc.io/?q=irc-otr&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=irc-otr+in%3Apath&type=Code))  irc-otr: information disclosure
 - [x] [`#710476`](https://lwn.net/Vulnerabilities/710476/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: three vulnerabilities
 - [x] [`#710487`](https://lwn.net/Vulnerabilities/710487/) ([search](http://search.nix.gsc.io/?q=libarchive&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libarchive+in%3Apath&type=Code))  libarchive: denial of service
 - [x] [`#710481`](https://lwn.net/Vulnerabilities/710481/) ([search](http://search.nix.gsc.io/?q=libpng&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libpng+in%3Apath&type=Code))  libpng: NULL dereference bug
 - [x] [`#604237`](https://lwn.net/Vulnerabilities/604237/) ([search](http://search.nix.gsc.io/?q=lzo&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=lzo+in%3Apath&type=Code))  lzo: denial of service/possible code execution
 - [x] [`#710489`](https://lwn.net/Vulnerabilities/710489/) ([search](http://search.nix.gsc.io/?q=mariadb&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mariadb+in%3Apath&type=Code))  mariadb: multiple unspecified vulnerabilities
 - [x] [`#623865`](https://lwn.net/Vulnerabilities/623865/) ([search](http://search.nix.gsc.io/?q=mutt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mutt+in%3Apath&type=Code))  mutt: denial of service
 - [x] [`#710489`](https://lwn.net/Vulnerabilities/710489/) ([search](http://search.nix.gsc.io/?q=mysql&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql+in%3Apath&type=Code))  mariadb: multiple unspecified vulnerabilities
 - [x] [`#710278`](https://lwn.net/Vulnerabilities/710278/) ([search](http://search.nix.gsc.io/?q=openfire&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openfire+in%3Apath&type=Code))  openfire: multiple vulnerabilities
 - [x] [`#710490`](https://lwn.net/Vulnerabilities/710490/) ([search](http://search.nix.gsc.io/?q=pillow&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pillow+in%3Apath&type=Code))  pillow: heap-based buffer overflow
 - [x] [`#629994`](https://lwn.net/Vulnerabilities/629994/) ([search](http://search.nix.gsc.io/?q=xdg-utils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xdg-utils+in%3Apath&type=Code))  xdg-utils: command execution

### curl (2 issues)
 - [x] [`#710474`](https://lwn.net/Vulnerabilities/710474/) ([search](http://search.nix.gsc.io/?q=curl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=curl+in%3Apath&type=Code))  curl: information leak
 - [x] [`#710279`](https://lwn.net/Vulnerabilities/710279/) ([search](http://search.nix.gsc.io/?q=curl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=curl+in%3Apath&type=Code))  curl: buffer overflow

### xen (2 issues)
 - [x] [`#710491`](https://lwn.net/Vulnerabilities/710491/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: denial of service
 - [x] [`#710284`](https://lwn.net/Vulnerabilities/710284/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: denial of service

**Comment by grahamc** [comment]
Xen vulns were old.

**Comment by 7c6f434c** [comment]
`libpng`, `firejail` : recently updated

**Comment by grahamc** [comment]
Should firejail be backported?

**Comment by 7c6f434c** [comment]
Hm, hard to say when the vulnerability appeared. OK, let's backport it just in case…

**Comment by 7c6f434c** [comment]
`chicken`: 4.11 seems to be about fixing these vulnerabilities, present in both master and release.

**Comment by grahamc** [comment]
@7c6f434c I see your backport, thank you! In the future, please backport using `git cherry-pick -x COMMIT`

**Comment by 7c6f434c** [comment]
Technically, for `firejail` it would be moot (different starting version, so a conflict), but will try to remember.

**Comment by grahamc** [comment]
Thanks! My tooling for security notes detects the `(cherry picked from commit ...)` to make sure to duplicate them.

**Comment by 7c6f434c** [comment]
`xdg_utils`: we have `1.1.1` (both places), which seems to contain the fix. The vulnerability is two years old.

**Comment by grahamc** [comment]
I really appreciate your help, this is excellent. I've noticed Gentoo has been picking up very old vulnerabilities lately, I wonder if they got some fresh blood on the team :)

**Comment by 7c6f434c** [comment]
Re: `postgresql`: does NixOS do logging in a similar enough way for that to be a concern? My only NixOS system doesn't run PostgreSQL, and my Nix-based PostgreSQL-running system does logging differently, but I expect `journald` to be different enough

**Comment by 7c6f434c** [comment]
I don't use mainline NixOS enough to make this call.

`lzo`: old stuff, we are good

**Comment by 7c6f434c** [comment]
`mutt`: we have the branch-latest releases in two branches (1.7.2 and 1.6.2), the vulnerability is about 1.5.x

**Comment by 7c6f434c** [comment]
`e2fsprogs`: we have fresh stuff

**Comment by grahamc** [comment]
Collapsed the completed ones.

**Comment by 7c6f434c** [comment]
`bash` report seems relevant. It is also a mass-rebuild. It looks like one of the bugs is present in 4.4 even, so we may need to take a patch (maybe from Gentoo)

**Comment by vcunat** [comment]
We might use the opportunity and switch the default non-interactive bash to 4.4 (on master/staging).  Can you see a reference to an upstream fix?  I see nothing in the official 4.4 patch list.

**Comment by 7c6f434c** [comment]
I think upstream considers the fix in 4.4 branch not to be worth rushing, and Gentoo decided to include it as a patch anyway

**Comment by 7c6f434c** [comment]
`mariadb` is about 10.0 branch, we use a 10.1 release that is also fresher than the 10.0.28 fix.

**Comment by grahamc** [comment]
We should verify the latest 10.1 releases to see if we're behind / missing a patch for something, and also our version(s) of mysql, since bugs in one are frequently in the other.

**Comment by 7c6f434c** [comment]
`cxf`: do we even ship Apache CXF?

**Comment by 7c6f434c** [comment]
`irssi_otr`: updated. Not sure whether we have some problems with `irssi` header installation; in this case it was easier to bruteforce `-I` flags to fit the layout, but it looks like `irssi` headers expect strange relative paths to work.

MySQL also updated.

Both fixes ported to release branch.

**Comment by 7c6f434c** [comment]
`openjpeg`: Apparently there is a ton of fuzzing-found issues upstream, and no recent changes in the master repository.

One of the people doing the fuzzing tried to fix as many of the issues as possible and thinks this patch is a good step in this direction; I haven't looked at the patch, though:
https://github.com/uclouvain/openjpeg/pull/875/files

**Comment by 7c6f434c** [comment]
`openfire` is an interesting case. The version in NixPkgs is older than what the CVE talks about; I used it long long time ago. The fresh version of OpenFire just expects to be able to write to its installation directory in random places (not just logs and config, which I have replaced with symlinks to somewhat reasonable locations), and on the other hand its installation is still just unpacking and patching a few lines here and there. I guess the package could be marked as broken.

**Comment by FRidh** [comment]
`python-crypto` or `pycrypto` isn't being maintained anymore. According to [this comment](https://github.com/dlitz/pycrypto/issues/176#issuecomment-261803364) the issue has been resolved on master already 3 years ago, but it hasn't been included in any release. 

A maintained fork of `pycrypto` is [`pycryptodome`](https://github.com/Legrandin/pycryptodome). We should see if we can replace `pycrypto` with `pycryptodome`.

**Comment by FRidh** [comment]
Pillow: 

> Integer overflow in the ImagingResampleHorizontal function in libImaging/Resample.c in Pillow before 3.1.1 allows remote attackers to have unspecified impact via negative values of the new size, which triggers a heap-based buffer overflow.

We have 3.4.2 on both stable and master so we're fine.

**Comment by grahamc** [comment]
@FRidh does that need to be backported? Is it okay to backport?

**Comment by vcunat** [comment]
Bash should be OK now in staging and 16.09,

**Comment by fpletz** [comment]
We're safe on gstreamer-plugins-good as we already have the release with the fix.

Tracker doesn't have a CVE but Fedora somehow sandboxed tracker. I think this is not applicable for us for now.

pycrypto is fixed by https://github.com/NixOS/nixpkgs/commit/fe9373460c08c83449657b22c026c806bec92d21.

**Comment by FRidh** [comment]
Unfortunately we can't just replace `pycrypto` with `pycryptodome`. In the long run we do have to get rid of that package which likely means updating a lot of dependents.

**Comment by FRidh** [comment]
@fpletz yes we can, #21671

**Comment by fpletz** [comment]
Irssi just released a new version due to these security vulnerabilities: https://irssi.org/security/irssi_sa_2017_01.txt

**Comment by fpletz** [comment]
I bumped smack on master from 3.4.1 to 4.1.9 where the issue is fixed. As we were using the pre-compiled jars, we can't trivally apply a patch and that version bump is likely to break stuff. Fortunately nothing in nixpkgs depends on smack.

Should we upgrade smack to 4.1.9 or mark is as broken? I'd go for upgrade because nobody is probably using it anyway.

**Comment by grahamc** [comment]
@fpletz I would prefer marking as broken than upgrading, for now. We'll see if people make an issue in the bug tracker what they'd like to do :)

**Comment by grahamc** [comment]
For openjpeg2, I've got found and applied several patches. Here is my diff:

```patch
diff --git a/pkgs/development/libraries/openjpeg/2.1.nix b/pkgs/development/libraries/openjpeg/2.1.nix
index 9e3c447..b9e0637 100644
--- a/pkgs/development/libraries/openjpeg/2.1.nix
+++ b/pkgs/development/libraries/openjpeg/2.1.nix
@@ -1,4 +1,4 @@
-{ callPackage, ... } @ args:
+{ callPackage, fetchpatch, ... } @ args:
 
 callPackage ./generic.nix (args // rec {
   version = "2.1.2";
@@ -12,5 +12,51 @@ callPackage ./generic.nix (args // rec {
     # Put in our source code to make sure we don't lose it, since that
     # referenced commit is someone else's fork, and not actually up-stream.
     ./CVE-2016-9580-and-CVE-2016-9581.patch
+
+    #(fetchpatch {
+    #  url = "https://bugzilla.suse.com/attachment.cgi?id=707353&action=diff&context=patch&collapsed=&headers=1&format=raw";
+    #  name = "CVE-2016-9113.patch";
+    #  sha256 = "1zb90m4hwrdddb8lc4pgi1xxmi5f08a22kcq3lbz2y6zfd5vfi4k";
+    #})
+    (fetchpatch {
+      url = "https://bugzilla.suse.com/attachment.cgi?id=707354&action=diff&context=patch&collapsed=&headers=1&format=raw";
+      name = "CVE-2016-9114.patch";
+      sha256 = "0qam3arw9kdbh4501xim2pyldl708dnpyjwvjmwc9gc7hcq4gfi3";
+    })
+    #(fetchpatch {
+    #  url = "https://bugzilla.suse.com/attachment.cgi?id=707355&action=diff&context=patch&collapsed=&headers=1&format=raw";
+    #  name = "CVE-2016-9115.patch";
+    #  sha256 = "1x9lh5ga67pvjf1z33dgdivzj4k8g8jwdgvfpmk5qqhmmk8zkg8x";
+    #})
+    (fetchpatch {
+      url = "https://bugzilla.suse.com/attachment.cgi?id=707356&action=diff&context=patch&collapsed=&headers=1&format=raw";
+      name = "CVE-2016-9116.patch";
+      sha256 = "0yyb3pxqi5sr44a48bacngzp206j4z49lzkg6hbkz1nra9na61a3";
+    })
+    #(fetchpatch {
+    #  url = "https://bugzilla.suse.com/attachment.cgi?id=707357&action=diff&context=patch&collapsed=&headers=1&format=raw";
+    #  name = "CVE-2016-9117.patch";
+    #  sha256 = "0m8c43msqlggiw2pmbr4cangbkkfpjwhp45bsf5vchh633ybyvz0";
+    #})
+    (fetchpatch {
+      url = "https://bugzilla.suse.com/attachment.cgi?id=707358&action=diff&context=patch&collapsed=&headers=1&format=raw";
+      name = "CVE-2016-9118.patch";
+      sha256 = "125n8bmh07y7697s0y82ypb39rxgj0bdn8rcywbvamscagwg2wy9";
+    })
+    (fetchpatch {
+      url = "https://bugzilla.suse.com/attachment.cgi?id=707359&action=diff&context=patch&collapsed=&headers=1&format=raw";
+      name = "CVE-2016-9112.patch";
+      sha256 = "18hqx73wdzfybr5n5k6pzhbhdlmawiqbjci8n82zykxiyfgp18pd";
+    })
+    #(fetchpatch {
+    #  url = "https://bugzilla.suse.com/attachment.cgi?id=707360&action=diff&context=patch&collapsed=&headers=1&format=raw";
+    #  name = "CVE-2016-9572-CVE-2016-9573.patch";
+    #  sha256 = "1qzmhr5k7vr1nlv2cgv92858mr4g2bhh8y4fw28dwgi9djfvnzn8";
+    #})
+    #(fetchpatch {
+    #  url = "https://bugzilla.suse.com/attachment.cgi?id=707351&action=diff&context=patch&collapsed=&headers=1&format=raw";
+    #  name = "CVE-2016-7445.patch";
+    #  sha256 = "1zswpsjs8if79x0a5dr27173434dx5q1jryv7ql9afd7sp1zdccw";
+    #})
   ];
 })
```

the commented ones don't apply cleanly, presumably because suse is on a different version. Debian doesn't have alternative patches yet. What do you think, @fpletz? Patch what we can now?

**Comment by vcunat** [comment]
All channels except nixos-unstable have updated and contain the mass-rebuild changes (e.g. bash).

**Comment by grahamc** [comment]
I've decided to apply the patches that I do have, and leave openjpeg2 in the list for next week to see if any development has taken place.

**Comment by grahamc** [comment]
Done. Phew! Good work and thank you :)
