### ISSUE TITLE
RFC: Graphical installer for NixOS

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#21662]
## Background

This is a project idea for Google Summer of Code 2017. I'm treating this more as a request for comment right now as opposed to a generic issue. Any and all feedback is welcome. Some of this proposal will probably change as I dive more into how Calamares works.

## Issue description

Basically, NixOS has a fairly complicated [installation process][1]. Some proposals like [nixos-assimilate][2] attempt to make this process easier but they are still a fairly low-level operation. The goal is to make the installation process for NixOS as easy as more mainstream distros like Ubuntu and Fedora.

## Proposal

This would rely heavily on [Calamares][3], a distro-independent system installation framework. It's the best framework I've been able to find and so doesn't require reimplemented menus and things used by other distros. An important goal is to keep this all in Nix expressions to allow for configuring the Calamares installer just like you would any other service. Calamares will be added as a NixOS service which can be enabled in the NixOS configuration and eventually added as the default for our "demo" profiles.

## Tasks

- [x] Package Calamares
- [ ] Add NixOS service
- [ ] Implement Calamares modules as Nix expressions (reuse where possible)
  - [ ] "try NixOS" module (KDE desktop) [5]
  - [ ] networking module (NetworkManager) [6]
  - [ ] partitioning module (nixpart) [7]
  - [ ] NixOS configuration generator module (menus for common profiles) [10]
    - keep versatile enough to be usable as a generic NixOS options GUI
  - [ ] nixos-install module (nixos-assimilate) [11]
- [ ] Add Calamares config file
- [ ] Add NixOS branding to Calamares
- [ ] Enable Calamares as demo profile

[1]: https://nixos.org/nixos/manual/index.html#ch-installation
[2]: https://github.com/NixOS/nixpkgs/issues/2079
[3]: https://calamares.io

**Comment by Mic92** [comment]
cc @cleverca22

**Comment by vcunat** [comment]
Note: we used to have calamares: c677c359.

**Comment by matthewbauer** [comment]
>cc @cleverca22 because you were working on a GUI for NixOS options/partition editor.

I hadn't seen [nixos-installer](https://github.com/cleverca22/nixos-installer)! I'll have to figure out how it's working and see if this proposal is still needed.

**Comment by michaelpj** [comment]
I'd love to see this go somewhere - installing NixOS is currently a bit unfriendly.

**Comment by Mic92** [comment]
@manveru and @manveru are also working on an [installer](https://github.com/manveru/nixos-installer)

**Comment by manveru** [comment]
@matthewbauer i at least managed to package calamares now. Played around a bit with branding and writing some simple python modules to generate a configuration.
My C++ skills are not good enough to write anything major for the GUI like a nixos configuration manager, but it should be good enough for getting an initial setup up and running.
I'm working on a nixos config editor for the browser as well, which might be useful down the line, but right now my priority is to get new users onboard ASAP.

**Comment by davidak** [comment]
The developers of [elementary OS](https://elementary.io/) and [Pop!_OS](https://system76.com/pop) (System76) are creating a new Installer. They say all available installers are complicated to modify and don't have good user experience.

https://medium.com/elementaryos/meet-the-upcoming-installer-a499341218f5
https://github.com/elementary/installer/wiki

The Frontend is written in Vala and Gtk+ while the backend is written in Rust.

https://github.com/elementary/installer
https://github.com/pop-os/distinst

They want to have it ready in April 2018 for their distros.

By using it we could have very user friendly design like elementary OS and build on a clean and modern foundation. What do you think?

**Comment by davidak** [comment]
This is a nice example how a very customizable setup can look:

![screenshot_2018-04-07_01-48-41](https://user-images.githubusercontent.com/91113/38448684-69a74994-3a06-11e8-836b-8686417f7bc3.png)

![screenshot_2018-04-07_01-49-06](https://user-images.githubusercontent.com/91113/38448688-6e272f52-3a06-11e8-9242-b854312b9eb7.png)

We can have the most important options there to get a desktop user started.

**Comment by cleverca22** [comment]
something i was also planning on with my idea was a `configuration.nix` editor that is aware of the syntax and the available options: https://www.youtube.com/watch?v=rIdPKzYTN-w

and also to be able to run the gui over http, so you could remotely configure a server

**Comment by leo60228** [comment]
NixOS modules can be introspected (like the options page on nixos.org does), right? Make some icons for top-level configuration options and a heuristic for formatting options, and you're already most of the way there for the data required for a configuration.nix editor.

**Comment by LeBaux** [comment]
I see the liveCD is already available, but still no installer. I understand it is no priority, but it would be nice to just hop on, Install nixos with GUI and mess around. GUI package manager would make it even more accessible. That is if nixos is intended for general use.

**Comment by tycho01** [comment]
> something i was also planning on with my idea was a `configuration.nix` editor that is aware of the syntax and the available options: https://www.youtube.com/watch?v=rIdPKzYTN-w
> 
> and also to be able to run the gui over http, so you could remotely configure a server

Generating form UIs from a spec has been explored in e.g. [`react-jsonschema-form`](https://mozilla-services.github.io/react-jsonschema-form/), in that case using JSON schema as a specification rather than Nix...

**Comment by davidak** [comment]
FYI: @manveru is working on a graphical NixOS installer based on Calamares.

https://discourse.nixos.org/t/what-are-your-goals-for-20-03/4773/7?u=davidak

I'm looking forward to be able to test it :)

**Comment by Mic92** [comment]
still important.

**Comment by milahu** [comment]
would be nice to have: a textual frontend for the same backend
* to bootstrap the graphical frontend (or as fallback in case the graphical menu is broken)
* to provide a menu for a headless setup
