### ISSUE TITLE
Vulnerability Roundup 18

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#21967]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/21803).

cc: @fpletz @FRidh @Mic92 @7c6f434c @LnL7 @bachp .

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.

Permanent CC's: @joepie91, @phanimahesh, @the-kenny,
@NixOS/security-notifications
If you would like to be CC'd on _all_ roundups (or removed from the
list), open a PR editing
https://github.com/NixOS/security/blob/master/lwnvulns/src/bin/instructions.md.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [ ] Run the issue through `reformat` one last time
 - [ ] Review commits since last roundup for backport candidates
 - [ ] Send an update e-mail to nix-security-announce@googlegroups.com
 - [ ] Update the database at https://github.com/NixOS/security

Without further ado...
### Assorted (2 issues)
 - [x] [`#711581`](https://lwn.net/Vulnerabilities/711581/) ([search](http://search.nix.gsc.io/?q=ark&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ark+in%3Apath&type=Code))  ark: code execution
 - [x] [`#711782`](https://lwn.net/Vulnerabilities/711782/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities

---
## 2 remaining, 32 completed

<details><summary><strong>
    CLICK TO EXPAND Show all 32 triaged and resolved issues
  </strong></summary>

### Assorted (30 issues)
 - [x] [`#645632`](https://lwn.net/Vulnerabilities/645632/) ([search](http://search.nix.gsc.io/?q=fuse&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=fuse+in%3Apath&type=Code))  fuse: privilege escalation
 - [x] [`#711858`](https://lwn.net/Vulnerabilities/711858/) ([search](http://search.nix.gsc.io/?q=icinga&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=icinga+in%3Apath&type=Code))  icinga: cross-site scripting
 - [x] [`#711775`](https://lwn.net/Vulnerabilities/711775/) ([search](http://search.nix.gsc.io/?q=icoutils&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=icoutils+in%3Apath&type=Code))  icoutils: three vulnerabilities
 - [x] [`#711459`](https://lwn.net/Vulnerabilities/711459/) ([search](http://search.nix.gsc.io/?q=python-pysaml2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-pysaml2+in%3Apath&type=Code))  python-psaml2: XML external entity attacks
 - [x] [`#711583`](https://lwn.net/Vulnerabilities/711583/) ([search](http://search.nix.gsc.io/?q=rabbitmq-server&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rabbitmq-server+in%3Apath&type=Code))  rabbitmq-server: authentication bypass
 - [x] [`#711774`](https://lwn.net/Vulnerabilities/711774/) ([search](http://search.nix.gsc.io/?q=wordpress&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wordpress+in%3Apath&type=Code))  wordpress: multiple vulnerabilities
 - [x] [`#711780`](https://lwn.net/Vulnerabilities/711780/) ([search](http://search.nix.gsc.io/?q=apache&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=apache+in%3Apath&type=Code))  apache: denial of service
 - [x] [`#711463`](https://lwn.net/Vulnerabilities/711463/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [x] [`#711457`](https://lwn.net/Vulnerabilities/711457/) ([search](http://search.nix.gsc.io/?q=bind9&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind9+in%3Apath&type=Code))  bind: three denial of service flaws
 - [x] [`#652803`](https://lwn.net/Vulnerabilities/652803/) ([search](http://search.nix.gsc.io/?q=freeradius&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=freeradius+in%3Apath&type=Code))  freeradius: insufficient certificate verification
 - [x] [`#710286`](https://lwn.net/Vulnerabilities/710286/) ([search](http://search.nix.gsc.io/?q=openjpeg2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openjpeg2+in%3Apath&type=Code))  openjpeg2: multiple vulnerabilities
 - [x] [`#711464`](https://lwn.net/Vulnerabilities/711464/) ([search](http://search.nix.gsc.io/?q=gnutls&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gnutls+in%3Apath&type=Code))  gnutls: multiple vulnerabilities
 - [x] [`#711458`](https://lwn.net/Vulnerabilities/711458/) ([search](http://search.nix.gsc.io/?q=ikiwiki&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ikiwiki+in%3Apath&type=Code))  ikiwiki: three vulnerabilities
 - [x] [`#711329`](https://lwn.net/Vulnerabilities/711329/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#711777`](https://lwn.net/Vulnerabilities/711777/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  tiff: three vulnerabilities
 - [x] [`#598449`](https://lwn.net/Vulnerabilities/598449/) ([search](http://search.nix.gsc.io/?q=miniupnpc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=miniupnpc+in%3Apath&type=Code))  miniupnpc: denial of service
 - [x] [`#711779`](https://lwn.net/Vulnerabilities/711779/) ([search](http://search.nix.gsc.io/?q=onionshare&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=onionshare+in%3Apath&type=Code))  onionshare: file injection
 - [x] [`#711776`](https://lwn.net/Vulnerabilities/711776/) ([search](http://search.nix.gsc.io/?q=pdns&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pdns+in%3Apath&type=Code))  pdns: multiple vulnerabilities
 - [x] [`#711461`](https://lwn.net/Vulnerabilities/711461/) ([search](http://search.nix.gsc.io/?q=qpid-java&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qpid-java+in%3Apath&type=Code))  qpid-java: information disclosure
 - [x] [`#711462`](https://lwn.net/Vulnerabilities/711462/) ([search](http://search.nix.gsc.io/?q=springframework-security&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=springframework-security+in%3Apath&type=Code))  springframework-security: security constraint bypass
 - [x] [`#711330`](https://lwn.net/Vulnerabilities/711330/) ([search](http://search.nix.gsc.io/?q=webkit2gtk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=webkit2gtk+in%3Apath&type=Code))  webkit2gtk: multiple vulnerabilities
 - [x] [`#711856`](https://lwn.net/Vulnerabilities/711856/) ([search](http://search.nix.gsc.io/?q=SimGear&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=SimGear+in%3Apath&type=Code))  SimGear: file overwrites
 - [x] [`#711582`](https://lwn.net/Vulnerabilities/711582/) ([search](http://search.nix.gsc.io/?q=docker&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=docker+in%3Apath&type=Code))  docker: privilege escalation
 - [x] [`#711781`](https://lwn.net/Vulnerabilities/711781/) ([search](http://search.nix.gsc.io/?q=irssi&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=irssi+in%3Apath&type=Code))  irssi: out of bounds read
 - [x] [`#711586`](https://lwn.net/Vulnerabilities/711586/) ([search](http://search.nix.gsc.io/?q=libgit2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgit2+in%3Apath&type=Code))  libgit2: multiple vulnerabilities
 - [x] [`#711778`](https://lwn.net/Vulnerabilities/711778/) ([search](http://search.nix.gsc.io/?q=libx11&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libx11+in%3Apath&type=Code))  libx11: denial of service
 - [x] [`#711324`](https://lwn.net/Vulnerabilities/711324/) ([search](http://search.nix.gsc.io/?q=phpBB&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=phpBB+in%3Apath&type=Code))  phpBB: two vulnerabilities
 - [x] [`#711325`](https://lwn.net/Vulnerabilities/711325/) ([search](http://search.nix.gsc.io/?q=phpmyadmin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=phpmyadmin+in%3Apath&type=Code))  phpmyadmin: two vulnerabilities
 - [x] [`#657322`](https://lwn.net/Vulnerabilities/657322/) ([search](http://search.nix.gsc.io/?q=vzctl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=vzctl+in%3Apath&type=Code))  vzctl: insecure ploop-based containers
 - [x] [`#711587`](https://lwn.net/Vulnerabilities/711587/) ([search](http://search.nix.gsc.io/?q=webmin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=webmin+in%3Apath&type=Code))  webmin: largely unspecified

### pgbouncer (2 issues)
 - [x] [`#711323`](https://lwn.net/Vulnerabilities/711323/) ([search](http://search.nix.gsc.io/?q=pgbouncer&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pgbouncer+in%3Apath&type=Code))  pgbouncer: authentication bypass
 - [x] [`#645925`](https://lwn.net/Vulnerabilities/645925/) ([search](http://search.nix.gsc.io/?q=pgbouncer&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=pgbouncer+in%3Apath&type=Code))  pgbouncer: denial of service

</details>

**Comment by vcunat** [comment]
Our libX11 is not vulnerable.  According to [the Debian commit](https://anonscm.debian.org/cgit/pkg-xorg/lib/libx11.git/commit/?id=a2dc2a69d6b4a3706ea3b3ac1b05c250ae8c7be3) the problem was introduced [after 1.6.4 release](https://cgit.freedesktop.org/xorg/lib/libX11/log/) as an incorrect attempt to fix a memory leak.  So, our version may only leak memory. I'd personally wait for a release for this one.

**Comment by the-kenny** [comment]
Our simgear doesn't seem to be vulnerable either: The [Fedora alert](https://lwn.net/Alerts/711820/) is about `2016.3.1` and we're on `2016.4.3`. 

I'll push an update to `2016.4.4` in a few hours.

**Comment by 7c6f434c** [comment]
`libgit2`: we have a fresh enough version

**Comment by globin** [comment]
libupnp: https://github.com/NixOS/nixpkgs/commit/3be6e9fc5af88fca55ba3b3a2f8be46ed21c9f35 (not related to this roundup)

**Comment by NeQuissimus** [comment]
We have Docker 1.12.6, which closes the vulnerability mentioned

**Comment by vcunat** [comment]
**gnutls**: their [advisories](https://gnutls.org/security.html#GNUTLS-SA-2017-2) possibly imply that 3.4 branch is no longer maintained at this point, though I see no explicit saying of that.  In any case, master and 16.09 have 3.4 as the default which was last updated on Dec 08 upstream.

**Comment by bachp** [comment]
Does someone have an idea how to handle the ark issues? Do we need to update all of KDE?

**Comment by bachp** [comment]
Actually I think the ark issue is already fixed in https://github.com/NixOS/nixpkgs/commit/7d01fff5160b12f2ce6795c028a1178bcd33805a

**Comment by grahamc** [comment]
Thanks for the research and looking y'all did today. I wasn't able to do very much due to working on secret side projects, but am carving out some time now.

**Comment by grahamc** [comment]
- [ ] Ikiwiki needs patching to 3.20170111 with backport

**Comment by 7c6f434c** [comment]
`ikiwiki`: done

**Comment by vcunat** [comment]
``libtiff``: took all patches from Debian, on both active branches.

**Comment by grahamc** [comment]
pdns: fixed in 1fe51342a98638d32349e0930afe6c1751e612ef (for notes later)

**Comment by grahamc** [comment]
Bind addressed in /2fd0a9f3c74a29e87952c7657aed8194258a83c4 and 7b34209e1bb5d38106115e52506a2ed777608672 (thank you, @peti)

**Comment by grahamc** [comment]
@bachp I suspect we need to fix ark on 16.09. Can you check in to that?

**Comment by 7c6f434c** [comment]
`php` security update ported to stable, except the `php71` part which is not relevant there.

**Comment by nlewo** [comment]
#22001 fixes all qemu CVEs mentionned above excepted CVE-2016-9908 because vulnerable code is not present in our qemu version.

We should definitely upgrade our qemu version as initiated by @7c6f434c with the 2.8 version.

**Comment by 7c6f434c** [comment]
@nlewo thanks

@grahamc I cherry-picked to stable, but I used the merge commit; not sure if I should have picked one-by-one

Re: `qemu_28`: NixPkgs-wise it is a no-brainer; NixOS tests need to be re-checked by people actually using NixOS and its tests, I guess.

**Comment by grahamc** [comment]
Amazing, @nlewo, thank you so much! How did you find the patches?

@7c6f434c Nice! _Extremely_ timely on those, thank you! Usually I pick one by one, but this should be fine :)

I'll see about running tests with qemu_28.

**Comment by nlewo** [comment]
@7c6f434c There are some tests that are declared in nixos/release.nix but I don't know if the CI executes them. I'm responsible of two of them and I'll try to run them with qemu 2.8.

@grahamc  By reading mails associated to the CVE desc on http://cve.mitre.org. I also get some information from https://security-tracker.debian.org (which is really nice).

**Comment by grahamc** [comment]
@nlewo if you submit a PR changing the default to 2.8, I can easily run the tests.

**Comment by bachp** [comment]
@grahamc I will try if I can backport the patch. I think it is this one here: https://github.com/KDE/ark/commit/82fdfd24d46966a117fa625b68784735a40f9065

**Comment by grahamc** [comment]
Special thank you to @nlewo and @bachp for getting those more annoying ones (IMO...) done, @7c6f434c for merging and cherry-picking commits, @vcunat for finding like a million patches that we were missing on debian ...! @the-kenny for so quickly triaging the flight package, @globin for tagging his libupnp patch despite being in this issue (very useful for making sure it gets in the notices) and @NeQuissimus, and any other anonymous triagers out there!

**Comment by fpletz** [comment]
@grahamc Last minute fix for libopus: 140d135ee2e2f2ea538591fe25719c9c91d4651e
