### ISSUE TITLE
chromium 111+ builds crashy under sway with output scale != 1

### ISSUE THREAD

**Issue by edrex** [NixOS/nixpkgs#225277]
### Describe the bug
Chromium (under sway wayland) crashes either at startup or when windows are moved between my two displays a few times. Reproducible with an empty profile. First appears in https://github.com/NixOS/nixpkgs/commit/de134a16be5e6393b8852b4c4aa61bc623c13eb8

I initially [reported this upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=1430657), but I've been unable to reproduce running the official builds with `steam-run` (`chrome://gpu` looks about the same as with nixpkgs build) so I'm now convinced this is something particular to the nixpkgs builds.

### TODO

- [x] Try to reproduce on another wayland env like plasma
  - couldn't reproduce on `startplasma-wayland`, Hyprland, or river, trying to replicate conditions/procedure (laptop hidpi output scale 2.25, using keybind to rapidly cycle maximize or fullscreen window between outputs). Text is a little blurry with the fractional scaling on hidpi output on all those compositors, but seems crisp always on sway. maybe related? Anyway, this seems to be a __sway-only bug__.
- [x] ~~I haven't heard from anyone else with this issue. I'm on an i915 igpu laptop (gen7)~~ **update:** it seems like @yashlala has the same crash with Arch Linux builds, while primeos can't repro with similar hardware/software.
- [x] ~~I'm 95% sure this started before I enabled the xanmod kernel, but I should check that~~ reproducible with default kernel
- [x] Test with both outputs scale=1
  - `eDP-1 scale=1`: no crash :thinking: 
  - `scale=2`: crash
- [ ] Build chromiumDev and see if it's present there.
  - [x] solve tmpfs out of space first. **update:** added swap, and set tmpfs size to 100% yield 16GB space
  - Especially curious whether [1356014 - \[Linux\]\[Wayland\] Non-integer scaling support - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1356014) makes any difference. That commit [seems to be in the current dev + beta](https://chromiumdash.appspot.com/commit/5e6a7691b5f63df3e30173f073ae8e9f697d5228). It has since been reverted but the revert [isn't in the channels yet afaict](https://chromiumdash.appspot.com/commit/446e2ae1963fe5d3ea0ffb548aad44e4182cef04). [Reland "\[Linux/Ozone/Wayland\] Support fractional-scale-v1" (4370091) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/4370091) is the one to watch going forward.
- [ ] Also, with above build, test with sway@HEAD which has [changes related to the fractional scaling protocol](https://github.com/search?q=repo%3Aswaywm%2Fsway+scale&type=commits&s=committer-date&o=desc)
### Notify maintainers

@primeos 

### Metadata

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.20-xanmod1, NixOS, 23.05 (Stoat)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by primeos** [comment]
We've recently updated Chromium to M112 (https://github.com/NixOS/nixpkgs/pull/224726) - is that version affected as well?

I'm also running Chromium under Sway via Ozone/Wayland (`--enable-features=UseOzonePlatform --ozone-platform=wayland`) but don't remember any crashes lately (there were definitely some issues in the past though (Ozone/Wayland is still(?) experimental) - e.g. I remember the crashes when repeatedly moving Chromium windows between displays but that was probably a year ago or so and got fixed with the next major release).

I have a gen7 Intel CPU+GPU as well.

**Comment by yashlala** [comment]
I found the issue you filed upstream. I'm having the same issue on Arch Linux, with the same chromium versions, on an Intel gen7 CPU+GPU. I also couldn't reproduce this with the latest official chromium build. 

I recognize this is the NixOS bug tracker; just thought I'd provide the [backtraces and about:gpu](https://gist.github.com/yashlala/ba6654c6c6144e92c2577abc13dac754) on my end, in case the issues are related.

**Comment by edrex** [comment]
> M112?

`112.0.5615.49 (Official Build) (64-bit)` from 0e19daa is still affected. Unrelated but what's the story with `chrome://version/` saying (`Official Build)`?

Test command: `nix run nixpkgs/nixos-unstable#chromium -- --user-data-dir=$(mktemp -d)`

Forgot to post the log here (it's in the upstream issue tho):

```
[139105:139105:0404/203928.426871:ERROR:wayland_event_watcher.cc(38)] libwayland: xdg_wm_base@15: error 4: wrong configure serial: 69136
[0404/203928.475957:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[0404/203928.477108:ERROR:process_memory_range.cc(75)] read out of range
fish: Job 1, 'chromium --user-data-dir=(mktem…' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

@yashlala does your log look like that? I don't see those call sites in your backtrace, although I'm not great at reading them.

**Comment by yashlala** [comment]
@edrex It's similar.

Test command: `chromium --user-data-dir=$(mktemp -d)`

Output: 

```
[15233:15233:0408/122327.921960:ERROR:wayland_event_watcher.cc(38)] libwayland: xdg_wm_base@15: error 4: wrong configure serial: 13347

[0408/122327.930374:ERROR:elf_dynamic_array_reader.h(64)] tag not found
[1]    15233 trace trap (core dumped)  chromium --user-data-dir=$(mktemp -d)
```

I've added package version numbers and log output to the Gist now.

**Comment by edrex** [comment]
I just tested with `startplasma-wayland`, river, and Hyprland, trying to reproduce equivalent conditions as much as possible (esp fractional scaling of my hidpi laptop display to `2.25`) and I can only repro on sway. I do notice that text looks a little blurry on those compositors on the fractional scaling output, while on sway it looks crisp all the time.  :thinking:

**Comment by edrex** [comment]
@yashlala can you confirm no crash with all outputs scale set to 1? (`wlr-randr --output eDP-1 --scale 1` etc, or similar with `way-displays`)

**Comment by edrex** [comment]
@primeos could you possibly try two outputs with one set to a fractional scale eg 1.5? Usually it either crashes immediately or after swapping the window between outputs a few times (<< 10). Waiting on chromiumDev build.

**Comment by yashlala** [comment]
@edrex I can confirm that. I can also confirm that there are no crashes with all outputs scaled to 3; there need to be _different_ scaling factors. Here's a link to the [Arch issue](https://bugs.archlinux.org/task/78149) I opened, where I record my findings.

**Comment by yashlala** [comment]
Do note that I don't have an issue when _moving_ windows, only when creating new ones. 

I half-remember problems with moving windows yesterday, but couldn't reproduce it today. I wouldn't rule out the "two separate issues" case yet.

**Comment by edrex** [comment]
Should be fixed by https://github.com/NixOS/nixpkgs/pull/229759

(see [my comment in upstream bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1430657#c12) for details)
