### ISSUE TITLE
Vulnerability Roundup 21

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#22549]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/22342).

cc: @nlewo @7c6f434c @bachp @vcunat @peterhoeg @fpletz @Szczyp @NeQuissimus @obadz @joachifm @shlevy.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.

Permanent CC's: @joepie91, @phanimahesh, @the-kenny, @7c6f434c, @k0001
@NixOS/security-notifications
If you would like to be CC'd on _all_ roundups (or removed from the
list), open a PR editing
https://github.com/NixOS/security/blob/master/lwnvulns/src/bin/instructions.md.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [x] Send an update e-mail to nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (27 issues)
 - [x] [`#713779`](https://lwn.net/Vulnerabilities/713779/) ([search](http://search.nix.gsc.io/?q=epiphany&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=epiphany+in%3Apath&type=Code))  epiphany: multiple vulnerabilities
 - [x] [`#713883`](https://lwn.net/Vulnerabilities/713883/) ([search](http://search.nix.gsc.io/?q=irssi-otr&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=irssi-otr+in%3Apath&type=Code))  irssi-otr: information leak
 - [x] [`#713270`](https://lwn.net/Vulnerabilities/713270/) ([search](http://search.nix.gsc.io/?q=libgd2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libgd2+in%3Apath&type=Code))  libgd2: two vulnerabilities
 - [x] [`#713272`](https://lwn.net/Vulnerabilities/713272/) ([search](http://search.nix.gsc.io/?q=libplist&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libplist+in%3Apath&type=Code))  libplist: two vulnerabilities
 - [x] [`#713565`](https://lwn.net/Vulnerabilities/713565/) ([search](http://search.nix.gsc.io/?q=mupdf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mupdf+in%3Apath&type=Code))  mupdf: three vulnerabilities
 - [x] [`#713426`](https://lwn.net/Vulnerabilities/713426/) ([search](http://search.nix.gsc.io/?q=bzrtp&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bzrtp+in%3Apath&type=Code))  bzrtp: man-in-the-middle vulnerability
 - [x] [`#713420`](https://lwn.net/Vulnerabilities/713420/) ([search](http://search.nix.gsc.io/?q=ntfs-3g&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=ntfs-3g+in%3Apath&type=Code))  ntfs-3g: privilege escalation
 - [x] [`#665254`](https://lwn.net/Vulnerabilities/665254/) ([search](http://search.nix.gsc.io/?q=openldap&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openldap+in%3Apath&type=Code))  openldap: unintended cipher usage
 - [x] [`#713274`](https://lwn.net/Vulnerabilities/713274/) ([search](http://search.nix.gsc.io/?q=openssh&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openssh+in%3Apath&type=Code))  openssh: denial of service
 - [x] [`#713569`](https://lwn.net/Vulnerabilities/713569/) ([search](http://search.nix.gsc.io/?q=phpMyAdmin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=phpMyAdmin+in%3Apath&type=Code))  phpmyadmin: multiple vulnerabilities
 - [x] [`#713269`](https://lwn.net/Vulnerabilities/713269/) ([search](http://search.nix.gsc.io/?q=salt&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=salt+in%3Apath&type=Code))  salt: two vulnerabilities
 - [x] [`#713771`](https://lwn.net/Vulnerabilities/713771/) ([search](http://search.nix.gsc.io/?q=spice&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=spice+in%3Apath&type=Code))  spice: two vulnerabilities
 - [x] [`#713563`](https://lwn.net/Vulnerabilities/713563/) ([search](http://search.nix.gsc.io/?q=svgsalamander&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=svgsalamander+in%3Apath&type=Code))  svgsalamander: server-side request forgery
 - [x] [`#713564`](https://lwn.net/Vulnerabilities/713564/) ([search](http://search.nix.gsc.io/?q=wavpack&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wavpack+in%3Apath&type=Code))  wavpack: multiple vulnerabilities
 - [x] [`#713772`](https://lwn.net/Vulnerabilities/713772/) ([search](http://search.nix.gsc.io/?q=gst-plugins-bad&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-bad+in%3Apath&type=Code))  gst-plugins-bad: two vulnerabilities
 - [x] [`#713773`](https://lwn.net/Vulnerabilities/713773/) ([search](http://search.nix.gsc.io/?q=gst-plugins-base-libs&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-base-libs+in%3Apath&type=Code))  gst-plugins-base-libs: multiple vulnerabilities
 - [x] [`#713774`](https://lwn.net/Vulnerabilities/713774/) ([search](http://search.nix.gsc.io/?q=gst-plugins-good&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-good+in%3Apath&type=Code))  gst-plugins-good: multiple vulnerabilities
 - [x] [`#713775`](https://lwn.net/Vulnerabilities/713775/) ([search](http://search.nix.gsc.io/?q=gst-plugins-ugly&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gst-plugins-ugly+in%3Apath&type=Code))  gst-plugins-ugly: two vulnerabilities
 - [x] [`#713776`](https://lwn.net/Vulnerabilities/713776/) ([search](http://search.nix.gsc.io/?q=gstreamer&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gstreamer+in%3Apath&type=Code))  gstreamer: denial of service
 - [x] [`#713782`](https://lwn.net/Vulnerabilities/713782/) ([search](http://search.nix.gsc.io/?q=iio-sensor-proxy&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=iio-sensor-proxy+in%3Apath&type=Code))  iio-sensor-proxy: unspecified
 - [x] [`#713428`](https://lwn.net/Vulnerabilities/713428/) ([search](http://search.nix.gsc.io/?q=iucode-tool&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=iucode-tool+in%3Apath&type=Code))  iucode-tool: code execution
 - [x] [`#713423`](https://lwn.net/Vulnerabilities/713423/) ([search](http://search.nix.gsc.io/?q=jasper&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jasper+in%3Apath&type=Code))  jasper: code execution
 - [x] [`#713424`](https://lwn.net/Vulnerabilities/713424/) ([search](http://search.nix.gsc.io/?q=moodle&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=moodle+in%3Apath&type=Code))  moodle: multiple vulnerabilities
 - [x] [`#713785`](https://lwn.net/Vulnerabilities/713785/) ([search](http://search.nix.gsc.io/?q=php&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php+in%3Apath&type=Code))  php: multiple vulnerabilities
 - [x] [`#713409`](https://lwn.net/Vulnerabilities/713409/) ([search](http://search.nix.gsc.io/?q=rabbitmq-server&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rabbitmq-server+in%3Apath&type=Code))  rabbitmq-server: denial of service
 - [x] [`#713425`](https://lwn.net/Vulnerabilities/713425/) ([search](http://search.nix.gsc.io/?q=wireshark&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wireshark+in%3Apath&type=Code))  wireshark: two denial of service flaws
 - [x] [`#713271`](https://lwn.net/Vulnerabilities/713271/) ([search](http://search.nix.gsc.io/?q=wordpress&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wordpress+in%3Apath&type=Code))  wordpress: multiple vulnerabilities

### GraphicsMagick (2 issues)
 - [x] [`#713787`](https://lwn.net/Vulnerabilities/713787/) ([search](http://search.nix.gsc.io/?q=GraphicsMagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=GraphicsMagick+in%3Apath&type=Code))  GraphicsMagick: multiple vulnerabilities
 - [x] [`#713786`](https://lwn.net/Vulnerabilities/713786/) ([search](http://search.nix.gsc.io/?q=GraphicsMagick&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=GraphicsMagick+in%3Apath&type=Code))  GraphicsMagick: multiple vulnerabilities

### kernel (3 issues)
 - [x] [`#713884`](https://lwn.net/Vulnerabilities/713884/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: information leak
 - [x] [`#713881`](https://lwn.net/Vulnerabilities/713881/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#713570`](https://lwn.net/Vulnerabilities/713570/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities

### libtiff (2 issues)
 - [x] [`#713880`](https://lwn.net/Vulnerabilities/713880/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  tiff: can't write files
 - [x] [`#713268`](https://lwn.net/Vulnerabilities/713268/) ([search](http://search.nix.gsc.io/?q=libtiff&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libtiff+in%3Apath&type=Code))  libtiff: information leak

### rtmpdump (2 issues)
 - [x] [`#713784`](https://lwn.net/Vulnerabilities/713784/) ([search](http://search.nix.gsc.io/?q=rtmpdump&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rtmpdump+in%3Apath&type=Code))  rtmpdump: multiple vulnerabilities
 - [x] [`#670061`](https://lwn.net/Vulnerabilities/670061/) ([search](http://search.nix.gsc.io/?q=rtmpdump&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=rtmpdump+in%3Apath&type=Code))  rtmpdump: code execution

**Comment by peterhoeg** [comment]
wordpress in master is already on 4.7.2 - only earlier versions are affected.

**Comment by peterhoeg** [comment]
iio-sensor-proxy is not packaged yet. I have a branch with the software and a nixos module, but it's not merged.

**Comment by grahamc** [comment]
Thank you! I ticked them off. Remember 17.03's branch-off is coming up, if you want to get that in to stable :)

**Comment by grahamc** [comment]
I'm plodding through the gstreamer updates :)

**Comment by grahamc** [comment]
gstreamer fixed in afd59811a1f4b2037d77293064a4fee0ac91af6f and 504d394.

**Comment by grahamc** [comment]
w00t we had already patched jasper.

**Comment by grahamc** [comment]
deleted moodle in 7db1f72

**Comment by NeQuissimus** [comment]
Kernels are good

**Comment by peterhoeg** [comment]
wireshark is already on version 2.2.4 which fixes to the 2 vulnerabilities.

**Comment by peterhoeg** [comment]
Currently building the derivations depending on wavpack, so don't waste your time on this.

**Comment by peterhoeg** [comment]
tiff is just a regular bug, not a vulnerability.
libtiff is not vulnerable (we are never).

**Comment by peterhoeg** [comment]
php is ok in master.

**Comment by peterhoeg** [comment]
mupdf is ok in master.

**Comment by grahamc** [comment]
@peterhoeg can you verify against stable (16.09) as well?

**Comment by peterhoeg** [comment]
> can you verify against stable (16.09) as well?
@grahamc - only mupdf is not ok.

**Comment by peterhoeg** [comment]
uicode-tool - we don't have it.

**Comment by peterhoeg** [comment]
The fixes have been backported (not to nixpkgs), but don't we consider pdf readers (and especially those that can run javascript) critical like browsers, so they need the latest version?

**Comment by nlewo** [comment]
The latest version of RabbitMQ is not impacted by the CVE.  I upgrade our rabbitmq version in #22573.

**Comment by grahamc** [comment]
@peterhoeg For now, I'd rather apply the backported patches to 16.09 for mupdf, especially if they're being so kind as to backport patches for us :)

**Comment by grahamc** [comment]
@codyopel, @viric, @spwhitt, @rbvermaa, would any of you like to update rtmpdump? Otherwise I'll probably mark it broken due to https://lwn.net/Vulnerabilities/713784/

**Comment by peterhoeg** [comment]
@grahamc, we have another issue. ```webkitgtk24x``` is badly outdated with lots of vulnerabilities and yet is still in use by a number of packages:
https://search.nix.gsc.io/?q=webkitgtk24x&i=fosho&files=&repos=

Here are details:
https://blogs.gnome.org/mcatanzaro/2017/02/08/an-update-on-webkit-security-updates/

Specifically:

> but this old version of WebKit is affected by over 200 known vulnerabilities and really has to go sooner rather than later

For emacs, if we simply only build the proper gtk UI, we should be fine and get rid of xwidgets.

I don't know about the others though.

**Comment by vcunat** [comment]
`webkitgtk24x`: we still have https://github.com/NixOS/nixpkgs/issues/18312 open for outdated webkit. For the `liferea` case: upstream now has a new -rc2 version that does build against newer libwebkit, but it didn't work well for me.

**Comment by 7c6f434c** [comment]
Ah, `rtmpdump` is an easy bump. Done

**Comment by 7c6f434c** [comment]
`irssi_otr` fix is upstream, we have the correct version already.

**Comment by fpletz** [comment]
libgd2 (gd) was already fixed.

**Comment by fpletz** [comment]
The graphicsmagick CVEs are weird. They seem to rather apply to imagemagick. As OpenSUSE is generally lagging behind on security updates a bit compared to other distros and graphicsmagick has a revamped codebase, I don't think all those issues also apply to graphicsmagick and OpenSUSE made some kind of error here. In the Debian security tracker those CVEs were assigned to imagemagick and not to graphicsmagick.

**Comment by fpletz** [comment]
epiphany was fixed on master. The only relevant issue (https://bugzilla.gnome.org/show_bug.cgi?id=752738) seems to be present in 3.22.x only according to the bugtracker while we have 3.20 on 16.03. No CVE was assigned yet.

**Comment by grahamc** [comment]
What a treat to wake up to!

@peterhoeg if we drop xwidgets, will that break emacs on darwin? ( @LnL7, @copumpkin ) After 17.03 releases, we should be in much closer shape to drop 24. I don't know that there is anything we can do about this for now :( maybe either: Debian has patches in this area?



@fpletz:

GraphicsMagick / ImageMagick is always weird. The only way I can tell the difference is via version numbers being very different. I'll try and figure it out, but frequently I just go back and try and find out if we're behind in versions.

epiphany: "Thanks to Hussam for reporting this bug so quickly after it was introduced" seems to suggest it might not, indeed, be present in 3.20.

**Comment by LnL7** [comment]
Not sure about emacs. I did add `wxmac` to nixpkgs for erlang, perhaps emacs could also use that?

**Comment by joachifm** [comment]
It seems unlikely that removing xwidgets would break emacs on darwin. xwidgets is for embedding other windows inside emacs, surely darwin emacs does not *rely* on that to function?

**Comment by grahamc** [comment]
You're right, @joachifm -- it is an extra add-on, usually disabled by distributions.

**Comment by LnL7** [comment]
Yes it's optional, but I don't use emacs so I'm not sure what it's used for. We also have the emacs macport I assume that's what darwin people would prefer to use if they want a graphical version.

**Comment by grahamc** [comment]
I'm marking libplist as "fixed" for now ,assuming they'll release a new version soon.

**Comment by grahamc** [comment]
Done: So fast this time :D Thank you all, again!

**Comment by vcunat** [comment]
Hmm, new glibc [claims to fix](https://sourceware.org/ml/libc-alpha/2017-02/msg00079.html) two CVEs and I can't see any reference to those around nixpkgs, so they might be new.
