### ISSUE TITLE
Vulnerability Roundup 22

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#22826]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/22549).

cc: @peterhoeg @NeQuissimus @nlewo @vcunat @7c6f434c @LnL7 @fpletz @joachifm .

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.

Permanent CC's: @joepie91, @phanimahesh, @the-kenny, @7c6f434c, @k0001, @peterhoeg
@NixOS/security-notifications
If you would like to be CC'd on _all_ roundups (or removed from the
list), open a PR editing
https://github.com/NixOS/security/blob/master/lwnvulns/src/bin/instructions.md.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [x] Send an update e-mail to nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (23 issues)
 - [x] [`#713991`](https://lwn.net/Vulnerabilities/713991/) ([search](http://search.nix.gsc.io/?q=calibre&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=calibre+in%3Apath&type=Code))  calibre: information leak
 - [x] [`#714502`](https://lwn.net/Vulnerabilities/714502/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#714430`](https://lwn.net/Vulnerabilities/714430/) ([search](http://search.nix.gsc.io/?q=libxml2&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libxml2+in%3Apath&type=Code))  libxml2: denial of service
 - [x] [`#714504`](https://lwn.net/Vulnerabilities/714504/) ([search](http://search.nix.gsc.io/?q=netpbm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=netpbm+in%3Apath&type=Code))  netpbm: three vulnerabilities
 - [x] [`#714262`](https://lwn.net/Vulnerabilities/714262/) ([search](http://search.nix.gsc.io/?q=quagga&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=quagga+in%3Apath&type=Code))  quagga: denial of service
 - [x] [`#714500`](https://lwn.net/Vulnerabilities/714500/) ([search](http://search.nix.gsc.io/?q=tomcat7&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat7+in%3Apath&type=Code))  tomcat: denial of service
 - [x] [`#714500`](https://lwn.net/Vulnerabilities/714500/) ([search](http://search.nix.gsc.io/?q=tomcat8&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat8+in%3Apath&type=Code))  tomcat: denial of service
 - [x] [`#714423`](https://lwn.net/Vulnerabilities/714423/) ([search](http://search.nix.gsc.io/?q=kdenetwork-kopete&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kdenetwork-kopete+in%3Apath&type=Code))  kdenetwork-kopete: social engineering attacks
 - [x] [`#714257`](https://lwn.net/Vulnerabilities/714257/) ([search](http://search.nix.gsc.io/?q=mysql-5.5&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mysql-5.5+in%3Apath&type=Code))  mysql: code execution
 - [x] [`#714127`](https://lwn.net/Vulnerabilities/714127/) ([search](http://search.nix.gsc.io/?q=redis&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=redis+in%3Apath&type=Code))  redis: two vulnerabilities
 - [x] [`#714431`](https://lwn.net/Vulnerabilities/714431/) ([search](http://search.nix.gsc.io/?q=tigervnc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tigervnc+in%3Apath&type=Code))  tigervnc: denial of service
 - [x] [`#714124`](https://lwn.net/Vulnerabilities/714124/) ([search](http://search.nix.gsc.io/?q=viewvc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=viewvc+in%3Apath&type=Code))  viewvc: cross-site scripting
 - [x] [`#714424`](https://lwn.net/Vulnerabilities/714424/) ([search](http://search.nix.gsc.io/?q=webkit2gtk&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=webkit2gtk+in%3Apath&type=Code))  webkit2gtk: multiple vulnerabilities
 - [x] [`#714256`](https://lwn.net/Vulnerabilities/714256/) ([search](http://search.nix.gsc.io/?q=bind&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bind+in%3Apath&type=Code))  bind: denial of service
 - [x] [`#714126`](https://lwn.net/Vulnerabilities/714126/) ([search](http://search.nix.gsc.io/?q=bitlbee&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=bitlbee+in%3Apath&type=Code))  bitlbee: denial of service
 - [x] [`#713992`](https://lwn.net/Vulnerabilities/713992/) ([search](http://search.nix.gsc.io/?q=gnome-boxes&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gnome-boxes+in%3Apath&type=Code))  gnome-boxes: password disclosure
 - [x] [`#580396`](https://lwn.net/Vulnerabilities/580396/) ([search](http://search.nix.gsc.io/?q=graphviz&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=graphviz+in%3Apath&type=Code))  graphviz: multiple vulnerabilities
 - [x] [`#714260`](https://lwn.net/Vulnerabilities/714260/) ([search](http://search.nix.gsc.io/?q=gtk-vnc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=gtk-vnc+in%3Apath&type=Code))  gtk-vnc
 - [x] [`#713996`](https://lwn.net/Vulnerabilities/713996/) ([search](http://search.nix.gsc.io/?q=irssi&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=irssi+in%3Apath&type=Code))  irssi: memory leak
 - [x] [`#624311`](https://lwn.net/Vulnerabilities/624311/) ([search](http://search.nix.gsc.io/?q=lsyncd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=lsyncd+in%3Apath&type=Code))  lsyncd: command injection
 - [x] [`#714263`](https://lwn.net/Vulnerabilities/714263/) ([search](http://search.nix.gsc.io/?q=nova-lxd&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nova-lxd+in%3Apath&type=Code))  nova-lxd: access restriction bypass
 - [x] [`#714505`](https://lwn.net/Vulnerabilities/714505/) ([search](http://search.nix.gsc.io/?q=openssl&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=openssl+in%3Apath&type=Code))  openssl: information disclosure
 - [x] [`#714427`](https://lwn.net/Vulnerabilities/714427/) ([search](http://search.nix.gsc.io/?q=vim&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=vim+in%3Apath&type=Code))  vim: buffer overflow

**Comment by peterhoeg** [comment]
calibre is OK in master, but 16.09 is vulnerable. Upstream moves quite quickly so I think it's unlikely that they would provide any backports. Fedora and Mageia handle it by upgrading.

**Comment by peterhoeg** [comment]
The blank line above is ```gtk-vnc```, just FYI.

**Comment by grahamc** [comment]
I just added gtk-vnc to it :)

**Comment by peterhoeg** [comment]
regd gtk-vnc, master is vulnerable - I'm upgrading now. As for stable, according to upstream, the API is not stable due to being < 1.0. Debian has the same version as us in their "stable", so maybe with a bit of luck somebody will do the hard work.

**Comment by peterhoeg** [comment]
webkitgtk2 is (naturally) vulnerable both in master and 16.09.

**Comment by peterhoeg** [comment]
kopete - we don't carry that in the kf5 flavour, only the kde4 version which was just ripped out.

**Comment by grahamc** [comment]
Unfortunately we have not removed KDE4 yet.

**Comment by peterhoeg** [comment]
graphviz: our version is newer in both master and 16.09. However, we carry an older version for compatibility which is only used by ```monotone-viz``` which had its most recent release in 2009. I suggest we simply mark ```graphviz_2_0``` as broken.

**Comment by grahamc** [comment]
cc @7c6f434c on marking graphviz_2_0 broken, which will break monotone_viz.

**Comment by 7c6f434c** [comment]
That would be annoying: I still use monotone-viz.

**Comment by 7c6f434c** [comment]
I guess I could make the old graphviz an implementation detail of monotone-viz not exposed on the top-level, though

**Comment by grahamc** [comment]
It looks like ubuntu ships monotone-viz with a newer graphviz. maybe they have a patch fixing it. Could you check in to that, @7c6f434c?

**Comment by grahamc** [comment]
I've got a patch for gnome-boxes. I can't commit right now, but will push them soon.

**Comment by grahamc** [comment]
The kopete issue is masking many clients vulnerable:

  - [ ] CVE-2017-5589: yaxim and Bruno (0.8.6 - 0.8.8; Android)
  - [ ] CVE-2017-5590: ChatSecure (3.2.0 - 4.0.0; only iOS) and Zom (all
versions up to 1.0.11; only iOS)
  - [ ] CVE-2017-5591: poezio (0.8 - 0.10)
  - [ ] CVE-2017-5592: profanity (0.4.7 - 0.5.0)
  - [ ] CVE-2017-5593: Psi+ (0.16.563.580 - 0.16.571.627)
  - [ ] CVE-2017-5602: jappix (1.0.0 to 1.1.6)
  - [ ] CVE-2017-5603: Jitsi (2.5.5061 - 2.9.5544)
  - [ ] CVE-2017-5604: mcabber (1.0.0 - 1.0.4)
  - [ ] CVE-2017-5605: Movim (0.8 - 0.10)
  - [ ] CVE-2017-5606: Xabber (only if manually enabled: 1.0.30, 1.0.30 VIP,
beta 1.0.3 - 1.0.74; Android)
  - [ ] CVE-2017-5858: Converse.js (0.8.0 - 1.0.6, 2.0.0 - 2.0.4)

(we may not have all these, but just in case.)

**Comment by peterhoeg** [comment]
Regd calibre, if we upgrade stable to the version in unstable, it is at least something that has gotten some testing.

**Comment by grahamc** [comment]
That sounds fine, esp. if other distros are backporting these updates.

**Comment by 7c6f434c** [comment]
I cannot see where Ubuntu actually patches the dot format parsing

**Comment by 7c6f434c** [comment]
And I think it is impossible to trigger graphviz vulnerabilities via monotone-viz

**Comment by grahamc** [comment]
I'll consider graphviz fixed.

**Comment by 7c6f434c** [comment]
I guess it is a good idea to hide the vulnerable `graphviz_2_0` inside `monotoneViz` expression, though. Done.

**Comment by grahamc** [comment]
Thank you!

**Comment by 7c6f434c** [comment]
`bind`: we have the patched version

**Comment by 7c6f434c** [comment]
`bitlbee`: 3.5.1 seems to be the upstream fix for all the mentioned problems, we have it

**Comment by 7c6f434c** [comment]
`irssi`: 1.0.0 has the problem, 1.0.1 is the fixed version, 0.8.x didn't get any mention so I guess it is fine as it is (in stable)

**Comment by bendlas** [comment]
`webkit2gtk`: the links should be [search](https://search.nix.gsc.io/?q=webkitgtk&i=fosho&repos=nixos-nixpkgs) [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=webkitgtk+in%3Apath&type=Code). otherwise only haskell packages show up.

**Comment by LnL7** [comment]
`vim` is up to date on master, working on a patch for 16.09

**Comment by LnL7** [comment]
I misread the version, updated on master and patched for 16.09 https://github.com/NixOS/nixpkgs/commit/538e642832a70cae3f1cfc595d954a4a3bdbb391

**Comment by phanimahesh** [comment]
> I guess it is a good idea to hide the vulnerable graphviz_2_0 inside monotoneViz expression, though. Done.
@7c6f434c Can you also mention links to commits or PRs?

It'll help for people like me to quickly checkout how it has been done, without wading through commit logs

**Comment by 7c6f434c** [comment]
>> I guess it is a good idea to hide the vulnerable graphviz_2_0 inside monotoneViz expression, though. Done.
>@7c6f434c Can you also mention links to commits or PRs?

c731738ecc132f450bc1cb0eaad7c1fa232fa299

>It'll help for people like me to quickly checkout how it has been done, without wading through commit logs

What was done: `mv`

**Comment by grahamc** [comment]
It also helps me when I make send notes, thank you!

**Comment by grahamc** [comment]
@tavyc can you look in to the Quagga update, and if we can go to 1.2 for unstable (which will become stable in 15 days)?

**Comment by grahamc** [comment]
@vcunat you seem to have some history with libxml2. Can you look in to this one?

**Comment by vcunat** [comment]
OK, in ~12 hours; feel free to do it first.  Upstream's git and releases are untouched for months, so we'll have to take the patches.

**Comment by 7c6f434c** [comment]
Oh, by the way, `irssi` update in master is 13a1d38f55829f10db31198ea1923d5168a3043c, stable doesn't need it

**Comment by tavyc** [comment]
@grahamc PR #22901 opened for quagga 1.2.0

**Comment by joachifm** [comment]
Opened a PR that addresses the first kernel cve. Note that for the other cve, the lwn page says
> At this time we understand no trust barrier has been crossed and there is *no security implications* in this flaw.

(emphasis mine)

**Comment by grahamc** [comment]
Thank you, @tavyc!

**Comment by grahamc** [comment]
Thank you, @joachifm!

**Comment by grahamc** [comment]
@peterhoeg can you backport calibre?

**Comment by grahamc** [comment]
Done! Great work, thank you all!

This most recent [sec-announce email](https://groups.google.com/forum/#!topic/nix-security-announce/o5JMTeaw0Q8) I sent includes a long-overdue component, where I thank everyone who authored and committed changes. Unfortunately this doesn't include other important help: PR reviewers, triagers, commenters, patch hunters, etc... I'll continue trying to make this better. This is truly a group effort, and I could never do these without the fabulous help from fellow community members. [I enjoy working _with_ you all.](https://github.com/NixOS/nixpkgs/issues/15866#issuecomment-280378273)
