### ISSUE TITLE
Vulnerability Roundup 23

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#23072]
Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/22826).

cc: @peterhoeg @7c6f434c @bendlas @LnL7 @phanimahesh @vcunat @tavyc @joachifm.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.

Permanent CC's: @joepie91, @phanimahesh, @the-kenny, @7c6f434c, @k0001, @peterhoeg
@NixOS/security-notifications
If you would like to be CC'd on _all_ roundups (or removed from the
list), open a PR editing
https://github.com/NixOS/security/blob/master/lwnvulns/src/bin/instructions.md.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [ ] Run the issue through `reformat` one last time
 - [ ] Review commits since last roundup for backport candidates
 - [ ] Send an update e-mail to nix-security-announce@googlegroups.com
 - [ ] Update the database at https://github.com/NixOS/security

Without further ado...
### Assorted (9 issues)
 - [x] [`#714850`](https://lwn.net/Vulnerabilities/714850/) ([search](http://search.nix.gsc.io/?q=diffoscope&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=diffoscope+in%3Apath&type=Code))  diffoscope: file overwrite
 - [x] [`#715043`](https://lwn.net/Vulnerabilities/715043/) ([search](http://search.nix.gsc.io/?q=firebird&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=firebird+in%3Apath&type=Code))  firebird: access restriction bypass
 - [x] [`#715166`](https://lwn.net/Vulnerabilities/715166/) ([search](http://search.nix.gsc.io/?q=libass&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libass+in%3Apath&type=Code))  libass: denial of service
 - [x] [`#715170`](https://lwn.net/Vulnerabilities/715170/) ([search](http://search.nix.gsc.io/?q=libplist&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libplist+in%3Apath&type=Code))  libplist: three vulnerabilities
 - [x] [`#714582`](https://lwn.net/Vulnerabilities/714582/) ([search](http://search.nix.gsc.io/?q=lynx&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=lynx+in%3Apath&type=Code))  lynx: invalid URL parsing
 - [x] [`#715167`](https://lwn.net/Vulnerabilities/715167/) ([search](http://search.nix.gsc.io/?q=nagios-core&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nagios-core+in%3Apath&type=Code))  nagios-core: privilege escalation
 - [x] [`#714852`](https://lwn.net/Vulnerabilities/714852/) ([search](http://search.nix.gsc.io/?q=postfixadmin&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=postfixadmin+in%3Apath&type=Code))  postfixadmin: security bypass
 - [ ] [`#714853`](https://lwn.net/Vulnerabilities/714853/) ([search](http://search.nix.gsc.io/?q=python-crypto&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-crypto+in%3Apath&type=Code))  python-crypto: code execution
 - [x] [`#715038`](https://lwn.net/Vulnerabilities/715038/) ([search](http://search.nix.gsc.io/?q=zoneminder&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=zoneminder+in%3Apath&type=Code))  zoneminder: information disclosure

### mupdf (2 issues)
 - [x] [`#715044`](https://lwn.net/Vulnerabilities/715044/) ([search](http://search.nix.gsc.io/?q=mupdf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mupdf+in%3Apath&type=Code))  mupdf: two vulnerabilities
 - [x] [`#715039`](https://lwn.net/Vulnerabilities/715039/) ([search](http://search.nix.gsc.io/?q=mupdf&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=mupdf+in%3Apath&type=Code))  mupdf: denial of service

---
## 11 remaining, 18 completed

<details><summary><strong>
    CLICK TO EXPAND Show all 18 triaged and resolved issues
  </strong></summary>

### Assorted (16 issues)
 - [x] [`#715045`](https://lwn.net/Vulnerabilities/715045/) ([search](http://search.nix.gsc.io/?q=Kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=Kernel+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#715045`](https://lwn.net/Vulnerabilities/715045/) ([search](http://search.nix.gsc.io/?q=Linux&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=Linux+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#715165`](https://lwn.net/Vulnerabilities/715165/) ([search](http://search.nix.gsc.io/?q=dropbear&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=dropbear+in%3Apath&type=Code))  dropbear: code execution
 - [x] [`#715041`](https://lwn.net/Vulnerabilities/715041/) ([search](http://search.nix.gsc.io/?q=jitsi&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=jitsi+in%3Apath&type=Code))  jitsi: user spoofing
 - [x] [`#715162`](https://lwn.net/Vulnerabilities/715162/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: information disclosure
 - [x] [`#714581`](https://lwn.net/Vulnerabilities/714581/) ([search](http://search.nix.gsc.io/?q=libevent&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=libevent+in%3Apath&type=Code))  libevent: three vulnerabilities
 - [x] [`#715042`](https://lwn.net/Vulnerabilities/715042/) ([search](http://search.nix.gsc.io/?q=netpbm&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=netpbm+in%3Apath&type=Code))  netpbm: three vulnerabilities
 - [x] [`#714586`](https://lwn.net/Vulnerabilities/714586/) ([search](http://search.nix.gsc.io/?q=php5&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php5+in%3Apath&type=Code))  php5: three vulnerabilities
 - [x] [`#715036`](https://lwn.net/Vulnerabilities/715036/) ([search](http://search.nix.gsc.io/?q=python-peewee&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=python-peewee+in%3Apath&type=Code))  python-peewee: largely unspecified
 - [x] [`#715168`](https://lwn.net/Vulnerabilities/715168/) ([search](http://search.nix.gsc.io/?q=qemu&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=qemu+in%3Apath&type=Code))  qemu: multiple vulnerabilities
 - [x] [`#715169`](https://lwn.net/Vulnerabilities/715169/) ([search](http://search.nix.gsc.io/?q=redis&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=redis+in%3Apath&type=Code))  redis: code execution
 - [x] [`#715037`](https://lwn.net/Vulnerabilities/715037/) ([search](http://search.nix.gsc.io/?q=sshrc&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=sshrc+in%3Apath&type=Code))  sshrc: unspecified
 - [x] [`#715045`](https://lwn.net/Vulnerabilities/715045/) ([search](http://search.nix.gsc.io/?q=the&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=the+in%3Apath&type=Code))  kernel: denial of service
 - [x] [`#715171`](https://lwn.net/Vulnerabilities/715171/) ([search](http://search.nix.gsc.io/?q=tomcat6&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat6+in%3Apath&type=Code))  tomcat: denial of service
 - [x] [`#715171`](https://lwn.net/Vulnerabilities/715171/) ([search](http://search.nix.gsc.io/?q=tomcat7&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=tomcat7+in%3Apath&type=Code))  tomcat: denial of service
 - [x] [`#715035`](https://lwn.net/Vulnerabilities/715035/) ([search](http://search.nix.gsc.io/?q=wireshark&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=wireshark+in%3Apath&type=Code))  wireshark: denial of service

### xen (2 issues)
 - [x] [`#715164`](https://lwn.net/Vulnerabilities/715164/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: denial of service
 - [x] [`#714585`](https://lwn.net/Vulnerabilities/714585/) ([search](http://search.nix.gsc.io/?q=xen&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=xen+in%3Apath&type=Code))  xen: three vulnerabilities

</details>

**Comment by LnL7** [comment]
`redis` is not vulnerable, it was updated to a more recent version for the last round up.

**Comment by 7c6f434c** [comment]
`dropbear`: fixed in 2016.74, we have it, both branches

**Comment by fpletz** [comment]
I've already got a commit with qemu patches from a few hours ago that I didn't push to master yet. I will take care of the remaining qemu issues.

**Comment by globin** [comment]
PHP vulnerabilities are fixed in the versions we are shipping.

**Comment by grahamc** [comment]
I'm working on the Xen issues.

**Comment by 7c6f434c** [comment]
`wireshark`: the report is for 1.12.1, but 2.2.4 is also affected; fixed in 194d137bd3646b8e73901d5c01ee4e90d3dcf2a4 and cherry-picked

**Comment by grahamc** [comment]
Tomcat is already fixed.

**Comment by grahamc** [comment]
xen patched in cc4919da8968ccdd2e4f76cbdde7e2ed6c385130 / 142fd06afc50d9513477ab29c9be17e46e38248f

**Comment by NeQuissimus** [comment]
We have all the kernel issues covered

**Comment by wizeman** [comment]
I have contacted the security team privately before, but I believe `neovim` has a serious vulnerability which was fixed in version `1.0.7`. NixOS stable only has version `1.0.5`.

Not sure if `vim` is also affected.

**Comment by grahamc** [comment]
hey @wizeman, I thought I had covered that last roundup, thank you for bringing it up again here, I'll make sure it is patched this time around. I'm sorry I missed it last.

**Comment by FRidh** [comment]
We don't have `peewee` in Nixpkgs so I am ticking it.

**Comment by vcunat** [comment]
Libevent should be OK now.

**Comment by FRidh** [comment]
We don't have `pycrypto` anymore but use `pycryptodome`. Maybe the latter is affected, I don't know.

**Comment by FRidh** [comment]
I've updated `diffoscope` on master https://github.com/NixOS/nixpkgs/commit/de4643eb80ffa13b65c6e5e662235080c093b3e1. Not sure what to do with it on 16.09 though.

**Comment by peterhoeg** [comment]
netpbm was fixed in last week's roundup.

**Comment by ndowens** [comment]
Not finding sshrc in repo

**Comment by grahamc** [comment]
firebird fixed in 6c37a92 / d87a40e

**Comment by grahamc** [comment]
libass is old

**Comment by grahamc** [comment]
nagios-core is old.

**Comment by grahamc** [comment]
We don't package postfixadmin.

**Comment by grahamc** [comment]
We don't package zoneminder.

**Comment by grahamc** [comment]
@wizeman is there any way you can work on updating stable to 0.1.7? It appears to be a fairly complex update, based on master's changes.

**Comment by grahamc** [comment]
@FRidh Looks like the crypto vulnerability has been taken down by LWN. I emailed them asking about it.

**Comment by grahamc** [comment]
@dezgeg @edolstra: is this diffoscope acceptable to backport to stable? https://github.com/NixOS/nixpkgs/commit/de4643eb80ffa13b65c6e5e662235080c093b3e1

**Comment by grahamc** [comment]
I'm working on patches for the DCCP bug (cc @NeQuissimus, @fpletz). Just waiting on compilation to check.

**Comment by dezgeg** [comment]
Yes, diffoscope is most likely ok to upgrade in stable.

**Comment by nh2** [comment]
Would like to be CCd.

**Comment by fpletz** [comment]
mupdf fixed in 6dfbb070fbfa48986c05c334996b8c3c47432cdd. The other mupdf issue is for mujs for which we already have the current git commit in which the issues are fixed.

**Comment by fpletz** [comment]
libplist has been marked as insecure in 30cea5f02245a20022ea93f8eec2f4fe053ad97a. Checked it off above.

**Comment by fpletz** [comment]
See comments to https://github.com/NixOS/nixpkgs/commit/afd59811a1f4b2037d77293064a4fee0ac91af6f. Maybe our gstreamer was still vulnerable. I'm preparing a bump to be on the safe side.

**Comment by vcunat** [comment]
I just picked that `diffoscope` update, so I suppose we can check it off.

**Comment by grahamc** [comment]
The pycrypto issue turned out to be a duplicate. Thanks, everyone, for finishing this out without me. I've had a busy time since last Thursday. Great work!
