### ISSUE TITLE
Vulnerability Roundup 24

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixpkgs#23334]
**This is a super easy one with more people being CC'd than issues. If the people CC'd want to be CC'd again to help on the next one, please leave a comment!**

Here are all the vulnerabilities from https://lwn.net/Vulnerabilities
since our [last roundup](https://github.com/NixOS/nixpkgs/issues/23072).

cc: @LnL7 @7c6f434c @fpletz @globin @NeQuissimus @wizeman @FRidh @vcunat @peterhoeg @ndowens @dezgeg @nh2.

_Note:_ The list of people CC'd on this issue participated in the last
roundup. If you participate on this roundup, I'll cc you on the next
one. If you don't participate in the next one, you won't be CC'd on
the one after that. If you would like to be CC'd on the next roundup,
add a comment to the most recent vulnerability roundup.

Permanent CC's: @joepie91, @phanimahesh, @the-kenny, @7c6f434c, @k0001, @peterhoeg
@NixOS/security-notifications
If you would like to be CC'd on _all_ roundups (or removed from the
list), open a PR editing
https://github.com/NixOS/security/blob/master/lwnvulns/src/bin/instructions.md.

## Notes on the list
1. The reports have been roughly grouped by the package name. This
   isn't perfect, but is intended to help identify if a whole group
   of reports is resolved already.
2. Some issues will be duplicated, because it affects multiple
   packages. For example, there are sometimes problems that impact
   thunderbird, and firefox. LWN might report in one vulnerability
   "thunderbird firefox". These names have been split to make sure
   both packages get addressed.
3. By each issue is a link to code search for the package name, and
   a Github search by filename. These are to help, but may not return
   results when we do in fact package the software. If a search
   doesn't turn up, please try altering the search criteria or
   looking in nixpkgs manually before asserting we don't have it.
4. This issue is created by https://github.com/NixOS/security

# Instructions:

1. Triage a report: If we don't have the software or our version isn't
   vulnerable, tick the box or add a comment with the report number,
   stating it isn't vulnerable.
2. Fix the issue: If we do have the software and it is vulnerable,
   either leave a comment on this issue saying so, even open a pull
   request with the fix. If you open a PR, make sure to tag this
   issue so we can coordinate.
3. When an entire section is completed, move the section to the
   "Triaged and Resolved Issues" `details` block below.

## Upon Completion ...

 - [x] Run the issue through `reformat` one last time
 - [x] Review commits since last roundup for backport candidates
 - [x] Send an update e-mail to nix-security-announce@googlegroups.com
 - [x] Update the database at https://github.com/NixOS/security

Without further ado...

### Assorted (4 issues)
 - [x] [`#715268`](https://lwn.net/Vulnerabilities/715268/) ([search](http://search.nix.gsc.io/?q=linux&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=linux+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#715268`](https://lwn.net/Vulnerabilities/715268/) ([search](http://search.nix.gsc.io/?q=linux-snapdragon&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=linux-snapdragon+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#715264`](https://lwn.net/Vulnerabilities/715264/) ([search](http://search.nix.gsc.io/?q=php7&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=php7+in%3Apath&type=Code))  php: two vulnerabilities
 - [x] [`#715263`](https://lwn.net/Vulnerabilities/715263/) ([search](http://search.nix.gsc.io/?q=profanity&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=profanity+in%3Apath&type=Code))  profanity: user impersonation

### kernel (2 issues)
 - [x] [`#715268`](https://lwn.net/Vulnerabilities/715268/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: two vulnerabilities
 - [x] [`#715266`](https://lwn.net/Vulnerabilities/715266/) ([search](http://search.nix.gsc.io/?q=kernel&i=fosho&repos=nixos-nixpkgs), [files](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=kernel+in%3Apath&type=Code))  kernel: privilege escalation

**Comment by 7c6f434c** [comment]
`profanity`: updated to 0.5.1 everywhere, should do the trick
b8812dfeacf9f55605d03b61b7b4b8a627d44739
5888067a7ddc30468e8b102599266317c820acc2

**Comment by 7c6f434c** [comment]
Anyone wants to check the full list in the initial announcements?

```
- CVE-2017-5589: yaxim and Bruno (0.8.6 - 0.8.8; Android)
- CVE-2017-5590: ChatSecure (3.2.0 - 4.0.0; only iOS) and Zom (all versions up to 1.0.11; only iOS)
- CVE-2017-5591: poezio (0.8 - 0.10)
- CVE-2017-5592: profanity (0.4.7 - 0.5.0)
- CVE-2017-5593: Psi+ (0.16.563.580 - 0.16.571.627)
- CVE-2017-5602: jappix (1.0.0 to 1.1.6)
- CVE-2017-5603: Jitsi (2.5.5061 - 2.9.5544)
- CVE-2017-5604: mcabber (1.0.0 - 1.0.4)
- CVE-2017-5605: Movim (0.8 - 0.10)
- CVE-2017-5606: Xabber (only if manually enabled: 1.0.30, 1.0.30 VIP, beta 1.0.3 - 1.0.74; Android)
- CVE-2017-5858: Converse.js (0.8.0 - 1.0.6, 2.0.0 - 2.0.4)
```
`mcabber`: cherry-picked c7ad684ab55f0aece1aeba8d850b6f207deeb71c into release, didn't realise it is a security fix before

**Comment by 7c6f434c** [comment]
@grahamc If you add a checkbox for every entry in IM client list, you could get the issue count closer to the mention count!

**Comment by NeQuissimus** [comment]
Kernel looks fine

**Comment by fpletz** [comment]
The PHP vulnerabilities are fixed in the version we're shipping.

And we're done. :smile:

**Comment by 7c6f434c** [comment]
I think `jitsi` is vulnerable in both branches.

**Comment by grahamc** [comment]
Todo: https://github.com/NixOS/nixpkgs/issues/23292

**Comment by 7c6f434c** [comment]
Re: `jitsi`: a straightforward update switched self-signed server certificates from «always accepted» to «rejected with a generic connection failure». It may also be that the failure is actually not about the certificate…

**Comment by grahamc** [comment]
- [ ] CVE-2017-5589: yaxim and Bruno (0.8.6 - 0.8.8; Android)
- [ ] CVE-2017-5590: ChatSecure (3.2.0 - 4.0.0; only iOS) and Zom (all versions up to 1.0.11; only iOS)
- [ ] CVE-2017-5591: poezio (0.8 - 0.10)
- [ ] CVE-2017-5592: profanity (0.4.7 - 0.5.0)
- [ ] CVE-2017-5593: Psi+ (0.16.563.580 - 0.16.571.627)
- [ ] CVE-2017-5602: jappix (1.0.0 to 1.1.6)
- [ ] CVE-2017-5603: Jitsi (2.5.5061 - 2.9.5544)
- [ ] CVE-2017-5604: mcabber (1.0.0 - 1.0.4)
- [ ] CVE-2017-5605: Movim (0.8 - 0.10)
- [ ] CVE-2017-5606: Xabber (only if manually enabled: 1.0.30, 1.0.30 VIP, beta 1.0.3 - 1.0.74; Android)
- [ ] CVE-2017-5858: Converse.js (0.8.0 - 1.0.6, 2.0.0 - 2.0.4)

**Comment by grahamc** [comment]
profanity: needs backport to 16.09
psi: I think we're good on it, it seems Psi released 0.15 quite recently.
jitsi: definitely need an update.

**Comment by 7c6f434c** [comment]
>- [ ] CVE-2017-5603: Jitsi (2.5.5061 - 2.9.5544)

I hope that Jitsi is the only one of these that is both packaged and
vulnerable. I tried quickly updating it and failed…

**Comment by grahamc** [comment]
Yeah, the rest look good. Just need to backport profanity to 16.09 as well.

**Comment by 7c6f434c** [comment]
>Yeah, the rest look good. Just need to backport profanity to 16.09 as well. 

0.5.1 is not fresh enough?

**Comment by 7c6f434c** [comment]
>psi: I think we're good on it, it seems Psi released 0.15 quite recently.

It was about Psi+ and apparently the vulnerability is newer than our 
Psi, not older. Anyway, doesn't seem to include Psi 0.15.

**Comment by grahamc** [comment]
Seems I had an out of date 16.09 locally :) You're right. 👍 I'll get on to trying to patch Jitsi. Thank you for the digging & patching on this.

**Comment by vcunat** [comment]
**CVE-2017-2624** [future roundup]: fixed on master and 17.03 via 25c590f91.  On 16.03 we have older xorg-server branch, which seems also affected, most likely, but there's no official release for it.  For now I've left 16.03 unpatched; [it's considered](https://www.x41-dsec.de/lab/advisories/x41-2017-001-xorg/) a low-impact issue.

**Comment by grahamc** [comment]
I've patched jitsi on unstable and 17.03-beta. @khumba, is upgrading jitsi 2.8.5426 -> 2.10.5550 a safe thing to do on Stable?

**Comment by grahamc** [comment]
Amazing how long it took to finish this one up :) I'm fairly sure I missed some announcements in the email, I'm working on improving that system now.

**Comment by grahamc** [comment]
TWhank

**Comment by grahamc** [comment]
Thank you, everyone, for your help!

**Comment by khumba** [comment]
Hi @grahamc, it seems that the 2.10 derivation has some issues both on 17.03 and (cherry-picked onto) 16.09, at least for me: there are a bunch of Java class not found / link errors on startup and PulseAudio and systray support seem to be broken as a result (it still found my webcam fine).  I'm sorry to say this but I haven't actively been using Jitsi for a while and don't even have an XMPP account to test with now, so I should probably remove myself from its maintainers.

**Comment by 7c6f434c** [comment]
I have an XMPP account, and Jitsi doesn't seem to be able to connect.
