### ISSUE TITLE
Tracking - Python section in nixpkgs manual.

### ISSUE THREAD

**Issue by alejandrosame** [NixOS/nixpkgs#240118]
## Project description

This tracking issue exists to help analyze the Python section in the `nixpkgs manual`. Eventually, follow-up tasks will be added.

So far, the linked open issues are split between:
 - reported problems with the `nixpkgs manual` Python section.
 - Python related Nix APIs, use cases, etc., possibly lacking reference documentation.
These are to be checked, but can be useful for other types of documentation.

## Python section issues

- [ ] https://github.com/NixOS/nixpkgs/issues/72167
- [ ] https://github.com/NixOS/nixpkgs/issues/66460

## Missing Python reference documentation
- [ ] https://github.com/NixOS/nixpkgs/issues/229337
- [ ] https://github.com/NixOS/nixpkgs/issues/89759
- [ ] https://github.com/NixOS/nixpkgs/issues/78442
- [ ] https://github.com/NixOS/nixpkgs/issues/61144
- [ ] https://github.com/NixOS/nixpkgs/issues/48663
- [ ] https://github.com/NixOS/nixpkgs/issues/40835
- [ ] https://github.com/NixOS/nixpkgs/issues/24128#issuecomment-490754724
- [ ] https://github.com/NixOS/nixpkgs/issues/23676
- [ ] https://github.com/NixOS/nixpkgs/issues/23438#issuecomment-1428920896
- [ ] https://github.com/NixOS/nixpkgs/issues/10597
- [ ] https://github.com/NixOS/nixpkgs/issues/1819
