### ISSUE TITLE
Migrate existing usages of fixup_yarn_lock with fixup-yarn-lock from prefetch-yarn-deps

### ISSUE THREAD

**Issue by lilyinstarlight** [NixOS/nixpkgs#240174]
## Issue description

This is a follow-up to #214062 to migrate existing packages which use `fixup_yarn_lock` (from yarn2nix) to `fixup-yarn-lock` (from `prefetch-yarn-deps`)

It should be a drop-in replacement, just by adding `prefetch-yarn-deps` to `nativeBuildInputs` and changing the `fixup_yarn_lock` invocation to `fixup-yarn-lock`

cc @NixOS/node

### Packages to update

* [x] `muzika` #269323
* [x] `oni2` #269322
* [x] `drawio` #269321
* [x] `tandoor-recipes` #269319
* [x] `element-desktop` (and `element-desktop.seshat`) #269318
* [x] `element-web` #269317
* [x] `schildichat-desktop` #269315
* [x] `schildichat-web` #269314
* [x] `teams-for-linux` #269312
* [x] `thelounge` #269310
* [x] `gitlab` #269307
* [x] `sapling` #269305
* [x] `podman-desktop` #269304
* [x] `coder` #269303/#301512
* [x] `electron-fiddle` #269302
* [x] `anki` #269301
* [x] `heroic` #269300
* [x] `r2modman` #269299
* [x] `akkoma-frontends.admin-fe` #249954
* [x] `akkoma-frontends.akkoma-fe` #249954
* [x] `alice-lg` #269298
* [x] `mastodon` #269295
* [x] `peertube` #269294
* [x] `rmfakecloud.ui` #269293
* [x] `teleport` #269286
* [x] `discourse` #269287
* [x] `outline` #269999
* [x] `pgadmin` #269276
* [x] `ratman` #269285
* [x] `tilt` #269885
* [x] `hydrogen-web` #269903
* [x] `python311Packages.dash` #269907
* [x] `electron` #269933
* [x] `redisinsight-electron` #307467
* [x] `gotify-server` #269873
* [x] `grafana-agent` #269865
* [x] `insulator2` #323882 
* [x] `crabfit-frontend` #323883
* [x] `tetrio-desktop`(specifically the `tetrio-plus.nix` file, as the package itself doesn't use it) #323884

**Comment by Stunkymonkey** [comment]
I started doing the package `docuseal` which used `fixup_yarn_lock` (worked). When using the new "drop-in-method" (`fixup-yarn-lock`) i am getting:
```
/nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:2325
    throw error;
    ^

Invariant Violation: Commit hash required
    at invariant (/nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:2318:15)
    at Extract.<anonymous> (/nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:89267:11)
    at Extract.emit (node:events:529:35)
    at finishMaybe (/nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:74117:14)
    at /nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:74095:5
    at module.exports.Extract._final (/nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:151032:3)
    at callFinal (/nix/store/ypig039xrfd6p355v3diy9avbs58zywj-yarn-1.22.19/libexec/yarn/lib/cli.js:74088:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  framesToPop: 1
}
```
I did it the same way the other two PRs were done.

**Comment by lilyinstarlight** [comment]
It seems to be due to yarn not liking missing a commit hash in both the resolved URL and version spec here: https://github.com/docusealco/docuseal/blob/3c69430b947c1c1ea61e25ad9275b14df005a3c7/package.json#L10

I've got a fix for fixup-yarn-lock that I'll PR imminently

**Comment by Stunkymonkey** [comment]
@lilyinstarlight what about the following files? they use the `fixup_yarn_lock`  as well:

- `pkgs/applications/networking/cluster/tilt/assets.nix`
- `pkgs/applications/networking/instant-messengers/hydrogen-web/unwrapped.nix`
- `pkgs/development/python-modules/dash/default.nix`
- `pkgs/development/tools/electron/common.nix`
- `pkgs/development/tools/redisinsight/default.nix`
- `pkgs/servers/gotify/ui.nix`
- `pkgs/servers/monitoring/grafana-agent/default.nix`

should these be added at the top?

**Comment by lilyinstarlight** [comment]
> should these be added at the top?

Yeah, I imagine they didn't use it at the time I made this tracking issue (also wow are there a lot of open PRs now!)

Feel free to edit them in yourself or I'll get around to it when I have some time to get through some of these, thank you so much! :)

**Comment by TomaSajt** [comment]
I'll try to rework the `redisinsight` derivation, 'cuz I think it was broken to begin with.

**Comment by SuperSandro2000** [comment]
> It should be a drop-in replacement, just by adding `prefetch-yarn-deps` to `nativeBuildInputs` and changing the `fixup_yarn_lock` invocation to `fixup-yarn-lock`

I have encountered one issue with that. fixup-yarn-lock has an extra dependency on nix-prefetch-git and through that git-lfs which busted a cache for me because I update my standard golang compiler. Is there a possibility to reduce the dependencies of prefetch-yarn-deps/nix-prefetch-git?

**Comment by SuperSandro2000** [comment]
I did a POC with that in #281902 which I still need to validate.

**Comment by Stunkymonkey** [comment]
currently only `redisinsight` is missing (currently failing on master). The rest is migrated. Do we keep this issue open?

**Comment by lilyinstarlight** [comment]
> currently only `redisinsight` is missing (currently failing on master). The rest is migrated. Do we keep this issue open?

If it's all done, I'm happy for it to be closed :)

Thank you for all of the work <3

**Comment by codingCoffee** [comment]
Hey, came across this issue while trying to install the `redisinsight` package. The installation still seems to be broken, is there any temporary workaround for installing it?

**Comment by pyrox0** [comment]
Packages that haven't been migrated:
* `insulator2`
* `crabfit-frontend`
* `tetrio-desktop`(specifically the `tetrio-plus.nix` file, as the package itself doesn't use it)

Would there be a way/an incentive to disallow new packages from using `fixup_yarn_lock`?  Alternatively, once all usages of it are removed from the tree, is there any reason to keep it around? If there is a reason, should there be a deprecation notice added when fixup_yarn_lock is used?

**Comment by Stunkymonkey** [comment]
@pyrox0 thanks. added them to the list with the MRs.
