### ISSUE TITLE
Normalize python-modules attribute names and pnames

### ISSUE THREAD

**Issue by mweinelt** [NixOS/nixpkgs#245383]
Python attribute and pnames should be normalized according to https://packaging.python.org/en/latest/specifications/name-normalization/#normalization.

The following list of names, that need work, was provided by @adisbladis in the nixpkgs python room.

Cc'ing people who are currently doing the work in the python ecosystem.
@dotlambda @fabaff @SuperSandro2000 @tjni @natsukium 

The workflow would be to
1. Normalize pname in the derivation
2. Normalize the directory name
3. Normalize attribute name and path in `pkgs/top-level/python-packages.nix`
4. Update all references to the old attribute name treewide
5. Create an alias in `pkgs/top-level/python-aliases.nix` for the old attribute name
6. Commit `python311Packages.newname: rename from oldname`

---

- [x] Polygon3 https://github.com/NixOS/nixpkgs/pull/248010
- [x] ViennaRNA https://github.com/NixOS/nixpkgs/pull/250922
- [x] amazon_kclpy https://github.com/NixOS/nixpkgs/pull/248014
- [x] async_generator https://github.com/NixOS/nixpkgs/pull/248081
- [x] async_stagger https://github.com/NixOS/nixpkgs/pull/248082
- [x] async-timeout https://github.com/NixOS/nixpkgs/pull/248083
- [x] asyncio-mqtt https://github.com/NixOS/nixpkgs/pull/248084
- [x] atsim_potentials https://github.com/NixOS/nixpkgs/pull/259675
- [x] backports_csv https://github.com/NixOS/nixpkgs/pull/245894
- [x] backports_functools_lru_cache https://github.com/NixOS/nixpkgs/pull/245894
- [x] backports_tempfile https://github.com/NixOS/nixpkgs/pull/245894
- [x] backports_unittest-mock https://github.com/NixOS/nixpkgs/pull/245894
- [x] backports_weakref https://github.com/NixOS/nixpkgs/pull/245894
- [x] bash_kernel #266657 
- [x] beancount_docverif https://github.com/NixOS/nixpkgs/pull/259679
- [x] bip_utils https://github.com/NixOS/nixpkgs/pull/260567
- [x] btsmarthub_devicelist #278382
- [x] clr-loader https://github.com/NixOS/nixpkgs/pull/247295
- [x] covCore #278385
- [x] cx_Freeze https://github.com/NixOS/nixpkgs/pull/246900
- [x] cx_oracle #278560
- [x] deep_merge https://github.com/NixOS/nixpkgs/pull/259944
- [x] distutils_extra https://github.com/NixOS/nixpkgs/pull/260573
- [x] django_classytags #245390
- [x] django_colorful #245390
- [x] django_compat #245390
- [x] django_contrib_comments #245390
- [x] django_nose #245390
- [x] django_silk #245390
- [x] django_tagging #245390
- [x] django_treebeard #245390
- [x] docker_pycreds #278553
- [x] et_xmlfile https://github.com/NixOS/nixpkgs/pull/261328
- [x] eyeD3 #278556
- [x] factory_boy https://github.com/NixOS/nixpkgs/pull/259729
- [x] fastnlo_toolkit #278569
- [x] filebrowser_safe #278565
- [x] flask_assets https://github.com/NixOS/nixpkgs/pull/250993
- [x] flask_elastic https://github.com/NixOS/nixpkgs/pull/250993
- [x] flask_mail https://github.com/NixOS/nixpkgs/pull/250993
- [x] flask_marshmallow https://github.com/NixOS/nixpkgs/pull/249441
- [x] flask_migrate https://github.com/NixOS/nixpkgs/pull/250993
- [x] flask_principal https://github.com/NixOS/nixpkgs/pull/250993
- [x] flask_script https://github.com/NixOS/nixpkgs/pull/250993
- [x] flowlogs_reader #278585
- [x] flufl_bounce #265198 #285868
- [x] flufl_i18n #265198 #285868
- [x] flufl_lock #265198 #285868
- [x] github3_py #278786
- [x] gradient_statsd #279201
- [x] grappelli_safe https://github.com/NixOS/nixpkgs/pull/259732
- [x] groestlcoin_hash #279214
- [x] guzzle_sphinx_theme https://github.com/NixOS/nixpkgs/pull/261330
- [x] hcs_utils #279221
- [x] ipython_genutils https://github.com/NixOS/nixpkgs/pull/260593
- [x] jinja2_pluralize https://github.com/NixOS/nixpkgs/pull/264721
- [x] jsonpath_rw #279223
- [x] jupyter_console https://github.com/NixOS/nixpkgs/pull/253281
- [x] jupyterlab_launcher https://github.com/NixOS/nixpkgs/pull/266803
- [x] jupyterlab_server #267010
- [x] keepkey_agent #279225
- [x] lazr_config https://github.com/NixOS/nixpkgs/pull/265243
- [x] lazr_delegates https://github.com/NixOS/nixpkgs/pull/265243
- [x] lazy_import #279255
- [x] lazy_imports https://github.com/NixOS/nixpkgs/pull/261332
- [x] lcov_cobertura #279256
- [x] ledger_agent #279257
- [x] line_profiler https://github.com/NixOS/nixpkgs/pull/265256
- [x] linear_operator #279258
- [x] ludios_wpull https://github.com/NixOS/nixpkgs/pull/267001
- [x] mac_alias #279332
- [x] memory_profiler https://github.com/NixOS/nixpkgs/pull/259952
- [x] mir_eval #279334
- [x] multi_key_dict https://github.com/NixOS/nixpkgs/pull/265582
- [x] nose_warnings_filters #279336
- [x] opsdroid_get_image_size https://github.com/NixOS/nixpkgs/pull/261334
- [x] posix_ipc #279338
- [x] proxy_tools https://github.com/NixOS/nixpkgs/pull/265587
- [x] pyRFC3339 #279466
- [x] pySmartDL https://github.com/NixOS/nixpkgs/pull/260345
- [x] py_scrypt #279350
- [x] py_stringmatching https://github.com/NixOS/nixpkgs/pull/266983
- [x] pygame_sdl2 #279396
- [x] pymaging_png https://github.com/NixOS/nixpkgs/pull/265260
- [x] pyqt5_sip #279395
- [x] pyqt5_with_qtmultimedia #279394
- [x] pyqt5_with_qtwebkit #279392
- [x] pyramid_beaker https://github.com/NixOS/nixpkgs/pull/250999
- [x] pyramid_chameleon https://github.com/NixOS/nixpkgs/pull/250999
- [x] pyramid_exclog https://github.com/NixOS/nixpkgs/pull/250999
- [x] pyramid_mako https://github.com/NixOS/nixpkgs/pull/250999
- [x] pyramid_multiauth https://github.com/NixOS/nixpkgs/pull/250999
- [x] ~pysideShiboken~ https://github.com/NixOS/nixpkgs/commit/9a87752f0b1fd2ea5fd8d0a0995ef812a018a601
- [x] ~pysideTools~ https://github.com/NixOS/nixpkgs/commit/9a87752f0b1fd2ea5fd8d0a0995ef812a018a601
- [x] python_docs_theme https://github.com/NixOS/nixpkgs/pull/265377
- [x] python_fedora https://github.com/NixOS/nixpkgs/pull/267482
- [x] python_openzwave #279388
- [x] qds_sdk https://github.com/NixOS/nixpkgs/pull/262430
- [x] querystring_parser #279390
- [x] radicale_infcloud #279389
- [x] radio_beam https://github.com/NixOS/nixpkgs/pull/265383
- [x] rank_bm25 #265845
- [x] readme_renderer #279385
- [x] recaptcha_client https://github.com/NixOS/nixpkgs/pull/262244
- [x] recursivePthLoader #279384
- [x] repoze_lru https://github.com/NixOS/nixpkgs/pull/266822
- [x] repoze_sphinx_autointerface https://github.com/NixOS/nixpkgs/pull/266822
- [x] repoze_who https://github.com/NixOS/nixpkgs/pull/266822
- [x] requests_download #279380
- [x] requests_ntlm #279378
- [x] restructuredtext_lint https://github.com/NixOS/nixpkgs/pull/265269
- [x] retry_decorator #279369
- [x] setuptoolsTrial https://github.com/NixOS/nixpkgs/pull/266826
- [x] sip_4 #279367
- [x] sorl_thumbnail https://github.com/NixOS/nixpkgs/pull/266978
- [x] spark_parser #279358
- [x] sphinx_pypi_upload https://github.com/NixOS/nixpkgs/pull/260349
- [x] sphinxcontrib_httpdomain https://github.com/NixOS/nixpkgs/pull/259350
- [x] sphinxcontrib_newsfeed https://github.com/NixOS/nixpkgs/pull/259350
- [x] supervise_api https://github.com/NixOS/nixpkgs/pull/260353
- [x] sysv_ipc #279355
- [x] thumborPexif #279356
- [x] torrent_parser https://github.com/NixOS/nixpkgs/pull/265386
- [x] trezor_agent #279353
- [x] tvdb_api https://github.com/NixOS/nixpkgs/pull/262250
- [x] ufoLib2 #279352
- [x] update_checker #279351
- [x] vega_datasets https://github.com/NixOS/nixpkgs/pull/265390
- [x] wxPython_4_2 #279359
- [x] x11_hash https://github.com/NixOS/nixpkgs/pull/265580
- [x] zc_lockfile #279227
- [x] zope_broken https://github.com/NixOS/nixpkgs/pull/245467
- [x] zope_component https://github.com/NixOS/nixpkgs/pull/245808
- [x] zope_configuration https://github.com/NixOS/nixpkgs/pull/266888
- [x] zope_contenttype https://github.com/NixOS/nixpkgs/pull/260333
- [x] zope_copy #279208
- [x] zope_deprecation https://github.com/NixOS/nixpkgs/pull/259576
- [x] zope_dottedname https://github.com/NixOS/nixpkgs/pull/266889
- [x] zope_event https://github.com/NixOS/nixpkgs/pull/265392
- [x] zope_exceptions https://github.com/NixOS/nixpkgs/pull/266973
- [x] zope_filerepresentation #279208
- [x] zope_i18nmessageid https://github.com/NixOS/nixpkgs/pull/246044
- [x] zope_interface #279208
- [x] zope_lifecycleevent https://github.com/NixOS/nixpkgs/pull/260342
- [x] zope_location #279208
- [x] zope_proxy https://github.com/NixOS/nixpkgs/pull/259591
- [x] zope_schema #279208
- [x] zope_size #279208
- [x] zope_testing https://github.com/NixOS/nixpkgs/pull/266970
- [x] zope_testrunner #279208
- [x] zxing_cpp https://github.com/NixOS/nixpkgs/pull/265575

**Comment by zimbatm** [comment]
Is there more context available to the name normalization reasoning?

As a user, the 1:1 mapping between pypi packages and nixpkgs package name is quite convenient. It allows me to copy-paste things around.

**Comment by mweinelt** [comment]
We follow [PEP 503 normalization rules](https://peps.python.org/pep-0503/#normalized-names), according to the python contributing guidelines.

> Attribute names in python-packages.nix as well as pnames should match the library's name on PyPI, but be normalized according to [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names). This means that characters should be converted to lowercase and . and _ should be replaced by a single - (foo-bar-baz instead of Foo__Bar.baz). If necessary, pname has to be given a different value within fetchPypi.

Originated in https://github.com/NixOS/nixpkgs/pull/45822

**Comment by Stunkymonkey** [comment]
for every entry there is now an PR ongoing, except for two package:

- `pysideShiboken`
- `pysideTools`

any idea what to do with them? they seem perfectly fine.

**Comment by Stunkymonkey** [comment]
@adisbladis can you please check if all packages (except #285868) are correct? or some new unnormalized sneaked in?

**Comment by Stunkymonkey** [comment]
I did myself a "quick" check and came up with this list of remaining packages:

- [ ] backports_shutil_get_terminal_size
- [ ] command_runner
- [ ] connect-box
- [ ] moderngl-window
- [ ] setuptools_dso
- [ ] smpp_pdu

**Comment by dotlambda** [comment]
imread's pname looks off

**Comment by Stunkymonkey** [comment]
FYI: @dotlambda I just sorted your list. Otherwise documenting the progress is hard. Hope that is ok.

**Comment by Stunkymonkey** [comment]
@dotlambda can you please verify again. I think we can close this issue.

**Comment by Stunkymonkey** [comment]
found some more packages:

- [ ] aspy-yaml
- [ ] smpp-pdu
- [ ] backports-shutil-which
- [ ] backports-shutil-get-terminal-size

**Comment by Stunkymonkey** [comment]
all the lists in this thread are now done. staging is merged into master.

Therefore I consider this done.
