### ISSUE TITLE
Documentation: Update bespoke markdown syntax reference

### ISSUE THREAD

**Issue by alejandrosame** [NixOS/nixpkgs#246357]
# Problem

Contributors working on improving the nixpkgs manual would be redirected to the [contributing chapter](https://nixos.org/manual/nixpkgs/unstable/#chap-contributing). This section is not up-to-date with all the syntax features supported by `nixos-render-docs`, forcing contributors to look for use examples over the whole manual. 

The same markdown syntax is used to write and generate the NixOS manual. However, this manual does not make any mention of the supported syntax. This makes it hard to contribute to the NixOS manual with relative isolation from the nixpkgs manual.

## Context
- https://github.com/NixOS/nixpkgs/pull/241656#discussion_r1253049361
- https://github.com/NixOS/nixpkgs/pull/241656#pullrequestreview-1514493143

# Proposal

Update `Contributing to this manual` in Nixpkgs manual to include reference material and examples on all the syntax features supported by `nixos-render-docs`. Link `Contributing to this manual` in Nixos manual for completion.

# TODO

- [x] remove references to `DocBook` in the `Nixpkgs manual`. `PR`: https://github.com/NixOS/nixpkgs/pull/241656
- [x] remove references to `DocBook` in the `NixOS manual`. https://github.com/NixOS/nixpkgs/pull/264450
- [x] add a `syntax section` redirecting to the syntax section in `Nixpkgs manual`.
- [x] add reference to lack of support for `HTML` https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `admonitions` support
- [x] add reference to `deflist` support
- [x] add reference to `example blocks` support https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `figure blocks` support https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `footnote` support https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `inline_comment` support https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `myst_role` support https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `replacements` support https://github.com/NixOS/nixpkgs/pull/264450
- [x] add reference to `table` support. `PR`: https://github.com/NixOS/nixpkgs/pull/241656

# Checklist
- [x] checked latest [nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#chap-contributing) ([source](https://github.com/NixOS/nixpkgs/blob/master/doc/contributing/contributing-to-documentation.chapter.md))
- [x] checked latest [NixOS manual](https://nixos.org/manual/nixos/unstable/#chap-contributing) ([source](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/contributing-to-this-manual.chapter.md))
- [x] checked `nixos-render-docs` syntax support ([source](https://github.com/NixOS/nixpkgs/blob/8b1253715d80e224908e29a53014b9323933abf7/pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/md.py#L581-L608))
