### ISSUE TITLE
Tracking Issue: Prepare Python packages for PyPA build

### ISSUE THREAD

**Issue by tjni** [NixOS/nixpkgs#247287]
This is a tracking issue that originates from https://github.com/NixOS/nixpkgs/pull/245509. I have been using that PR to reference work that is needed before merging it, but it distracts from the core logic in the PR itself, so I am going to use this issue to track the related work instead.

#### Prerequisites to merging

- [x] https://github.com/NixOS/nixpkgs/pull/245671
- [x] https://github.com/NixOS/nixpkgs/pull/246963
- [x] https://github.com/NixOS/nixpkgs/pull/248826
- [x] https://github.com/NixOS/nixpkgs/pull/247064
- [x] https://github.com/NixOS/nixpkgs/pull/249644
- [x] https://github.com/NixOS/nixpkgs/pull/249646
- [x] https://github.com/NixOS/nixpkgs/pull/247073
- [x] https://github.com/NixOS/nixpkgs/pull/246908
- [x] https://github.com/NixOS/nixpkgs/pull/246917
- [x] https://github.com/NixOS/nixpkgs/pull/246922
- [x] https://github.com/NixOS/nixpkgs/pull/246829
- [x] https://github.com/NixOS/nixpkgs/pull/246900
- [x] https://github.com/NixOS/nixpkgs/pull/246905
- [x] https://github.com/NixOS/nixpkgs/pull/246907
- [x] https://github.com/NixOS/nixpkgs/pull/246909
- [x] https://github.com/NixOS/nixpkgs/pull/246912
- [x] https://github.com/NixOS/nixpkgs/pull/246915
- [x] https://github.com/NixOS/nixpkgs/pull/246919
- [x] https://github.com/NixOS/nixpkgs/pull/246920
- [x] https://github.com/NixOS/nixpkgs/pull/246925
- [x] https://github.com/NixOS/nixpkgs/pull/246946
- [x] https://github.com/NixOS/nixpkgs/pull/247239
- [x] https://github.com/NixOS/nixpkgs/pull/247246
- [x] https://github.com/NixOS/nixpkgs/pull/247250
- [x] https://github.com/NixOS/nixpkgs/pull/247258
- [x] https://github.com/NixOS/nixpkgs/pull/247260
- [x] https://github.com/NixOS/nixpkgs/pull/247269
- [x] https://github.com/NixOS/nixpkgs/pull/247272
- [x] https://github.com/NixOS/nixpkgs/pull/247295
- [x] https://github.com/NixOS/nixpkgs/pull/247305
- [x] https://github.com/NixOS/nixpkgs/pull/247306
- [x] https://github.com/NixOS/nixpkgs/pull/247308
- [x] https://github.com/NixOS/nixpkgs/pull/247310
- [x] https://github.com/NixOS/nixpkgs/pull/247311
- [x] https://github.com/NixOS/nixpkgs/pull/247313
- [x] https://github.com/NixOS/nixpkgs/pull/247460
- [x] https://github.com/NixOS/nixpkgs/pull/247464
- [x] https://github.com/NixOS/nixpkgs/pull/247508
- [x] https://github.com/NixOS/nixpkgs/pull/247852
- [x] https://github.com/NixOS/nixpkgs/pull/246735
- [x] https://github.com/NixOS/nixpkgs/pull/247864
- [x] https://github.com/NixOS/nixpkgs/pull/248067
- [x] https://github.com/NixOS/nixpkgs/pull/248066
- [x] https://github.com/NixOS/nixpkgs/pull/248072
- [x] https://github.com/NixOS/nixpkgs/pull/245152
- [x] https://github.com/NixOS/nixpkgs/pull/248084
- [x] https://github.com/NixOS/nixpkgs/pull/248319
- [x] https://github.com/NixOS/nixpkgs/pull/248511
- [x] https://github.com/NixOS/nixpkgs/pull/248589
- [x] https://github.com/NixOS/nixpkgs/pull/248595
- [x] https://github.com/NixOS/nixpkgs/pull/248598
- [x] https://github.com/NixOS/nixpkgs/pull/248601
- [x] https://github.com/NixOS/nixpkgs/pull/248606
- [x] https://github.com/NixOS/nixpkgs/pull/248612
- [x] https://github.com/NixOS/nixpkgs/pull/248614
- [x] https://github.com/NixOS/nixpkgs/pull/248623
- [x] https://github.com/NixOS/nixpkgs/pull/248626
- [x] https://github.com/NixOS/nixpkgs/pull/248640
- [x] https://github.com/NixOS/nixpkgs/pull/248643
- [x] https://github.com/NixOS/nixpkgs/pull/248754
- [x] https://github.com/NixOS/nixpkgs/pull/248757
- [x] https://github.com/NixOS/nixpkgs/pull/248759
- [x] https://github.com/NixOS/nixpkgs/pull/248773
- [x] https://github.com/NixOS/nixpkgs/pull/248776
- [x] https://github.com/NixOS/nixpkgs/pull/248780
- [x] https://github.com/NixOS/nixpkgs/pull/248785
- [x] https://github.com/NixOS/nixpkgs/pull/248787
- [x] https://github.com/NixOS/nixpkgs/pull/248798
- [x] https://github.com/NixOS/nixpkgs/pull/248800
- [x] https://github.com/NixOS/nixpkgs/pull/248822
- [x] https://github.com/NixOS/nixpkgs/pull/248836
- [x] https://github.com/NixOS/nixpkgs/pull/248840
- [x] https://github.com/NixOS/nixpkgs/pull/248850
- [x] https://github.com/NixOS/nixpkgs/pull/248859
- [x] https://github.com/NixOS/nixpkgs/pull/248872
- [x] https://github.com/NixOS/nixpkgs/pull/248943
- [x] https://github.com/NixOS/nixpkgs/pull/248946
- [x] https://github.com/NixOS/nixpkgs/pull/248949
- [x] https://github.com/NixOS/nixpkgs/pull/249459
- [x] https://github.com/NixOS/nixpkgs/pull/249466
- [x] https://github.com/NixOS/nixpkgs/pull/249473
- [x] https://github.com/NixOS/nixpkgs/pull/249486
- [x] https://github.com/NixOS/nixpkgs/pull/249489
- [x] https://github.com/NixOS/nixpkgs/pull/249519
- [x] https://github.com/NixOS/nixpkgs/pull/249648
- [x] https://github.com/NixOS/nixpkgs/pull/249763
- [x] https://github.com/NixOS/nixpkgs/pull/249768
- [x] https://github.com/NixOS/nixpkgs/pull/249775
- [x] https://github.com/NixOS/nixpkgs/pull/249779
- [x] https://github.com/NixOS/nixpkgs/pull/249796
- [x] https://github.com/NixOS/nixpkgs/pull/249798
- [x] https://github.com/NixOS/nixpkgs/pull/249800
- [x] https://github.com/NixOS/nixpkgs/pull/249801
- [x] https://github.com/NixOS/nixpkgs/pull/249815
- [x] https://github.com/NixOS/nixpkgs/pull/249821
- [x] https://github.com/NixOS/nixpkgs/pull/249837
- [x] https://github.com/NixOS/nixpkgs/pull/249838
- [x] https://github.com/NixOS/nixpkgs/pull/249842
- [x] https://github.com/NixOS/nixpkgs/pull/249847
- [x] https://github.com/NixOS/nixpkgs/pull/249849
- [x] https://github.com/NixOS/nixpkgs/pull/249850
- [x] https://github.com/NixOS/nixpkgs/pull/249854
- [x] https://github.com/NixOS/nixpkgs/pull/249856
- [x] https://github.com/NixOS/nixpkgs/pull/249916
- [x] https://github.com/NixOS/nixpkgs/pull/250036
- [x] https://github.com/NixOS/nixpkgs/pull/250059
- [x] https://github.com/NixOS/nixpkgs/pull/250061
- [x] https://github.com/NixOS/nixpkgs/pull/250110
- [x] https://github.com/NixOS/nixpkgs/pull/250111
- [x] https://github.com/NixOS/nixpkgs/pull/250114
- [x] https://github.com/NixOS/nixpkgs/pull/250117
- [x] https://github.com/NixOS/nixpkgs/pull/250124
- [x] https://github.com/NixOS/nixpkgs/pull/250153
- [x] https://github.com/NixOS/nixpkgs/pull/250155
- [x] https://github.com/NixOS/nixpkgs/pull/250157
- [x] https://github.com/NixOS/nixpkgs/pull/250158
- [x] https://github.com/NixOS/nixpkgs/pull/250162
- [x] https://github.com/NixOS/nixpkgs/pull/250165
- [x] https://github.com/NixOS/nixpkgs/pull/250206
- [x] https://github.com/NixOS/nixpkgs/pull/250209
- [x] https://github.com/NixOS/nixpkgs/pull/250211
- [x] https://github.com/NixOS/nixpkgs/pull/250215
- [x] https://github.com/NixOS/nixpkgs/pull/250240
- [x] https://github.com/NixOS/nixpkgs/pull/250256
- [x] ~https://github.com/NixOS/nixpkgs/pull/250261~ https://github.com/NixOS/nixpkgs/pull/250778/commits/f13d239861c6f837031201c96ff7fdb4849fb26f
- [x] https://github.com/NixOS/nixpkgs/pull/250262
- [x] https://github.com/NixOS/nixpkgs/pull/250458
- [x] https://github.com/NixOS/nixpkgs/pull/250464
- [x] https://github.com/NixOS/nixpkgs/pull/250649
- [x] https://github.com/NixOS/nixpkgs/pull/250665
- [ ] https://github.com/NixOS/nixpkgs/pull/229480
- [x] https://github.com/NixOS/nixpkgs/pull/250671
- [x] https://github.com/NixOS/nixpkgs/pull/250672
- [x] https://github.com/NixOS/nixpkgs/pull/250679
- [x] https://github.com/NixOS/nixpkgs/pull/250681
- [x] https://github.com/NixOS/nixpkgs/pull/250687
- [x] https://github.com/NixOS/nixpkgs/pull/250689
- [x] https://github.com/NixOS/nixpkgs/pull/250700
- [x] https://github.com/NixOS/nixpkgs/pull/250706
- [x] https://github.com/NixOS/nixpkgs/pull/250798
- [x] https://github.com/NixOS/nixpkgs/pull/250801
- [x] https://github.com/NixOS/nixpkgs/pull/250814
- [x] https://github.com/NixOS/nixpkgs/pull/250817
- [x] https://github.com/NixOS/nixpkgs/pull/250819
- [x] https://github.com/NixOS/nixpkgs/pull/250822
- [x] https://github.com/NixOS/nixpkgs/pull/250823
- [x] https://github.com/NixOS/nixpkgs/pull/250824
- [x] https://github.com/NixOS/nixpkgs/pull/250850
- [x] https://github.com/NixOS/nixpkgs/pull/250886
- [x] https://github.com/NixOS/nixpkgs/pull/250905
- [x] https://github.com/NixOS/nixpkgs/pull/251047
- [x] python310Packages.esphome-dashboard-api https://github.com/NixOS/nixpkgs/pull/250778/commits/669bfe2355c30d16bcfc4be43567f8e2c2b83ddb
- [x] python310Packages.remarshal https://github.com/NixOS/nixpkgs/pull/250778/commits/abc57e2f0f9f716e5f9f33efde43cd6d1d5e7018
- [x] python310Packages.distributed https://github.com/NixOS/nixpkgs/pull/250778/commits/3d3b361ac1352ba3ed80044640d8ebc0378f25c0
- [x] python310Packages.fastparquet https://github.com/NixOS/nixpkgs/pull/250778/commits/2ead800ce76e7a0155748841685a7387fa216fd4
- [x] https://github.com/NixOS/nixpkgs/pull/247885
- [x] https://github.com/NixOS/nixpkgs/pull/251065
- [x] https://github.com/NixOS/nixpkgs/pull/251096
- [x] https://github.com/NixOS/nixpkgs/pull/251240
- [x] https://github.com/NixOS/nixpkgs/pull/251533
- [x] https://github.com/NixOS/nixpkgs/pull/251548
- [x] https://github.com/NixOS/nixpkgs/pull/251677
- [x] https://github.com/NixOS/nixpkgs/pull/251679
- [x] https://github.com/NixOS/nixpkgs/pull/251708
- [x] https://github.com/NixOS/nixpkgs/pull/251730
- [x] https://github.com/NixOS/nixpkgs/pull/251733
- [x] https://github.com/NixOS/nixpkgs/pull/251736
- [x] https://github.com/NixOS/nixpkgs/pull/251739

#### Makes life easier

- [x] https://github.com/NixOS/nixpkgs/pull/246926
- [x] https://github.com/NixOS/nixpkgs/pull/247207
- [x] https://github.com/NixOS/nixpkgs/pull/246723
- [x] https://github.com/NixOS/nixpkgs/pull/248019
- [x] https://github.com/NixOS/nixpkgs/pull/248273
- [x] https://github.com/NixOS/nixpkgs/pull/248231
- [x] https://github.com/NixOS/nixpkgs/pull/246931
- [x] https://github.com/NixOS/nixpkgs/pull/248760
- [x] https://github.com/NixOS/nixpkgs/pull/244535
- [x] https://github.com/NixOS/nixpkgs/pull/249841

**Comment by tjni** [comment]
There are still a few lingering packages that need to be fixed, but the main body of the changes have been merged back into `master` and will be fixed one-by-one when time permits. I'll be closing this ticket now. I want to thank everyone who has been so helpful with reviewing the PRs here.
