### ISSUE TITLE
texlive: switch to buildEnv/withPackages

### ISSUE THREAD

**Issue by xworld21** [NixOS/nixpkgs#250243]
This is to track various changes to modernize `texlive` and make it work like haskell, lua, perl, python, which seem to have converged on the same interface. This comes after quite a lot of work to make the existing `texlive` almost 100% functional and with lots of tests, so we should be able to spot breakages easily. That's the theory anyway.

Feedback and comments are *very* welcome. Cc @veprbl @apfelkuchen6.

### Intended outcome
Building a new TeX Live environment:
```nix
texlive.withPackages (ps: with ps; [ scheme-small dvipng ])
```
Building a TeX Live environment with documentation or a different paper size:
```nix
texlive.buildEnv.override { packages = ps: with ps; [ scheme-small ]; extraOutputsToInstall = [ "texdoc" ]; }
texlive.scheme-small.override { extraOutputsToInstall = [ "texdoc" ]; paperSize = "letter"; }
```
Building a TeX Live package outside of `texlive`
```nix
stdenv.mkDerivation { outputs = [ "out" "tex" ]; ... }
```
Replace a TeX Live package with a different version, or pass other overrides
```nix
texlive.scheme-small.override { packageOverrides = final: prev: { asymptote = asymptote; }; }
```

The changes will also make it easier to ship different snapshots of TeX Live, or at least to upgrade/downgrade locally, and to package [tlcontrib](https://contrib.texlive.info/). We should also become able to deduplicate the formats.

### Roadmap
Here is a tentative roadmap. I believe we have enough of the difficult parts in draft form to make it by 23.11, and be prepared to drop the old stuff in 24.05/24.11, so that we make a single big change. We should really try to do this once: I already made a mistake this cycle when introducing `tlDeps`, which in hindsight was the wrong choice (see `requiredTeXPackages` below)!

Still, each step should be fully backward compatible, so we *can* stop halfway if we don't make it.

0. [ ] Procure more tests! #248960 for start, plus #247798 to fix `tests.texlive.licenses`.
1. [ ] Refactor the packages outside of `texlive` (fix #237227).
   - [ ] Refactor package building in separate `buildTeXLivePackage` (ready in #247550). Strictly for *TeX Live* packages so tightly coupled with `tlpdb.nix`, not for general use.
   - [ ] Create scope `texlive.pkgs`, set `texlivePackages = texlive.pkgs` (this is the pattern used by the other interpreters, at least). Luckily a straight `makeScope` without splicing should be fine. Cc @apfelkuchen6.
   - [ ] Backward compatibility: keep aliases `texlive.example = texlivePackages.example;`.
2. [ ] Use a 'multi-output' approach for TeX Live packages. Proof-of-concept in #249803: not literally multi-output, packages are still groups of fixed output derivations that build independently of each other.
   - [ ] Rewrite `buildTeXLivePackage` accordingly.
   - [ ] Backward compatibility: provide 'alias' `texlivePackages.example.pkgs` with old `tlType` interface, set `texlive.example = { inherit (texlivePackages.example) pkgs; }`.
   - This change allows exposing the single TeX Live packages in search (i.e. `texlivePackages = recurseIntoAttrs texlive.pkgs`). But we don't have to do that necessarily.
3. [ ] Implement `texlive.buildEnv` and shorthand `texlive.withPackages`.
   - [ ] Rewrite `combine` logic for multi-output packages (proof-of-concept in #249803). Suggested arguments: `{ extraName, extraOutputsToInstall, extraVersion, packageOverrides, packages, paperSize }`. For instance `extraOutputsToInstall = [ "texdoc" ]` adds the package docs; `packages = [ example example.texdoc ]` adds the docs for `example` only. (`paperSize` implemented in #248768).
   - [ ] Change `tlDeps = [ ... ]` dependencies into `requiredTeXPackages = ps: [ ... ]`. Otherwise the packages may be pulled from the wrong scope.
   - Backward compatibilty: keep accepting `tlDeps` for dependencies, provide `texlive.combine` alias which accepts the old argument `pkgFilter`.

Everything can/will be gated behind `config.allowAliases` and/or a deprecation warning so that people have time to adjust, plus documentation (including how to migrate), release notes, etc.

Ideal scenario, we merge everything by the end of September, to have a good period of testing before 23.11.
