### ISSUE TITLE
Package request: libhelium

### ISSUE THREAD

**Issue by Ashvith10** [NixOS/nixpkgs#250997]
**Project description**
The elegant framework for building beautiful and useful apps. libhelium is suited for building amazing native applications, regardless of design background or skill level.

**Metadata**

* homepage URL: https://docs.developers.tauos.co/libhelium/libhelium-1/
* source URL: https://github.com/tau-OS/libhelium
* license: lgpl3
* platforms: unix

**Dependencies**
- [ ] [tau-hydrogen](https://github.com/NixOS/nixpkgs/issues/251512) (icon theme)
- [ ] [tau-helium](https://github.com/NixOS/nixpkgs/issues/251513) (gtk theme)
- [ ] [libbismuth](https://github.com/NixOS/nixpkgs/issues/251518) (responsive widgets)

**Comment by Ashvith10** [comment]
I'm not able to progress here, because I'm not able to figure out how to deal with issues related to wrap. In my case, it is the tau-helium theme. For now, I've made a separate [theme](https://github.com/tau-OS/tau-helium) package in Nix, it builds just fine, but I'm not able to figure out how to use the built CSS files of that package with this library.

Pinging GTK maintainers @magnouvean and @bobby285271, a little assistance would be appreciated.

**Comment by bobby285271** [comment]
> issues related to wrap

Ugh, this can probably be reported to upstream as downloading won't be possible in sandbox. As a temporarily hack, I wonder if it is possible to patch the meson.build to use a hardcoded absolute path for now, like `@theme@/share/themes/Helium/gtk-4.0/gtk.css` (then substitute the `@theme@` using e.g. `substituteAll`)

**Comment by Ashvith10** [comment]
@bobby285271 I've tried contacting you and @jtojnar over Element, but I didn't receive a response. Perhaps you're both busy atm.

If you don't mind, can you check out my progress at [all-patch-work-for-skiff-and-helium](https://github.com/Ashvith10/nixpkgs/tree/all-patch-work-for-skiff-and-helium)? It's a messy branch, but I plan to make separate branches for a cleaner PR. Here's what the branch includes:

- skiff-desktop
- tau-helium GTK3/4 theme
- tau-hydrogen icon theme
- libhelium
- libbismuth

For now, I've disabled building the optional dependency for `libhelium` that is `libbismuth`. The build keeps failing because meson switches to absolute path for some reason. I've worked closely with the actual devs, and they were kind enough to make amends with meson for nixpkg compatibility.

But I was never able to deal with [find_program](https://github.com/mesonbuild/meson/issues/7453). Perhaps this dependency going to be shelled out soon, but since it's a requirement to test the demo app at least for the time being, I've felt that it was necessary to add the same.

Another issue is that I've made a mess of the theme file. It is a dependency for both libhelium (which is how it should be) and skiff-desktop. I'm very much new to GTK4, so I'd love your input.

**Comment by bobby285271** [comment]
Sorry, I am not sure what you mean here, so to be brief are you not able to build libbismuth on https://github.com/Ashvith10/nixpkgs/commit/0cbf362922d698804536635ce13ded6730b061b0 (or since you mention https://github.com/mesonbuild/meson/issues/7453 are you doing cross compiling stuff here)? Adding `python3` to `nativeBuildInputs` and adding

```nix
postPatch = ''
  patchShebangs src/gen-public-types.py
'';
```

is enough for me to get this built (natively).

**Comment by Ashvith10** [comment]
Apologies, I'll add the logs to make sure that something trying to resolve the meson issue might come across this:
```console
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/gnzpj1xsbl415lvqqxcnl79qr839jihn-libbismuth
source root is libbismuth
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
meson flags: --buildtype=plain         --libdir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/lib --libexecdir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/libexec         --bindir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/bin --sbindir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/sbin         --includedir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/include         --mandir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/share/man --infodir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/share/info         --localedir=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/share/locale         -Dauto_features=enabled         -Dwrap_mode=nodownload         --prefix=/nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1  
The Meson build system
Version: 1.2.0
Source dir: /build/libbismuth
Build dir: /build/libbismuth/build
Build type: native build
Project name: libbismuth
Project version: 1.0.0
C compiler for the host machine: gcc (gcc 12.3.0 "gcc (GCC) 12.3.0")
C linker for the host machine: gcc ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wdate-time: YES 
Compiler for C supports arguments -Werror=format-security -Werror=format=2: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Werror=incompatible-pointer-types: YES 
Compiler for C supports arguments -Werror=missing-declarations: YES 
Compiler for C supports arguments -Werror=overflow: YES 
Compiler for C supports arguments -Werror=return-type: YES 
Compiler for C supports arguments -Werror=shift-count-overflow: YES 
Compiler for C supports arguments -Werror=shift-overflow=2: YES 
Compiler for C supports arguments -Werror=implicit-fallthrough=3: YES 
Compiler for C supports arguments -Wformat-nonliteral: YES 
Compiler for C supports arguments -Wformat-security: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wmaybe-uninitialized: YES 
Compiler for C supports arguments -Wmissing-field-initializers: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wmissing-noreturn: YES 
Compiler for C supports arguments -Wnested-externs: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wno-sign-compare: YES 
Compiler for C supports arguments -Wno-strict-aliasing: YES 
Compiler for C supports arguments -Wno-unused-parameter: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wredundant-decls: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wswitch-default: YES 
Compiler for C supports arguments -Wswitch-enum: YES 
Compiler for C supports arguments -Wtype-limits: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused-function: YES 
Found pkg-config: /nix/store/bhn19xy6sva5vf6nzz5szljdyyvlnrib-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Program glib-compile-resources found: YES (/nix/store/84i5h9dhivs5j80k70nwz5446bvlxaax-glib-2.76.4-dev/bin/glib-compile-resources)
Configuring bis-version.h using configuration
Program glib-mkenums found: YES (/nix/store/84i5h9dhivs5j80k70nwz5446bvlxaax-glib-2.76.4-dev/bin/glib-mkenums)
Program glib-mkenums found: YES (/nix/store/84i5h9dhivs5j80k70nwz5446bvlxaax-glib-2.76.4-dev/bin/glib-mkenums)
Program glib-mkenums found: YES (/nix/store/84i5h9dhivs5j80k70nwz5446bvlxaax-glib-2.76.4-dev/bin/glib-mkenums)
Program glib-mkenums found: YES (/nix/store/84i5h9dhivs5j80k70nwz5446bvlxaax-glib-2.76.4-dev/bin/glib-mkenums)
Program gen-public-types.py found: YES (/build/libbismuth/src/gen-public-types.py)
Found pkg-config: /nix/store/bhn19xy6sva5vf6nzz5szljdyyvlnrib-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Run-time dependency gio-2.0 found: YES 2.76.4
Run-time dependency gtk4 found: YES 4.10.4
Run-time dependency glib-2.0 found: YES 2.76.4
Run-time dependency fribidi found: YES 1.0.13
Library m found: YES
Configuring config.h using configuration
Checking if "ld_supports_version_script" : links: YES 
Run-time dependency gobject-introspection-1.0 found: YES 1.76.1
Dependency gobject-introspection-1.0 found: YES 1.76.1 (cached)
Program g-ir-scanner found: YES (/nix/store/nvianfrmvnlkpzz5b9yibjcgmzwwsbcq-gobject-introspection-1.76.1-dev/bin/g-ir-scanner)
Dependency gobject-introspection-1.0 found: YES 1.76.1 (cached)
Program g-ir-compiler found: YES (/nix/store/nvianfrmvnlkpzz5b9yibjcgmzwwsbcq-gobject-introspection-1.76.1-dev/bin/g-ir-compiler)
Program vapigen found: YES (/nix/store/n60dn0m5w94pxj80n4ih62k77ky5jjks-vala-0.56.9/bin/vapigen)
Build targets in project: 11

libbismuth 1.0.0

  Options
    Introspection: True
    Vapi         : True

  User defined options
    auto_features: enabled
    bindir       : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/bin
    buildtype    : plain
    includedir   : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/include
    infodir      : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/share/info
    libdir       : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/lib
    libexecdir   : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/libexec
    localedir    : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/share/locale
    mandir       : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/share/man
    prefix       : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1
    sbindir      : /nix/store/gnhrbc06hqxhja7bi9c6g8xpgx0a7x77-bismuth-1.6.1/sbin
    wrap_mode    : nodownload

Found ninja-1.11.1 at /nix/store/sxdnfgd4708mzaa5b0zcn8agpysyhmzy-ninja-1.11.1/bin/ninja
meson: enabled parallel building
meson: enabled parallel installing
@nix { "action": "setPhase", "phase": "buildPhase" }
building
build flags: -j8
[1/45] Generating src/bis-resources_h with a custom command
[2/45] Generating src/bis-resources_c with a custom command
[3/45] Generating src/bis-enums-private.h with a custom command (wrapped by meson because command contains newlines, to capture output)
[4/45] Generating src/bis-enums-private.c with a custom command (wrapped by meson because command contains newlines, to capture output)
[5/45] Generating src/bis-enums.c with a custom command (wrapped by meson because command contains newlines, to capture output)
[6/45] Generating src/bis-enums.h with a custom command (wrapped by meson because command contains newlines, to capture output)
[7/45] Generating src/bis-public-types.c with a custom command (wrapped by meson to capture output)
FAILED: src/bis-public-types.c 
/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/bin/meson --internal exe --capture src/bis-public-types.c -- /build/libbismuth/src/gen-public-types.py ../src/bis-animation.h ../src/bis-animation-target.h ../src/bis-animation-util.h ../src/bis-bin.h ../src/bis-carousel.h ../src/bis-carousel-indicator-dots.h ../src/bis-carousel-indicator-lines.h ../src/bis-latch.h ../src/bis-latch-layout.h ../src/bis-latch-scrollable.h ../src/bis-deprecation-macros.h ../src/bis-easing.h ../src/bis-enum-list-model.h ../src/bis-lapel.h ../src/bis-fold-threshold-policy.h ../src/bis-album.h ../src/bis-main.h ../src/bis-navigation-direction.h ../src/bis-spring-animation.h ../src/bis-spring-params.h ../src/bis-hugger.h ../src/bis-swipe-tracker.h ../src/bis-swipeable.h ../src/bis-timed-animation.h src/bis-version.h src/bis-enums.h
Traceback (most recent call last):
  File "/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/bin/meson", line 9, in <module>
    sys.exit(main())
  File "/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 294, in main
    return run(sys.argv[1:], launcher)
  File "/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 282, in run
    return run_script_command(args[1], args[2:])
  File "/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/lib/python3.10/site-packages/mesonbuild/mesonmain.py", line 223, in run_script_command
    return module.run(script_args)
  File "/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/lib/python3.10/site-packages/mesonbuild/scripts/meson_exe.py", line 122, in run
    return run_exe(exe)
  File "/nix/store/0a1194i61f8smpdrrqz2xm0g04vq01n3-meson-1.2.0/lib/python3.10/site-packages/mesonbuild/scripts/meson_exe.py", line 66, in run_exe
    p = subprocess.Popen(cmd_args, env=child_env, cwd=exe.workdir,
  File "/nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/lib/python3.10/subprocess.py", line 1751, in _execute_child
    self._posix_spawn(args, executable, env, restore_signals,
  File "/nix/store/wlxpsdzfvdanfzh704qmgyzb42qvy4fr-python3-3.10.12/lib/python3.10/subprocess.py", line 1696, in _posix_spawn
    self.pid = os.posix_spawn(executable, args, env, **kwargs)
FileNotFoundError: [Errno 2] No such file or directory: '/build/libbismuth/src/gen-public-types.py'
[8/45] Compiling C object src/libbismuth-1.so.1.p/meson-generated_.._bis-enums-private.c.o
[9/45] Compiling C object src/libbismuth-1.so.1.p/meson-generated_.._bis-resources.c.o
[10/45] Compiling C object src/libbismuth-1.so.1.p/bis-animation-util.c.o
[11/45] Compiling C object src/libbismuth-1.so.1.p/bis-bin.c.o
[12/45] Compiling C object src/libbismuth-1.so.1.p/bis-animation-target.c.o
[13/45] Compiling C object src/libbismuth-1.so.1.p/meson-generated_.._bis-enums.c.o
[14/45] Compiling C object src/libbismuth-1.so.1.p/bis-animation.c.o
ninja: build stopped: subcommand failed.
```

**Comment by Ashvith10** [comment]
So far, that fixes the build issue with libbismuth, and the demo app works just fine. But now there's another roadblock, @bobby285271. It's about the theming. I've added the tau-helium-gtk-theme in the `buildInputs` in libhelium, and I was expecting that `gappsWrapperArgs` would work the fine if I add libhelium as a `buildInputs` dependency for `skiff-desktop`. But I'm forced to use `tau-helium-gtk-theme` again?

**Comment by bobby285271** [comment]
> But I'm forced to use tau-helium-gtk-theme again

Ugh, so what is the issue right now (what is expected and what is not expected and what do you wish to achieve)? The app looks quite good on https://github.com/Ashvith10/nixpkgs/commit/0cbf362922d698804536635ce13ded6730b061b0.

> I've added the tau-helium-gtk-theme in the buildInputs in libhelium, and I was expecting that gappsWrapperArgs would work the fine if I add libhelium as a buildInputs dependency for skiff-desktop

This shouldn't work I think. If skiff-desktop hardcodes GTK theme, then passing the theme to `XDG_DATA_DIRS` in its `gappsWrapperArgs` should be enough, if libhelium hardcodes GTK theme, personally I will probably do:

```vala
var data_dirs = Environment.get_variable ("XDG_DATA_DIRS");
Environment.set_variable ("XDG_DATA_DIRS", "%s:%s".printf ("/path/to/your/theme/share", data_dirs), true);
```

(I imagine putting this before `base.startup ();`, but this probably will be best to ask upstream for suggestions)

**Comment by Ashvith10** [comment]
@bobby285271 thanks for the response. I'll try to simplify what I'm asking about  - maybe I am in the wrong here, but I've already done:
```nix
preFixup = ''
  gappsWrapperArgs+=(
    --prefix XDG_DATA_DIRS : "${tau-helium-gtk-theme}/share"
  )
'';
```
in the **libhelium** Nix file, then can I do something like:
```nix
preFixup = ''
  gappsWrapperArgs+=(
    --prefix XDG_DATA_DIRS : "${libhelium}/share"
  )
'';
```
in **skiff-desktop** instead of having to re-define:
```nix
```nix
preFixup = ''
  gappsWrapperArgs+=(
    --prefix XDG_DATA_DIRS : "${tau-helium-gtk-theme}/share"
  )
'';
```
?

**Comment by bobby285271** [comment]
> ?

I think no, you can give it a try :joy: 

> libhelium is supposed to be the buildInput, wherein, it enforces the theme at runtime through it's tau-helium-gtk-theme dependency.

Yeah I don't think we can wrap libraries here so this is why I am thinking of https://github.com/NixOS/nixpkgs/issues/250997#issuecomment-1692998490.

**Comment by Ashvith10** [comment]
@bobby285271 I guess I'm going the way I originally intended. Perhaps someone with more GTK app development and packaging experience than me can review the branch ?

**Comment by Ashvith10** [comment]
libhelium branch is ready. Looking for maintainers to review this branch before I push a PR.
