### ISSUE TITLE
Add channel-critical tests for all display managers

### ISSUE THREAD

**Issue by primeos** [NixOS/nixpkgs#25131]
## Motivation

Add channel-critical tests for all display managers in order to prevent unnecessary breakage through side effects, mistakes, etc.

## TODO (volunteers wanted :smile:)

Add tests for the following display managers
- [ ] lightdm
- [x] slim (dc87b5587e3fb39e96e6b965a26f324daf7508f8 added a test)

Fix the tests for the following DMs:
- [ ] gdm

## Current situation (2017-04-29)

- [x] SDDM
  - [x] Test: [sddm.nix](https://github.com/NixOS/nixpkgs/blob/352e335f3d643b84f34d5c102a4828712924a267/nixos/tests/sddm.nix)
  - [x] Release-critical: [release-combined.nix#L95](https://github.com/NixOS/nixpkgs/blob/352e335f3d643b84f34d5c102a4828712924a267/nixos/release-combined.nix#L95)
- [ ] LightDM
  - [x] Test: [lightdm.nix](https://github.com/NixOS/nixpkgs/blob/9153d8ed640e4df38422cad89a72a43c9df9f057/nixos/tests/lightdm.nix)
  - [ ] Release-critical: [release-combined.nix#L69](https://github.com/NixOS/nixpkgs/blob/9153d8ed640e4df38422cad89a72a43c9df9f057/nixos/release-combined.nix#L69) (disabled)
- [x] SLiM
  - [x] Test: [slim.nix](https://github.com/NixOS/nixpkgs/blob/dc87b5587e3fb39e96e6b965a26f324daf7508f8/nixos/tests/slim.nix)
  - [x] Release-critical: [release-combined.nix#L97](https://github.com/NixOS/nixpkgs/blob/dc87b5587e3fb39e96e6b965a26f324daf7508f8/nixos/release-combined.nix#L97)
- [ ] GDM
  - [x] Test: [gnome3-gdm.nix](https://github.com/NixOS/nixpkgs/blob/ce953d0bc90f17dfc35f0e498cfe192bfad0cc20/nixos/tests/gnome3-gdm.nix)
  - [ ] Release-critical: no (only a `Gnome` test with the fake/auto DM)

**Comment by cleverca22** [comment]
lightdm: https://github.com/NixOS/nixpkgs/blob/master/nixos/release-combined.nix#L76

the test is currently commented out

gdm: its not in that list currently

slim: no test currently exists

**Comment by coretemp** [comment]
If the test for sddm is already operational it should also be testing in cases where people have mixed up Qt versions. Mixed up Qt versions shouldn't lead to sddm failing, because that is a complete system failure. The impact any one user should have should be limited to their own user accounts, because otherwise it becomes a DoS attack vector. 

Imagine working at a large company with a shared NFS Nix store and then doing something that causes this message. It would result in all users not being able to login anymore, until a system administrator would learn about this particular problem. It seems unworkable.

It might be that I misunderstood the situation, but not being able to login in any desktop environment, because of something a user has done (even if it is the administrator in systemPackages) seems to be something that should be avoided at all cost. 

NixOS configuration in shipped and enabled modules should always go first (unless one starts doing `mkForce`, etc.). This is how I imagine most users would expect the system to work. Details such as mixed Qt versions are the problem of the NixOS system designers and a user (this includes system administrators) should never see this.

**Comment by primeos** [comment]
## Current situation (2020-06-05)

Based on: https://hydra.nixos.org/build/121141339#tabs-constituents

- [:white_check_mark:] SDDM
  - [x] Test
  - [x] Release-critical: `nixos.tests.sddm.default.x86_64-linux`
  - The test uses `autoLogin`, which might not be enough
- [:heavy_check_mark:] LightDM
  - [x] Test
  - [x] Release-critical: `nixos.tests.lightdm.x86_64-linux`
- ~~[ ] SLiM~~: "slim has been removed. Please use a different display-manager"
- [:white_check_mark:] GDM
  - [x] Test
  - [x] Release-critical: `nixos.tests.gnome3{-xorg}.x86_64-linux`
  - There are two tests but both use `autoLogin`, which might not be enough

## Conclusion

Still not perfect but I guess/hope our current tests are sufficient for most cases :)
