### ISSUE TITLE
RFC: "meta" packages for util-linux, procps, and nettools

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#25188]
# RFC
Lots of packages depend on either util-linux, and nettools. Both of these packages are Linux only and there isn't an easy way to port them to macOS. However, most packages that depend on either util-linux or nettools just want one small binary, some of which have macOS equivalents.

My basic proposal is to make "meta" packages for each of these commands and encourage package maintainers to list each one that is needed. In addition, I will create a Darwin package that provides as much of nettools, procps, and utillinux as we can. Any suggestions on other packages that needs similar treatment would be helpful.

## nettools
- **arp(8) (in network_cmds)**
- **hostname(1) (in shell_cmds)**
- **ifconfig(8) (in network_cmds)**
- ipmaddr
- iptunnel
- mii-tool(8)
- nameif(8)
- **netstat(8) (in network_cmds)**
- plipconfig(8)
- **rarp(8) (in network_cmds)**
- **route(8) (in network_cmds)**
- slattach(8)

## util-linux
- addpart(8)
- agetty(8)
- blkdiscard(8)
- blkid(8)
- blockdev(8)
- **cal(1) (in misc_cmds)**
- cfdisk(8)
- chcpu(8)
- **chfn(1) (in system_cmds)**
- chrt(1)
- **chsh(1) (in system_cmds)**
- **col(1) (in text_cmds)**
- **colcrt(1) (in doc_cmds)**
- **colrm(1) (in text_cmds)**
- **column(1) (in text_cmds)**
- delpart(8)
- **dmesg(1) (in system_cmds)**
- eject(1)
- fallocate(1)
- fdformat(8)
- **fdisk(8) (in diskdev_cmds)**
- findfs(8)
- findmnt(8)
- flock(1)
- **fsck(8) (in diskdev_cmds)**
- fsfreeze(8)
- fstab(5)
- fstrim
- **getopt(1) (in shell_cmds)**
- **hexdump(1) (in shell_cmds)**
- hwclock(8)
- ionice(1)
- ipcmk(1)
- **ipcrm(1) (in file_cmds)**
- **ipcs(1) (in file_cmds)**
- isosize(8)
- **kill(1) (in shell_cmds)**
- **last(1) (in adv_cmds)**
- ldattach(8)
- **logger(1) (in remote_cmds)**
- **login(1) (in system_cmds)**
- **look(1) (in text_cmds)**
- losetup(8)
- lsblk(8)
- lscpu(1)
- lsipc(1)
- lslocks(8)
- lslogins(1)
- lsns(8)
- mcookie(1)
- **mesg(1) (in basic_cmds)**
- mkfs(8)
- mkswap(8)
- **more(1) (in man)**
- **mount (in diskdev_cmds)**
- mountpoint(1)
- namei(1)
- **newgrp(1) (in system_cmds)**
- **nologin(8) (in system_cmds)**
- partx(8)
- pivot_root(8)
- prlimit(1)
- raw(8)
- readprofile(8)
- rename(1)
- **renice(1) (in shell_cmds)**
- resizepart(8)
- **rev(1) (in text_cmds)**
- runuser(1)
- **script(1) (in shell_cmds)**
- scriptreplay(1)
- setarch(8)
- setpriv(1)
- setsid(1)
- setterm(1)
- sfdisk(8)
- **su(1) (in shell_cmds)**
- sulogin(8)
- swaplabel(8)
- swapoff(8)
- swapon(8)
- switch_root(8)
- taskset(1)
- **ul(1) (in text_cmds)**
- **umount(8) (in diskdev_cmds)**
- utmpdump(1)
- uuidd(3)
- uuidgen(1)
- **vipw(8) (in system_cmds)**
- **wall(1) (in remote_cmds)**
- wdctl(8)
- **whereis(1) (in shell_cmds)**
- wipefs(8)
- **write(1) (in basic_cmds)**

## procps
- free(1)
- **pgrep(1) (in adv_cmds)**
- pidof(1)
- **pkill(1) (in adv_cmds)**
- pmap(1)
- **ps(1) (in adv_cmds)**
- pwdx(1)
- slabtop(1)
- **sysctl(8) (in system_cmds)**
- tload(1)
- **top(1) (in top)**
- **uptime(1) (in shell_cmds)**
- vmstat(8) (vm_stat is available?)
- **w(1) (in shell_cmds)**
- watch(1) (apparently compiles on macOS?)

# Tasks
- [ ] package opensource.apple.com
  - [ ] adv_cmds
  - [x] basic_cmds
  - [ ] doc_cmds
  - [ ] diskdev_cmds
  - [ ] file_cmds (current broken)
  - [ ] man
  - [ ] network_cmds (currently broken)
  - [ ] remote_cmds
  - [ ] shell_cmds (currently broken)
  - [ ] system_cmds (see facebook/xcbuild#188)
  - [ ] text_cmds
  - [ ] top
- [ ] create meta-drvs for each output of:
  - [ ] nettools (see list above)
  - [ ] util-linux (see list above)
  - [ ] procps (see list above)
- [ ] rename compatibility drvs
  - [ ] util-linux + procps -> unixtools
  - [ ] remove utillinux [refs](https://github.com/NixOS/nixpkgs/search?q=utillinux) (unless specifically necessary)
  - [ ] remove procps [refs](https://github.com/NixOS/nixpkgs/search?q=procps) (unless specifically necessary)
- [ ] create darwin compatibility drvs
  - [ ] network_cmds + shell_cmds = nettools
  - [ ] adv_cmds + basic_cmds + diskdev_cmds + shell_cmds + system_cmds + text_cmds = unixtools

**Comment by Mic92** [comment]
As far as I understood `stdenv` is used to cover platform abstraction. Would be such meta-packages also fit into this scope?

**Comment by matthewbauer** [comment]
Closing in favor of #37840.

**Comment by dtzWill** [comment]
Hmm, what about tools like `getconf`, `getent`, `iconv`, `locale` (and possibly others in `glibc.bin`)?

I'm not sure if these are used on Darwin or not, but I've been looking at making a `libc-utils` or similar to handle them for compatibility between glibc/musl, and this seemed the best place for that discussion to start O:).

**Comment by matthewbauer** [comment]
```getconf```, ```iconv```, and ```locale``` are in the POSIX standard:

- http://pubs.opengroup.org/onlinepubs/9699919799/utilities/getconf.html
- http://pubs.opengroup.org/onlinepubs/9699919799/utilities/iconv.html
- http://pubs.opengroup.org/onlinepubs/9699919799/utilities/locale.html

```getent``` is not however.

```glibc``` should be in the stdenv right? It would be good to put these in the macOS stdenv as well though.

**Comment by dtzWill** [comment]
I suppose the question is where do these come from? musl doesn't include them, is this something that should be provided as part of our "libc" abstraction or gathered elsewhere?

i was asking about Darwin (or any other platform, really), in case the answer helped inform the design used to address this.

**Comment by matthewbauer** [comment]
Hopefully all Linux can use "glibc.bin" ? Here is how I would implement it with unix-tools:

```
  getconf = singleBinary "getconf" {
    linux = pkgs.glibc.bin;
    darwin = pkgs.darwin.system_cmds;
  };
  iconv = singleBinary "iconv" {
    linux = pkgs.glibc.bin;
  };
  locale = singleBinary "locale" {
    linux = pkgs.glibc.bin;
  };
```

Basically they should be tied to the kernel, not the ABI/libc.
