### ISSUE TITLE
sudo-rs tracking issue

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nixpkgs#253465]
# sudo-rs is coming to nixos

The roadmap
- [x] sudo-rs packaged (https://github.com/NixOS/nixpkgs/issues/252193)
- [x] sudo module adjusted to work with current sudo-rs (https://github.com/NixOS/nixpkgs/pull/253876)
- [x] all patches upstreamed
  - [x] skip self check when run as root (https://github.com/memorysafety/sudo-rs/pull/772)
- [ ] sudo-rs implements all features needed for basic nixos sudo config
  - [ ] $feature ($sudo-rs issue)
  - [x] SETENV/NOSETENV (https://github.com/memorysafety/sudo-rs/issues/760)
  - [x] https://github.com/memorysafety/sudo-rs/issues/61
  - [x] `--prompt`/`-p` is used by several tools, inculding `nixos-rebuild-ng` (https://github.com/trifectatechfoundation/sudo-rs/issues/842)
- [ ] sudo-rs and sudo have feature parity as far as nixpkgs is concerned

**Comment by Nyabinary** [comment]
What patches need to be upstreamed?

**Comment by mkg20001** [comment]
@Nyabinary added

**Comment by yorickvP** [comment]
Another minor difference: It looks like sudo-rs does not support wildcards in arguments, opting to interpret them as literal wildcards instead

**Comment by squell** [comment]
The [skip self check when run as root](https://github.com/NixOS/nixpkgs/blob/9b7c14b3504abe9d2201f5a8dd5774be2aaefb4e/pkgs/tools/security/sudo-rs/default.nix#L28) has been adopted by the sudo-rs team: https://github.com/memorysafety/sudo-rs/pull/772.

**Comment by squell** [comment]
> Another minor difference: It looks like sudo-rs does not support wildcards in arguments, opting to interpret them as literal wildcards instead

@yorickvP is correct, we actually actively removed that functionality here: https://github.com/memorysafety/sudo-rs/pull/334 (in technical terms, changing the matcher for arguments from a `glob::Pattern` into a `Option<Box<[String]>>`).

**Comment by mkg20001** [comment]
> Another minor difference: It looks like sudo-rs does not support wildcards in arguments, opting to interpret them as literal wildcards instead

According to https://github.com/memorysafety/sudo-rs/issues/333 it still works in the config, where it's necesarry.

In the shell, resolving wildcards should be the shell's responsibility. Bash will likely already do it for you if you un-quote the argument.

**Comment by r-vdp** [comment]
Added https://github.com/trifectatechfoundation/sudo-rs/issues/842 to the list.

**Comment by squell** [comment]
Note: latest release (0.2.5.) incorporate all the closed issues in this tracking issue.

**Comment by leana8959** [comment]
Hello,

I noticed that `sudo-rs` (version 0.2.6) doesn't like the `--version` flag used with environment variables:
```sh
$ sudo --version
--version cannot be used together with environment variable
usage: sudo -h | -K | -k | -V
usage: sudo -v [-BknS] [-g group] [-u user]
usage: sudo -l [-BknS] [-g group] [-U user] [-u user] [command [arg ...]]
usage: sudo [-BknS] [-D directory] [-g group] [-u user] [-i | -s] [command [arg ...]]
usage: sudo -e [-BknS] [-D directory] [-g group] [-u user] file ...
```

Is this a known issue?

I can confirm that `sudo` (version 1.9.17) accepts this flag just fine.

**Comment by isitreallyalive** [comment]
I don't believe this is a known issue, or at least I can't find any mention of it. Perhaps report it upstream?

**Comment by leana8959** [comment]
Hmm, I asked here because the error message makes me wonder if NixOS is causing this by how the setuid binaries are wrapped. Could this be the case ?

**Comment by squell** [comment]
> Hello,
> 
> I noticed that `sudo-rs` (version 0.2.6) doesn't like the `--version` flag used with environment variables:
> 
> $ sudo --version
> --version cannot be used together with environment variable
> usage: sudo -h | -K | -k | -V
> usage: sudo -v [-BknS] [-g group] [-u user]
> usage: sudo -l [-BknS] [-g group] [-U user] [-u user] [command [arg ...]]
> usage: sudo [-BknS] [-D directory] [-g group] [-u user] [-i | -s] [command [arg ...]]
> usage: sudo -e [-BknS] [-D directory] [-g group] [-u user] file ...
> 
> Is this a known issue?
> 
> I can confirm that `sudo` (version 1.9.17) accepts this flag just fine.

👋 This is not a 'known issue' (in the sense that it is known behaviour but not known to be an issue). I think it is pretty harmless to let the `--version` or `--help` flags override/ignore any other command arguments.
