### ISSUE TITLE
CVE-2023-4863 (libwebp heap buffer overflow) tracking

### ISSUE THREAD

**Issue by delroth** [NixOS/nixpkgs#254798]
Filing this issue to track [CVE-2023-4863](https://chromereleases.googleblog.com/2023/09/stable-channel-update-for-desktop_11.html) related actions in nixpkgs. Feel free to send questions my way and/or contribute via comments in this issue!

## What's CVE-2023-4863

A buffer overflow in `libwebp` which allows a malicious actor to potentially get code execution in software that displays a specially crafted image file. This impacts pretty much all web browsers, as well as other software which might process or display untrusted images (image editing software, email clients, chat clients, social media clients, etc.). Chrome has rated this vulnerability as **critical severity** and has indicated that they have evidence some actors are already exploiting it in the wild.

This vulnerability was very shortly referred to as CVE-2023-5129, but that second CVE for the same vulnerability has since been withdrawn.

## Current status

Firefox and Chromium are not vulnerable anymore as of 2023-09-16 in `unstable` and `23.05`. Direct dependents of the system `libwebp` are also not vulnerable anymore. Some applications bundle their own version of libwebp instead of using the system version (including some other web browsers in nixpkgs: Brave, Tor Browser, etc.). Each of these need to be updated separately by nixpkgs maintainers. See below for a list of all the known applications that need an update and their status.

## How to help

- Review/merge any nixpkgs PR that you see pending in the task list below.
- Help figure out a course of action for [yet untriaged packages](https://docs.google.com/spreadsheets/d/1IiTQDwAM1oU3V8Td3qZytIUsPNYo_34r6Y18fLVzkUM/edit#gid=0). Report your findings and suggested course of action in a comment here, and I'll update the sheet and the task list below.
- If you have an idea of how to fix/address the vulnerability in any of the packages listed in the task list below, don't hesitate to post a comment here and send pull requests! Feel free to cc me on PRs so I can make sure they're tracked and they don't get lost.

## Task list

- [x] libwebp is updated in staging-next (unstable: https://github.com/NixOS/nixpkgs/pull/254775, 23.05: https://github.com/NixOS/nixpkgs/pull/254789)
  - [x] This will make it to master via https://github.com/NixOS/nixpkgs/pull/253854 - @vcunat said likely this weekend.
  - [x] We need to merge staging-23.05 to release-23.05.  That should also finish this week: https://github.com/NixOS/nixpkgs/pull/254997
- [x] electron is also vulnerable. Upstream is making new releases on all their supported branches to include the patch.
  - [x] electron 26 bumped in master (#254816).
  - [x] electron 25 bumped in master (#255069).
  - [x] electron 24 bumped in master (#255069).
  - [x] electron 22 bumped in master (#255069).
  - [x] electron 26 bumped in 23.05 (#254819).
  - [x] electron 25 bumped in 23.05 (#255072).
  - [x] electron 24 bumped in 23.05 (#255072).
  - [x] electron 22 bumped in 23.05 (#255072).
- [ ] We should figure out what else might be vendoring libwebp. Not sure if there's tooling for this? List of derivations to investigate further and possibly patch:
  - [List of stuff found to vendor libwebp + triaging status](https://docs.google.com/spreadsheets/d/1IiTQDwAM1oU3V8Td3qZytIUsPNYo_34r6Y18fLVzkUM/edit#gid=0)
  - [x] High risk stuff (mail clients, IM clients, web browsers)
    - [x] armcord
    - [x] caprine-bin (#257372, #257472)
    - [x] discord (#256943, #256994)
      - [x] Darwin version: #257496 / #257716
    - [x] fluffychat (https://github.com/NixOS/nixpkgs/pull/257166)
    - [x] gitter (#255784, #255786)
    - [x] mailspring
    - [x] mattermost-desktop (#257162 / #257243)
    - [x] mautrix-whatsapp (#256178 / 23.05 #256209)
    - [x] microsoft-edge (#256223 / #256595)
    - [x] mullvad-browser (#255078 / #255106)
    - [x] palemoon-bin (#257126, #257614)
    - [x] rocketchat-desktop (#255910 / #257128)
    - [x] signal-desktop (#255129, #255139)
    - [x] signal-desktop-beta (#256435 / #257169)
    - [x] slack (#257135 / #257149)
    - [x] threema-desktop (embedded electron not used)
    - [x] tor-browser-bundle-bin (#255076 / #255105)
    - [x] tutanota-desktop (#255335 / #255888)
  - [ ] Libs that other stuff might depend on
    - [x] flutter
    - [x] libcef (#256001 / #256003)
    - [x] opencv (#256444 / #257726)
    - [x] qt5.qtimageformats (https://github.com/NixOS/nixpkgs/pull/255044 / https://github.com/NixOS/nixpkgs/pull/255432)
    - [ ] qtwebengine (darwin only, maybe?)
    - [x] smooth (#255994 / #256182)
  - [x] darktable (https://github.com/NixOS/nixpkgs/issues/254798#issuecomment-1717129891)
  - [ ] golden-cheetah-bin: ships a vulnerable prebuilt libwebp (cc: @gador @adamcstephens)
  - [ ] koreader: ships a vulnerable prebuilt libwebp (cc: @contrun @neonfuz)
  - [x] libreoffice (https://github.com/NixOS/nixpkgs/issues/254798#issuecomment-1717798614)
  - [ ] localsend: ships a vulnerable prebuilt libwebp (cc: @sikmir)
  - [ ] obs-studio (https://github.com/NixOS/nixpkgs/issues/254798#issuecomment-1719795560)
  - [ ] rigsofrods-bin (ships a vulnerable prebuilt libwebp (cc: @wegank))
  - [x] Anything Rust that depends (transitively or not) on libwebp-sys2 < v0.1.8
    - libwebp-sys2 might silently decide to build its vendored version, if it can't find system libwebp or if the `static` crate feature is enabled.
    - [x] gst_all_1.gst-plugins-rs (https://github.com/NixOS/nixpkgs/pull/254915)
    - [x] catppuccin-catwalk (https://github.com/NixOS/nixpkgs/pull/254911)
  - [x] Anything Rust that depends (transitively or not) on libwebp-sys < v0.9.3
    - Linking against system webp is intentionally not supported: https://github.com/NoXF/libwebp-sys/issues/17
    - [x] oculante #255247 
  - [ ] .NET software that uses SkiaSharp. Upstream has yet to release a fixed version. (https://github.com/mono/SkiaSharp/issues/2608)
    - [ ] avalonia-ilspy
    - [ ] BeatSaberModManager
    - [ ] denaro
    - [ ] galaxy-buds-client
    - [ ] jellyfin
    - [ ] mission-planner
    - [ ] mqttmultimeter
    - [ ] opentracker
    - [ ] openutau
    - [ ] ryujinx
    - [ ] scarab
    - [ ] wasabiwallet
  - [ ] Go software linking with https://github.com/chai2010/webp (https://github.com/chai2010/webp/issues/61, https://github.com/bep/gowebp/issues/7) - broken down per vulnerable lib
    - [ ] https://github.com/chai2010/webp (unmaintained, likely never getting patched - action should be getting upstream to migrate away)
      - [x] hydron (#255959 / #256181)
      - [x] mautrix-whatsapp (https://github.com/mautrix/whatsapp/issues/650)
    - [ ] https://github.com/bep/gowebp (https://github.com/bep/gowebp/issues/7)
      - [ ] hugo
  - [ ] Godot related derivations: these should be unvendored (capability already exists in the build system).
    - [ ] godot_4
    - [ ] godot3
    - [ ] godot3-server
    - [ ] godot3-headless
    - [ ] godot3-export-templates
    - Built using Godot
      - [ ] lorien
      - [ ] oh-my-git
  - [ ] Electron apps where we ship upstream binaries instead of using nixpkgs electron
    - Best course of action: upstream should update to electron >= 26.2.1, >= 25.8.1, >= 24.8.3, or >= 22.3.24 and tag a new release
    - [ ] atom
    - [ ] hakuneko
    - [ ] hyper
    - [ ] indigenous-desktop
    - [ ] joplin-desktop
    - [ ] keeweb (unmaintained, mark as insecure?)
    - [ ] keybase-gui
    - [ ] insomnia
    - [ ] mullvad-vpn
    - [ ] simplenote

## Notes

- For derivations that vendor a vulnerable libwebp, priority list of preferred action to take:
  - De-vendor libwebp and use the version from nixpkgs. (Difficult/impossible for binary provenance derivations.)
  - Update to a new version from upstream that has a more recent libwebp patched for the vulnerability (TODO: how to check?)
  - Mark as `knownVulnerable` at some point if upstream can't be convinced to make a new release.
- List of all software in nixpkgs known to contain libwebp: https://gist.github.com/delroth/a49ce318c4a2c28ec3d7c8bc4adb9b61

**Comment by delroth** [comment]
https://github.com/electron/electron/releases/tag/v26.2.1 is now out

**Comment by theotheroracle** [comment]
i think one way you could check for vendored webp is with nix-locate, searching for libwebp.so, for example darktable might be vulnerable :
```
darktable.out                                    35,056 x /nix/store/1gzd3ccrpay6gxzcpdgyw32rxbjx14hg-darktable-4.4.1/lib/darktable/plugins/imageio/format/libwebp.so
```

**Comment by delroth** [comment]
> i think one way you could check for vendored webp is with nix-locate, searching for libwebp.so

Thanks, that's indeed useful! I think the most common case though would be bundling the code and linking statically with the lib, which wouldn't necessarily be found by this - but maybe I'm just too pessimistic :)

**Comment by delroth** [comment]
darktable: links with libwebp, the libwebp.so is an internal plugin and is not a vendored version.

**Comment by delroth** [comment]
koreader: binary provenance, ships a vulnerable prebuilt libwebp (cc: @contrun @neonfuz).

**Comment by delroth** [comment]
localsend: binary provenance, ships a vulnerable prebuilt libwebp (cc: @sikmir)

**Comment by delroth** [comment]
golden-cheetah-bin: binary provenance, ships a vulnerable prebuilt libwebp (cc: @gador @adamcstephens)

**Comment by yu-re-ka** [comment]
libreoffice sources file lists a libwebp-1.3.0.tar.gz (or libwebp-1.2.4.tar.gz for libreoffice-still)

**Comment by yu-re-ka** [comment]
`oculante`, `gst_all_1.gst-plugins-rs` vendor libwebp via the rust crate libwebp-sys2

**Comment by delroth** [comment]
> `oculante`, `gst_all_1.gst-plugins-rs` vendor libwebp via the rust crate libwebp-sys2

Ugh, and good luck finding all the things that end up transitively depending on that crate I guess. https://github.com/qnighy/libwebp-sys2-rs/pull/21 I suggested they file a GHSA so dependabot can go and do its thing, but it might still take a while to trickle down through dependents.

Anyway, libwebp-sys2 version 0.1.8 looks like it's fixed.

**Comment by delroth** [comment]
> libreoffice sources file lists a libwebp-1.3.0.tar.gz (or libwebp-1.2.4.tar.gz for libreoffice-still)

There's also `++ optionals (lib.versionAtLeast (lib.versions.majorMinor version) "7.4") [ libwebp ];` and I can't seem to find the vendored code by grepping for strings in the binaries. Would need further checking, but I'm tempted to say libreoffice is fine?

**Comment by yu-re-ka** [comment]
The libwebp-sys2 crate also will link against the system libwebp if it is found.
I'm currently compiling a list of rust packages that use libwebp-sys2.

**Comment by delroth** [comment]
> The libwebp-sys2 crate also will link against the system libwebp if it is found.

But since it transparently falls back to the vendored source, I'm going to assume most Rust programs in nixpkgs haven't bothered declaring libwebp (and pkg-config?) as buildInputs... But at least that might give us a lever to patch without requiring an upstream cargo deps bump?

**Comment by yu-re-ka** [comment]
...unless the application has enabled the libwebp-sys2 'static' feature, then it will skip looking for the system one and build its own 🙃

**Comment by yu-re-ka** [comment]
Unsure how to deal with the libwebp-sys2 things, which would still be vulnerable for cross-compiling and pkgsStatic. Opened an upstream issue: https://github.com/qnighy/libwebp-sys2-rs/issues/23

**Comment by xyzeva** [comment]
Hi!

Sorry for just popping in randomly, are there any publicly available workarounds for this issue currently? I'm on `nixos-unstable`, but it seems like firefox nor others have gotten their version bump on that branch.

**Comment by delroth** [comment]
> Sorry for just popping in randomly, are there any publicly available workarounds for this issue currently? I'm on `nixos-unstable`, but it seems like firefox nor others have gotten their version bump on that branch.

Not really, and as noted in this issue's description relying on the browser's version number is misleading here (because nixpkgs doesn't use the vendored libwebp, so what matters is the version of the libwebp dependency).

If someone wants to write instructions using `replaceDependency` I'll gladly add those to the issue description for future reference.

**Comment by vcunat** [comment]
On the `staging-next` branch we're only missing a few thousand builds per platform right now, so I'd hope for `nixos-unstable` to update tomorrow.

**Comment by delroth** [comment]
> > libreoffice sources file lists a libwebp-1.3.0.tar.gz (or libwebp-1.2.4.tar.gz for libreoffice-still)
> 
> There's also `++ optionals (lib.versionAtLeast (lib.versions.majorMinor version) "7.4") [ libwebp ];` and I can't seem to find the vendored code by grepping for strings in the binaries. Would need further checking, but I'm tempted to say libreoffice is fine?

From the [latest hydra build log for libreoffice](https://nix-cache.s3.amazonaws.com/log/b6wpkxyq2s2kllm61fyz439974jdqpch-libreoffice-7.4.7.2.drv):
```
checking which libwebp to use... external
checking for libwebp... yes
```

So looks like this one is fine.

**Comment by delroth** [comment]
staging-next was merged to master, so users on nixos-unstable should have their browsers patched on the next channel bump.

**Comment by felschr** [comment]
Fixes for Tor Browser & Mullvad Browser:
- https://github.com/NixOS/nixpkgs/pull/255076
- https://github.com/NixOS/nixpkgs/pull/255105
- https://github.com/NixOS/nixpkgs/pull/255078
- https://github.com/NixOS/nixpkgs/pull/255106

**Comment by xyzeva** [comment]
> staging-next was merged to master, so users on nixos-unstable should have their browsers patched on the next channel bump.

Hi!

I use the `nixos-unstable` branch specifically in my flake, any ETA on when that branch will get the update pushed?

**Comment by delroth** [comment]
> I use the `nixos-unstable` branch specifically in my flake, any ETA on when that branch will get the update pushed?

Depends on how fast stuff ends up rebuilding, I'd expect within 1-2 days at the latest. It's all in automation's hand at this point, unless there's somehow a breakage we didn't notice.

**Comment by xyzeva** [comment]
> You can switch to `nixos-unstable-small` which already has it (but might require you to do more rebuilds from source), or follow https://nixpk.gs/pr-tracker.html?pr=254775 for the status of the fix.

I think I might channel-switch for a bit for this fix, thanks for the help!

**Comment by lilyinstarlight** [comment]
Additional packages which have a vendored libwebp that I found on my system via the `grep` that @delroth posted in Matrix:
* slack
* obs-studio (via `libcef.so`)
* openutau (via embedded `libSkiaSharp.so`, also oops this package is mine 🙈)

**Comment by mweinelt** [comment]
Same method as mentioned by Lily, found:

- android-studio
- discord
- idea-community
- vial (via `libqwebp.so`)
- joplin
- jetbrains-jdk-jcef (via `libcef.so`)
- qtimageformats (via `libqwebp.so`)

**Comment by lilyinstarlight** [comment]
I looked more into .NET apps that depend on Avalonia and I've also confirmed these vendor libwebp (all via `libSkiaSharp.{so,dll,dylib}`). I've not confirmed that any of them use the vulnerable version directly, but it seems highly likely they do given a new SkiaSharp release has still not been made since the release of the CVE fix:
* BeatSaberModManager
* alttpr-opentracker
* avalonia-ilspy
* denaro
* galaxy-buds-client
* git-credential-manager
* jellyfin
* mission-planner
* mqttmultimeter
* ryujinx
* scarab
* space-station-14-launcher
* wasabiwallet

**Comment by Janik-Haag** [comment]
same method as hexa and liliy
```
/nix/store/1023znavdaiwqg331hpps8fdm9g4wnnc-qtimageformats-5.15.10/lib/qt-5.15.10/plugins/imageformats/libqwebp.so
/nix/store/wj9b8x3z5hiz3djgi65ywvx2l0h1an02-electron-24.8.1/libexec/electron/.electron-wrapped
/nix/store/a80wxcj7xlnd5dxi0pkzf22jvwh48sls-electron-25.7.0/libexec/electron/.electron-wrapped
/nix/store/6n7q31qg5asmj1s4ip4dzdgcxb19n6zj-teams-1.5.00.23861/opt/teams/teams
/nix/store/cm7aqq365rf5qinvivjladgl25imwiy9-signal-desktop-6.30.1/lib/Signal/signal-desktop
/nix/store/sh5gyyfcbp3b46shsfz6gc281yhs63qp-hugo-0.118.2/bin/hugo
```

**Comment by SuperSandro2000** [comment]
Also going to add onlyoffice-bin, libsForQt5.qt5.qtimageformats and remarkable{,2}-toolchain to the naughty vendoring list.

**Comment by mweinelt** [comment]
> currently working on a betterbird update. Not sure about thunderbird and I don't really have the time to check it right now.

If it uses buildMozillaMach it uses our system package.

**Comment by xfix** [comment]
Got a match for "no memory during frame initialization." in `vscodium`, probably not very useful to know due to the fact that it's using a binary directly:

/nix/store/z613gjk28c3q0ypjsdch9vshdlydc9fm-vscodium-1.82.0.23250/lib/vscode/codium

**Comment by delroth** [comment]
I've ran a grep on ~200K Nix store paths from a full Hydra evaluation - here are the results: https://gist.github.com/delroth/a49ce318c4a2c28ec3d7c8bc4adb9b61

Let's start categorizing that a bit and translating it into trackable tasks :) I've already listed all the SkiaSharp dependents. A few other categories I see:
- CEF users
- Vendored Electron users
- Qt libs

**Comment by vcunat** [comment]
For reference, I believe that all supported channels (6) have updated past the `libwebp` patching (the non-vendored one).  This weekend turned out to be a pessimistic estimate.

**Comment by adamcstephens** [comment]
golden-cheetah-bin:

PR to mark insecure: #255339
Also reported upstream: https://github.com/GoldenCheetah/GoldenCheetah/issues/4396

**Comment by vcunat** [comment]
opencv seems like a relatively common package (with multiple versions).  Maybe the maintainer @basvandijk could have a look?

**Comment by delroth** [comment]
High priority things that I think are still yet to be updated:

Chat apps / browsers / mail clients:
- fluffychat (uses vendored flutter < v3.13.4, cc @mkg20001 @gilice)
- gitter (no maintainer / maintainer has deleted their github? upstream seems unmaintained anyway, should be removed?)
- mautrix-whatsapp (vendored via some Go dep, cc @vskilet @ma27 @chvp)
- signal-desktop-beta (cc @cmovcc who took care of Signal, can you maybe have a look?)
- threema-desktop (lib/threema/threema-web - is this even used? since we use nixpkgs electron, cc @WolfangAukang)
- tutanota-desktop (opt/tutanota-desktop/tutanota-desktop - similar to threema-desktop, also cc @WolfangAukang)

**Comment by delroth** [comment]
- mattermost-desktop (share/mattermost-desktop/mattermost-desktop, cc @jokogr)

**Comment by delroth** [comment]
- rocketchat-desktop (cc @gbtb): I think just needs a bump to 3.9.7 for https://github.com/RocketChat/Rocket.Chat.Electron/commit/c7d74c6932a99342804b76f191cb09c1ec5e166d

**Comment by colonelpanic8** [comment]
Yeah removing gutter seems fine

**Comment by chvp** [comment]
There's a mautrix-whatsapp bump here: https://github.com/NixOS/nixpkgs/pull/255504, not sure how I can check whether this is fixed by that PR?

**Comment by delroth** [comment]
> @delroth do you recommend moving FluffyChat from stable -> a git commit temporarily?
> 
> By the way, flutter itself seems to have a bad vendored version. Need to push out 3.13.4.

If cherry-picking the patch is an option it's probably less invasive, if upstream is planning a release in the next 2-3 days I think I wouldn't mind waiting too. If neither of these options apply (or if you don't mind bumping twice in rapid succession if upstream pushes a new release) going to an unstable version SGTM.

**Comment by delroth** [comment]
> @delroth `tutanota-desktop` was updated and merged recently (#255335). Would that count?

Looks like that new version contains https://github.com/tutao/tutanota/commit/e2c9ac1f93bab36f5ffdf869051a29a3167c2a2a which is a proper fix. Thanks for the pointer! Just needs backport to 23.05 now.

**Comment by mweinelt** [comment]
> @delroth `tutanota-desktop` was updated and merged recently (#255335). Would that count?

It was mentioned in the changelog, please read them when updating a package. It will count once the backport to release-23.05 has happened.

**Comment by chvp** [comment]
@delroth I had already reported the issue to mautrix-whatsapp in private to lessen the chance of exploitation (they use the webp dependency to decode webp images and are thus vulnerable). I've had no response yet though.

**Comment by delroth** [comment]
> @delroth I had already reported the issue to mautrix-whatsapp in private to lessen the chance of exploitation (they use the webp dependency to decode webp images and are thus vulnerable). I've had no response yet though.

Heh, I don't think there's much value in reporting this in private (and making coordination/tracking harder) given that it's a publicly disclosed vulnerability already. I noticed you said you'd talk to upstream but couldn't find any trace of that, so I went ahead and filed that bug...

**Comment by delroth** [comment]
Godot (godot3, godot_4, godot3-headless, godot3-server, godot3-export-templates): upstream has merged https://github.com/godotengine/godot/pull/81663 which I think is getting backported to the 3.x branch. But it also appears that, at least for 4.x, libwebp can be unvendored: https://github.com/godotengine/godot/blob/e3e2528ba7f6e85ac167d687dd6312b35f558591/SConstruct#L241

I think that's what we should be doing while waiting for new releases, and this is likely true of many other dependencies that can be unvendored via the same mechanism. cc maintainers: @Twey @shiryel @Rotaerk (please cc me on any fix PR and make sure to backport to 23.05).

**Comment by chvp** [comment]
Fix for mautrix-whatsapp here: https://github.com/NixOS/nixpkgs/pull/256178

**Comment by xyzeva** [comment]
Worth noting `insomnia` is vulnerable, upstream fix was in PR Kong/insomnia#6504, though it hasn't gotten a release yet.

**Comment by cmovcc** [comment]
#256435 is a fix for signal-desktop-beta, thanks @equirosa.

**Comment by risicle** [comment]
:heart: to all who have contributed to this.

**Comment by delroth** [comment]
Explicitly pinging the maintainers for the remaining high-risk use cases:

- @ludovicopiero @wrmilling armcord still uses vulnerable Electron 26.1.0. Please get upstream to fix their security vulnerabilities.
- @ShamrockLee caprine-bin is presumably built by upstream from Electron 24.1.3 from 151 days ago. Please get upstream to fix their security vulnerabilities. (Additionnally, why is this a binary build instead of something we build from source?)
- @MP2E @Scrumplex @Artturin @Infinidoge @jopejoe1 Discord doesn't seem to have an update for this. Unless you have some evidence otherwise, I'm fairly sure it's still vulnerable to this CVE. Please get upstream to fix their security vulnerabilities.
- @mkg20001 @gilice Fluffychat is impacted via some Flutter dep, which is fixed in master (https://groups.google.com/g/flutter-announce/c/b81TwwJkp5w) but not in 23.05. Please figure out how we can avoid having a vulnerable libwebp vendored in your Flutter app on 23.05.
- @toschmidt mailspring uses Electron 17, which is hopelessly out of date, EOL, and insecure. Please get upstream to fix their security vulnerabilities.
- @jokogr mattermost-desktop is out of date in nixpkgs. Their latest release is based on Electron 26.1.0, which is also insecure. Please get upstream to fix their security vulnerabilities.
- @gbtb rocketchat-desktop also needs a bump in release-23.05. I've started the backport process via the master PR, please test it and let me know when it's ready to be merged.
- @equirosa @Mic92 @urandom2 signal-desktop-beta is still vulnerable on 23.05. As mentioned in the master PR a few days ago, this needs a cherry-pick.
- @amaxine @mmahut slack released 4.34.119 12 days ago, presumably containing a fix for this. Please bump master and cherry-pick to 23.05, cc me on the PRs.

Everything in this list that hasn't been updated by Friday 2023-09-29 00:00 UTC will be marked as insecure next weekend.

**Comment by joepie91** [comment]
Also mentioned this on Matrix, but for posterity: SideQuest is also affected (and frequently loads untrusted content). It appears to use a bundled Electron 13, which has not received and will not receive a patch. I've e-mailed the upstream in the hopes that they can update to a newer Electron ASAP.

**Comment by Scrumplex** [comment]
> Discord doesn't seem to have an update for this. Unless you have some evidence otherwise, I'm fairly sure it's still vulnerable to this CVE. Please get upstream to fix their security vulnerabilities.

Using `discordPackage.override {withVencord = true; withOpenASAR = true;}` and then checking the output of `navigator.userAgent` by opening DevTools (Ctrl+Shift+I) 

- `discordPackage = discord-canary;`: `Electron/22.3.24`
- `discordPackage = discord-ptb;`: `Electron/22.3.24`
- `discordPackage = discord;`: `Electron/22.3.12` <- vulnerable?

**Comment by delroth** [comment]
Great, thanks for looking into it! Hopefully they'll roll out that update to the stable branch soon... I guess it's difficult for a small indie developer like them, it's only been 2 weeks since the fix was made available! :-)

**Comment by Artturin** [comment]
`discord` just got updated in master so it's not in nixos-unstable yet.

**Comment by delroth** [comment]
Thanks! I checked 0.0.30 (which is on master and 23.05 as of yesterday) and it seems to be on Electron 22.3.24. Marking as fixed 👍

**Comment by ShamrockLee** [comment]
Thanks for pinning me.

> @ShamrockLee caprine-bin is presumably built by upstream from Electron 24.1.3 from 151 days ago. Please get upstream to fix their security vulnerabilities.

Just created an issue there:
https://github.com/sindresorhus/caprine/issues/2070

> Additionally, why is this a binary build instead of something we build from source?

Because the source build failed the time I tried to package Caprine (some years ago). It's a pain to an build Electron app from source in Nixpkgs.

**Comment by SebTM** [comment]
Regarding Mailspring there is https://github.com/Foundry376/Mailspring/pull/2444, I will ask about their plans to move forwards ✌🏻

**Comment by wrmilling** [comment]
There should be a pre-release with electron 27 for armcord, will dig in tomorrow.

**Comment by contrun** [comment]
Currently we are not building koreader from source (see https://github.com/NixOS/nixpkgs/pull/230938#issuecomment-1646990844 for some efforts). Since the released upstream deb package has not fixed CVE-2023-4863 (https://github.com/koreader/koreader-base/pull/1656 fixed it, but it is not released yet), we have to wait a while for a new koreader release.

**Comment by xyzeva** [comment]
> Great, thanks for looking into it! Hopefully they'll roll out that update to the stable branch soon... I guess it's difficult for a small indie developer like them, it's only been 2 weeks since the fix was made available! :-)

To make it better, I reported them this like 2 weeks ago! They're still working on running the npm command on the stable branch, give them some time!

**Comment by mkg20001** [comment]
fluffychat and flutter updates have been backported now: https://github.com/NixOS/nixpkgs/pull/257166

**Comment by ShamrockLee** [comment]
I made a draft PR that contains the caprine-bin update (#257372), but the updated app turns out to be unusable (sindresorhus/caprine#2070).

**Comment by ShamrockLee** [comment]
> I made a draft PR that contains the caprine-bin update (#257372), but the updated app turns out to be unusable ([sindresorhus/caprine#2074](https://github.com/sindresorhus/caprine/issues/2074)).

The above issue is resolved in Caprine 2.58.3. Please take a look at #257372.

**Comment by delroth** [comment]
@Artturin @Scrumplex it was brought to my attention that the Darwin version for Discord was not bumped in 6 months, and is thus still vulnerable to this libwebp vuln.

If nobody maintains this software can it be removed and/or marked as knownVulnerable? Thanks!

**Comment by vcunat** [comment]
I'd say that after a bit of wait you mark packages as vulnerable and _that_ is the main way of finding out whether someone is really willing to keep it alive.

**Comment by Scrumplex** [comment]
> it was brought to my attention that the Darwin version for Discord was not bumped in 6 months, and is thus still vulnerable to this libwebp vuln.
> 
> If nobody maintains this software can it be removed and/or marked as knownVulnerable? Thanks!

I have bumped them in #257496. The main issue is that r-ryantm isn't helping us out here, as there is no `updateScript` for the darwin packaging. Not sure if any of the other Discord maintainers are using Darwin, but I certainly don't and would need some assistance testing these.

**Comment by ShamrockLee** [comment]
I created mifi/lossless-cut#1726 to remind the LosslessCut upstream to make a new patch release, so that me can update `losslesscut-bin`.

**Comment by OPNA2608** [comment]
`palemoon-bin` is affected, fix: https://github.com/NixOS/nixpkgs/pull/257126

**Comment by delroth** [comment]
All the packages I evaluated as being high-risk have now been taken care of (and most of them did actually get updates, woo! only marked 2 or 3 as insecure). Right now I don't think anyone has the bandwidth to try and track the rest. I'm going to close this bug - if someone does want to take over the remediation for the rest of the impacted packages, feel free to reopen and assign yourself.

(Note however that there is a large overlap between vulnerable to this libwebp vuln and vulnerable to the recent libvpx vuln... so maybe just go help over there instead of reusing this bug.)

**Comment by fabianhjr** [comment]
Unpinning due to closing
