### ISSUE TITLE
CVE-2023-5217 (libvpx heap buffer overflow) tracking

### ISSUE THREAD

**Issue by xyzeva** [NixOS/nixpkgs#258048]
CVE-2023-5217 is a heap buffer overflow in libvpx's VP8 encoder, as many things such as electron and more are being tracked in this issue, so we can fix them in nixpkgs.

This vulnerability is yet to be rated, but we can assume (as its a heap buffer overflow), that it *might* be a big deal.
## Current status

We currently have patched the `libvpx` package with #257941, vendored dependencies are tracked below.

## How to help
  - Review/merge any nixpkgs PR that you see pending in the task list below.
  -  If you have an idea of how to fix/address the vulnerability in any of the packages listed in the task list below, don't hesitate to post a comment here and send pull requests! Feel free to cc me on PRs so I can make sure they're tracked and they don't get lost.

## Task list

- [X] libvpx is updated in master #257941
   -  [X] libvpx is updated in release-23.05 #257960
- [ ] electron needs to be updated to 26.2.4
  - [ ] backport fix to electron_25 (update to 25.8.4)
  - [ ] backport fix to electron_24 (update to 24.8.5)
  - [ ] backport fix to electron_22 (update to 22.3.25)
- [ ] Vendoring
  - [ ] High risk stuff (mail clients, IM clients, web browsers)
      - [ ] signal-desktop needs to be updated to 6.32
        - [ ] signal-desktop-beta needs to be updated to 6.32
      - [ ] rocketchat-desktop
      - [ ] armcord
      - [ ] indigenous-desktop (homepage URL leads to 404, appears to be a chat app)
      - [ ] mattermost-desktop 
      - [ ] threema-desktop
      - [ ] thedesk
      - [ ] gitter
      - [ ] aether (upstream hasnt had a commit since 2021, TODO mark/remove?)
      - [ ] caprine-bin
      - [ ] wire-desktop
      - [ ] keybase-gui
      - [ ] mailspring
      - [ ] brave needs to be updated to 1.58.135 
      - [ ] tor-browser
      - [ ] mullvad-browser
  - [ ] Other stuff
       - [ ] octant-desktop (now [archived](https://github.com/vmware-archive/octant), TODO mark/remove?)
       - [ ] figma-linux
       - [ ] insomnia
       - [ ] freeswitch
       - [ ] losselesscut-bin
       - [ ] popcorntime
       - [ ] snapmaker-luban
       - [ ] keeweb
       - [ ] zotero
       - [ ] polar-bookshelf (homepage link broken)
       - [ ] join-desktop
       - [ ] passky-desktop
       - [ ] isabelle
       - [ ] onlyoffice
       - [ ] jellyseer
       - [ ] yesplaymusic
       - [ ] obs-studio
       - [ ] atom
       - [ ] pulsar
       - [ ] simplenote (no upstream commits since 2021, TODO mark/remove?)
       - [ ] joplin-desktop
       - [ ] cypress (upstream has had a fix but hasn't version bumped yet)
       - [ ] premid
       - [ ] tidal-hifi
       - [ ] radicle-upstream
       - [ ] Jetbrains applications
          - [ ] mps
          - [ ] pycharm-community
          - [ ] idea-community
   - [ ] Libraries
      - [ ] qtwebengine
      - [ ] libtoxcore
      - [ ] termcolor
      - [ ] libaom
      - [ ] nwjs
      - [ ] jetbrains-jdk-jcef
      - [ ] python310Packages.get-video-properties #257947
      
 This task list may or may not be complete, if you think we are missing something, please feel free to cc me! [Here](https://seashells.io/v/FyR2Jury) is the scan ran by @delroth for vulnerable dependencices

**Comment by xyzeva** [comment]
@Kiwi: simplenote, binary provenance, package seems obsolete

**Comment by xyzeva** [comment]
@maxhille: aether, binary provenance, package seems obsolete

**Comment by xyzeva** [comment]
@06kellyjac: octant-desktop, binary provenance, upstream is archived

**Comment by xyzeva** [comment]
@noneucat: polar-bookshelf, binary provenance, package seems obsolete

**Comment by xyzeva** [comment]
@WolfangAukang: indigenous-desktop, binary provenance, package seems obsolete

**Comment by xyzeva** [comment]
@Mic92, @equirosa, @urandom2: signal-desktop-beta, binary provenance, update available, priority is high

**Comment by WolfangAukang** [comment]
> @WolfangAukang: indigenous-desktop, binary provenance, package seems obsolete

Not obsolete, they changed the repo name. I can build it from source, but the problem is that it does not work with an Electron version superior to 19.

**Comment by WolfangAukang** [comment]
Regarding `threema-desktop` (I'm the maintainer), there was a similar issue (https://github.com/NixOS/nixpkgs/issues/254798) that asked to remove `lib/threema/threema-web`, but as this package is using the bundled electron, it wasn't necessary to keep tracking.

Still I have this PR open that removes that component https://github.com/NixOS/nixpkgs/pull/255899

**Comment by MikaelFangel** [comment]
Brave is being updated in this PR #258060

**Comment by WolfangAukang** [comment]
Regarding `thedesk` (I'm the maintainer), this is a similar case as [threema-desktop](https://github.com/NixOS/nixpkgs/issues/258048#issuecomment-1741217036): application is using bundled electron version but the package contains the binary from the deb file.

**Comment by xyzeva** [comment]
@travisbhartwell, @manveru, @prusnak: could we get electron fixes underway?

**Comment by mweinelt** [comment]
> > @WolfangAukang: indigenous-desktop, binary provenance, package seems obsolete
> 
> Not obsolete, they changed the repo name. I can build it from source, but the problem is that it does not work with an Electron version superior to 19.

Then it should be marked `knownVulnerable`, because they use an end-of-life and vulnerable electron version. Please make that happen if you are opposed ti removing it.

**Comment by WolfangAukang** [comment]
> > > @WolfangAukang: indigenous-desktop, binary provenance, package seems obsolete
> > 
> > 
> > Not obsolete, they changed the repo name. I can build it from source, but the problem is that it does not work with an Electron version superior to 19.
> 
> Then it should be marked `knownVulnerable`, because they use an end-of-life and vulnerable electron version. Please make that happen if you are opposed to removing it.

You mean `knownVulnerabilities`? Not able to find any examples with `knownVulnerable`.

**Comment by xyzeva** [comment]
New logs starting up by @delroth, should be more usable for reading [seashell link](https://seashells.io/v/dufRR7PU)

**Comment by felschr** [comment]
- https://github.com/NixOS/nixpkgs/pull/258116
- https://github.com/NixOS/nixpkgs/pull/258137
- https://github.com/NixOS/nixpkgs/pull/258135
- https://github.com/NixOS/nixpkgs/pull/258138

**Comment by rhysmdnz** [comment]
* https://github.com/NixOS/nixpkgs/pull/258155

**Comment by vcunat** [comment]
In addition to the VP8 CVE above, there's now a VP9 CVE https://github.com/NixOS/nixpkgs/pull/258295  so maybe updating everything will need to be redone again?

**Comment by xyzeva** [comment]
> In addition to the VP8 CVE above, there's now a VP9 CVE #258295 so maybe updating everything will need to be redone again?

We are talking about what to do with the new CVE on the matrix room, we are going to use the same tracking issue, probably

**Comment by MikaelFangel** [comment]
Maybe the solution for mailspring and archord should be the same as this #258217, it should be noted that there is some effort to update the electron version of mailspring, though.

**Comment by SuperSandro2000** [comment]
We should take this opportunity to drop atom. https://atom.io redirects to https://github.blog/2022-06-08-sunsetting-atom/ which explicitly states ``No more security updates`` and the repo is archived since last November.

#258440

**Comment by MikaelFangel** [comment]
As for gitter then it has been removed by #255784 as part of the another CVE.

**Comment by buckley310** [comment]
Looks like Brave didn't get auto-backport properly. I can do a PR in the next day or two unless someone feels like grabbing it sooner.

**Comment by xyzeva** [comment]
One mass-ping for everyone:

mattermost-desktop: @jokogr 
caprine-bin: @ShamrockLee 
wire-desktop: @arianvp, @Kiwi, @toonn 
keybase-gui: @Avaq, @rvolosatovs, @puffnfresh, @np, @Br1ght0ne, @kf5grd
figma-linux: @ercao, @kashw2 
insomnia: @markus1189, @babariviere, @kashw2 
freeswitch: drop, no maintainers (cc @mweinelt)
popcorntime: @onny 
snapmaker-luban: @simonkampe 
keeweb: @sikmir 
zotero: @i077 
polar-bookshelf: @noneucat 
join-desktop: @SuperSandro2000 
passky-desktop: @akkesm 
isabelle: @jwiegley, @jvanbruegge 
onlyoffice: @nh2, @GTrunSec 
jellyseer: @camillemndn
yesplaymusic: @LostAttractor
obs-studio: @jb55, @MP2E, @deviant, @materusPL
pulsar: @COLAMAroro 
simplenote: @Kiwi
cypress: @thorstenweber83, @mmahut, @Craftzman7 
premid: @natto1784
tidal-hifi: @qbit, @spikespaz 
radicle-upstream: @d-xo 
jetbrains.mps: @rasendubi
jetbrains.pycharm-community: @GenericNerdyUsername, @tymscar
jetbrains.idea-community: @edwtjo, @gytis-ivaskevicius, @steinybot, @AnatolyPopov, @tymscar
qtwebengine: @milahu, @NickCao

**Comment by xyzeva** [comment]
libtoxcore: @peterhoeg, @ehmry
termcolor: @prusnak
libaom: @primeos, @kiloreux, @dali99 
nwjs: @offlinehacker
jetbrains.jdk: @edwtjo 

thats all! please update/drop your packages maintainers!

**Comment by COLAMAroro** [comment]
A fair warning concerning Pulsar

I didn't get the time to do it yet, but I will probably soon drop my maintainer status of Pulsar (due to lack of time, and some personal reasons). I gave every piece of documentation I could upstream so that someone else there can take over.

Beyond that, I doubt there will be an update to a newer Electron in the near future (because backporting the Atom codebase to a newer electron is a pain). "Fortunately", I think there is a low risk for this CVE on Pulsar. It's not as widespread as Atom once was, printing arbitrary HTML isn't quite straightforward, and probably will require a plugin, which can already run arbitrary JavaScript.

Pinging @mauricioszabo who has been leading this Electron version bump. If comes a patch for this CVE and nobody can take the maintainership, I'll see if I can find some time to update for nixpkgs.

**Comment by SuperSandro2000** [comment]
dropping join-desktop in #259067

**Comment by mauricioszabo** [comment]
@COLAMAroro I am glad to say that you're wrong about the update to a newer Electron :).

Currently, I am using - even professionally - Pulsar under Electron 25 (can't bump to Electron 26 because it crashes on my Linux machine). In fact, it's been working so well that we're about to start a "next-gen" or maybe "beta" channel for it, so people that want to check if their packages run in this new version of Pulsar can actually try it.

**Comment by dali99** [comment]
As far as I can tell (and I have asked for clarification in the security room - but not yet received an answer), libaom does not vendor libvpx.

It is however a google media codec, and has inherited big parts of libvpx. I've tried finding similar code as what's been patched, but haven't found anything

**Comment by deviant** [comment]
Is there any place to see why individual packages were flagged? All of the seashell links are broken, presumably expired. I'm a maintainer for obs-studio, and can't find them vendoring libvpx— rather it's used via libavcodec, from ffmpeg, which pulls in libvpx from Nixpkgs.

**Comment by delroth** [comment]
IIRC obs-studio vendors a libcef.so which vendors libvpx.

**Comment by deviant** [comment]
@delroth Thanks for the pointer! It's actually vendoring files from Nixpkgs' libcef [pname is "cef-binary"] package, which should probably be on the list instead.

**Comment by delroth** [comment]
> @delroth Thanks for the pointer! It's actually vendoring files from Nixpkgs' libcef [pname is "cef-binary"] package, which should probably be on the list instead.

Yeah, I'm not sure why it's not on the list, the automated tooling should have detected it too. I'll let @xyzeva double check this.

OTOH if this is really just vendored without any modifications it should probably be symlinked instead. Not only would that help us with security tracking in cases like this, but it's a 300MB binary duplicated for (likely?) no good reason.

**Comment by deviant** [comment]
> Yeah, I'm not sure why it's not on the list,

I've just checked and the libcef package is already recent enough to be based on a version of Chromium that isn't vulnerable. So it's not actually an issue— meaning obs-studio should be safe. This issue was created prior to libcef being updated, so it wasn't a false-positive, just no longer valid.

> OTOH if this is really just vendored without any modifications it should probably be symlinked instead. Not only would that help us with security tracking in cases like this, but it's a 300MB binary duplicated for (likely?) no good reason.

Good idea! I'm not sure why exactly, appears to be a copy+paste job. I'll create an issue for it.

**Comment by xyzeva** [comment]
I just updated everything according to the replies & new open PRs, thanks everyone for collaborating and fixing up my mistakes 😅

**Comment by MikaelFangel** [comment]
Freeswitch has implemented a fix for the CVE here: signalwire/freeswitch/pull/2259, but haven't version bumped yet.

**Comment by jvanbruegge** [comment]
I am not entirely sure, but isabelle might be fixed with the new version: https://github.com/NixOS/nixpkgs/pull/243497

**Comment by OPNA2608** [comment]
Pale Moon's UXP / XUL bundles libvpx and upstream says they were affected, https://github.com/NixOS/nixpkgs/pull/259204 bumps `palemoon-bin` to a fixed version.

**Comment by ShamrockLee** [comment]
I created an issue at the upstream project of `caprine-bin` (sindresorhus/caprine#2081).

**Comment by i077** [comment]
Zotero 6 is not affected by this according to the [dev mailing list](https://groups.google.com/g/zotero-dev/c/VWlqSLYyUEc/m/n7nJ_rAsAgAJ).

**Comment by vcunat** [comment]
I'm a bit doubtful.  The list above was created by some scanning of the binary, right?  AFAIK zotero is based on Firefox/XUL, and default XUL binary does bundle libvpx inside...

**Comment by i077** [comment]
I think it is based on XUL, but I think the version of Firefox that comes from is very old. In the JS console in version 6.0.26, `Services.appinfo.platformVersion` evaluates to `"60.9.0"`, but running the same in the browser console of the most recent release of Firefox evaluates to `"118.0.1"`. Firefox 60.9.0 was [released](https://www.mozilla.org/en-US/firefox/60.9.0/releasenotes/) in September 2019. I don't know exactly how the scan was done, as the link to the scan results in the OP is broken.

I can contact their security email or post in the forums about this, but I'm not really sure what the best course of action here is in the meantime. There is Zotero 7 in beta, which patched this vulnerability in a recent build.

**Comment by NickCao** [comment]
`qtwebengine` uses system libvpx thus should not be affected.

**Comment by MikaelFangel** [comment]
I have applied a patch for the CVE in freeswitch in this pr: #259881

**Comment by MikaelFangel** [comment]
Suggesting to remove simplenote in: #259889

**Comment by MikaelFangel** [comment]
I looked at mattermost-desktop, and it doesn't use the shipped Electron version, rather it uses the Electron_26 from nixpkgs. Thus, if I haven't missed anything, it should be resolved, right?

See the line [here](https://github.com/NixOS/nixpkgs/blob/f99e5f03cc0aa231ab5950a15ed02afec45ed51a/pkgs/applications/networking/instant-messengers/mattermost-desktop/default.nix#L55). 😃

**Comment by MikaelFangel** [comment]
Also should mullvad-vpn not be on the list? It was also found by the vendoring checker [https://clbin.com/haJzA](https://clbin.com/haJzA). It has an upstream release bundling a new Electron version.

**Comment by maxhille** [comment]
@xyzeva `aether` is now removed from `master` by https://github.com/NixOS/nixpkgs/pull/258556

**Comment by qbit** [comment]
For tidal-hifi there is a push to get it building from source: https://github.com/NixOS/nixpkgs/pull/252307 - I am not versed enough to be able to help.. maybe someone else can?

**Comment by MikaelFangel** [comment]
Mark figma-linux as vulnerable to this CVE in #261404 until fix is available.

Maintainer will update on next release see: https://github.com/Figma-Linux/figma-linux/issues/341#issuecomment-1764332718

**Comment by MikaelFangel** [comment]
I suggest marking pulsar, a vulnerable in #262376 because it uses a very outdated version of electron and doesn't seem to plan to bundle a new version anytime soon.

**Comment by MikaelFangel** [comment]
Update pycharm here: #262418

**Comment by MikaelFangel** [comment]
Have opened a draft pr fixing nwjs #258048, but I still need to do some more testing to ensure nothing breaks.

**Comment by i077** [comment]
The current stable version of Zotero, based on Firefox 60 as discussed earlier here, is not going to get patched from what I can tell, so #262808 marks it as vulnerable until Zotero 7 hits GA.

**Comment by Inkbottle007** [comment]
> The current stable version of Zotero, based on Firefox 60 as discussed earlier here, is not going to get patched from what I can tell, so #262808 marks it as vulnerable until Zotero 7 hits GA.

Hi, as much as I would love to see Zotero 7 come to GA, it seems Zotero 6 has been patched: "Changes in 6.0.30 (November 2, 2023), [Security] Disabled libvpx support (CVE-2023-5217)" (https://www.zotero.org/support/changelog).

**Comment by camillemndn** [comment]
> > The current stable version of Zotero, based on Firefox 60 as discussed earlier here, is not going to get patched from what I can tell, so #262808 marks it as vulnerable until Zotero 7 hits GA.
> 
> Hi, as much as I would love to see Zotero 7 come to GA, it seems Zotero 6 has been patched: "Changes in 6.0.30 (November 2, 2023), [Security] Disabled libvpx support ([CVE-2023-5217](https://github.com/advisories/GHSA-qqvq-6xgj-jw8g))" (https://www.zotero.org/support/changelog).

Hi, for those interested, I managed to package Zotero 7 built from source in https://github.com/camillemndn/nixos-config/tree/main/pkgs/applications/office/zotero, but I could not upstream it since it is based on Firefox 102 which is already deprecated...

**Comment by shlevy** [comment]
Opened https://github.com/NixOS/nixpkgs/pull/266033 to update Zotero 6

**Comment by Inkbottle007** [comment]
> Hi, for those interested, I managed to package Zotero 7 built from source in https://github.com/camillemndn/nixos-config/tree/main/pkgs/applications/office/zotero, but I could not upstream it since it is based on Firefox 102 which is already deprecated...

Good job building Zotero 7 from source. Zotero seems like a Heath Robinson machine and the only way to distribute is is through its prebuilt which is what the Zotero 6 nixos package is doing I understand. I don't know why they need to vendor Firefox but that's another story.
