### ISSUE TITLE
Tracking: Lomiri Desktop Environment

### ISSUE THREAD

**Issue by OPNA2608** [NixOS/nixpkgs#260859]
#### Project description

Lomiri is a continuation of Canonical's Unity8 desktop environment. It's based on:
- Qt5 (Qt6 support is being considered)
- Mir (currently Mir 1.x & Mir-protocol, Mir 2.x & Wayland is being worked on)
- Ayatana Indicators (continuation of Canonical's Application Indicators)

Corresponding RFP: #99090

---

I have a working version of Lomiri in a branch, with too many commits & inits to nicely upstream. I've started upstreaming individual packages, but progress has been slow and likely not very transparent. I would like to use this issue to track the progress of individually upstreaming all the components needed to make enabling Lomiri as easy as i.e. XFCE.

#### Overview of needed packages

Graph date: 2023-10-08
![image](https://github.com/NixOS/nixpkgs/assets/23431373/13d5111b-5a08-4a6e-ae73-d588fbb48de6)

- [ ] `accounts-qml-module`
- [ ] `address-book-app`
- [ ] `address-book-service`
- [ ] `ayatana-indicator-application`
- [ ] `ayatana-indicator-bluetooth`
- [ ] `ayatana-indicator-datetime`
- [ ] `ayatana-indicator-display`
- [ ] `ayatana-indicator-keyboard`
- [ ] `ayatana-indicator-messages`: #243476
- [ ] `ayatana-indicator-notifications`
- [ ] `ayatana-indicator-power`
- [ ] `ayatana-indicator-printers`
- [ ] `ayatana-indicator-session`
- [ ] `ayatana-indicator-sound`
- [ ] `biometryd`
- [ ] `buteo-syncfw`
- [ ] `buteo-syncfw-qml`
- [x] `cmake-extras`: #236282
- [ ] `content-hub`
- [ ] `dbus-cpp`
- [x] `dbus-test-runner`: #236282
- [x] `deviceinfo`: #241265
- [ ] `dialer-app`
- [ ] `dsme`
- [x] `geonames`: #241259
- [x] `gmenuharness`: #236282
- [ ] `hfd-service`
- [ ] `history-service`
- [ ] `indicator-location`
- [ ] `libayatana-common`: #243307 (still needs Lomiri features enabled)
- [ ] `libcal`
- [ ] `libdsme`
- [ ] `libiphb`
- [ ] `libmce-qt`
- [ ] `libngf`
- [x] `libqtdbusmock`: #236282
- [x] `libqtdbustest`: #236282
- [x] `libusermetrics`: #241335
- [ ] `location-service`
- [ ] `lomiri`
- [ ] `lomiri-action-api`
- [x] `lomiri-api`: #236282
- [ ] `lomiri-app-launch`: #245803
- [ ] `lomiri-calculator-app`
- [ ] `lomiri-calendar-app`
- [ ] `lomiri-camera-app`
- [ ] `lomiri-clock-app`
- [ ] `lomiri-download-manager`: #245900
- [ ] `lomiri-filemanager-app`
- [ ] `lomiri-gallery-app`
- [ ] `lomiri-indicator-network`
- [ ] `lomiri-keyboard`
- [ ] `lomiri-music-app`
- [ ] `lomiri-notifications`
- [ ] `lomiri-online-accounts`
- [ ] `lomiri-schemas`: #245904
- [ ] `lomiri-session`
- [ ] `lomiri-settings-components`: #259238
- [ ] `lomiri-sounds`
- [ ] `lomiri-system-settings`
- [ ] `lomiri-system-settings-online-accounts`
- [ ] `lomiri-system-settings-security-privacy`
- [ ] `lomiri-terminal-app`: #247112
- [ ] `lomiri-thumbnailer`: #259740
- [ ] `lomiri-ui-extras`: #247101
- [ ] `lomiri-ui-toolkit`: #241717
- [ ] `lomiri-url-dispatcher`: #259377
- [ ] `lomiri-music-app`
- [ ] `lomiri-wallpapers`
- [ ] `mce`
- [ ] `mce-dev`
- [ ] `mediaplayer-app`
- [ ] `mediascanner2`
- [ ] `messaging-app`
- [ ] `morph-browser`
- [ ] `net-cpp`
- [ ] `persistent-cache-cpp`: #259393
- [x] `qdjango`: #237543
- [ ] `qmenumodel`: #245911
- [ ] `qqc2-suru-style`
- [ ] `qtmir`: #259804
- [x] `qtpim`: #214164
- [x] `qtsystems`: #214179
- [ ] `qzxing`
- [ ] `repowerd`
- [ ] `sync-monitor`
- [ ] `telephony-service`
- [ ] `trust-store`
- [ ] `u1db-qt`
- [ ] `usb_moded`
- [ ] `xsct`

Not in the graph, but additionally required changes:
- [ ] `qmltermwidget`: #245778

Some of these may not be necessary and only fulfill optional functionalities (I doubt the parts of the SailfishOS stack - `mce`, `buteo-syncfw` etc - are *really* required), I'll have to review the affected reverse dependencies when I upstream them to Nixpkgs.

**Comment by ilya-fedin** [comment]
I fail to install lomiri due to telephony-service which fails to build due to unit tests

**Comment by OPNA2608** [comment]
https://github.com/NixOS/nixpkgs/pull/315117 or its 24.05 backport may not have propagated to whatever nixpkgs version you're using yet.

**Comment by ilya-fedin** [comment]
Finally landed to unstable... Am I the only one unable to resize windows and firefox crashing entire session?

**Comment by OPNA2608** [comment]
Resizing works for me, you need to hover barely outside of the window borders and drag (the cursor doesn't change for me, not sure what this is down to).

Firefox is at least known to not work correctly. I think the crashing might be an issue only we are having, but I believe on Debian it also doesn't work (it brings up an empty window on bookworm, not sure about trixie/sid). I think this is an issue in qtmir, I might need to re-sync our package and check if there's been any improvement on that front. The bundled Morph Browser should work, not sure about others. Suboptimal, I know…

**Comment by ilya-fedin** [comment]
Hm. Firefox works just fine in Ubuntu 22.04 Lomiri testing edition for me (googled some article on Ubuntu Unity website, it has the iso, can provide a link).

Regarding the cursor: last time I saw a similar issue (not on Lomiri though), it was the lack of $XDG_DATA_DIRS/icons/default symlink to a cursor theme.

**Comment by OPNA2608** [comment]
Can try switching to https://gitlab.com/ubports/development/core/qtmir/-/tree/personal/sunweaver/debian-upstream branch, which seems to be what ubuntu 24.04 is using.
