### ISSUE TITLE
OpenTracing should be dropped

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#261927]
As said in [🛑 Deprecating OpenTracing #163](https://github.com/opentracing/specification/issues/163), OpenTracing is deprecated and should be dropped.

**Comment by tomodachi94** [comment]
List of packages (and pings for their maintainers):

- [ ] opentracing, @Rakesh4G
- [x] opentracing-cpp, @rbvermaa
- [x] python3Packages.opentracing, @Rakesh4G
- [x] python3Packages.jaeger-client, maintainerless
- [ ] haskellPackages.opentracing, maintainerless
- [ ] haskellPackages.opentracing-wai, maintainerless
- [ ] haskellPackages.opentracing-jaeger, maintainerless
- [ ] haskellPackages.opentracing-zipkin-v2, maintainerless
- [ ] haskellPackages.opentracing-zipkin-v1, maintainerless
- [ ] haskellPackages.opentracing-http-client, maintainerless
- [ ] haskellPackages.opentracing-zipkin-common, maintainerless
- [ ] haskellPackages.lightstep-haskell ("LightStep OpenTracing client library"), maintainerless
- [x] Nginx module `opentracing`, maintainerless

And a single remaining dependent:
- [x] python3Packages.gevent, @bjornfor 

**Note for prospective helpers: It's probably best to wait until after the feature freeze to drop any packages.**

**Comment by bjornfor** [comment]
> And a single remaining dependent:
>
> [ ] python3Packages.gevent, @bjornfor

It seems to be there only for passthru.tests, for build time checking of reverse deps, to prevent breaking opentracing on gevent updates. So that reference can be removed without loss.

**Comment by AndersonTorres** [comment]
Just for the record:

- Last modification of https://github.com/rbvermaa/nixpkgs: 10 years ago
- Last modification of https://github.com/Rakesh4G/nixpkgs: 3 years ago

I will draft an RFC for dropping inactive maintainers asap.

**Comment by tomodachi94** [comment]
I'm not sure how to drop the Haskell packages. Is there a special process?

**Comment by AndersonTorres** [comment]
Maybe ping Haskell team?

**Comment by tomodachi94** [comment]
@AndersonTorres is there a reason this was closed?
