### ISSUE TITLE
NixOS `apply` script [refactor + feature]

### ISSUE THREAD

**Issue by roberth** [NixOS/nixpkgs#266290]
**Project description**

_Add an "apply" script to NixOS._

Audience:
 - deployment tool developers
 - power users (e.g. `nix run .#.nixosConfigurations.foo.config.system.build.apply`).

Benefits:

- Reduce the number of `--target-host` ssh roundtrips and `sudo` invocations (ie solve https://github.com/NixOS/nixpkgs/issues/258974)
- Provide a good interface for deployment tools that handle evaluation and build for their user.
  - `nixos-rebuild` is not suitable as a backend for most such tools because it can't take a toplevel path. Most `nixos-rebuild` functionality is redundant.
  - `switch-to-configuration` does not manage the profile. Changing this script breaks too much.
    That said, we have some currently incorrect documentation claiming that `switch-to-configuration switch` is equivalanet to `nixos-rebuild switch`.

Functionality:

Manage the profile link and initiate actions that need to run on the target host.

**Responsibilities of NixOS scripts**

- `nixos-rebuild`: UI, build and remote deployment. Specifically:
  - building a new Nix that matches the configuration
  - evaluation and realisation of the configuration
  - ssh to the target machine (if --target-host is specified)
- `apply`: Exactly the things that need to be done on the target host
  - set the profile to new path
    - or perform profile rollback, noting the "new" path
  - run the action safely and reproducibly in `systemd-run` if available
  - initiating the switch
  - initiating the installation of the bootloader
- `switch-to-configuration`:
   - the grunt work of actually switch and installing the bootloader

**Callers of the apply script**

The new apply script will be called and packaged in multiple ways:

- The `nixos-rebuild` package: For applying configurations that pre-date the toplevel/bin/apply script
- `toplevel/bin/apply`: The normal script for applying configurations. The script is copied into toplevel because it needs to hardcode the toplevel path. Deployment tools may call this directly.
- `system.build.apply`: Same script but not incorporated into toplevel in order to GC the activation stuff after activation has run (it's a tradeoff). Very optional to even use this.

**Interface**

- Similar to `switch-to-configuration`.
- Extra: a parameter that allows `pathToConfig` to be specified, which is useful when reusing the script implementation for deploying legacy (non-`apply`) configurations.
- Extra: default action. `switch`? This makes the command nicer to use when called directly by a user. Maybe the default action should be switch + timeout + rollback? At least for configurations that have such functionality. That's TBD, so perhaps the default should be postponed until that's done.

Out of scope: if we'll have a `nixos` command, it could have an `apply` subcommand that has `nixos-rebuild`-like functionality evaluates and builds before deferring to an `apply` script that has a very similar interface. For me this is reason to think about `apply` as a somewhat nice interface for users, because then it will be feasible to have an analogous interface in the `nixos apply` command.

**TODO**

- [ ] Make `nixos-rebuild` not write a result symlink. It performs a non-permanent deployment - not to be confused with `build-vm`, which is for testing "in isolation" (somewhat).
- [x] Write a test for `--target-host`. See `nixops_unstable` test for example of this kind of thing. Add it to `nixos-rebuild.tests`.
- [ ] Implement the apply script outside of `toplevel` and make `nixos-rebuild` use it in order to perform the steps after build. This includes reading the profile when it's a rollback instead of a new toplevel, as well as setting the new profile regardless of rollback vs new.
  - [ ] Clean up the control flow in a prep PR first?
- [ ] Add `apply` to `toplevel/bin`. Make `nixos-rebuild` call it when it knows that the script exists (ie not a rollback), or come up with an `sh` script that defers this compatibility logic to the remote?
- [ ] Update the manual. Most occurrences of `switch-to-configuration` should probably be changed to `apply`.

**Comment by Majiir** [comment]
What is the value in keeping `apply` separate from `switch-to-configuration`? In other words, what if you wrap the existing `switch-to-configuration` with the logic you've outlined here for `apply`?

It would break usages that depend on the existing behavior where `switch-to-configuration` does _not_ update the profile as documented. But it would make the script work as already documented! We can update the manual, but there are many unofficial resources that reference `switch-to-configuration`, so maintaining consistency with it could be helpful.

**Comment by roberth** [comment]
> What is the value in keeping `apply` separate from `switch-to-configuration`?

- No breaking changes.
  - No new bugs in all existing solutions.
  - Not changing responsibilities keeps the legacy logic in `nixos-rebuild` understandable.

- Easy to observe whether a toplevel implements the new behavior
  - Deployment tools opt in to the new behavior - can make their own trade-off. For instance they can disable their own solution for the problem `systemd-run` solves now.

- Separation of concerns.
  - Relevant parts of the deployment process have their own names
  - `switch-to-configuration` would have to re-invoke itself in order to enter `systemd-run`*, which blurs the line of responsibilities.
     - This could be mitigated by first renaming `switch-to-configuration` to something else, and renaming the proposed `apply` to `switch-to-configuration`. Hard to explain, but valid.

- Better name
  - `apply` is short and sweet, just like what it does, compared to `nixos-rebuild`
    - I have an urge to abbreviate to `s-t-c` when writing these things, which wouldn't help anyone. I've seen others do this kind of thing in discussions.
  - `switch-to-configuration` suggests it's only for the `switch` action.

\*: entering `systemd-run` is a requirement for `apply` (or `switch-to-configuration`) to serve as an equally safe backend for other deployment tools (ie not `nixos-rebuild` but most of the other ones). Those should also go through `systemd-run`.


> but there are many unofficial resources that reference `switch-to-configuration`

Indeed that is unfortunate, but we can add a warning that tells what to do (when not invoked via `apply`). The problem is not critical. `switch` behaves like `test`. `boot` might be more serious, but either way it can be solved by running the new command.
The fact that this documentation has been wrong for at least some time seems to suggest that it's not a big problem in the first place, and that can be explained by the fact that normal users use `nixos-rebuild` anyway, and not some internal script - and for a one-off, the `test`-like behavior might be what they want.

**Comment by roberth** [comment]
Implementation ready for review:
- https://github.com/NixOS/nixpkgs/pull/344407

**Comment by Luflosi** [comment]
I'm reopening this issue, since the PR above has been reverted.
