### ISSUE TITLE
[Tracking Issue] Remaining OpenSSL 1.1 dependents

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#269713]
## Issue description

Now that it's clear that OpenSSL 1.1 is EOL to everyone (https://endoflife.date/openssl), we need to take care of the remnants of OpenSSL 1.1.

- [ ] home-assistant-chip-core @mweinelt 
- [ ] osquery @nlewo @RaitoBezarius 
- [ ] Ruby @ajs124 
- [ ] Viber @SimonBrandner @prtzl
- [ ] AWS workspace @dylanmtaylor @mausch
- [ ] PHP legacy extension @RaitoBezarius 
- [ ] PHP's relay package @ostrolucky 
- [ ] Lisp's `cl-async-ssl` @Uthar 
- [ ] paddlepaddle @happysalada 
- [ ] pcsc-safenet @charles-dyfis-net 
- [ ] sgx-sdk @blitz 
- [ ] sublimetext4 @PedroHLC @jtojnar 
- [ ] runescaper launcher @GRBurst 
- [ ] quickbms @samuelgrf 
- [ ] wraith @ajs124 @elitak 
- [ ] kore @JohnMH 
- [ ] wkhtmltopdf-bin @kalbasit @nbr 
- [ ] mrustc's bootstrap @progval @r-burns 
- [ ] archiveopteryx @phunehehe 
- [ ] bip: no maintainer

If those dependencies are not migrated one month before 2 months before the next release process starts, I propose to remove them from nixpkgs.

**Comment by mweinelt** [comment]
For `home-assistant-chip-core` we are at the mercy of the upstream Matter SDK. Their build system is pinned to Ubuntu 20.04, which only carries OpenSSL 1.1, so the wheels get built against that.

Building that from source is not feasible, as the Git repo with all required submodules is 27 GiB in size, before it bootstraps and downloads even more things.

Issue reported earlier this year at https://github.com/project-chip/connectedhomeip/issues/25688

**Comment by charles-dyfis-net** [comment]
The upstream documentation for pcsc-safenet _claims_ that it's possible to make it work with newer OpenSSL releases. I haven't succeeded in doing so to date, but will take another shot at it.

**Comment by mausch** [comment]
This will be solved for aws-workspaces when we get this done: https://github.com/NixOS/nixpkgs/pull/251976

**Comment by eclairevoyant** [comment]
Besides bip being unmaintained in nixpkgs, it's also dead upstream, no commits in nearly 2 years, and the openssl situation was raised a while ago w no response <https://projects.duckcorp.org/issues/780>

And in nixpkgs it seems that we are just adding patch after patch just to keep it alive.

**Comment by blitz** [comment]
FYI I'm looking into upgrading the sgx-sdk.

**Comment by blitz** [comment]
From my perspective getting #254845 merged is the best option to remove its OpenSSL 1.1 dependency.

**Comment by nbr** [comment]
wkhtmltopdf-bin does not seem to depend on `openssl_1_1` as far as I can tell (unless I am missing something?)

**Comment by kirillrdy** [comment]
> wkhtmltopdf-bin does not seem to depend on `openssl_1_1` as far as I can tell (unless I am missing something?)

```
libssl.so.1.1 wanted by /nix/store/qkkgc8yjxb6bz13i9mhxv8vfnn26srg8-wkhtmltopdf-bin-0.12.6-3/bin/wkhtmltopdf
```

**Comment by phlip9** [comment]
[sgx-sdk: 2.21 -> 2.23](https://github.com/NixOS/nixpkgs/pull/283405) should also close out any remaining OpenSSL 1.1 from the sgx-* packages.

**Comment by mweinelt** [comment]
The next home-assistant-chip-core release will migrate to boringssl. Finally.

**Comment by mweinelt** [comment]
> If those dependencies are not migrated one month before 2 months before the next release process starts, I propose to remove them from nixpkgs.

I think we're getting closer to having to follow up on that consideration.

**Comment by ostrolucky** [comment]
Updating the list from OG post would be nice. Lot of those packages from list have meanwhile removed openssl 1.1 dependency.

**Comment by zimbatm** [comment]
wkhtmltopdf-bin doesn't depend on openssl_1_1 anymore. fixed in  #327641

**Comment by dylanmtaylor** [comment]
There is a WIP PR that will remove the openssl dependency and upgrade to a newer aws-workspaces, but I think we may need some help figuring out the schema issues to get this into a mergeable state if anyone has time to look at this. https://github.com/NixOS/nixpkgs/pull/344875

**Comment by jaredcrean** [comment]
The newest version on Amazon workspaces moves off openssl 1.1. So that one will be checked off soon.  Here is the work being done to make it work. #344875

**Comment by pyrox0** [comment]
With #375039 being merged, mrustc no longer depends on openssl 1.1 on the master branch.

**Comment by gepbird** [comment]
I tried to deal with the last 2 remaining dependants:
- [x] https://github.com/NixOS/nixpkgs/pull/531289
- [x] https://github.com/NixOS/nixpkgs/pull/531298

**Comment by iedame** [comment]
`bolt-launcher` has been handled. I believe that was the final blocker for dropping OpenSSL 1.1.
