### ISSUE TITLE
[Tracking] updating the Nixpkgs manual to a consistent style

### ISSUE THREAD

**Issue by DanielSidhion** [NixOS/nixpkgs#278769]
The Nixpkgs manual has several different styles for documenting things depending on which section you're looking at. In an effort to keep it more consistent, I'm going through the manual and updating every file to use the same conventions. These conventions are documented in #278762.

As I go through the files, I may discover certain usages which might also be added to the conventions. Any additions will be discussed with the Nix documentation team during the documentation team meetings before being adopted.
Since additions may happen after certain files have been changed, I'm documenting which "version" of the conventions each file is at to make it easier to go back and apply newer versions to files that were changed with older versions.
This is a somewhat inefficient process, but it's what allows me to handle this bit by bit.

It's outside of the scope of this issue, but I can't help it: as I go through each file, I'm also updating the information in them to be more up to date.

I'm going through each file in the sequence below (paths are relative to `/docs`):

- [x] ./preface.chapter.md
- [x] ./contributing.md
- [x] ./functions.md
- [x] ./stdenv.md
- [x] ./README.md
- [x] ./development.md
- [x] ./build-helpers.md
- [x] ./lib.md
- [x] ./using-nixpkgs.md
- [x] ./build-helpers/testers.chapter.md
  - (v1) #275585
  - (v1) #275791
- [x] ./build-helpers/images/appimagetools.section.md
  - (v1) #276029
- [x] ./build-helpers/images/binarycache.section.md
  - (v1) #276821
- [x] ./build-helpers/images/dockertools.section.md
  - (v3) #278956
  - (v3) #281491
  - (v3) #283106
  - (v3) #283392
  - (v3) #285223
  - (v3) #286882
  - (v3) #288414
- [ ] (to be moved to internal README) ./build-helpers/images/makediskimage.section.md
- [x] ./build-helpers/images/ocitools.section.md
  - (v3) #290886
- [x] ./build-helpers/images/portableservice.section.md
  - (v3) #292267
- [x] ./build-helpers/images/snaptools.section.md
  - #293416
- [x] ./build-helpers/images.md
- [ ] **currently here** ./build-helpers/fetchers.chapter.md
  - (v3) #297654
  - (v3) #300429
  - (v3) #302692
- [ ] ./build-helpers/trivial-build-helpers.chapter.md
- [ ] ./build-helpers/special.md
- [ ] ./build-helpers/special/checkpoint-build.section.md
- [ ] ./build-helpers/special/fhs-environments.section.md
- [ ] ./build-helpers/special/makesetuphook.section.md
- [ ] ./build-helpers/special/mkshell.section.md
- [ ] ./build-helpers/special/vm-tools.section.md
- [ ] ./contributing/contributing-to-documentation.chapter.md
- [ ] ./contributing/coding-conventions.chapter.md
- [ ] ./contributing/quick-start.chapter.md
- [ ] ./contributing/reviewing-contributions.chapter.md
- [ ] ./contributing/submitting-changes.chapter.md
- [ ] ./contributing/vulnerability-roundup.chapter.md
- [ ] ./development/opening-issues.chapter.md
- [ ] ./functions/debug.section.md
- [ ] ./functions/generators.section.md
- [ ] ./functions/prefer-remote-fetch.section.md
- [ ] ./functions/nix-gitignore.section.md
- [ ] ./hooks/automake.section.md
- [ ] ./hooks/autoconf.section.md
- [ ] ./hooks/autopatchelf.section.md
- [ ] ./hooks/bmake.section.md
- [ ] ./hooks/breakpoint.section.md
- [ ] ./hooks/cmake.section.md
- [ ] ./hooks/gdk-pixbuf.section.md
- [ ] ./hooks/ghc.section.md
- [ ] ./hooks/gnome.section.md
- [ ] ./hooks/index.md
- [ ] ./hooks/installShellFiles.section.md
- [ ] ./hooks/libiconv.section.md
- [ ] ./hooks/libxml2.section.md
- [ ] ./hooks/meson.section.md
- [ ] ./hooks/mpi-check-hook.section.md
- [ ] ./hooks/ninja.section.md
- [ ] ./hooks/patch-rc-path-hooks.section.md
- [ ] ./hooks/perl.section.md
- [ ] ./hooks/pkg-config.section.md
- [ ] ./hooks/postgresql-test-hook.section.md
- [ ] ./hooks/python.section.md
- [ ] ./hooks/scons.section.md
- [ ] ./hooks/tetex-tex-live.section.md
- [ ] ./hooks/unzip.section.md
- [ ] ./hooks/validatePkgConfig.section.md
- [ ] ./hooks/waf.section.md
- [ ] ./hooks/xcbuild.section.md
- [ ] ./hooks/zig.section.md
- [ ] ./languages-frameworks/agda.section.md
- [ ] ./languages-frameworks/android.section.md
- [ ] ./languages-frameworks/beam.section.md
- [ ] ./languages-frameworks/bower.section.md
- [ ] ./languages-frameworks/chicken.section.md
- [ ] ./languages-frameworks/coq.section.md
- [ ] ./languages-frameworks/crystal.section.md
- [ ] ./languages-frameworks/cuda.section.md
- [ ] ./languages-frameworks/cuelang.section.md
- [ ] ./languages-frameworks/dart.section.md
- [ ] ./languages-frameworks/dhall.section.md
- [ ] ./languages-frameworks/dotnet.section.md
- [ ] ./languages-frameworks/emscripten.section.md
- [ ] ./languages-frameworks/gnome.section.md
- [ ] ./languages-frameworks/go.section.md
- [ ] ./languages-frameworks/haskell.section.md
- [ ] ./languages-frameworks/hy.section.md
- [ ] ./languages-frameworks/idris.section.md
- [ ] ./languages-frameworks/index.md
- [ ] ./languages-frameworks/ios.section.md
- [ ] ./languages-frameworks/java.section.md
- [ ] ./languages-frameworks/javascript.section.md
- [ ] ./languages-frameworks/julia.section.md
- [ ] ./languages-frameworks/lisp.section.md
- [ ] ./languages-frameworks/lua.section.md
- [ ] ./languages-frameworks/maven.section.md
- [ ] ./languages-frameworks/nim.section.md
- [ ] ./languages-frameworks/ocaml.section.md
- [ ] ./languages-frameworks/octave.section.md
- [ ] ./languages-frameworks/perl.section.md
- [ ] ./languages-frameworks/php.section.md
- [ ] ./languages-frameworks/pkg-config.section.md
- [ ] ./languages-frameworks/python.section.md
- [ ] ./languages-frameworks/qt.section.md
- [ ] ./languages-frameworks/r.section.md
- [ ] ./languages-frameworks/ruby.section.md
- [ ] ./languages-frameworks/rust.section.md
- [ ] ./languages-frameworks/swift.section.md
- [ ] ./languages-frameworks/texlive.section.md
- [ ] ./languages-frameworks/titanium.section.md
- [ ] ./languages-frameworks/vim.section.md
- [ ] ./module-system/module-system.chapter.md
- [ ] ./packages/cataclysm-dda.section.md
- [ ] ./packages/citrix.section.md
- [ ] ./packages/darwin-builder.section.md
- [ ] ./packages/dlib.section.md
- [ ] ./packages/eclipse.section.md
- [ ] ./packages/elm.section.md
- [ ] ./packages/emacs.section.md
- [ ] ./packages/etc-files.section.md
- [ ] ./packages/firefox.section.md
- [ ] ./packages/fish.section.md
- [ ] ./packages/fuse.section.md
- [ ] ./packages/ibus.section.md
- [ ] ./packages/index.md
- [ ] ./packages/kakoune.section.md
- [ ] ./packages/linux.section.md
- [ ] ./packages/locales.section.md
- [ ] ./packages/nginx.section.md
- [ ] ./packages/opengl.section.md
- [ ] ./packages/shell-helpers.section.md
- [ ] ./packages/steam.section.md
- [ ] ./packages/urxvt.section.md
- [ ] ./packages/weechat.section.md
- [ ] ./packages/xorg.section.md
- [ ] ./stdenv/cross-compilation.chapter.md
- [ ] ./stdenv/meta.chapter.md
- [ ] ./stdenv/multiple-output.chapter.md
- [ ] ./stdenv/platform-notes.chapter.md
- [ ] ./stdenv/stdenv.chapter.md
- [ ] ./using/configuration.chapter.md
- [ ] ./using/overlays.chapter.md
- [ ] ./using/overrides.chapter.md
- [ ] ./using/platform-support.chapter.md

Any help is appreciated to update other files, just try to pick something not being worked on yet.

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by AndersonTorres** [comment]
Lemme know when you pick waf, scons and the like.
