### ISSUE TITLE
Tracking issue: trivialBuild should retire in favor of melpaBuild

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#278925]
### Describe the bug

According to @jian-lin the `trivialBuild` function has some problems that make it a bad fit for Emacs ecosystem in Nixpkgs. 

In packages made via `trivialBuild`:

- The builtin package manager package.el will not activate it at the Emacs' startup
  - autoloaded commands does not work out-of-the-box, requiring bolierplate code like ` (require 'foo-autoloads)`
  - info manual becomes inaccessible via`M-x info`
- its package dir is [not searched](https://github.com/emacs-mirror/emacs/blob/310ed338c195c755b11e0c62bde9629797b644c8/lisp/emacs-lisp/package.el#L738) by Emacs
- it does not contain a [foo-pkg.el](https://github.com/emacs-mirror/emacs/blob/310ed338c195c755b11e0c62bde9629797b644c8/lisp/emacs-lisp/package.el#L717) file

References:
- https://github.com/NixOS/nixpkgs/pull/278201#discussion_r1441301238

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jian-lin** [comment]
I think we should:
- make reviewers and contributors aware that `trivialBuild` has some issues and its usage is discouraged
- replace existing `trivialBuild` in [manual-packages](https://github.com/NixOS/nixpkgs/tree/efc960b6d6a6498c23868f4ba59fcb8bb51c9861/pkgs/applications/editors/emacs/elisp-packages/manual-packages) with `melpaBuild` or `elpaBuild`

**Comment by AndersonTorres** [comment]
We should do this in reverse: first by looking at current code that uses trivialBuild, and only then to warn new devs.

I say this because I remember some packages fail with melpaBuild.

**Comment by AndersonTorres** [comment]
Directories inside `pkgs/applications/editors/emacs/elisp-packages/manual-packages/` that call trivialBuild:

- [ ] agda-input
- [ ] agda2-mode
- [ ] codeium
- [ ] color-theme-solarized
- [ ] control-lock
- [ ] copilot
- [ ] ess-R-object-popup
- [ ] evil-markdown
- [ ] font-lock-plus
- [ ] git-undo
- [ ] helm-words
- [ ] hsc3
- [ ] idris2-mode
- [ ] isearch-plus
- [ ] isearch-prop
- [ ] jam-mode
- [ ] llvm-mode
- [ ] lspce
- [ ] notdeft
- [ ] ott-mode
- [ ] perl-completion
- [ ] pod-mode
- [ ] prolog
- [ ] rect-mark
- [ ] sunrise-commander
- [ ] sv-kalender
- [ ] urweb-mode
- [ ] voicemacs
- [ ] wat-mode
- [ ] yes-no
- [ ] youtube-dl

**Comment by jian-lin** [comment]
elpaBuild expects src to be a file or a tarball meeting some requirements.  The requirement of src of melpaBuild is less strict than the one of elpaBuild.

Have you tried melpaBuild?

**Comment by AndersonTorres** [comment]
I tried it a long time ago. But let's do it again:

```nix
{ lib
, emacs
, fetchFromGitHub
, melpaBuild
, writeText
}:

melpaBuild {
  pname = "sunrise-commander";
  ename = "sunrise-commander";
  version = "unstable-2021-09-27";

  src = fetchFromGitHub {
    owner = "sunrise-commander";
    repo = "sunrise-commander";
    rev = "16e6df7e86c7a383fb4400fae94af32baf9cb24e";
    hash = "sha256-D36qiRi5OTZrBtJ/bD/javAWizZ8NLlC/YP4rdLCSsw=";
  };

  packageRequires = [
    emacs
  ];

  recipe = writeText "recipe" ''
    (sunrise-commander :repo "sunrise-commander/sunrise-commander" :fetcher github :files ("*.el"))
  '';

  fileSpecs = [ "*.el" ];

  meta = {
    homepage = "https://github.com/sunrise-commander/sunrise-commander/";
    description = "Orthodox (two-pane) file manager for Emacs";
    license = lib.licenses.gpl3Plus;
    maintainers = [ lib.maintainers.AndersonTorres ];
    platforms = lib.platforms.all;
  };
}
```

Log:

```txt
emacs-sunrise-commander-unstable> Running phase: installPhase
emacs-sunrise-commander-unstable> Error: file-missing ("Opening input file" "No such file or directory" "/build/packages/sunrise-commander-unstable-2021-09-27.tar")
emacs-sunrise-commander-unstable>   mapbacktrace(#f(compiled-function (evald func args flags) #<bytecode -0xcc6be0a6510e41>))
emacs-sunrise-commander-unstable>   debug-early-backtrace()
emacs-sunrise-commander-unstable>   debug-early(error (file-missing "Opening input file" "No such file or directory" "/build/packages/sunrise-commander-unstable-2021-09-27.tar"))
emacs-sunrise-commander-unstable>   insert-file-contents-literally("/build/packages/sunrise-commander-unstable-2021-09-27.tar")
emacs-sunrise-commander-unstable>   (if is-tar (insert-file-contents-literally file) (insert-file-contents file))
emacs-sunrise-commander-unstable>   (progn (if is-tar (insert-file-contents-literally file) (insert-file-contents file)) (if is-tar (progn (tar-mode))) (elpa2nix-install-from-buffer))
emacs-sunrise-commander-unstable>   (unwind-protect (progn (if is-tar (insert-file-contents-literally file) (insert-file-contents file)) (if is-tar (progn (tar-mode))) (elpa2nix-install-from-buffer)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))
emacs-sunrise-commander-unstable>   (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if is-tar (insert-file-contents-literally file) (insert-file-contents file)) (if is-tar (progn (tar-mode))) (elpa2nix-install-from-buffer)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))
emacs-sunrise-commander-unstable>   (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if is-tar (insert-file-contents-literally file) (insert-file-contents file)) (if is-tar (progn (tar-mode))) (elpa2nix-install-from-buffer)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer)))))
emacs-sunrise-commander-unstable>   (let ((is-tar (string-match "\\.tar\\'" file))) (let ((temp-buffer (generate-new-buffer " *temp*" t))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (if is-tar (insert-file-contents-literally file) (insert-file-contents file)) (if is-tar (progn (tar-mode))) (elpa2nix-install-from-buffer)) (and (buffer-name temp-buffer) (kill-buffer temp-buffer))))))
emacs-sunrise-commander-unstable>   elpa2nix-install-file("/build/packages/sunrise-commander-unstable-2021-09-27.tar")
emacs-sunrise-commander-unstable>   (progn (setq package-user-dir elpa) (elpa2nix-install-file archive))
emacs-sunrise-commander-unstable>   (let ((archive x0) (elpa x2)) (progn (setq package-user-dir elpa) (elpa2nix-install-file archive)))
emacs-sunrise-commander-unstable>   (if (null x3) (let ((archive x0) (elpa x2)) (progn (setq package-user-dir elpa) (elpa2nix-install-file archive))))
emacs-sunrise-commander-unstable>   (let* ((x2 (car-safe x1)) (x3 (cdr-safe x1))) (if (null x3) (let ((archive x0) (elpa x2)) (progn (setq package-user-dir elpa) (elpa2nix-install-file archive)))))
emacs-sunrise-commander-unstable>   (if (consp x1) (let* ((x2 (car-safe x1)) (x3 (cdr-safe x1))) (if (null x3) (let ((archive x0) (elpa x2)) (progn (setq package-user-dir elpa) (elpa2nix-install-file archive))))))
emacs-sunrise-commander-unstable>   (let* ((x0 (car-safe command-line-args-left)) (x1 (cdr-safe command-line-args-left))) (if (consp x1) (let* ((x2 (car-safe x1)) (x3 (cdr-safe x1))) (if (null x3) (let ((archive x0) (elpa x2)) (progn (setq package-user-dir elpa) (elpa2nix-install-file archive)))))))
emacs-sunrise-commander-unstable>   (if (consp command-line-args-left) (let* ((x0 (car-safe command-line-args-left)) (x1 (cdr-safe command-line-args-left))) (if (consp x1) (let* ((x2 (car-safe x1)) (x3 (cdr-safe x1))) (if (null x3) (let ((archive x0) (elpa x2)) (progn (setq package-user-dir elpa) (elpa2nix-install-file archive))))))))
emacs-sunrise-commander-unstable>   elpa2nix-install-package()
emacs-sunrise-commander-unstable>   command-line-1(("-l" "/nix/store/4jj63z4v1xp13rh2md053dccq920hd45-elpa2nix.el" "-f" "elpa2nix-install-package" "/build/packages/sunrise-commander-unstable-2021-09-27.tar" "/nix/store/6gf924kvnbpjgf7mrwmm93ih5pcjpkrr-emacs-sunrise-commander-unstable-2021-09-27/share/emacs/site-lisp/elpa"))
emacs-sunrise-commander-unstable>   command-line()
emacs-sunrise-commander-unstable>   normal-top-level()
emacs-sunrise-commander-unstable> Opening input file: No such file or directory, /build/packages/sunrise-commander-unstable-2021-09-27.tar
```

**Comment by jian-lin** [comment]
Here is a working example: `ename` and `recipe` need to be change to `sunrise` and `commit` is needed for now

```nix
{ lib
, emacs
, fetchFromGitHub
, melpaBuild
, writeText
}:

melpaBuild {
  pname = "sunrise-commander";
  ename = "sunrise";
  version = "20210924.1620";

  src = fetchFromGitHub {
    owner = "sunrise-commander";
    repo = "sunrise-commander";
    rev = "16e6df7e86c7a383fb4400fae94af32baf9cb24e";
    hash = "sha256-D36qiRi5OTZrBtJ/bD/javAWizZ8NLlC/YP4rdLCSsw=";
  };

  # not sure whether it is still needed when a newer[1] package-build is used
  # [1]: https://github.com/NixOS/nixpkgs/pull/276943 is in the staging branch for now
  commit = "foo";

  # should be redundant
  # packageRequires = [
  #   emacs
  # ];

  recipe = writeText "recipe" ''
    (sunrise :repo "sunrise-commander/sunrise-commander" :fetcher github)
  '';

  meta = {
    homepage = "https://github.com/sunrise-commander/sunrise-commander/";
    description = "Orthodox (two-pane) file manager for Emacs";
    license = lib.licenses.gpl3Plus;
    maintainers = [ lib.maintainers.AndersonTorres ];
    platforms = lib.platforms.all;
  };
}
```

**Comment by AndersonTorres** [comment]
Nice. Now we need to wait the Staging Truckload.

----------

1. Where did the attribute `version = "20210924.1620";` come from?
     I have grepped the installed files and it comes from nowhere except an autogenerated sunrise-pkg.el...
2. What does fileSpecs do? It is not documented anywhere...

**Comment by jian-lin** [comment]
https://github.com/NixOS/nixpkgs/issues/190746 is related

**Comment by jian-lin** [comment]
> Where did the attribute version = "20210924.1620"; come from?

This is the version format [MELPA unstable](https://github.com/melpa/package-build/blob/414b328a4f18a6237867739c56e8777e8086d2e8/package-build.el#L523-L533) uses.

```elisp
(let ((time 1703448134))
  (concat (format-time-string "%Y%m%d." time t)
          (format "%d" (string-to-number
                        (format-time-string "%H%M" time t)))))
```

`time` is produced by a [git command](https://github.com/melpa/package-build/blob/414b328a4f18a6237867739c56e8777e8086d2e8/package-build.el#L339-L349) `git log -n1 --first-parent --pretty='format:%H %cd' --date=unix`.

I think `fileSpecs` has no effect since https://github.com/NixOS/nixpkgs/commit/d3cea4860862754d74f60a4332c24b646f1446c9#diff-2a37290b0927d8abb03148a01a10a84dd3a18be9be80d27c7aac6c02d8ea6841L14

**Comment by AndersonTorres** [comment]
Some obvious findings:

- The recipe format is described here: https://github.com/melpa/melpa#recipe-format
   maybe it can be Nixified.

**Comment by hraban** [comment]
Thanks for your work on this, y'all! 🙌

**Comment by jian-lin** [comment]
I created https://github.com/NixOS/nixpkgs/pull/316107 to improve the UX of `melpaBuild`.

**Comment by jian-lin** [comment]
With https://github.com/NixOS/nixpkgs/pull/316726, the UX of `melpaBuild` should be on a par with `elpaBuild` and `trivialBuild`.

Given that it has fewer issues than `trivialBuild` and that its requirement for `src` is looser than `elpaBuild`, it should be recommended as the default builder for manual packages.

**Comment by AndersonTorres** [comment]
Now that it reached Master, we can restart!

**Comment by hraban** [comment]
How do you use melpaBuild to create very simple in-line packages?

```
          (e.trivialBuild {
            pname = "foo";
            version = "2024-07-15";
            src = builtins.toFile "foo.el" ''(defun foo-three () 3) (provide 'foo)'';
          })
```

I use this to create light-weight emacs plugins from my Nix config, it's a neat way to integrate the broader system config into Emacs.

**Comment by AndersonTorres** [comment]
@hraban you can look at https://github.com/NixOS/nixpkgs/pull/325168 to take some inspiration.

The problem is that maybe melpaBuild is a bit stricter, since it transfers control to Emacs build system.

**Comment by AndersonTorres** [comment]
I will split this in order to accomodate EmacsWiki repacks:

- [ ] control-lock
- [ ] isearch-plus
- [ ] isearch-prop
- [ ] perl-completion
- [ ] rect-mark
- [ ] sv-kkalender
- [ ] yes-no

**Comment by hraban** [comment]
> The minimal `melpaBuild` equivalent is
> 
> ```nix
>   e.melpaBuild {
>     pname = "foo";
>     version = "0-unstable-2024-07-15";
>     # version = "20240715.0"; # if your Nixpkgs is old
>     src = builtins.toFile "foo.el" ''
>       ;;; foo.el ---
>       (defun foo-three () 3) (provide 'foo)
>     '';
>   };
> ```
> 
> The first line (file header) `;;; foo.el ---` is needed by `melpaBuild` to generate `foo-pkg.el`.

Thanks! Good catch: that line was necessary for melpaBuild but not for trivialBuild

> If `trivialBuild` works well for your use case, then there is no need to switch to `melpaBuild`. `melpaBuild` is still a good fit for "normal" packages.

That'd be good for my use case, I was going off the impression from this issue title that trivialBuild is on the way to becoming obsolete but if it's still available that's nice.

**Comment by jian-lin** [comment]
> EmacsWiki repacks (they should be dealt with separately):

@AndersonTorres What do you mean by "they should be dealt with separately"?  Why and how?

**Comment by AndersonTorres** [comment]
It is better explained with an example:

Let's pick control-lock.

Webpage: https://www.emacswiki.org/emacs/ControlLock
Download page: https://www.emacswiki.org/emacs/download/control-lock.el

There is virtually no version control.

However, there is a backup at GitHub:

https://github.com/emacsmirror/emacswiki.org/blob/master/control-lock.el

My intention is to create a "package" for this EmacsWiki mirror and do something like `files = ''("control-lock.el")''`.

**Comment by AndersonTorres** [comment]
Another thing to be seen is the auto-update scripts.

**Comment by jian-lin** [comment]
> Another thing to be seen is the auto-update scripts.

Since `trivialBuild` works well in that use case (autolaoding is not used by `update-melpa.el`) and users is unlikely to look at that file, it's fine to not change it to `melpaBuild`.

---

I am working on the last piece of this issue, i.e., writing doc for these builders.

**Comment by AndersonTorres** [comment]
I wasn't clear. I was talking about `passthru.updateScript`.

**Comment by jian-lin** [comment]
@AndersonTorres Could you switch `mkDerivation` to `melpaBuild` for `cask`?

**Comment by AndersonTorres** [comment]
Yes I can. However I will need to study cask a little bit, since Cask is a commandline app.

**Comment by AndersonTorres** [comment]
For now the only "non-conforming" packages are xapian-lite and cedille.
However Cedille is broken:

> # Broken due to Agda update.  See
> # https://github.com/NixOS/nixpkgs/pull/129606#issuecomment-881107449.
>

**Comment by jian-lin** [comment]
The bug you mention is that Emacs lisp packages built by `elpaBuild` have `emacs` itself in their closures.  This bug have already [been] [fixed], which means `nixos-24.11` and `nixos-unstable` do not have this bug.  If you are using older nixos releases, one way to fix the bug is to use Emacs lisp packages from [emacs-overlay].

If you want to discuss this bug future, please open a new issue.

[been]: https://github.com/nix-community/emacs2nix/pull/72
[fixed]: https://github.com/NixOS/nixpkgs/pull/331025
[emacs-overlay]: https://github.com/nix-community/emacs-overlay
