### ISSUE TITLE
Documentation: necessity of `meta.mainProgram`

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/nixpkgs#281276]
## Problem

The documentation for `meta.mainProgram` says: "must be set when appropriate".

https://github.com/NixOS/nixpkgs/blob/5223d1f86aab688bf05c6069b87be5f662d84eac/pkgs/README.md?plain=1#L387

What does it mean for `meta.mainProgram` to "be appropriate"?

## Proposal

My guess is that `meta.mainProgram` is "appropriate" in one of the two cases:

- When the main binary exposed by the package is different than the attribute name in Nixpkgs.

    For instance, the Nixpkgs attribute `ripgrep` exposes a main binary `rg`, so it should definitely have `meta.mainProgram = "rg"`.

- For _any package_ that exposes a "main" binary.

    In this case, even a package like `xterm` (which is a top-level attribute in Nixpkgs called `xterm`), would also be required to set `meta.mainProgram = "xterm"`.

(The inverse question would be, are packages required to set `meta.mainProgram` when the attribute name in Nixpkgs is the same as the main binary name?  If so, this requirement should be clearly documented in the above README.)

## Checklist

- [X] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates (I only sort of did this.  It is hard to search for `mainProgram` without getting a bunch of irrelevant issues)
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by cdepillabout** [comment]
Let me cc @infinisil, since I'm guessing he would likely know the answer to this (or at least be able to cc someone else who would).

**Comment by raphaelr** [comment]
> (The inverse question would be, are packages required to set meta.mainProgram when the attribute name in Nixpkgs is the same as the main binary name? If so, this requirement should be clearly documented in the above README.)

meta.mainProgram should be set explicitly when it makes sense. Since 23.11 accesssing `meta.mainProgram` raises a warning if it wasn't set explicitly.

**Comment by yu-re-ka** [comment]
> For any package that exposes a "main" binary.
> 
> In this case, even a package like xterm (which is a top-level attribute in Nixpkgs called xterm), would also be
> required to set meta.mainProgram = "xterm".

this is correct

**Comment by kirillrdy** [comment]
> > For any package that exposes a "main" binary.
> > In this case, even a package like xterm (which is a top-level attribute in Nixpkgs called xterm), would also be
> > required to set meta.mainProgram = "xterm".
> 
> this is correct

I interpret that mainProgram is required for any derivation that has something executable in $out/bin

**Comment by yu-re-ka** [comment]
> I interpret that mainProgram is required for any derivation that has something executable in $out/bin

not correct.

for example, pkgs.coreutils  has something executable in $out/bin, but it should not have a mainProgram, because what would be the mainProgram of coreutils

**Comment by kirillrdy** [comment]
@yu-re-ka I agree that coreutils shouldn't have mainProgram

but just out curiosity coreutils actually contians bin/coreutils

```
nix run nixpkgs#coreutils -- --help
Usage: /nix/store/khndnv11g1rmzhzymm1s5dw7l2ld45bc-coreutils-9.4/bin/coreutils --coreutils-prog=PROGRAM_NAME [PARAMETERS]... 
Execute the PROGRAM_NAME built-in program with the given PARAMETERS.

      --help        display this help and exit
      --version     output version information and exit

Built-in programs:
 [ b2sum base32 base64 basename basenc cat chcon chgrp chmod chown chroot cksum comm cp csplit cut date dd df dir dircolors dirname du echo env expand expr factor false fmt fold ginstall groups head hostid id join kill link ln logname ls md5sum mkdir mkfifo mknod mktemp mv nice nl nohup nproc numfmt od paste pathchk pinky pr printenv printf ptx pwd readlink realpath rm rmdir runcon seq sha1sum sha224sum sha256sum sha384sum sha512sum shred shuf sleep sort split stat stdbuf stty sum sync tac tail tee test timeout touch tr true truncate tsort tty uname unexpand uniq unlink uptime users vdir wc who whoami yes

Use: '/nix/store/khndnv11g1rmzhzymm1s5dw7l2ld45bc-coreutils-9.4/bin/coreutils --coreutils-prog=PROGRAM_NAME --help' for individual program help.

GNU coreutils online help: <https://www.gnu.org/software/coreutils/>
Full documentation <https://www.gnu.org/software/coreutils/coreutils>
or available locally via: info '(coreutils) Multi-call invocation'
```

**Comment by SuperSandro2000** [comment]
I would like to throw in, that we should document that mainProgram should not be set to pname which was the previous behaviour.

**Comment by Atemu** [comment]
Note that `meta.mainProgram` is also used in `lib.getExe` which has different constraints.

The argument for this I've seen and to which I nowadays agree is that you could guess the mainProgram based on pname (and indeed `nix run` does this) but, in pure Nix, there is no way to know whether that executable will actually exist in the built store path. `pkgs.foo` may simply not have a binary under `${pkgs.foo}/bin/foo` but `lib.getExe` would happily return that string. Using the result of that would lead to a confusing error at runtime.  
`nix run` can get away with guessing because it has access to the built path and can then display a sane error message. (Though even there I could see the argument that it probably shouldn't even try to do so.)

Additionally, implicit creation of `meta.mainProgram` implies that every package A. has executables and B. has an executable that would be considered its "main" program.  
I assert that this is not possible to determine automatically and must be done via manual human input.

My conclusion is that `meta.mainProgram` should explicitly be declared when a main program exists for these reasons, even if it's the same as `pname`.

**Comment by infinisil** [comment]
I agree with @Atemu on this, 

> * For _any package_ that exposes a "main" binary.
>       In this case, even a package like `xterm` (which is a top-level attribute in Nixpkgs called `xterm`), would also be required to set `meta.mainProgram = "xterm"`.

I agree that this is what it should mean. A PR to the contributor docs would be great :)
