### ISSUE TITLE
[Tracking Issue] Sunset scripted initrd and scripted networking

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixpkgs#287308]
## Issue description

This is about sunsetting our code for scripted initrd and scripted networking, including scripted initrd networking.

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

**Comment by misuzu** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/264967 https://github.com/NixOS/nixpkgs/issues/251388

**Comment by BeatLink** [comment]
Any update on this?

**Comment by mweinelt** [comment]
New Installation default to networkmanager with #421082.

**Comment by ctheune** [comment]
Greetings from the SaltSprint! This is a report where we spend time on reviving this issue and making a plan and get commitment from some interested parties to work on it. I'm piggy-backing on this issue to ensure interested parties that weren't at the sprint get sufficient visibility. We tried coming up with a plan that could be moved to the description of this issue or make a new issue to replace this one.

# Requirements

There are multiple overlapping requirements that we tried to untangle and come up with a "unified" approach that can be executed as serial steps that will enable new capabilities over time, shift workloads towards alternatives and hopefully this is the way the scripted networking ends: not with a bang but a whimper.

The goals we want to get under one umbrella:

1. Make systemd-networkd (finally) the default backend.
2. Implementing an alternative network stack for users where systemd-networkd is not a good fit.
3. Getting rid of scripted networking.

I'm one of the founders of the Flying Circus and we've been on record for relying on scripted networking a lot (with some patches) and are reluctant to go down the systemd-networkd route for multiple reasons - including reliability, predictability, and others.

We investigated [ifstate](https://ifstate.net/2.4/) at the sprint which already has a NixOS module and resonates with us as an alternative to systemd-networkd from a data center / server side perspective. Also, the author is not directly a member of the NixOS community but has colleagues already working on the NixOS integration, so there's interest and potential from multiple parties here. Also, ifstate presents itself as a mature and active network config management suite and is also receptive to outside contributions.

Talking to people (like @arianvp) at the sprint there was a strong signal that `networking.*` is intended for users to declaring a baseline networking configuration that is independent of the network stack implementation. Having multiple actual implementations thus should be a goal when scripted networking is retired to keep this promise in the long term. This is in contrast to the stance on supporting only systemd as an init system.

# Step 1: NixOS 26.11 – cleanups and resuming work 

* [ ] Introduce `networking.backend` as a proper option ("none", "systemd-networkd", "ifstate", "scripted") to select the networking stack implementation. 
* [ ] (?) Mark `scripted-networking` as deprecated and announce removal in 28.11.
* [ ] (?) Mark `useNetworkd` as deprecated - review and clean up where it gets used.
* [ ] (?) Make `systemd-networkd` the default option. (See #10001) 
* [ ] Introduce "ifstate" as a new backend that is basically a noop `task` module but manages `resolvconf` and allow using the ifstate module directly.
* [ ] Resume some light touch maintenance on scripted networking, upstream [Flying Circus patches](https://github.com/NixOS/nixpkgs/compare/nixos-26.05...flyingcircusio:nixpkgs:nixos-26.05) around interface renaming and some dependencies to reduce breakage and workload to focus work on upstream instead of downstream integration issues.
* [ ] Make interface renaming a supported option via `networking.interfaces.<foo>.permanentMacAddress` and provide scripted-networking and systemd-networkd integration.
* [ ] provide basic test cases for ifstate

# Step 2: NixOS 27.05

* [ ] establish a policy and go through open issues related to scripted networking and close them off and/or provide guidance where to direct it instead
* [ ] provide "shadow" mode for ifstate so scripted-networking can be enabled but an ifstate config can be generated and used to check whether ifstate agrees with the state achieved by scripted networking.
* [ ] start working on ifstate config generator from `networking.*` (XXX select use cases we want to support here)
* [ ] review systemd `network*` target unit integration for ifstate

# Step 3: NixOS 27.11

* [ ] more ifstate config generator

# Step 4: NixOS 28.05

* [ ] reach feature completeness for `networking.*` with ifstate

# Step 5: NixOS 28.11

* [ ] rip out scripted networking

**Comment by mweinelt** [comment]
>  Introduce networking.backend as a proper option

That sounds like we'll continue maintaining an abstraction going forward. I'm reluctant to accept that as a good idea. The better approach imo is that people use the direct configuration facilities of their network managment tool (ifstate, networkd, networkmanager), so they get the full expressiveness, and we get a low maintenance burden.

Is the only reason here to provide a migration path for existing users of the `networking.interfaces` options?

>  Make interface renaming a supported option via networking.interfaces.<foo>.permanentMacAddress and provide scripted-networking and systemd-networkd integration.

I think this can be achieved through both ifstate and networkd, but who wants to maintain parity for networkmanager for example? After all networkmanager is very capable and iirc the default on RHEL.

> > Are there still plans to remove scripted networking?

> At least the backend.

I think my opinion might have changed a bit in the last year. 🤔

**Comment by ctheune** [comment]
The discussions at the sprint indicated everyone being happy to maintain `networking.*` as an abstraction. Are you saying `networking.*` should be removed completely? I guess that would be an option as well.

I think there is a place for this kind of abstraction - without having to go overboard with it, to help people bootstrap on / get into NixOS without having to initially decide which network stack to go to and then have the ability for a graceful migration and leveraging the full power of their committed stack when they want to. In my experience this can layer nicely if we don't overcomplicate it.

> > > Are there still plans to remove scripted networking?
> 
> > At least the backend.
> 
> I think my opinion might have changed a bit in the last year. 🤔

I'm not sure what this means. :)

**Comment by ctheune** [comment]
Also: maybe not having an abstraction is absolutely fine. It does reduce a ton of work if deemed superfluous / a non-goal. It will hide our progress regarding being ready to get rid of scripted networking, though. My estimation is still that we'll need that time to move off it - it just won't be visible. Maybe we need more voices on this to make a decision.

@MarcelCoding any input from your side as you started the work on the ifstate module?

**Comment by mweinelt** [comment]
> > I think my opinion might have changed a bit in the last year. 🤔
> 
> I'm not sure what this means. :)

I'm apparently now also opposing the frontend.

> The discussions at the sprint indicated everyone being happy to maintain networking.* as an abstraction. Are you saying networking.* should be removed completely? I guess that would be an option as well.

I'm wary about having a `networking.backend` option that requires parity among multiple implementations and responsive maintainers which we haven't always had in the past. Or if someone wanted to add an option they'd now be forced to build it for multiple backends or create the relevant asserts.

> In my experience this can layer nicely if we don't overcomplicate it.

And this is the part that requires not only proper design but also active gatekeepers, that block requests that go overboard.

**Comment by BeatLink** [comment]
I think its a good idea to keep the networking.xxx options as an abstraction, especially since many other modules depend on the values of those options to configure their settings. If networking.xxx options were removed and were replaced with the direct options like systemd-networkd or networkmanager, I'm pretty sure that those dependent modules would need to be updated to check and manage all of those potential direct configurations.

**Comment by mweinelt** [comment]
```
❯ rg networking.interfaces nixos/modules/ -l
nixos/modules/tasks/network-interfaces-systemd.nix
nixos/modules/tasks/network-interfaces.nix
nixos/modules/tasks/network-interfaces-scripted.nix
nixos/modules/hardware/facter/networking/default.nix
nixos/modules/system/boot/initrd-network.nix
nixos/modules/virtualisation/google-compute-config.nix
nixos/modules/virtualisation/nixos-containers.nix
nixos/modules/rename.nix
nixos/modules/services/networking/tayga.nix
nixos/modules/services/security/hologram-agent.nix
nixos/modules/services/networking/yggdrasil.md
nixos/modules/services/networking/dhcpcd.nix
nixos/modules/virtualisation/virtualbox-host.nix
```

I don't think that is *many* modules.

**Comment by BeatLink** [comment]
Okay fair enough. Then it might be better to go the direct route after all.

**Comment by ctheune** [comment]
> I'm apparently now also opposing the frontend.

Are we still agreeing that people should be able to run different network config stacks? 

> > In my experience this can layer nicely if we don't overcomplicate it.
> 
> And this is the part that requires not only proper design but also active gatekeepers, that block requests that go overboard.

Yeah, giving that set of options an explicit mission would be helpful there - which will require some people to come up with a better definition and maybe some retrospective on how it appeared initially.

> ```
> ❯ rg networking.interfaces nixos/modules/ -l
> nixos/modules/tasks/network-interfaces-systemd.nix
> nixos/modules/tasks/network-interfaces.nix
> nixos/modules/tasks/network-interfaces-scripted.nix
> nixos/modules/hardware/facter/networking/default.nix
> nixos/modules/system/boot/initrd-network.nix
> nixos/modules/virtualisation/google-compute-config.nix
> nixos/modules/virtualisation/nixos-containers.nix
> nixos/modules/rename.nix
> nixos/modules/services/networking/tayga.nix
> nixos/modules/services/security/hologram-agent.nix
> nixos/modules/services/networking/yggdrasil.md
> nixos/modules/services/networking/dhcpcd.nix
> nixos/modules/virtualisation/virtualbox-host.nix
> ```
> 
> I don't think that is _many_ modules.

Now this is more interesting. If the general idea is that you CAN run different networking stacks on NixOS, then looking at the backreferences will be interesting. If we do not have a frontend, then basically all back-references to any specific
implementations will lead to fraction and or make alternative stacks completely unviable.

(We could put an inversion of control thing there and instead of making it a frontend one could imagine the different stacks providing values that can be depended upon by others, but that's for read-dependencies, not write-dependencies.)

**Comment by mweinelt** [comment]
> > I'm apparently now also opposing the frontend.
> 
> Are we still agreeing that people should be able to run different network config stacks?

I absolutely agree that people should be able to mix and match different network config stacks on the same host even.

> If we do not have a frontend, then basically all back-references to any specific
implementations will lead to fraction and or make alternative stacks completely unviable.

A generic introspection of the network configuration can get complicated fast, especially because we don't lock the user into a generic interface. Introspection is great, but would need to be built individually downstream in my scenario.

**Comment by ctheune** [comment]
So IMHO that means the various network stack implementations will still have do work to ensure compatibility and we need to ensure that authors of more specific application level modules MUST not ever reference back to any specific stack, right?

I mean, those are challenges, but we can document those as guidelines and use them as a basis for stewardship and see whether this results in constructive or destructive chaos ... ;)
