### ISSUE TITLE
[Tracking issue] remove all `src = ./.` entries that unintentionally include their own `.nix` files

### ISSUE THREAD

**Issue by philiptaron** [NixOS/nixpkgs#301014]
## Issue description

Derivations that use `src = ./.` will be rebuilt on any change to the `.nix` file that includes them, including formatting changes caused by `nixfmt-rfc-style` for [RFC 166](https://github.com/NixOS/rfcs/blob/master/rfcs/0166-nix-formatting.md).

### List of files where this may be the case

Generated with `rg -F 'src = ./.' --sort=path -l -tnix` and not very thoroughly audited. Unchecked entries need work or attention.

- [x] [doc/default.nix](https://github.com/NixOS/nixpkgs/blob/master/doc/default.nix#L102): https://github.com/NixOS/nixpkgs/pull/319875
- [x] [maintainers/scripts/convert-to-import-cargo-lock/default.nix](https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/convert-to-import-cargo-lock/default.nix#L7) (uses `cleanSourceWith`)
- [x] [nixos/lib/test-driver/default.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/test-driver/default.nix#L20): https://github.com/NixOS/nixpkgs/pull/319878
- [x] [pkgs/build-support/node/fetch-npm-deps/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/node/fetch-npm-deps/default.nix#L9) (uses `cleanSourceWith`)
- [x] [pkgs/build-support/release/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/release/default.nix#L99) (only in a comment)
- [x] [pkgs/build-support/rust/test/import-cargo-lock/basic/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/basic/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/basic-dynamic/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/basic-dynamic/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/git-dependency/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/git-dependency/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/git-dependency-branch/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/git-dependency-branch/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/git-dependency-rev/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/git-dependency-rev/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/git-dependency-rev-non-workspace-nested-crate/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/git-dependency-rev-non-workspace-nested-crate/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/git-dependency-tag/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/git-dependency-tag/default.nix#L7) #303146
- [x] [pkgs/build-support/rust/test/import-cargo-lock/v1/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/test/import-cargo-lock/v1/default.nix#L7) #303146
- [x] [pkgs/by-name/pu/purescm/package.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/pu/purescm/package.nix#L18)
- [x] [pkgs/by-name/pu/purescm/package.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/pu/purescm/package.nix#L22)
- <s>[ ] [pkgs/development/compilers/ghcjs/8.10/stage0.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/ghcjs/8.10/stage0.nix#L72)</s> (not used)
- <s>[ ] [pkgs/development/compilers/pakcs/curry-frontend.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/pakcs/curry-frontend.nix#L9)</s> (not used)
- [x] [pkgs/development/compilers/reason/tests/hello/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/reason/tests/hello/default.nix#L7): https://github.com/NixOS/nixpkgs/pull/319883
- [x] [pkgs/development/cuda-modules/saxpy/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/cuda-modules/saxpy/default.nix#L25): https://github.com/NixOS/nixpkgs/pull/319886
- [x] [pkgs/development/interpreters/python/tests/test_nix_pythonprefix/typeddep/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/tests/test_nix_pythonprefix/typeddep/default.nix#L9): https://github.com/NixOS/nixpkgs/pull/319888
- [x] [pkgs/development/julia-modules/tests/julia-top-n/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/julia-modules/tests/julia-top-n/default.nix#L7): https://github.com/NixOS/nixpkgs/pull/320580
- [x] [pkgs/development/libraries/nanopb/test-message-with-annotations/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/nanopb/test-message-with-annotations/default.nix#L6): https://github.com/NixOS/nixpkgs/pull/315684
- [x] [pkgs/development/libraries/nanopb/test-message-with-options/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/nanopb/test-message-with-options/default.nix#L6): https://github.com/NixOS/nixpkgs/pull/315684
- [x] [pkgs/development/libraries/nanopb/test-simple-proto2/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/nanopb/test-simple-proto2/default.nix#L6): https://github.com/NixOS/nixpkgs/pull/315684
- [x] [pkgs/development/libraries/nanopb/test-simple-proto3/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/nanopb/test-simple-proto3/default.nix#L6): https://github.com/NixOS/nixpkgs/pull/315684
- [x] [pkgs/development/libraries/science/math/libtorch/test/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/science/math/libtorch/test/default.nix#L30): https://github.com/NixOS/nixpkgs/pull/320579
- [x] [pkgs/development/libraries/science/math/mkl/test/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/science/math/mkl/test/default.nix#L15) #323634
- [x] [pkgs/development/ocaml-modules/reason-native/tests/console/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/ocaml-modules/reason-native/tests/console/default.nix#L7) #322767
- [x] [pkgs/development/python-modules/spacy/annotation-test/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/spacy/annotation-test/default.nix#L6) #319939
- [x] [pkgs/development/python-modules/spacy-transformers/annotation-test/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/spacy-transformers/annotation-test/default.nix#L6) #319939
- [x] [pkgs/development/python-modules/waitress-django/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/waitress-django/default.nix#L8) https://github.com/NixOS/nixpkgs/pull/313628
- [x] [pkgs/development/tools/yarn2nix-moretea/yarn2nix/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/yarn2nix-moretea/yarn2nix/default.nix#L403): https://github.com/NixOS/nixpkgs/pull/320578
- [x] [pkgs/misc/documentation-highlighter/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/documentation-highlighter/default.nix#L11) (uses `cleanSourceWith`)
- [ ] [pkgs/servers/mx-puppet-discord/node-packages.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/mx-puppet-discord/node-packages.nix#L3261)
- [x] [pkgs/servers/sip/kamailio/test-kamailio-bin/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sip/kamailio/test-kamailio-bin/default.nix#L6) #312519
- [x] [pkgs/test/haskell/cabalSdist/local/generated.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test/haskell/cabalSdist/local/generated.nix#L6): https://github.com/NixOS/nixpkgs/pull/320572
- [x] [pkgs/test/haskell/setBuildTarget/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test/haskell/setBuildTarget/default.nix#L10): https://github.com/NixOS/nixpkgs/pull/320572
- [x] [pkgs/tools/nix/nixos-option/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/nix/nixos-option/default.nix#L13) #307564 #307936 #325614
- [x] [pkgs/tools/system/dell-command-configure/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/system/dell-command-configure/default.nix#L58) #307479

**Comment by oliviacrain** [comment]
Did a quick check for false positives:

#### Uses `lib.cleanSourceWith` to filter out default.nix

[pkgs/build-support/node/fetch-npm-deps/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/node/fetch-npm-deps/default.nix#L9) 
[maintainers/scripts/convert-to-import-cargo-lock/default.nix](https://github.com/NixOS/nixpkgs/blob/master/maintainers/scripts/convert-to-import-cargo-lock/default.nix#L7)
[pkgs/misc/documentation-highlighter/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/documentation-highlighter/default.nix#L11)

#### Found `src = ./.` in a comment

[pkgs/build-support/release/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/release/default.nix#L99)

**Comment by philiptaron** [comment]
Thanks! I updated the listing to check those off.

**Comment by infinisil** [comment]
Note that we can use the new [`lib.fileset`](https://nixos.org/manual/nixpkgs/unstable/#sec-functions-library-fileset) library ([tutorial](https://nix.dev/tutorials/file-sets)) to fix this now!

**Comment by infinisil** [comment]
Made a bunch of PRs to fix some of these, see the links above :)

**Comment by philiptaron** [comment]
> Made a bunch of PRs to fix some of these, see the links above :)

All ✅ by me or someone else.

**Comment by infinisil** [comment]
Also mentioning it here, this is a hack to print the filtered out files of a fileset by default :P:

```diff
diff --git a/lib/fileset/default.nix b/lib/fileset/default.nix
index bb327226731e..32bfcf21ecf6 100644
--- a/lib/fileset/default.nix
+++ b/lib/fileset/default.nix
@@ -123,6 +123,7 @@ let
     isPath
     pathExists
     seq
+    trace
     typeOf
     nixVersion
     ;
@@ -473,6 +474,8 @@ in {
             - Set `fileset` to a file set that cannot contain files outside the `root` (${toString root}). This could change the files included in the result.''
     else
       seq sourceFilter
+      trace "lib.fileset.toSource: These files are excluded:"
+      seq (_printFileset (_difference (_singleton root) fileset))
       cleanSourceWith {
         name = "source";
         src = root;

```

**Comment by infinisil** [comment]
Whoops it looks like we missed https://github.com/NixOS/nixpkgs/pull/300428

**Comment by philiptaron** [comment]
For [pkgs/tools/nix/nixos-option/default.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/nix/nixos-option/default.nix#L13), consider merging https://github.com/NixOS/nixpkgs/pull/313497 instead.

**Comment by Atemu** [comment]
@Infinidoge and I fixed fetchYarnDeps unaware of this tracking issue. It appears to have been missed in this list somehow, perhaps your regex needs updating.

https://github.com/NixOS/nixpkgs/pull/319623

**Comment by infinisil** [comment]
Fixing a bunch here: https://github.com/NixOS/nixpkgs/pull/326430

**Comment by philiptaron** [comment]
I think this is done.
