### ISSUE TITLE
NixOS 24.05 — Feature Freeze & Release Blockers

### ISSUE THREAD

**Issue by wegank** [NixOS/nixpkgs#303286]
Hi, we are [Weijia Wang](https://github.com/wegank) & [Jörg Thalheim](https://github.com/Mic92), the [release managers](https://nixos.github.io/release-wiki/Release-Managers.html) for NixOS 24.05 ("_Uakari_").

As we approach the next release of NixOS, it's time to discuss the upcoming feature freeze period. We want to ensure that this release is as stable and reliable as possible, and your contributions are crucial to achieving that goal, here are the two upcoming dates in that context:

- **2024-04-17**: Restrict breaking changes to [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html)
- **2024-05-01**: Restrict all breaking changes except for desktop environments.

The complete timeline is available here:

- https://github.com/NixOS/nixpkgs/issues/303285

The first restriction will be in place very soon, therefore, we encourage all teams to check in now and mention possible roadblocks, so we get a good overview of what's ahead.

# Blockers

Whether you were pinged or not, we encourage everyone to create issues for release blockers and add them to the [24.05 Blockers project](https://github.com/orgs/NixOS/projects/59).

# Check-in

Please comment your status quo and possible issues as soon as possible. We'll check teams once they have checked in.

If you think some subsystem, person or team should be added or removed from this list, update `maintainers/team-list.nix` in time before the next feature freeze announcement.

# Desktop environments

- [x] Cinnamon: @bobby285271 @mkg20001
- [x] DDE: @wineee
- [x] Enlightenment: @NixOS/enlightenment
- [x] GNOME: @NixOS/gnome @bobby285271 @dasj19 @amaxine
- [x] Lomiri: @OPNA2608
- [x] Lumina: @NixOS/lumina
- [x] LXQt: @NixOS/lxqt
- [x] MATE: @bobby285271 @johannesloetzsch @romildo
- [x] Pantheon: @NixOS/pantheon
- [x] Qt / KDE: @NixOS/qt-kde @ilya-fedin @K900 @LunNova @mjm @NickCao @SuperSandro2000
- [x] Xfce: @bobby285271 @romildo @muscaln

# Platforms

- [x] Darwin: @NixOS/darwin-maintainers

# Languages ecosystem

- [x] BEAM: @NixOS/beam @minijackson
- [x] C: @matthewbauer @Mic92
- [x] Coq: @CohenCyril @Zimmi48 @siraben @vbgl @Alizter
- [x] Dhall: @Gabriella439 @ehmry
- [x] Go: @NixOS/golang
- [x] Haskell: @NixOS/haskell
- [x] Lisp: @NixOS/lisp @hraban
- [x] Lua: @NixOS/lua
- [x] Node.js: @lilyinstarlight @marsam @winterqt
- [x] OCaml: @NixOS/ocaml @Alizter @vbgl
- [x] Perl: @stigtsp
- [x] PHP: @NixOS/php
- [x] Python: @FRidh @mweinelt @jonringer @tjni
- [x] R: @bcdarwin @jbedo
- [x] Ruby: @marsam
- [x] Rust: @NixOS/rust
- [x] Zig: @AndersonTorres @figsoda

# Compilers, build systems

- [x] Bazel: @mboes @marsam @uri-canva @avdv @olebedev @groodt @aherrmann @ylecornec
- [x] LLVM: @dtzWill @Ericson2314 @lovek323 @alyssais @RossComputerGuy @rrbutani @sternenseemann

# Programs

- [x] Geospatial: @NixOS/geospatial @l0b0

# Modules

- [x] ACME: @aanderse @andrew-d @arianvp @emilazy @flokli @m1cr0man
- [x] systemd: @NixOS/systemd

# Core

- [x] Docs:
- [x] Marketing: @garbas @tomberek
- [x] Module system: @infinisil @roberth
- [x] Nix/nix-cli ecosystem: @NixOS/nix-team 
- [x] NixOS tests: @tfc

# Everyone Else

@NixOS/nixpkgs-committers @NixOS/release-engineers

# Finally

No issue is too big or too small, but let's remember that we are all working on the project voluntarily in our free time here, so let's focus on issues that can be realistically addressed in the remaining time before the release.

We thank everyone for their contribution!

**Comment by wegank** [comment]
(Reserved for pings)

**Comment by RossComputerGuy** [comment]
On my side, LLVM is good to go. I would like to get #299807 in but isn't a blocker. If it can get in before the release then that'll be cool.

**Comment by K900** [comment]
Plasma is as good as it's going to be probably, though #300933 would be nice to get in.

**Comment by tfc** [comment]
@wegank The only thing regarding NixOS tests that should ideally be sorted before the next release is the situation regarding https://github.com/NixOS/nixpkgs/pull/303187 and https://github.com/NixOS/nixpkgs/pull/303150. 

Should be a minor thing but i consider it important.
Summary: NixOS integration tests work just fine on macOS, but currently they are marked as not supported by the `platform` list. Just need to resolve this.

**Comment by ElvishJerricco** [comment]
I would be very disappointed if 24.05 didn't include systemd stage 1 by default, but I do have a lot of work left to make that happen. [This issue](https://github.com/NixOS/nixpkgs/issues/287308) looks worse than it is. Hopefully I can power this out in the next week or two. Any help would be appreciated.

**Comment by arianvp** [comment]
I would like to have https://nixos.github.io/amis either linked from the homepage or integrated into the homepage. So that people are aware again that there are AWS AMIs for 24.05!

**Comment by imincik** [comment]
Geospatial software (@NixOS/geospatial) is in pretty good shape, no major changes are required, just regular maintenance.

**Comment by maralorn** [comment]
I think the Haskell packages are fine since we just updated to GHC 9.6. We will do another round of "remove all broken flags and see how many packages do actually build now" before release, but we have plenty of time for that.

**Comment by raboof** [comment]
For the [Reproducible Builds initiative in NixOS](https://reproducible.nixos.org), I think we are in good shape: for us the only blockers should be issues that prevent reproduction of the minimal iso. While https://github.com/orgs/NixOS/projects/30 does list some of those, the jfsutils nondeterminism seems sporadic and the others have known workarounds.

**Comment by garbas** [comment]
> I would like to have https://nixos.github.io/amis either linked from the homepage or integrated into the homepage. So that people are aware again that there are AWS AMIs for 24.05!
> 
> Happy to coordinate with the marketing team on this

Awesome work. Let's get this work done ... are you able to do this work yourself, or you need some help from the marketing team?

The relevant code is here:
- https://github.com/NixOS/nixos-homepage/blob/main/src/components/pages/download/AWSTable.astro
- https://github.com/NixOS/nixos-homepage/blob/main/flake.nix#L63-L65

**Comment by hraban** [comment]
Lisp compilers are good to go 👍

**Comment by wineee** [comment]
No blockers for deepin

deepin will release v23 at the end of May, and I plan to port it on 24.11

**Comment by bobby285271** [comment]
No blockers for all GNOME-adjacent desktop environments [I maintain](https://hydra.nixos.org/dashboard/rjl931189261@126.com) so far, unfortunately I lost track of GNOME 46 update progress and I believe I really need to get around to test all the stuff there.

**Comment by superherointj** [comment]
I'm sorry. I have messed the topic message above. I have by mistake clicked on the checkbox not knowing it would edit the message. Now I need to revert it.

**Comment by SuperSandro2000** [comment]
We have a blocker for an unknown amount of wrapped python applications which unfortunately is a mass rebuild https://github.com/NixOS/nixpkgs/pull/302385

**Comment by jbedo** [comment]
R is good to go :+1:

**Comment by matklad** [comment]
Vivaldi browser is currently broken with plasma 6:

https://github.com/NixOS/nixpkgs/pull/286522#issuecomment-1960433519

I have a hacky PR which fixes this issue by allowing the user to explicitly opt-into plasma 6:

https://github.com/NixOS/nixpkgs/pull/292148

Would be good to fix this properly though, but I am unlikely to do that.

**Comment by happysalada** [comment]
Beam ecosystem (erlang , elixir...) Has no blockers .

**Comment by ulrikstrid** [comment]
Not sure if this should be considered a blocker but without https://github.com/NixOS/nixpkgs/pull/299589 `composable_kernel` in the ROCm packages is not cached by hydra and since it takes multiple hours to build even on a 64 core machine it's essentially unusable without the cache.

Cc @mschwaig

**Comment by mschwaig** [comment]
> Not sure if this should be considered a blocker but without #299589 `composable_kernel` in the ROCm packages is not cached by hydra and since it takes multiple hours to build even on a 64 core machine it's essentially unusable without the cache.
> 
> Cc @mschwaig

Yes. Landing https://github.com/NixOS/nixpkgs/pull/299589 would be important, since I would consider ROCm 6.0 effectively broken without it. If we cannot backport this later I would consider it a blocker.

It would be nice it we could also get in get in https://github.com/NixOS/nixpkgs/pull/298388, to get ROCm working out of the box on more GPUs, since there are users on stable releases, who have opened issues related to that (https://github.com/NixOS/nixpkgs/issues/302412).

**Comment by thufschmitt** [comment]
Regarding Nix, we plan on releasing 2.22 next week, and we'd like to have that be the version included in NixOS 24.05

**Comment by RaitoBezarius** [comment]
> Regarding Nix, we plan on releasing 2.22 next week, and we'd like to have that be the version included in NixOS 24.05

We can make it an `nixUnstable` version but I am not so sure a `nixStable` attribute can be made so fast and in time for this NixOS' release window, unfortunately.

**Comment by jonringer** [comment]
I agree with @RaitoBezarius , I think some time on nixpkgs unstable is warranted to ensure that there's no obvious regressions. (e.g. submodule flake usage broke in 2.20)

**Comment by lf-** [comment]
> Regarding Nix, we plan on releasing 2.22 next week, and we'd like to have that be the version included in NixOS 24.05

I don't think this is a good idea personally, nix releases historically need time to bake, perhaps like a month of being the unstable to knock out the regressions not caught by people running the development branch (does anyone do that?), and it's too late in the release cycle to make that happen imo.

**Comment by RossComputerGuy** [comment]
> I don't think this is a good idea personally, nix releases historically need time to bake, perhaps like a month of being the unstable to knock out the regressions not caught by people running the development branch (does anyone do that?), and it's too late in the release cycle to make that happen imo.

Agreed, I was thinking of updating the default LLVM version but it was decided to not do that until after 24.05 for a similar reason. We don't want sudden regressions before a release. Maybe after a release and it isn't backported then that would be fine.

**Comment by reckenrode** [comment]
I had a hope that I might be able to get cctools and ld64 updated for the release, but they’re going to have to wait because the refactoring I’m doing along with the update is too much change this close to the release. I was hoping https://github.com/NixOS/nixpkgs/pull/301354 could make it, but it’s probably going to have to wait.

> Agreed, I was thinking of updating the default LLVM version but it was decided to not do that until after 24.05 for a similar reason. We don't want sudden regressions before a release. Maybe after a release and it isn't backported then that would be fine.

Darwin will be updating as well (since the plan after last year’s stdenv work was to do the update annually). If it helps make things easier, I can wait until after Linux is updated. I wouldn’t do the update on Darwin anyway until the 18.1.x update cycle ends to avoid requiring LLVM 18 updates go through staging.

**Comment by infinisil** [comment]
No blockers for the module system :)

Just a brief note regarding `lib`, I plan to write release notes for all changes to it, like [I did last release](https://github.com/NixOS/nixpkgs/pull/268871)

**Comment by SomeoneSerge** [comment]
No blockers for CUDA specifically, but there is a related PR open where a decision needs to be made about the recently introduced `virtualisation.containers.cdi` before the release: https://github.com/NixOS/nixpkgs/pull/290979 (CC @ereslibre).

**Comment by jonringer** [comment]
For python, we are doing a `python-updates` round, and that's the major changes I would like to see before going into ZHF.

cc @mweinelt for any additional python changes he would like to see as well.

**Comment by marsam** [comment]
- **Ruby**
  No blockers. 
  I wanted make [Ruby 3.2 the default](https://github.com/NixOS/nixpkgs/pull/289621), I think it's quite safe but I didn't have the time to fully test it.

- **Node.js**
  No blockers
  `master` now has Node.js [v22.0.0](https://github.com/nodejs/node/tree/v22.0.0), and I removed [v21.7.3](https://github.com/nodejs/node/tree/v21.7.3) since it was going to EOL during the 25.05 release
  
- **Bazel**
  No blockers

- **PostgreSQL**
  No blockers for PostgreSQL

---
This is my [last involvement with NixOS](https://github.com/NixOS/nixpkgs/pull/306702), so I wish you a very successful 25.05 release.

**Comment by ShamrockLee** [comment]
Sylabs SingularityCE (`singularity`) on `master` fails to execute images.

The fix is now available as #306730, but that unfortunately includes behavioral changes and argument/configuration option deprecation. Is it possible to backport a fix like this one with deprecation warning omitted?

Cc: @GaetanLepage @jbedo @SomeoneSerge

**Comment by Mic92** [comment]
* **C**
  No blocker as far as I know. Everything is up-to-date.

**Comment by ryantm** [comment]
Can you remove me from the docs contact? I am no longer the best contact here.

**Comment by teto** [comment]
Lots of improvements on the lua side for this release. There is a big last one pending in staging then I'll need to fix 2/3 of 3 packages for ZHF. 
I would like to bring neovim plugin transitive dependencies in the wrapper (e.g, you install rocks.nvim, it brings all its lua dependencies in scope, which doesnt work at the moment). I have it working locally and it shouldn't be breaking but I will have other people betatest.

**Comment by wegank** [comment]
NixOS 24.05 released! https://discourse.nixos.org/t/nixos-24-05-released/46279/2
