### ISSUE TITLE
First-class Wayland support in Nixpkgs - meta/tracking issue

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixpkgs#30753]
## Issue description

Eventually we will (will we?) move to Wayland instead of X so let's gather all the issues here that are related to that. The added benefit is that it should make it easier to get more people to try out wayland.

- [ ] Anti-aliasing disabled in konsole when running as a wayland session, #30752
- [ ] KDE Wayland session uses llvmpipe for OpenGL, not hardware acceleration, #30649 
- [ ] SDL: wayland support, #30827 
- [ ] xwayland: enable acceleration with help of glamor, #30828

References:
 - #30493

**Comment by 7c6f434c** [comment]
Maybe this should be called «First-class Wayland support in Nixpkgs» tracking issue?

I mean, Linux supports using more than one VT, so having fully functional Wayland is nice even while Xorg stays the default.

**Comment by NeQuissimus** [comment]
Our discussion on #30493 may also be relevant

**Comment by gnidorah** [comment]
> - [ ]  KDE Wayland session uses llvmpipe for OpenGL, not hardware acceleration, #30649

I have the same issue in sway, though my videocard if fresh enough:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel Open Source Technology Center (0x8086)
    Device: Mesa DRI Intel(R) HD Graphics 505 (Broxton)  (0x5a84)
    Version: 17.2.2
    Accelerated: yes
    Video memory: 3072MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
```

**Comment by gnidorah** [comment]
Some PRs regarding graphics acceleration https://github.com/NixOS/nixpkgs/pull/30827 https://github.com/NixOS/nixpkgs/pull/30828

**Comment by Eisfreak7** [comment]
#5071 is relevant, too.

**Comment by peterhoeg** [comment]
Closing as I created a project for this that should make it easier to keep track of the various bits.

https://github.com/NixOS/nixpkgs/projects/11
