### ISSUE TITLE
Tracking issue for Darwin stdenv LLVM update: LLVM 16 -> LLVM 18

### ISSUE THREAD

**Issue by reckenrode** [NixOS/nixpkgs#309365]
This is the tracking issue for this year’s LLVM update for Darwin. Linux is already on LLVM 17, but both will be going to LLVM 18. My goal with this issue is to document common problems as well as their fixes. I’ve encountered a few breaking changes so far that have common solutions. Unlike last year’s update, the Darwin stdenv is in pretty good shape. It’s other packages that need fixed.

The target is to do the update early after the release of 24.05, so there is time to fix problems.

Previous tracking issue: https://github.com/NixOS/nixpkgs/issues/234710

### error: non-private labels cannot appear between .cfi_startproc / .cfi_endproc pairs

This is due to https://github.com/llvm/llvm-project/commit/d506aa4edfa66074db3dc1fa84da9d9c80d71500. It affects GCC and compiler-rt versions from LLVM 17 and earlier.

- [ ] https://github.com/NixOS/nixpkgs/pull/309405

### error: '\_\_abi_tag\_\_' attribute only applies to structs, variables, functions, and namespaces

This is a GCC bug when bootstrapping against newer versions of libc++. It is fixed upstream, but the patches are not yet available on a released version of GCC 6 through GCC 13.

### undefined symbol: `__availability_version_check`

LLVM 17 weakly links `_availability_verison_check`, but it is not available in the SDK until 10.15. This error shouldn’t happen because it has been fixed, but if it does, the fix is to revert back to finding the symbol at runtime using `dlsym`.

- [ ] https://github.com/NixOS/nixpkgs/pull/309385

### C23 attributes expose bugs in attribute macros

Clang 18 adds support for C23 attributes, which gnulib will use preferentially. Unfortunately, older versions of gnulib either don’t try or don’t detect correctly whether the compiler supports `inline` in headers. This results in trying to use `static [[__maybe_unused__]]`, which is not valid C23.

Packages that use gettext with autoreconfHook will have `m4/extern-inline.m4` clobbered. If running `autoreconf` is not strictly necessary, the issue can be fixed by dropping the hook. Otherwise, the update to gettext should fix the issue.

- [ ] https://github.com/NixOS/nixpkgs/pull/299647

Another example is darwin.system_cmds, which attempts to use `static [[noreturn]]`. Even though `static _Noreturn` is valid in C11, `_Noreturn` is deprecated in C23, and `[[noreturn]]` is intended to replace `_Noreturn`, `static [[noreturn]]` is not valid C23. The fix is to use `[[noreturn]] static` instead.

### Incompatible vendored dependencies

Some vendored dependencies are incompatible with clang 18. If the issue has been fixed upstream (and in nixpkgs) and the package supports it, switch the vendored dependency to the fixed package in nixpkgs. Otherwise, you’ll have to patch the vendored dependency to fix the issue.

**Comment by reckenrode** [comment]
Darwin was updated to LLVM 19 in https://github.com/NixOS/nixpkgs/pull/354107.
