### ISSUE TITLE
[Tracking] Improve JDK infrastucture

### ISSUE THREAD

**Issue by jlesquembre** [NixOS/nixpkgs#313216]
This issue tracks all the issues and pull requests related to improving the JDK infrastucture on nixpkgs (See
https://discourse.nixos.org/t/improve-the-jdk-infrastructure-on-nixpkgs/)

I will continue to update this issue as new pull requests or issues are created. While discussions should primarily take place on the corresponding issues themselves, feel free to leave a comment here if you believe something relevant
has been missed.

## Automate JDK version updates

- [x] https://github.com/NixOS/nixpkgs/pull/306616
  - [x] https://github.com/NixOS/nixpkgs/pull/318742
- [ ] #301653
- [x] https://github.com/NixOS/nixpkgs/pull/286267
  - [x] #313920 
  - [x] #313923 
  - [x] #313925 
  - [x] #313927 
  - [x] #313928 
  - [x] #313929
  - [x] #314377 
  - [x] #314378 
  - [x] #314380 
  - [x] #314381

## Remove old/unused JDK derivations

- [ ] https://github.com/NixOS/nixpkgs/pull/310466
- https://github.com/NixOS/nixpkgs/issues/313208
- https://github.com/NixOS/nixpkgs/issues/313211
- https://github.com/NixOS/nixpkgs/issues/313210

## Build OpenJDK

- https://github.com/NixOS/nixpkgs/issues/313209
- https://github.com/NixOS/nixpkgs/issues/313212
  -  https://github.com/NixOS/nixpkgs/pull/350736
- https://github.com/NixOS/nixpkgs/issues/313213
  - [x] #316300
- #314873

## Documentation

To be done

---

cc @doronbehar @rjpcasalino @nessdoor @raboof @Infinidoge

**Comment by liff** [comment]
Does #301653 count as a JDK version update automation? Even though JBR is pretty specifically for JetBrains IDEs…

**Comment by Infinidoge** [comment]
It does. Whether we like it or not, it's a JDK.

**Comment by Infinidoge** [comment]
#286267 has been split into a number of smaller PRs:
- #313920 (merged)
- #313923 (merged)
- #313925 (draft)
- #313927 (open)
- #313928 (draft)
- #313929 (merged)
- #314377 (open)
- #314378 (open)
- #314380 (open)
- #314381 (open)

I expect several of these to need to be switched over to staging, but I'm waiting until OfBorg evals them and until I have enough spoons to actually do that. I've already accidentally failed one cross-branch rebase today, I'm not going it again.

Lesson learned, break up PRs as much as possible.

**Comment by msgilligan** [comment]
I'm a new Nixpkgs contributor and my knowledge of Nix is still fairly limited, but I would like to help with this. I have made a few minor contributions to the JDK packages:

* PR #421362
* PR #421637

I assigned myself to this task (partly to make it easier to find in the future) and definitely not to say I can make more than a handful of small contributions, but I do have some ideas for improvements and would like to work on them.

**Comment by msgilligan** [comment]
Idea 1:

Create a Nix JDK Package dashboard. This would be a Nixpkgs utility module/package that uses metadata from the various JDK packages to generate a (JSON?) file containing a table that lists all the major versions of each package and has columns like "current version", "is free", "platforms supported", "has JavaFX", "is alias", etc.

The JSON could be transformed to HTML for easy viewing, either as a build option, a separate module, etc.

As I am new to Nixpkgs, I would love input or suggestions as to how this could be done.

Stretch goal: For Nix JDK packages that provide an updater (to find the latest version) list which packages are up-to-date or EOL.

~~If there is interest, I will create an issue for this where we can continue discussion.~~

I created an issue for this task as I have started working on it:

* Issue #425860

**Comment by msgilligan** [comment]
Idea 2:

Create a JDK test module that could be used to perform basic testing on any of the JDK packages (e.g. openjdk, zulu, graalvm-ce, etc.) This would be an expansion and generalization of PR #421637 and similar existing tests. It could be called with metadata that describes whether a JDK package provides optional features (e.g. JavaFX or `jpackage`.) At a minimum it could simply invoke each tool in the JDK with a `--help` option  (e.g. `java`, `javac`, `jar`, `jlink`, `jpackage` etc.) It could also compile some simple Java examples.

Ultimately we might be able to port something link [Eclipse AQAvit™](https://adoptium.net/aqavit/) to Nixpkgs.

If there is interest, I will create an issue for this where we can continue discussion.
