### ISSUE TITLE
[tracking] aarch64 build on Packet Type 2A

### ISSUE THREAD

**Issue by vielmetti** [NixOS/nixpkgs#31606]
## Issue description

A tracking issue to work on a release of NixOS to the Packet "Type 2A" Cavium ThunderX servers.

### Steps to reproduce

Log in to Packet, http://packet.net . Try to provision a Type 2A server with NixOS, notice that NixOS is missing as an operating system choice.

## Technical details

* System: Packet Type 2A https://www.packet.net/bare-metal/servers/type-2a/ (Cavium ThunderX dual socket 96-core ARMv8)

## See also

Packet Community Slack #worksonarm channel

The issue on the Packet Trello board is https://trello.com/c/Rv5YQb7T/127-support-nixos-on-armv8

**Comment by dezgeg** [comment]
As for image building, here's my recollection of what needs to be done:
- [ ] Figure out how to run KVM virtual machines on those servers
- [ ] Figure out whether to use `make-disk-image.nix` or my `sd-image.nix` image building infra
    - `make-disk-image.nix` (I expect this is the better solution):
         - depends on KVM
         - also depends on lkl which has bunch of arch-specific stuff
         - can already build images that do legacy booting with GRUB on x86, presumably easy to convert to EFI grub
    - `sd-image.nix`
        - doesn't need KVM
        - doesn't do GRUB (currently)
        - grub-install (even for EFI) might not like being run without root
        - the GRUB config generator probably doesn't like being run in Nix builder context without major surgery
              - in theory could just hand-write an initial grub.cfg, but sounds like maintenance disaster
 - [ ] Figure out what options to make the GRUB output its menu over the serial console for recovering (IIRC it didn't with what NixOS currently writes to grub.cfg)

**Comment by copumpkin** [comment]
We could probably kill the KVM dependency in `make-disk-image.nix` with a bit more effort. I think the OpenWRT project figured out how to convince qemu to install to an image, and if necessary we could also submit a patch upstream. See [here](https://wiki.openwrt.org/doc/howto/vmware) and [here](https://dev.openwrt.org/browser/trunk/target/linux/x86/image/Makefile?rev=49407#L107).

**Comment by copumpkin** [comment]
> grub-install (even for EFI) might not like being run without root

TBC, `grub-install` is the only reason `make-disk-image` uses KVM. It's the only thing I wasn't able to do in a pure builder.

**Comment by dezgeg** [comment]
Note that I expect EFI GRUB installation to be easier as non-root than legacy GRUB installation, given how much 'simpler' it is. There you just write the files to a filesystem and you are done. In legacy mode, you write some stuff to the MBR, some raw sectors to the unpartitioned space between the MBR and the first filesystem, then some files to the filesystem again... with all those three parts somehow co-operating.

With that said, wow https://dev.openwrt.org/browser/trunk/target/linux/x86/image/Makefile?rev=49407#L69 indeed does look promising.

**Comment by bjornfor** [comment]
Another alternative is genimage. Buildroot uses it to create MBR and EFI bookable disk images. No root or VM needed.

**Comment by dezgeg** [comment]
Hmm, crap. LKL gives:
````
make: Entering directory '/tmp/nix-build-lkl-2017-08-09.drv-0/linux-083cdeece0577635d523244dcf0da86074e23e4e-src/tools/lkl'
Makefile:82: *** Unrecognized platform: elf64-littleaarch64.  Stop.
````

**Comment by grahamc** [comment]
PR here incorporates some netboot patches I've had kicking around: https://github.com/NixOS/nixpkgs/pull/32031

After that PR merges, we should recycle the branch for further testing, as https://hydra.nixos.org/jobset/nixos/unstable-aarch64 is setup already.

**Comment by volth** [comment]
Anyone succeeded with KVM on those machines?

I see that
```
# ls -l /dev/kvm
crw-rw-rw- 1 root root 10, 232 Dec  6 03:31 /dev/kvm

# qemu-system-aarch64 -machine type=virt,accel=kvm -cpu host
KVM_SET_DEVICE_ATTR failed: No such device
Aborted
```

```strace``` shows that an ```ioctl``` call failed.

Perhaps KVM works with a proper kernel/qemu combination (I used master's default: kernal-4.9.66 and qemu-2.10.1)

**Comment by volth** [comment]
```qemu``` without ```kvm``` works well on Pocket 2A (but slow).
So if the problem is only about how to run the image builder, it might be the answer.

**Comment by dezgeg** [comment]
It's somehow related to the GIC virtualization options that need to be set on that hardware: https://bugzilla.redhat.com/show_bug.cgi?id=1375571.

**Comment by dezgeg** [comment]
Yep. And with `gic-version=host` it also works on machines with GICv2 (such as the Jetson TX1). I wonder who decided the default value for that option... Anyway, done in https://github.com/NixOS/nixpkgs/commit/b2e315f97f645fc70627febd43ddd62dd4de1412

**Comment by volth** [comment]
>  Anyway, done in b2e315f

Besides Pocket 2A there are ```Cavium```s at Scaleway, which are sliced into KVM virtual servers with no nested KVM possible :(

It might have sense to add check for existence of ```/dev/kvm``` and add drop ```-enable-kvm -cpu host``` if the file is absent, similar to https://github.com/NixOS/nixpkgs/blob/59d60ea7f66260fe243fe4410e0af9ec469551ff/pkgs/applications/virtualization/qemu/default.nix#L109

**Comment by grahamc** [comment]
Long done =)
