### ISSUE TITLE
glibc 2.26 breakage tracking issue

### ISSUE THREAD

**Issue by orivej** [NixOS/nixpkgs#31696]
Here is the list of packages that broke due to the glibc upgrade in #28622 and have not been fixed yet, with `|` separating dependent packages. (The maintainers are mentioned here to be notified, not to assign the work.)

- [x] afl (@thoughtpolice) (15ba4a5cfd13966a54e0b66dafd2f39f3e95ba34)
- [x] bochs (@AndersonTorres) (4cc5d222ce596fd79d9541c1eb7e7c2b0164bec3)
- [x] ~breakpad~ (#31746; see #31748)
- [x] chez (@thoughtpolice) (72de80f)
- [x] clisp-tip (@7c6f434c, @tohl) (c127e94)
- [x] criu (@thoughtpolice) (f8077b7ef114955ade79bd71ec1c0b2dfc8d98df)
- [x] dgsh (@vrthra) (ff7be8f807dc41c340ff9a21b49421da6ab87e71)
- [x] gcc-snapshot (e188747d89e89442876d2c178a34d4db1ec807b0: mark as broken)
- [x] gvpe (@7c6f434c) (f55308e)
- [x] inadyn (@viric) (34f4b97a50d316e859059b4e7aa83e48d5cc0b10)
- [x] kcov (@FlorentBecker) (30fa830633fb29c2cfb704bfe3fdbf76c168aa35)
- [x] kmscon (5018c27a3d3dd049b6b0adbb416e29bbdb835905)
- [x] libaal | reiser4progs (@fuuzetsu) (3835526a9479e6aa19e36bf045fc19ca2ad89002)
- [x] ~libnscd~ (ea011d65a8bfc41d1edaa3200b0abe41f588f11c, c0794dc140c3b43a1b57d7f54adda24a0513bb39: delete)
- [x] libreswan | hash-slinger (@afranchuk) (a7daf37c3ec1e255a94b0479f027783c87954d35)
- [x] mkcl (@tohl) (35e52ff)
- [x] obliv-c (@7c6f434c) (7f8bc042cc66682af06f6828bb4762af1e7b75e4; see https://github.com/samee/obliv-c/issues/48)
- [x] pgpool | pgpool93 pgpool94 (@wkennington) (68a703b4059a59e8411db7e01b1a308fce5ac561)
- [x] ptlib | opal sipcmd (@7c6f434c) (f96b3bf8717f11191cecdafd3fe8ff96ca02df52)
- [x] rdf4store (@7c6f434c) (6ab109a6732cf8a8e7335d50f3ee4db95d1568b7)
- [x] vpcs (@primeos) (41e0d4b68d15e771002afb09690bd0305c04bfea)
- [x] #31700 nss lookups on many non-NixOS distros broken after glibc upgrade

**Comment by 7c6f434c** [comment]
Partial status report:
`obliv-c`: https://github.com/samee/obliv-c/issues/48
`ptlib`: no life since last release in GNOME; maybe switch to http://opalvoip.sf.net/ version
`gvpe`: no life since latest release `3.0`, Debian included. Sad.
`clisp-tip`: pushed a fix.

**Comment by orivej** [comment]
I've fixed a bunch: gvpe, ptlib, rdf4store, libnscd.

**Comment by orivej** [comment]
Another bunch: kcov, kmscon, libaal, pgpool, libreswan.

**Comment by orivej** [comment]
Done: vpcs, idanyn, bochs, afl, breakpad, gcc-snapshot.

**Comment by orivej** [comment]
Fixed build of the remaining criu, dgsh, obliv-c.
