### ISSUE TITLE
Haskell binaries with excessive closure sizes on aarch64-darwin

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nixpkgs#318013]
As you may remember from #140774, GHC on aarch64-darwin can't properly eliminate dead code, leading to a lot of references if `Paths_` modules are involved that may not be necessary.

A common case is that binaries that depend on other libraries that use a `Paths_` module will incure a reference on that library's `out` path despite being statically linked against the library (even though the reference itself is dead code). On other platforms (even x86_64-darwin) GHC is able to eliminate such references, but not on aarch64-darwin. For such packages, `justStaticExecutables` is practically useless since GHC is pulled in transitively.

@9999years has contributed an extra check to `justStaticExecutables` which prevents this scenario (#304352). As a consequence, a few packages are broken on aarch64-darwin. In the interest of landing the bundled changes from `haskell-updates` soon, I'll disable `justStaticExecutables` for the following packages on aarch64-darwin since it wasn't doing much anyways:

- [ ] hadolint
- [ ] haskell-ci
- [ ] hci @roberth 
- [ ] hercules-ci-agent @roberth
- [ ] matterhorn
- [ ] hledger-web @maralorn
- [ ] shake @ncfavier
- [ ] stack @cdepillabout 
- [ ] emanote (effective on all platforms since the reference was present everywhere) @srid

This will take effect when #315167 is merged.

Maintainers are encouraged to submit a workaround for the issue on aarch64-darwin via `remove-references-to` (which seems to be the only solution at the moment) and to reenable justStaticExecutables. Examples for such fixes are:

- https://github.com/NixOS/nixpkgs/commit/2901eb87d663306293047ada0e1ec72ec988df75
- https://github.com/NixOS/nixpkgs/commit/caa1c9699601fb63ccbccdb88aac6e2a1a6223f8

Please make sure these fixes are conditional to aarch64-darwin.

**Comment by roberth** [comment]
I've opened https://github.com/NixOS/nix/pull/10877 to make this easier to analyze.
Worth a try it, especially if you have no idea what to even look for, but if you're running a `nix-daemon` you'll have to run e.g. `sudo nix run github:hercules-ci/nix/report-forbidden-path-as-chain build <your actual thing>`, with `sudo` so that the freshly built Nix will build on its own instead of letting the old daemon do it.

**Comment by erics118** [comment]
I'm willing to fix the remaining packages and add back the usage of `justStaticExecutables`.

I just made a PR for reducing closure size for hadolint. Once that PR gets approved, I can start working on the other packages
