### ISSUE TITLE
.NET 6/7 are EOL

### ISSUE THREAD

**Issue by JamieMagee** [NixOS/nixpkgs#326335]
.NET 7 went EOL on 14th May 2024[^1]. Similar to #202572, which dealt with the deprecation of .NET Core 3.1, we should make an effort to update or patch packages whick rely on .NET 7.

## Packages

- [ ] `pkgs/applications/audio/famistudio/default.nix`
- [x] `pkgs/applications/audio/openutau/default.nix`
  - #340611 
- [ ] `pkgs/applications/blockchains/wasabibackend/default.nix`
- [ ] `pkgs/applications/editors/jetbrains/default.nix`
- [x] `pkgs/applications/graphics/pinta/default.nix`
  - #327375
- [ ] `pkgs/by-name/be/beatsabermodmanager/package.nix`
  - #339370
- [x] `pkgs/by-name/do/dotnet-outdated/package.nix`
  - #361048
- [ ] `pkgs/by-name/lu/lumafly/package.nix`
- [ ] `pkgs/by-name/pa/pablodraw/package.nix`
- [ ] `pkgs/by-name/pu/pupdate/package.nix`
- [x] `pkgs/by-name/re/retrospy/package.nix`
  - #326461
- [x] `pkgs/by-name/ro/roslyn-ls/package.nix`
  - #318497
- [x] `pkgs/development/tools/fsautocomplete/default.nix`
  - #326130
- [x] `pkgs/development/tools/misc/netcoredbg/default.nix`
  - #329845
- [x] `pkgs/development/tools/omnisharp-roslyn/default.nix`
  - #343690
- [ ] `pkgs/games/vintagestory/default.nix`
- [x] `pkgs/tools/security/certdump/default.nix`
  - #352540

[^1]: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core

**Comment by konradmalik** [comment]
netcoredbg will stop relying on dotnet 7 with this PR: https://github.com/NixOS/nixpkgs/pull/329845
roslyn-ls was upgraded with https://github.com/NixOS/nixpkgs/pull/318497

**Comment by pyrox0** [comment]
`pinta` now uses dotnet 8, see #327375
`fsautocomplete` relies only on the 8.0 sdk at runtime but still needs 6 and 7 for building.

**Comment by gepbird** [comment]
IMO we can use this issue for also tracking .NET 6 packages:
- [ ] doc/languages-frameworks/dotnet.section.md
- [ ] alttpr-opentracker
- [ ] am2rlauncher
- [ ] avalonia-ilspy
- [ ] azure-functions-core-tools
- [ ] beatsabermodmanager
- [ ] blendfarm
- [ ] boogie
- [ ] clr-loader
- [ ] cyclonedx-cli
- [ ] dafny
- [ ] dotnet-outdated
- [ ] eventstore
- [ ] formula
- [ ] fsautocomplete
- [ ] garnet
- [ ] gh-gei
- [ ] ilspycmd
- [ ] inklecate
- [ ] knossosnet
- [ ] kryptor
- [ ] msbuild
- [ ] naps2
- [ ] networkminer
- [ ] omnisharp-roslyn https://github.com/NixOS/nixpkgs/pull/360598
- [ ] openra
- [ ] ps3-disc-dumper
- [ ] roslyn
- [ ] roslyn-ls
- [ ] scarab
- [ ] sonarr
- [ ] space-station-14-launcher
- [ ] tone
- [ ] vrcadvert

**Comment by corngood** [comment]
beatsabermodmanager: #361128

**Comment by konradmalik** [comment]
removing both 6 and 7 from roslyn-ls: https://github.com/NixOS/nixpkgs/pull/357963 - looking for reviewers/mergers.

**Comment by GGG-KILLER** [comment]
> - [ ] space-station-14-launcher https://github.com/NixOS/nixpkgs/pull/361563

Hi, just wanted to note that https://github.com/NixOS/nixpkgs/pull/361563 isn't actually removing neither .NET 6 nor 7 from any packages, it just changes how they depend on it so that *temporarily* (and mistakenly) they don't get marked as insecure. However we should still actually remove any references from .NET 6 and 7 from any packages modified on it.

**Comment by corngood** [comment]
`godot_4-mono` seems to be missing from this list.  specific issue here: https://github.com/NixOS/nixpkgs/issues/365975

**Comment by GGG-KILLER** [comment]
`eventstore` has a newer version upstream with .NET 8 support, however the license has been changed to an unfree one.

**Comment by GGG-KILLER** [comment]
`msbuild` repository has been archived. We should probably remove it.

**Comment by GGG-KILLER** [comment]
Unable to upgrade `naps2` as it uses some APIs that are marked as preview when building with a patch that changes `TargetFramework`s to `net8` instead of `net6`:

```
...
/build/source/NAPS2.Escl.Server/EsclApiController.cs(310,62): error CA2252: Using 'Aborted' requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252) [/build/source/NAPS2.Escl.Server/NAPS2.Escl.Server.csproj::TargetFramework=net8]
/build/source/NAPS2.Escl.Server/EsclApiController.cs(322,40): error CA2252: Using 'ContentType' requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252) [/build/source/NAPS2.Escl.Server/NAPS2.Escl.Server.csproj::TargetFramework=net8]
/build/source/NAPS2.Escl.Server/EsclApiController.cs(325,23): error CA2252: Using 'WriteDocumentTo' requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252) [/build/source/NAPS2.Escl.Server/NAPS2.Escl.Server.csproj::TargetFramework=net8]
/build/source/NAPS2.Escl.Server/EsclApiController.cs(339,37): error CA2252: Using 'Processing' requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252) [/build/source/NAPS2.Escl.Server/NAPS2.Escl.Server.csproj::TargetFramework=net8]
/build/source/NAPS2.Escl.Server/EsclApiController.cs(339,62): error CA2252: Using 'Completed' requires opting into preview features. See https://aka.ms/dotnet-warnings/preview-features for more information. (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2252) [/build/source/NAPS2.Escl.Server/NAPS2.Escl.Server.csproj::TargetFramework=net8]
    1 Warning(s)
    163 Error(s)

Time Elapsed 00:00:04.39
```

**Comment by GGG-KILLER** [comment]
`space-station-14-launcher` has an upgrade upstream (https://github.com/space-wizards/SS14.Launcher/commit/ed386b8a40a6a635cce7e1cbe221d697cb8f6d2a) but hasn't turned into a release yet, should an unstable version of it be made?

There are no maintainers so I'm unsure if this package should be kept at all unless if someone else picks it up.

**Comment by GGG-KILLER** [comment]
Taking care of `alttpr-opentracker`, `am2rlauncher`, `avalonia-ilspy`, `clr-loader`, `dafny`, `formula`, `gh-gei`, `ilspycmd`, `inklecate` and `knossosnet` over at https://github.com/NixOS/nixpkgs/pull/366067

**Comment by eliandoran** [comment]
> Unable to upgrade `naps2` as it uses some APIs that are marked as preview when building with a patch that changes `TargetFramework`s to `net8` instead of `net6`:

OK, I'll have a look. Maybe in the newer version of NAPS2 they updated to a newer version of .NET.

**Comment by FliegendeWurst** [comment]
> `msbuild` repository has been archived. We should probably remove it.

There is the newer https://github.com/dotnet/msbuild/ we can use instead.

**Comment by oynqr** [comment]
> `space-station-14-launcher` has an upgrade upstream ([space-wizards/SS14.Launcher@ed386b8](https://github.com/space-wizards/SS14.Launcher/commit/ed386b8a40a6a635cce7e1cbe221d697cb8f6d2a)) but hasn't turned into a release yet, should an unstable version of it be made?
> 
> There are no maintainers so I'm unsure if this package should be kept at all unless if someone else picks it up.

`space-station-14-launcher` no longer depends on dotnet 6 since https://github.com/NixOS/nixpkgs/pull/362431 was merged.

On another note, ever since https://github.com/NixOS/nixpkgs/pull/359409, the launcher has been broken for me (the launcher itself starts fine, but it can't launch the game). Since apparently only myself and one other unfortunate soul on the ss14 discord have ran into this, I'd guess the overall usage of this package is low.

**Comment by jDanek** [comment]
> `msbuild` repository has been archived. We should probably remove it.
> 
> I'll do it in a separate PR from the ones I'm doing currently. I'll have to figure out how removals work in `pkgs/by-name`.
> 
> cc: @jirkadanek

Hi, I was wondering why I got the notification. I get it now, same name different person. Could still be a half-brother :D 

Merry Christmas wishes jDanek :D

![image](https://github.com/user-attachments/assets/5c5a4b78-9eee-4146-96b9-71462c5429e4)

**Comment by GGG-KILLER** [comment]
> > `msbuild` repository has been archived. We should probably remove it.
> 
> There is the newer https://github.com/dotnet/msbuild/ we can use instead.

That's already part of the .NET SDK, I think the only use it had was compiling .NET Framework projects on Linux, but I don't know how to move on with those as I don't think there are .NET Framework targeting packs for Linux

**Comment by GGG-KILLER** [comment]
> Hi, I was wondering why I got the notification. I get it now, same name different person. Could still be a half-brother :D 
> 
> Merry Christmas wishes jDanek :D

Yeah, my bad 😅 
I got used to most people using their GitHub usernames in the maintainers list that I didn't double check, I'm sorry.

**Comment by konradmalik** [comment]
hmm, any idea what could've happened to roslyn-ls In the past week?
In my flake that uses it I've removed insecurePackages on Dec 10th and it worked fine, but today it started generating errors about insecure dotnet 6 again, and the trace points to roslyn-ls. I see there was only this https://github.com/NixOS/nixpkgs/commit/1cd9516969553291792021f1b327f0e2e2775b3c but it does not look like it could change that behavior...

I have automatic dep updates on that flake every Friday, so it worked on Dec 10th (manual update), worked on Dec 13th, and stopped working somewhere between Dec 13th and Dec 20th (today).

In particular, this works: https://github.com/konradmalik/neovim-flake/actions/runs/12253416030, and today this failed: https://github.com/konradmalik/neovim-flake/actions/runs/12424292928

**Comment by konradmalik** [comment]
@GGG-KILLER thanks, this makes sense. @corngood suggested that this could help with the insecurePackages warning. Seems like it does not, which is fine, but I still do not understand why it did not generate warnings for me for more than a week and started to do so again today.

**Comment by GGG-KILLER** [comment]
> Seems like it does not,which is fine, but I still do not understand why it did not generate warnings for me for more than a week and started to do so again today.

It used to, before we merged a change that made usage of packages from .NET 6 and 7 generate insecure warnings.
So for a short while that "solved" the warnings (but shouldn't have, which is why we made that change).

**Comment by GGG-KILLER** [comment]
gh-gei was done in https://github.com/NixOS/nixpkgs/pull/366482 already. Will remove it from my PR.

**Comment by JamieMagee** [comment]
Looks like the remaining packages are:
- .NET 7.0
  - avalonia
  - wasabibackend
- .NET 6.0
  - eventstore
  - msbuild
  - networkminer
  - openraPackages.engines.release
  - roslyn

**Comment by gepbird** [comment]
Thanks for the reminder!

Here's what I know of these packages (I'll be updating this comment):

- .NET 7.0
  - avalonia
  - wasabibackend: waiting for review, was tested by one person: https://github.com/NixOS/nixpkgs/pull/361232, cc @mmahut ,
- .NET 6.0
  - eventstore
  - msbuild
  - networkminer: recently a new version was released, [download source](https://www.netresec.com/?page=NetworkMinerSourceCode), [home page with changelogs](https://www.netresec.com/?page=NetworkMiner), looking at the csproj files, I see `<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>`, how was this .NET 6 before and not the old .NET Framework 4.8? cc @emilytrau
  - openraPackages.engines.release: there's `openraPackages.engines.bleed` which is the next version using .NET 8, when will it replace stable? cc @mdarocha 
  - roslyn

**Comment by dtomvan** [comment]
Vintagestory will move to dotnet 8 by the next stable release, and it's already in prerelease.

**Comment by corngood** [comment]
avalonia at #423073

**Comment by JamieMagee** [comment]
eventstore: https://github.com/NixOS/nixpkgs/pull/436377

**Comment by JamieMagee** [comment]
vintagestory: #436539

**Comment by pyrox0** [comment]
since msbuild is archived upstream, I believe it should be fine to remove. Packages depending on it should have migrated to an alternative solution if they're still maintained, and if they're not, that is also an argument for removing them.

These packages still depend on `msbuild`:

- `eddie`
- `networkminer`
- `spotlight-downloader`

**Comment by corngood** [comment]
Sorry I didn't realise that `msbuild` is the mono version.

> https://github.com/mono/msbuild/ is archived, but that's because the repository was moved to https://github.com/dotnet/msbuild/. So it does still exist, and is actively maintained.

But we're still talking about the `msbuild` package which is using the former repo, right:

https://download.mono-project.com/sources/msbuild/msbuild-${version}.tar.xz

**Comment by corngood** [comment]
`msbuild` actually does build if you just switch it to SDK 8.  I don't think it actually uses the SDK for anything important.  It seems to just do horrific stuff like:

```
    ln -s $(find ${dotnet-sdk.unwrapped}/share/dotnet -name libhostfxr${sharedLibrary}) artifacts/mono-msbuild/SdkResolvers/Microsoft.DotNet.MSBuildSdkResolver/
```

In fact, it doesn't even need `dotnet-sdk` in `nativeBuildInputs`.  It only has it there so `dotnet-sdk-setup-hook.sh` will run and configure nuget stuff.

**Comment by corngood** [comment]
> Yeah, so if we do decide to do the update, we'd need to update from [the `v16.9.0` tag](https://github.com/mono/msbuild/releases/tag/v16.9.0) in `mono/msbuild` to [the `v17.14.13` tag](https://github.com/dotnet/msbuild/releases/tag/v17.14.13) in `dotnet/msbuild`. Or maybe something like [the `v16.11.6`](https://github.com/dotnet/msbuild/releases/tag/v16.11.6) or [`16.9.2` tag](https://github.com/dotnet/msbuild/releases/tag/v16.9.2) doing it step-by-step.

I think I'm a bit lost, but I'm not sure how this would practically help build something like `networkminer`.  We already have msbuild 17.whatever in `dotnet-sdk`, so we could just use that, right?

> When I say it supports net472, I mean it supports it as a runtime i.e. you can run msbuild on .NET Framework. Not that it provides the targeting pack. The targeting pack comes from mono.

I always thought that there was something special in mono/msbuild that made this work.

For now I made a PR to move msbuild to sdk 8: #436941.

**Comment by JamieMagee** [comment]
> I think I'm a bit lost, but I'm not sure how this would practically help build something like `networkminer`. We already have msbuild 17.whatever in `dotnet-sdk`, so we could just use that, right?

Yeah, I think we can build `networkminer` using `dotnet msbuild`.

I think the only difference between using `msbuild` package versus `dotnet msbuild` from the `dotnetCorePackages.sdk_8_0` is the closure will be larger. `sdk_8_0` includes the .NET runtime, base class library, etc. We'd need `mono` and `sdk_8_0`.

I am okay with that, if it works.

> I always thought that there was something special in mono/msbuild that made this work.
> 
> For now I made a PR to move msbuild to sdk 8: [#436941](https://github.com/NixOS/nixpkgs/pull/436941).

According to the mono 5.0.0 release notes[^1] they are the same:

> Over the past year we have been working to integrate the open-sourced msbuild build tool into Mono. It is now available as part of your Mono installation, and it is the same [MSBuild](https://github.com/Microsoft/msbuild) that is used on .NET on Windows.

[^1]: https://www.mono-project.com/docs/about-mono/releases/5.0.0/#msbuild

**Comment by corngood** [comment]
> Yeah, I think we can build networkminer using dotnet msbuild.

I had a go at this.  First thing I hit was `TargetFrameworkRootPath` wasn't being set automatically in certain projects (e.g. NetworkMiner.csproj).  I think maybe just the old-style projects?  I hacked that in, and then I hit:

https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/msbuild/errors/msb3822.md

I'm not really motivated to put any more work into it right now, but it would be handy to have better support for these old projects.  We can start a new PR for that if/when one of us wants to investigate some more.

**Comment by gepbird** [comment]
There are some new packages that depend on .NET 6:
- [ ] tshock
- [ ] renode
- [ ] python3Packages.pythonnet

**Comment by gepbird** [comment]
Renode should support .NET 9 by upstream: https://github.com/renode/renode/issues/715#issuecomment-2610030452
cc @otavio @znaniye

**Comment by JamieMagee** [comment]
Looks like we're down to 3 packages still on .NET 6
 
- `pkgs/games/openra/engines/release/default.nix` - uses `sdk_6_0-bin`
- `pkgs/development/python-modules/pythonnet/default.nix` - uses `dotnet-sdk_6`
- `pkgs/by-name/ts/tshock/package.nix` - uses `dotnet-sdk_6` and `dotnet-runtime_6`

**Comment by JamieMagee** [comment]
I think we are done 🎉 

See you in November for the .NET 8/9 EOL 😅
