### ISSUE TITLE
Qt4 deprecation tracking issue

### ISSUE THREAD

**Issue by yanalunaterra** [NixOS/nixpkgs#33248]
List of files mentioning Qt4:

* [ ] nixos/modules/i18n/input-method/uim.nix
* [x] nixos/modules/programs/ccache.nix
* [x] nixos/modules/programs/environment.nix
* [x] pkgs/applications/altcoins/bitcoin-unlimited.nix
* [ ] ~pkgs/applications/altcoins/bitcoin-xt.nix~
* [ ] ~pkgs/applications/altcoins/btc1.nix~
* [ ] pkgs/applications/altcoins/dogecoin.nix
* [ ] ~pkgs/applications/altcoins/freicoin.nix~
* [x] pkgs/applications/altcoins/litecoin.nix
* [ ] ~pkgs/applications/altcoins/memorycoin.nix~
* [ ] pkgs/applications/altcoins/namecoin.nix
* [ ] ~pkgs/applications/altcoins/primecoin.nix~
* [x] pkgs/applications/altcoins/zcash/default.nix
* [x] pkgs/applications/audio/cantata/default.nix
* [x] pkgs/applications/audio/clementine/default.nix #89821
* [ ] pkgs/applications/audio/faust/faust2alqt.nix
* [ ] pkgs/applications/audio/faust/faust2jaqt.nix
* [ ] pkgs/applications/audio/faust/faust2lv2.nix
* [ ] ~pkgs/applications/audio/google-musicmanager/default.nix~
* [x] pkgs/applications/audio/hydrogen/default.nix
* [ ] pkgs/applications/audio/hydrogen/0.nix
* [x] pkgs/applications/audio/jackmix/default.nix
* [x] pkgs/applications/audio/kid3/default.nix
* [x] pkgs/applications/audio/mixxx/default.nix
* [x] pkgs/applications/audio/pianobooster/default.nix
* [x] pkgs/applications/audio/picard/default.nix
* [x] pkgs/applications/audio/projectm/default.nix #82427 #89821
* [x] pkgs/applications/audio/puddletag/default.nix #96645
* [ ] pkgs/applications/audio/qmidiroute/default.nix
* [x] pkgs/applications/audio/qtractor/default.nix
* [ ] pkgs/applications/audio/qtscrobbler/default.nix
* [ ] pkgs/applications/audio/soundscape-renderer/default.nix
* [ ] ~pkgs/applications/audio/tomahawk/default.nix~
* [ ] pkgs/applications/audio/vmpk/default.nix
* [ ] pkgs/applications/display-managers/lightdm/default.nix
* [ ] pkgs/applications/editors/texmacs/default.nix
* [x] pkgs/applications/editors/texmaker/default.nix
* [x] pkgs/applications/editors/texstudio/default.nix
* [x] pkgs/applications/editors/vim/qvim.nix #96768
* [x] pkgs/applications/gis/qgis/default.nix
* [x] pkgs/applications/graphics/djview/default.nix
* [x] pkgs/applications/graphics/fontmatrix/default.nix
* [x] pkgs/applications/graphics/freecad/default.nix
* [x] pkgs/applications/graphics/ipe/default.nix
* [ ] pkgs/applications/graphics/leocad/default.nix
* [x] pkgs/applications/graphics/openscad/default.nix
* [ ] ~pkgs/applications/graphics/photivo/default.nix~
* [ ] pkgs/applications/graphics/qscreenshot/default.nix
* [ ] ~pkgs/applications/graphics/qtpfsgui/default.nix~
* [ ] pkgs/applications/graphics/scantailor/default.nix
* [ ] pkgs/applications/graphics/screencloud/default.nix
* [ ] pkgs/applications/graphics/smartdeblur/default.nix
* [x] pkgs/applications/misc/bibletime/default.nix
* [ ] ~pkgs/applications/misc/bitcoinarmory/default.nix~
* [ ] pkgs/applications/misc/confclerk/default.nix
* [x] pkgs/applications/misc/diffpdf/default.nix
* [x] pkgs/applications/misc/diffpdf/fix_path_poppler_qt4.patch
* [x] pkgs/applications/misc/doomseeker/default.nix
* [ ] pkgs/applications/misc/electrum-dash/default.nix
* [x] pkgs/applications/misc/electrum-ltc/default.nix
* [ ] ~pkgs/applications/misc/evopedia/default.nix~
* [ ] pkgs/applications/misc/fbreader/default.nix
* [ ] pkgs/applications/misc/gnuradio/default.nix
* [x] pkgs/applications/misc/googleearth/default.nix
* [ ] pkgs/applications/misc/keepassx/2.0.nix
* [ ] pkgs/applications/misc/keepassx/default.nix
* [x] pkgs/applications/misc/librecad/default.nix
* [ ] pkgs/applications/misc/multimon-ng/default.nix
* [ ] pkgs/applications/misc/navipowm/default.nix
* [x] pkgs/applications/misc/navit/default.nix
* [x] pkgs/applications/misc/open-pdf-presenter/default.nix
* [x] pkgs/applications/misc/qlcplus/default.nix
* [ ] pkgs/applications/misc/qmetro/default.nix
* [x] pkgs/applications/misc/qpdfview/default.nix
* [x] pkgs/applications/misc/rescuetime/default.nix
* [ ] pkgs/applications/misc/sqliteman/default.nix
* [ ] pkgs/applications/misc/tpmmanager/default.nix
* [x] pkgs/applications/misc/vym/default.nix
* [ ] pkgs/applications/misc/xautoclick/default.nix
* [ ] pkgs/applications/misc/xkblayout-state/default.nix
* [ ] pkgs/applications/misc/yate/default.nix
* [x] pkgs/applications/misc/yubioath-desktop/default.nix
* [x] pkgs/applications/networking/browsers/arora/default.nix
* [x] pkgs/applications/networking/ike/default.nix
* [x] pkgs/applications/networking/instant-messengers/blink/default.nix
* [x] pkgs/applications/networking/instant-messengers/psi/default.nix
* [ ] pkgs/applications/networking/instant-messengers/pybitmessage/default.nix
* [ ] pkgs/applications/networking/instant-messengers/skype-call-recorder/default.nix
* [ ] pkgs/applications/networking/instant-messengers/vacuum/default.nix
* [x] pkgs/applications/networking/mumble/default.nix
* [ ] pkgs/applications/networking/ostinato/default.nix
* [x] pkgs/applications/networking/p2p/eiskaltdcpp/default.nix
* [x] pkgs/applications/networking/remote/teamviewer/default.nix
* [x] pkgs/applications/networking/remote/x2goclient/default.nix
* [x] pkgs/applications/networking/sync/backintime/qt4.nix - #102417
* [x] pkgs/applications/office/libreoffice/default.nix - #89395
* [x] pkgs/applications/office/libreoffice/still.nix
* [x] pkgs/applications/office/qnotero/default.nix
* [ ] pkgs/applications/office/scribus/default.nix
* [ ] pkgs/applications/office/tagainijisho/default.nix
* [ ] pkgs/applications/science/chemistry/avogadro/default.nix
* [ ] pkgs/applications/science/electronics/qfsm/default.nix
* [ ] pkgs/applications/science/electronics/qucs/default.nix
* [ ] pkgs/applications/science/medicine/aliza/default.nix
* [ ] pkgs/applications/science/misc/gplates/default.nix
* [ ] pkgs/applications/science/misc/openmodelica/default.nix
* [ ] pkgs/applications/science/misc/tulip/default.nix
* [ ] pkgs/applications/science/misc/vite/default.nix
* [ ] ~pkgs/applications/science/robotics/gazebo/default.nix~
* [x] pkgs/applications/search/recoll/default.nix
* [x] pkgs/applications/version-management/git-and-tools/git-cola/default.nix
* [x] pkgs/applications/version-management/git-and-tools/svn2git-kde/default.nix
* [ ] pkgs/applications/version-management/guitone/default.nix
* [x] pkgs/applications/version-management/tortoisehg/default.nix
* [x] pkgs/applications/video/avidemux/default.nix
* [x] pkgs/applications/video/avidemux/wrapper.nix
* [ ] ~pkgs/applications/video/avxsynth/default.nix~
* [x] pkgs/applications/video/clipgrab/default.nix
* [x] pkgs/applications/video/linuxstopmotion/default.nix
* [x] pkgs/applications/video/makemkv/default.nix
* [x] pkgs/applications/video/minitube/default.nix
* [x] pkgs/applications/video/mythtv/default.nix
* [ ] pkgs/applications/video/natron/default.nix
* [ ] ~pkgs/applications/video/qgifer/default.nix~
* [ ] ~pkgs/applications/video/recordmydesktop/qt.nix~
* [x] pkgs/applications/video/simplescreenrecorder/default.nix
* [x] pkgs/applications/video/vlc/default.nix
* [ ] pkgs/development/compilers/eql/default.nix
* [x] pkgs/development/libraries/aqbanking/gwenhywfar.nix
* [ ] pkgs/development/libraries/attica/default.nix
* [ ] pkgs/development/libraries/audio/suil/default.nix
* [ ] pkgs/development/libraries/avahi/default.nix
* [ ] pkgs/development/libraries/dssi/default.nix
* [ ] pkgs/development/libraries/grantlee/default.nix
* [ ] ~pkgs/development/libraries/gstreamer/legacy/qt-gstreamer/default.nix~
* [ ] ~pkgs/development/libraries/gstreamer/qt-gstreamer/default.nix~
* [ ] pkgs/development/libraries/libbluedevil/default.nix
* [ ] pkgs/development/libraries/libdbusmenu-qt/default.nix
* [ ] pkgs/development/libraries/libechonest/default.nix
* [ ] pkgs/development/libraries/libjreen/default.nix
* [x] pkgs/development/libraries/liblastfm/default.nix
* [x] pkgs/development/libraries/libqglviewer/default.nix
* [ ] pkgs/development/libraries/ntrack/default.nix
* [x] pkgs/development/libraries/opencascade/default.nix
* [x] pkgs/development/libraries/openscenegraph/default.nix
* [x] pkgs/development/libraries/phonon/backends/gstreamer.nix
* [x] pkgs/development/libraries/phonon/backends/vlc.nix
* [x] pkgs/development/libraries/phonon/default.nix
* [x] pkgs/development/libraries/physics/geant4/default.nix
* [ ] pkgs/development/libraries/polkit-qt-1/qt-4.nix
* [x] pkgs/development/libraries/poppler/default.nix
* [ ] pkgs/development/libraries/prison/default.nix
* [ ] pkgs/development/libraries/qimageblitz/default.nix
* [ ] pkgs/development/libraries/qjson/default.nix
* [ ] pkgs/development/libraries/qscintilla/default.nix
* [ ] pkgs/development/libraries/qt-4.x/4.8/default.nix
* [ ] pkgs/development/libraries/qt-4.x/4.8/qmake-hook.sh
* [ ] pkgs/development/libraries/qt-5/modules/qtbase.nix
* [ ] pkgs/development/libraries/qtkeychain/default.nix
* [ ] pkgs/development/libraries/qt-mobility/default.nix
* [ ] pkgs/development/libraries/qtscriptgenerator/default.nix
* [ ] pkgs/development/libraries/qwt/6_qt4.nix
* [ ] pkgs/development/libraries/qwt/default.nix
* [ ] pkgs/development/libraries/qxt/default.nix
* [ ] pkgs/development/libraries/soprano/default.nix
* [x] pkgs/development/libraries/soqt/default.nix
* [ ] ~pkgs/development/libraries/strigi/default.nix~
* [ ] ~pkgs/development/libraries/torch/default.nix~
* [ ] pkgs/development/libraries/wt/default.nix
* [x] pkgs/development/python-modules/matplotlib/default.nix
* [x] pkgs/development/python-modules/pykde4/default.nix
* [x] pkgs/development/python-modules/pykde4/kdelibs.nix
* [ ] pkgs/development/python-modules/pyqt/4.x.nix
* [ ] pkgs/development/python-modules/pyside/apiextractor.nix
* [ ] pkgs/development/python-modules/pyside/default.nix
* [ ] pkgs/development/python-modules/pyside/generatorrunner.nix
* [ ] pkgs/development/python-modules/pyside/shiboken.nix
* [ ] pkgs/development/python-modules/pyside/tools.nix
* [ ] pkgs/development/r-modules/default.nix
* [ ] pkgs/development/ruby-modules/gem-config/default.nix
* [x] pkgs/development/tools/analysis/snowman/default.nix
* [ ] pkgs/development/tools/analysis/valkyrie/default.nix
* [ ] pkgs/development/tools/build-managers/cmake/2.8.nix
* [ ] pkgs/development/tools/build-managers/cmake/default.nix
* [ ] pkgs/development/tools/documentation/doxygen/default.nix
* [ ] pkgs/development/tools/misc/automoc4/default.nix
* [x] pkgs/development/tools/misc/gede/default.nix
* [x] pkgs/development/tools/misc/xxdiff/default.nix
* [ ] pkgs/development/tools/profiling/oprofile/default.nix
* [x] pkgs/games/anki/default.nix
* [x] pkgs/games/anki/fix-paths.patch
* [ ] pkgs/games/gambatte/default.nix
* [x] pkgs/games/hedgewars/default.nix
* [ ] pkgs/games/holdingnuts/default.nix
* [x] pkgs/games/mnemosyne/default.nix
* [x] pkgs/games/openmw/default.nix
* [x] pkgs/games/pokerth/default.nix
* [ ] ~pkgs/games/sdlmame/default.nix~
* [ ] pkgs/misc/drivers/hplip/3.16.11.nix
* [x] pkgs/misc/frescobaldi/default.nix
* [x] pkgs/misc/gnash/default.nix
* [x] pkgs/os-specific/linux/ffado/default.nix
* [x] pkgs/os-specific/linux/i7z/default.nix
* [x] pkgs/os-specific/linux/wpa_supplicant/gui.nix
* [ ] pkgs/os-specific/windows/jom/default.nix
* [ ] pkgs/tools/audio/acoustid-fingerprinter/default.nix
* [ ] pkgs/tools/cd-dvd/unetbootin/default.nix
* [x] pkgs/tools/graphics/nifskope/default.nix
* [x] pkgs/tools/graphics/pfstools/default.nix
* [x] pkgs/tools/graphics/wkhtmltopdf/default.nix
* [x] pkgs/tools/graphics/zbar/default.nix
* [x] pkgs/tools/inputmethods/fcitx-engines/fcitx-libpinyin/default.nix
* [ ] pkgs/tools/inputmethods/fcitx/unwrapped.nix
* [ ] pkgs/tools/inputmethods/ibus/ibus-qt.nix
* [x] pkgs/tools/inputmethods/touchegg/default.nix
* [ ] pkgs/tools/inputmethods/uim/default.nix
* [x] pkgs/tools/misc/qjoypad/default.nix
* [x] pkgs/tools/misc/yubikey-personalization-gui/default.nix
* [ ] pkgs/tools/security/meo/default.nix
* [ ] pkgs/tools/security/omapd/default.nix
* [ ] pkgs/tools/text/qshowdiff/default.nix
* [ ] pkgs/top-level/all-packages.nix
* [ ] pkgs/top-level/python-packages.nix

```
git grep qt4 | cut -d: -f1 | sort | uniq | awk '{ print "* [ ] " $0; }'
```

Moved from #33239.

/cc @adisbladis @orivej @peterhoeg

**Comment by jtojnar** [comment]
For poppler, see https://github.com/NixOS/nixpkgs/issues/32883

**Comment by Ma27** [comment]
`googleearth` seems to be severely broken, started chasing errors locally, a PR will follow :)

**Comment by peterhoeg** [comment]
@Ma27, you can also have a look at #30539

**Comment by Ma27** [comment]
@yegortimoshenko `frescobaldi` uses `qt5` since 545495b132882053e399b1b96628132240ddc7a3

**Comment by Ma27** [comment]
@yegortimoshenko the `wpa_supplicant_gui` seems to use QT5 as well %)

**Comment by Ma27** [comment]
btw do we have any plan what to do with unupgradable packages (e.g. due to no QT5 support)?
I've seen a lot of old packages that weren't updated in years, the latest QT4 release was 4.8.7 which was released some years ago, so I guess that in the long term we should consider dropping old packages, right?

**Comment by jtojnar** [comment]
I would just drop them, people can still use them by fetching from the commit history, or for more popular packages, they can be added to [NUR](https://github.com/nix-community/NUR) by their maintainers.

**Comment by vcunat** [comment]
I personally don't think we need to get rid of qt4.  My point is more like migrate as much to qt5 as possible; removing the rest doesn't seem to help much.  Still, in general I see value in some kind of distinction between well-maintained packages and the rest...

- `vlc` is qt5 since https://github.com/NixOS/nixpkgs/pull/35124

**Comment by Ma27** [comment]
full ack regarding qt5 migration :+1: 

the reason why I asked this question in the first place was since I've seen a lot of very old (and hence unmaintained) packages and I'm not sure if we actually want to keep them in our package set.

**Comment by andrew-d** [comment]
@yegortimoshenko - wkhtmltopdf updated in #46392

**Comment by schmittlauch** [comment]
The people over at Gentoo have decided to package a pre-release version of backintime-1.2 to get rid of qt4. Could this be an option for us as well?

**Comment by peterhoeg** [comment]
> package a pre-release version of backintime-1.2

I personally thing that a pre-release version of backup software might not be the best idea, but we can definitely package it as "backintime-git" or similar using a commit on master.

**Comment by matthiasbeyer** [comment]
I'm currently trying to build octave with gui (and with qt5) but am failing to do so: https://github.com/NixOS/nixpkgs/issues/57900

**Comment by delroth** [comment]
#58247 has moved zbar to qt5.

**Comment by rkoe** [comment]
> > package a pre-release version of backintime-1.2
> 
> I personally thing that a pre-release version of backup software might not be the best idea, but we can definitely package it as "backintime-git" or similar using a commit on master.

backintime-1.2 was released a few months ago. Will the package be updated?

**Comment by jtojnar** [comment]
There are currently no maintainers, you can try to update it yourself or wait if someone else finds a time to do it.

https://github.com/NixOS/nixpkgs/blob/1c709e0e6c037961cea0b3206d1f850e2e1ad636/pkgs/applications/networking/sync/backintime/common.nix#L38

**Comment by peterhoeg** [comment]
yubioath-desktop was migrated some time ago.

**Comment by delroth** [comment]
https://www.gnuradio.org/news/2019-08-10-gnu-radio-v3-8-0-0-release/

GNU Radio 3.8 migrates from Qt4 to Qt5.

**Comment by aanderse** [comment]
September 7th freeze date announced for `19.09`. Hopefully we can eliminate a few of these before then.

**Comment by Anton-Latukha** [comment]
- [x] `pkgs/applications/graphics/djview/default.nix` is Qt4->Qt5: https://github.com/NixOS/nixpkgs/pull/69061
 - [x] `pkgs/applications/audio/picard/default.nix` is Qt5 already.
 - [x] ~~`pkgs/development/libraries/phonon/backends/gstreamer.nix`~~
 - [x] ~~`pkgs/development/libraries/phonon/backends/vlc.nix`~~
 - [x] ~~`pkgs/development/libraries/phonon/default.nix`~~
Phonon was adopted in 4.4, and was deprecated into 5.0 series. "Phonon in Qt will continue for the 4.x series, Qt has already replaced Phonon with QtMultimedia and QtMobility." So it is literally need to be deprecated with Qt4.

  - [x] ~`pkgs/development/libraries/gstreamer/legacy/qt-gstreamer/default.nix`~
  - [x] ~`pkgs/development/libraries/gstreamer/qt-gstreamer/default.nix`~
Last stable falls under compile error (constant casted not right). I achieved the build of last `qt-gstreamer` commit, they lazily (after a big gap of time) fixed the build there. Project marked as unmaintained. Found out that it is a Gnome-related project, and observed they seems to have project `gstreamermm` supplying bindings to C++, but not Qt. Both `qt-gstreamer`s we have are not depended upon in repo. So it it probably time to cut them, or I can publish last working version for antiquariat purposes.

**Comment by Anton-Latukha** [comment]
Dropping both `qt-gstreqmer`'s.

**Comment by Anton-Latukha** [comment]
- `ibus-qt` should be dropped only when actual deprecation happens. It is also a stalled (2015) project, but needed for Qt4.

**Comment by Anton-Latukha** [comment]
- `unetbooting` is kinda essential utility, there is `multibootusb` also,, but I had exp that YUMI (MultiBootUSB) cant chain-boot some special ISOs, while `unetbooting` could. `unetbooting` port issue: "https://github.com/unetbootin/unetbootin/issues/53", also there is done port in PR upstream, that is not merged. Pinged the devs on decision.

**Comment by Anton-Latukha** [comment]
- `acoustid-fingerprinter` seems to be needed to be dropped. It has GUI, and seems like no CLI util. Upsteam stopped at 2017. Acoustid experimented by developing new GUI tool in Go after that. Seems like they are abandoned this project.
  CLI util is `fpcalc` provided by `chromaprint` package.
  MusicBrainz Pickard is Qt5 now, and it includes functionality of `acoustid-fingerprinter`, relying on `chromaprint`.
  @ehmry, you can drop it, or I can drop it.

**Comment by Anton-Latukha** [comment]
- `anki` has a lot of maintainers, and it is Qt5 already.

**Comment by Anton-Latukha** [comment]
- `clementine` I don't know. Development still happens. It is still super-rich player. But When they port - I don't know.

**Comment by Anton-Latukha** [comment]
- [x] `pkgs/applications/audio/projectm/default.nix` is Qt5 by https://github.com/NixOS/nixpkgs/pull/70433

**Comment by jtojnar** [comment]
Phonon no longer supports Qt 4 as of https://github.com/NixOS/nixpkgs/pull/71745 so I marked it as broken in https://github.com/NixOS/nixpkgs/pull/73876.

**Comment by bignaux** [comment]
For Navit, qt4 support is broken and anyway qt5 should work with improving navit cmake support  (i spend a month on it already).

**Comment by veprbl** [comment]
A revert for wkhtmltopdf is planned in #96379
