### ISSUE TITLE
[Tracking issue] `buildFHSEnv`-based derivations in nixpkgs often omit `version`

### ISSUE THREAD

**Issue by Pandapip1** [NixOS/nixpkgs#336576]
## Issue description

A **lot** of `buildFHSnv`-based derivations in nixpkgs omit `version`. This is incorrect in almost all cases.

### Examples

https://github.com/NixOS/nixpkgs/blob/b9d225182c390ca02b1a0d068a7f12c1c838d538/pkgs/by-name/en/envision/package.nix
https://github.com/NixOS/nixpkgs/blob/b9d225182c390ca02b1a0d068a7f12c1c838d538/pkgs/applications/misc/bottles/default.nix
https://github.com/NixOS/nixpkgs/blob/b9d225182c390ca02b1a0d068a7f12c1c838d538/pkgs/applications/misc/lutris/fhsenv.nix
https://github.com/NixOS/nixpkgs/blob/2d7db58c2fddcf05871e426318941146496e8992/pkgs/applications/graphics/unigine-superposition/default.nix
https://github.com/NixOS/nixpkgs/blob/2d7db58c2fddcf05871e426318941146496e8992/pkgs/applications/graphics/unigine-superposition/default.nix
https://github.com/NixOS/nixpkgs/blob/2d7db58c2fddcf05871e426318941146496e8992/pkgs/applications/misc/sidequest/default.nix

There are many more, this was just a cursory search through the first few pages of `git grep buildFHSEnv`

**Comment by tomodachi94** [comment]
Here's a Bash one-liner that finds all files that use `buildFHSEnv` but don't contain `version`: `grep -lr "buildFHSEnv" ./pkgs | xargs -d "\n" grep -L version | sed 's/\(.*\)/- [ ] \1/g'`

And a checklist for sprinting:
- [x] ~~./pkgs/test/buildFHSEnv/default.nix~~ false positive
- [ ] ./pkgs/games/steam/fhsenv.nix
- [ ] ./pkgs/games/space-station-14-launcher/default.nix
- [ ] ./pkgs/games/shticker-book-unwritten/default.nix
- [ ] ./pkgs/games/heroic/fhsenv.nix
- [ ] ./pkgs/development/embedded/platformio/chrootenv.nix
- [ ] ./pkgs/development/embedded/arduino/arduino-core/chrootenv.nix
- [ ] ./pkgs/tools/package-management/appimage-run/default.nix
- [ ] ./pkgs/by-name/en/envision/package.nix
- [ ] ./pkgs/applications/blockchains/sparrow/fhsenv.nix
- [ ] ./pkgs/applications/misc/lutris/fhsenv.nix
- [ ] ./pkgs/applications/misc/bottles/fhsenv.nix

**Comment by Stunkymonkey** [comment]
@Pandapip1 what version do you expect to b given? seems similar to "environments", "patches": https://github.com/NixOS/nixpkgs/issues/103997#issuecomment-1431348167

is it all `1.0.0` (seems odd for me)? Or the same version as the package (then how would you deal with multiple packages being combined in a single one)?

we first should find a reasonable agreement, before we take actions

**Comment by Pandapip1** [comment]
> is it all `1.0.0` (seems odd for me)? Or the same version as the package (then how would you deal with multiple packages being combined in a single one)?

The same version as the package corresponding to `meta.mainProgram` or `runScript`, if it exists.

**Comment by Pandapip1** [comment]
> Is there relevant documentation about this? If not, maybe this is more of a documentation problem?

I mean, I presume that the `version` parameter has to be documented _somewhere_ (although it's telling that I couldn't actually find said documentation in the two minutes I spent searching the nixpkgs manual). The main reason I bring this up is because tools such as https://search.nixos.org/ can't show versions if they aren't set.

**Comment by Stunkymonkey** [comment]
with `./pkgs/tools/package-management/appimage-run/default.nix` we will run into trouble, because passing the `version` parameter is not enforced, but just optional.

**Comment by Pandapip1** [comment]
FWIW your bash script misses a few (e.g. https://github.com/NixOS/nixpkgs/blob/2d7db58c2fddcf05871e426318941146496e8992/pkgs/applications/graphics/unigine-superposition/default.nix). A manual pass might be needed.

**Comment by Stunkymonkey** [comment]
I am going to start a list of what I expect to be skip: (I will add more when i find them)
- `./pkgs/tools/package-management/appimage-run/default.nix`
- `./pkgs/test/buildFHSEnv/default.nix`
- `./pkgs/games/steam/fhsenv.nix`

**Comment by Stunkymonkey** [comment]
@Pandapip1 i think i went through all. the exceptions are documented in https://github.com/NixOS/nixpkgs/issues/336576#issuecomment-2506764699

from my POV this issue is done.

**Comment by Pandapip1** [comment]
All PRs appear to be merged!
