### ISSUE TITLE
AArch64 for 18.03

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nixpkgs#33745]
Let's get AArch64 support into a reasonable state for 18.03. 

- [x] #33749 Make Hydra build the aarch64 sd-image (For Raspberry Pi 3 as the main hardware target) similar to how the ISOs are built: https://github.com/NixOS/nixpkgs/blob/master/nixos/release.nix#L144
- [x] Refactor x86-isms in https://github.com/NixOS/nixpkgs/blob/master/nixos/release.nix
- [ ] Implement the Packet image: https://github.com/NixOS/nixpkgs/issues/31606. I have some progress in https://github.com/NixOS/nixpkgs/pull/32618.
- [ ] ZHF: https://github.com/NixOS/nixpkgs/issues/32326. Let's target to having less failures than Darwin ;)
- [ ] Perhaps migrate some documentation from the Wiki to the official docs.

**Comment by dezgeg** [comment]
https://github.com/NixOS/nixpkgs/pull/33749 is the first part of the 'refactor x86-isms from release.nix`

**Comment by Ericson2314** [comment]
@dezgeg I was already planning on doing some  https://github.com/NixOS/nixpkgs/blob/master/nixos/release.nix and  https://github.com/NixOS/nixpkgs/blob/master/nixos/release-lib.nix overhaul for cross, lets coordinate.

**Comment by dezgeg** [comment]
@Ericson2314 sure, do you have some code written already somewhere? https://github.com/NixOS/nixpkgs/pull/33951/files is the next one up which is very similar to the previous PR and I don't expect any future ones to differ much either.

**Comment by bachp** [comment]
What's the best way to help testing NixOS on a Raspberry Pi? Is there a place to get an image?

**Comment by dezgeg** [comment]
See https://nixos.wiki/wiki/NixOS_on_ARM & related wiki pages.

**Comment by vcunat** [comment]
Now I wonder about the approach to 18.03 &ndash; two options:
 1. share with `x86_64-linux`, i.e. common pair of jobsets and channels for both; or
 2. split like we do with `x86_64-darwin`, i.e. separate jobsets and separate channels.

**Comment by vcunat** [comment]
I think for the stable stuff it might be easier to have (1), assuming that we _really_ want Zero Hydra Failures for aarch64 (i.e. explicitly disable on aarch64 whatever we don't fix).

**Comment by vcunat** [comment]
Well, I had to go for (2.) for now, as Hydra currently can't manage the evaluation in a nixos jobset with two platforms.  (`too many heap sections` etc.  I tried more than five times without any success.)

**Comment by grahamc** [comment]
IMO we have to fix Hydra to allow this to build, because managing a deployment of aarch64 and linux with nixops becomes frustrating at best and impossible at worst if they don't share a common channel.

**Comment by vcunat** [comment]
I think we can manage to fix it until release.

**Comment by grahamc** [comment]
I wonder if bumping the initial heaps again on Hydra would do the business:  https://github.com/NixOS/nixos-org-configurations/blob/master/delft/hydra.nix#L75

**Comment by vcunat** [comment]
Yeah, that sounds promising.  Even if it would mean to reduce the number of parallel evaluations a little.  It might actually save some work, due to the waste.  (Even trunk-combined gets a nontrivial fraction killed due to this.)

**Comment by 7c6f434c** [comment]
Isn't it enough to have two channels with the same revisions? Is it possible to have a repository which tracks _beginning_ of a Hydra build (as opposed to already existing channel-bump branches), and have a job that builds `aarch64` based on that?

**Comment by 7c6f434c** [comment]
(I am not arguing against fixing Hydra builds of multiple platforms, I am just trying to put a bound on the worst-case loss)

**Comment by peterhoeg** [comment]
Should this be moved to 18.09 or can it be closed?

**Comment by samueldr** [comment]
Closing, nothing exactly relevant still to do, except maybe the documentation one. See #33745 for that one.
