### ISSUE TITLE
Qt5.6 deprecation tracking issue

### ISSUE THREAD

**Issue by adisbladis** [NixOS/nixpkgs#33798]
There is not a whole lot of packages still depending on Qt `5.6`  and `5.9` is the current LTS.

Packages depending on Qt 5.6:
- [x] qgo (https://github.com/NixOS/nixpkgs/commit/0fbb2f1517e83a0bb35c8e06d57170a3574c2f04)
- [x] apitrace (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [x] cool-retro-term (~~Broken package, does not even work with Qt 5.6~~, works when installed in `systemPackages`) (https://github.com/NixOS/nixpkgs/commit/3538492f3308952b74570ddd63e1bc1999f9c641)
- [x] hotspot (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [x] owncloud-client (https://github.com/NixOS/nixpkgs/commit/1ec304ce0122ba8bf9d001495f2a03d9f37f0afd)
- [x] supercollider (https://github.com/NixOS/nixpkgs/commit/7dea1f20ed5512fd2992ced563e9b355e70afe97)
- [x] qcachegrind (https://github.com/NixOS/nixpkgs/commit/08ab28b9a32254445e3fcf1b8ccb2bd68071bde4)
- [x] xxdiff-tip (e2f7267ba2f89e858fc60b6033f0f85191b1ee61)
- [ ] cutegram (Fixed in https://github.com/NixOS/nixpkgs/pull/33823)
- [x] gpsbabel [(WIP](https://github.com/NixOS/nixpkgs/pull/33836))
- [x] luminanceHDR (https://github.com/NixOS/nixpkgs/commit/cad14c782b15da7bb5b636a8bd70fee985905b40)
- [x] mendeley (~~Unfree package, might be tricky~~ (https://github.com/NixOS/nixpkgs/pull/33864))
- [x] mumble (See https://github.com/NixOS/nixpkgs/pull/33800)
- [x] smtube (https://github.com/NixOS/nixpkgs/commit/747431cf4229e7f02f691534d7203acb8d1b07e9)
- [x] notepadqq (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [x] qgroundcontrol (https://github.com/NixOS/nixpkgs/commit/5f232de6cda58185c4a0a4f3d4a73b9e9f2856be)
- [x] qsyncthingtray (See https://github.com/NixOS/nixpkgs/pull/33128)
- [x] rapcad (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [x] ricochet (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [x] sigil (https://github.com/NixOS/nixpkgs/commit/4ffc43f49cf0636ca0e4169bf0dd76f61e5a080b)
- [x] cura (Fixed in https://github.com/NixOS/nixpkgs/pull/33799)
- [x] teamspeak_client (~~Unfree package, might be tricky~~ (https://github.com/NixOS/nixpkgs/pull/33863))
- [x] trojita (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [x] vogl (Addressed in https://github.com/NixOS/nixpkgs/pull/33803)
- [ ] golden-cheetah (Has pre-release that should work with 5.9) 

cc @ttuegel @peterhoeg @bkchr @yegortimoshenko

**Comment by ttuegel** [comment]
Because Qt guarantees ABI compatibility, we should be able to re-link unfree packages against Qt 5.9 with patchelf. However, unfree packages should really provide their own Qt; we can run them from a chroot if necessary.

**Comment by globin** [comment]
This has been merged in the openssl 1.1 upgrade (#22357)

**Comment by adisbladis** [comment]
@globin Great :) Thanks!
