### ISSUE TITLE
Tracking issue: undocumented setup hooks

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#341479]
## Issue description

We currently have 146 setup hooks included in packages (that I can find):

```sh
$ rg -F "setupHook =" -l | wc -l
146
```

Combined with 12 (documented) setup hooks included in the stdenv (counted manually).

Compare this with the 29 documentation pages (and 12 additional sections for stdenv hooks):

```sh
$ ls doc/hooks/ | wc -l
29
```

Even if we're lenient and count the "Language and frameworks" section as documentation for one hook (there are 46 sections), that leaves us with **59 undocumented setup hooks** if I did the math correctly:
```
$ echo "146-12-29-46" | bc
59
```

Documenting these is important to help avoid duplicating behavior across packages.

## Tracking list
I've done my best to compile a list of all undocumented hooks below. Apologies if I missed anything.

- [ ] `pkgs/applications/editors/emacs/build-support/generic.nix`
- [x] `pkgs/applications/science/logic/coq/default.nix` (`#sec-language-coq`)
- [x] `pkgs/applications/science/math/R/default.nix` (`#r`)
- [ ] `pkgs/applications/science/misc/root/5.nix`
- [ ] `pkgs/applications/science/misc/root/default.nix`
- [ ] `pkgs/build-support/dotnet/fetch-nupkg/overrides.nix` (unsure whether this is documented)
- [ ] `pkgs/build-support/mitm-cache/default.nix`
- [x] `pkgs/by-name/bm/bmake/package.nix` (`#bmake-hook`)
- [ ] `pkgs/by-name/ha/haredo/package.nix`
- [ ] `pkgs/by-name/ju/just/package.nix`
- [x] `pkgs/by-name/me/meson/package.nix` (`#meson`)
- [ ] `pkgs/by-name/mo/monado/package.nix`
- [x] `pkgs/by-name/ni/ninja/package.nix` (`#ninja`)
- [ ] `pkgs/by-name/ri/ripunzip/package.nix`
- [ ] `pkgs/by-name/sc/scons/package.nix`
- [ ] `pkgs/by-name/sd/SDL1/package.nix`
- [ ] `pkgs/by-name/sd/SDL_compat/package.nix`
- [ ] `pkgs/by-name/tu/tup/package.nix`
- [ ] `pkgs/by-name/un/unrar/package.nix`
- [ ] `pkgs/data/icons/hicolor-icon-theme/default.nix` (`#ssec-gnome-hooks-hicolor-icon-theme`)
- [ ] `pkgs/data/misc/cacert/default.nix`
- [ ] `pkgs/data/misc/iana-etc/default.nix`
- [ ] `pkgs/data/misc/tzdata/default.nix`
- [ ] `pkgs/desktops/enlightenment/efl/default.nix`
- [ ] `pkgs/desktops/gnustep/make/default.nix`
- [ ] `pkgs/desktops/lxqt/lxqt-build-tools/default.nix`
- [ ] `pkgs/desktops/plasma-5/default.nix`
- [ ] `pkgs/desktops/plasma-5/libkscreen/default.nix`
- [ ] `pkgs/desktops/xfce/core/xfce4-dev-tools/default.nix`
- [x] `pkgs/development/beam-modules/build-erlang-mk.nix` (`#sec-beam`)
- [x] `pkgs/development/beam-modules/build-mix.nix` (`#sec-beam`)
- [x] `pkgs/development/beam-modules/build-rebar3.nix` (`#sec-beam`)
- [x] `pkgs/development/beam-modules/hex/default.nix` (`#sec-beam`)
- [x] `pkgs/development/beam-modules/webdriver/default.nix` (`#sec-beam`)
- [ ] `pkgs/development/compilers/ats2/default.nix`
- [ ] `pkgs/development/compilers/chez/default.nix`
- [ ] `pkgs/development/compilers/chez-racket/default.nix`
- [x] `pkgs/development/compilers/chicken/4/chicken.nix` (`#sec-chicken`)
- [x] `pkgs/development/compilers/chicken/5/chicken.nix` (`#sec-chicken`)
- [x] `pkgs/development/compilers/dart/package-source-builders/handy-window/default.nix` (`#sec-language-dart`)
- [x] `pkgs/development/compilers/dart/package-source-builders/matrix/default.nix` (`#sec-language-dart`)
- [x] `pkgs/development/compilers/dart/package-source-builders/olm/default.nix` (`#sec-language-dart`)
- [x] `pkgs/development/compilers/dart/package-source-builders/sqlite3/default.nix` (`#sec-language-dart`)
- [ ] `pkgs/development/compilers/haxe/default.nix`
- [x] `pkgs/development/compilers/sbcl/default.nix` (maybe? `#sec-language-lisp`)
- [ ] `pkgs/development/compilers/swift/swiftpm/default.nix`
- [ ] `pkgs/development/compilers/vala/default.nix`
- [ ] `pkgs/development/compilers/yosys/default.nix`
- [ ] `pkgs/development/interpreters/guile/1.8.nix`
- [ ] `pkgs/development/interpreters/guile/2.0.nix`
- [ ] `pkgs/development/interpreters/guile/2.2.nix`
- [ ] `pkgs/development/interpreters/guile/3.0.nix`
- [ ] `pkgs/development/interpreters/lua-5/interpreter.nix`
- [ ] `pkgs/development/interpreters/luajit/default.nix`
- [ ] `pkgs/development/interpreters/perl/interpreter.nix`
- [ ] `pkgs/development/interpreters/python/cpython/2.7/default.nix` (`#sec-language-python`)
- [x] `pkgs/development/interpreters/python/cpython/default.nix` (`#sec-language-python`)
- [x] `pkgs/development/interpreters/python/hooks/default.nix` (`#sec-language-python`)
- [x] `pkgs/development/interpreters/python/pypy/default.nix` (`#sec-language-python`)
- [x] `pkgs/development/interpreters/python/pypy/prebuilt_2_7.nix` (`#sec-language-python`)
- [x] `pkgs/development/interpreters/python/pypy/prebuilt.nix` (`#sec-language-python`)
- [ ] `pkgs/development/libraries/aws-c-common/default.nix`
- [ ] `pkgs/development/libraries/dleyna-core/default.nix`
- [x] `pkgs/development/libraries/gdk-pixbuf/default.nix` (`#ssec-gnome-gdk-pixbuf-loaders`)
- [ ] `pkgs/development/libraries/glibc/locales.nix` (a lot of hits but no documentation about the hook)
- [x] `pkgs/development/libraries/glib/default.nix` (`#ssec-gnome-packaging`)
- [x] `pkgs/development/libraries/gobject-introspection/default.nix` (`#ssec-gnome-packaging`)
- [ ] `pkgs/development/libraries/grantlee/5/default.nix`
- [x] `pkgs/development/libraries/grilo/default.nix` (`#ssec-gnome-hooks-gst-grl-plugins`)
- [x] `pkgs/development/libraries/gstreamer/core/default.nix` (`#ssec-gnome-hooks-gst-grl-plugins`)
- [ ] `pkgs/development/libraries/incrtcl/default.nix`
- [ ] `pkgs/development/libraries/jemalloc/rust.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/default.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/extra-cmake-modules/default.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/kauth/default.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/kded.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/kdelibs4support/default.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/kinit/default.nix`
- [ ] `pkgs/development/libraries/kde-frameworks/kwayland.nix`
- [ ] `pkgs/development/libraries/librep/default.nix`
- [ ] `pkgs/development/libraries/physics/cernlib/default.nix`
- [ ] `pkgs/development/libraries/physics/geant4/datasets.nix`
- [ ] `pkgs/development/libraries/physics/geant4/default.nix`
- [ ] `pkgs/development/libraries/physics/lhapdf/pdf_sets.nix`
- [x] `pkgs/development/libraries/qt-5/modules/qtbase.nix` (`#sec-language-qt`)
- [x] `pkgs/development/libraries/qt-5/modules/qttools.nix` (`#sec-language-qt`)
- [x] `pkgs/development/libraries/qt-6/modules/qtbase.nix` (`#sec-language-qt`)
- [ ] `pkgs/development/libraries/SDL2/default.nix`
- [ ] `pkgs/development/libraries/slib/default.nix`
- [ ] `pkgs/development/mobile/webos/cmake-modules.nix`
- [ ] `pkgs/development/ocaml-modules/bap/default.nix`
- [ ] `pkgs/development/ocaml-modules/eliom/default.nix`
- [ ] `pkgs/development/ocaml-modules/ocamlmake/default.nix`
- [x] `pkgs/development/python2-modules/pytest/default.nix` (`#using-pytest`)
- [x] `pkgs/development/python-modules/cython/0.nix` (`#sec-language-python`)
- [x] `pkgs/development/python-modules/cython/default.nix` (`#sec-language-python`)
- [ ] `pkgs/development/python-modules/pdm-backend/default.nix`
- [ ] `pkgs/development/python-modules/poetry-dynamic-versioning/default.nix`
- [ ] `pkgs/development/python-modules/pybind11/default.nix`
- [ ] `pkgs/development/python-modules/pytest/7.nix` (`#using-pytest`)
- [ ] `pkgs/development/python-modules/pytest/default.nix` (`#using-pytest`)
- [ ] `pkgs/development/python-modules/pytest-forked/default.nix`
- [ ] `pkgs/development/python-modules/pytest-xdist/default.nix`
- [ ] `pkgs/development/python-modules/setuptools-odoo/default.nix`
- [ ] `pkgs/development/python-modules/setuptools-scm/default.nix` (hits but no documentation about the hook)
- [ ] `pkgs/development/python-modules/whool/default.nix`
- [ ] `pkgs/development/tools/analysis/frama-c/default.nix`
- [ ] `pkgs/development/tools/build-managers/build2/bootstrap.nix`
- [ ] `pkgs/development/tools/build-managers/build2/default.nix`
- [ ] `pkgs/development/tools/build-managers/gn/generic.nix`
- [ ] `pkgs/development/tools/misc/automake/automake-1.11.x.nix` (`#setup-hook-automake`)
- [ ] `pkgs/development/tools/misc/automake/automake-1.15.x.nix` (`#setup-hook-automake`)
- [ ] `pkgs/development/tools/misc/automake/automake-1.16.x.nix` (`#setup-hook-automake`)
- [ ] `pkgs/development/tools/misc/automake/automake-1.17.x.nix` (`#setup-hook-automake`)
- [ ] `pkgs/development/tools/misc/luarocks/default.nix` (`#sec-language-lua`)
- [ ] `pkgs/development/tools/misc/patchelf/default.nix`
- [ ] `pkgs/development/tools/misc/patchelf/unstable.nix`
- [ ] `pkgs/development/tools/misc/premake/3.nix`
- [ ] `pkgs/development/tools/misc/premake/5.nix`
- [ ] `pkgs/development/tools/misc/premake/default.nix`
- [ ] `pkgs/development/tools/ocaml/camlidl/default.nix`
- [ ] `pkgs/development/tools/ocaml/findlib/default.nix` (hits but no hook documentation)
- [ ] `pkgs/development/web/nodejs/nodejs.nix` (`#sec-language-javascript`)
- [ ] `pkgs/kde/frameworks/extra-cmake-modules/default.nix`
- [ ] `pkgs/os-specific/bsd/netbsd/pkgs/install/package.nix`
- [ ] `pkgs/os-specific/darwin/apple-sdk-11.0/apple_sdk.nix` (`#sec-darwin`)
- [ ] `pkgs/os-specific/darwin/apple-sdk/default.nix` (`#sec-darwin`)
- [ ] `pkgs/os-specific/linux/paxctl/default.nix`
- [ ] `pkgs/os-specific/linux/sgx/sdk/default.nix`
- [ ] `pkgs/servers/x11/xorg/overrides.nix` (`#sec-xorg`)
- [ ] `pkgs/tools/archivers/7zz/default.nix`
- [ ] `pkgs/tools/archivers/p7zip/default.nix`
- [ ] `pkgs/tools/archivers/undmg/default.nix`
- [ ] `pkgs/tools/archivers/unrar-wrapper/default.nix`
- [x] `pkgs/tools/archivers/unzip/default.nix` (`#unzip`)
- [ ] `pkgs/tools/compression/lzip/default.nix`
- [ ] `pkgs/tools/graphics/vulkan-extension-layer/default.nix`
- [ ] `pkgs/tools/graphics/vulkan-tools-lunarg/default.nix`
- [ ] `pkgs/tools/misc/desktop-file-utils/default.nix`
- [x] `pkgs/tools/package-management/akku/akkuDerivation.nix` (`#sec-scheme-package-management-akku`)
- [ ] `pkgs/tools/package-management/dpkg/default.nix`
- [ ] `pkgs/tools/text/gawk/gawkextlib.nix`
- [ ] `pkgs/tools/text/sgml/opensp/default.nix`
- [x] `pkgs/tools/typesetting/tex/tetex/default.nix` (`#tetex-tex-live`)
- [ ] `pkgs/top-level/darwin-packages.nix` (??)
- [ ] `pkgs/top-level/python-packages.nix` (??)

To regenerate this list, run the following: `rg -F "setupHook =" -l | sort | sed -e 's/^/- [ ] `/' | sed -e 's/$/`/'`.

Unfortunately, I had to check off entries manually by searching the manual using Ctrl+F and ripgrep.

**Comment by tomodachi94** [comment]
> Many of the setup hooks just "do something", but don't provide any config option. Is it really worth documenting those?

I think it is, though I'm interested in the opinions to the contrary. Setup hooks can introduce surprising behavior, which should always be documented.
