### ISSUE TITLE
Some setup hooks attempt to add phases to nonexistent `postHooks` array

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#341930]
### Describe the bug
Some hooks attempt to add functions as phases to the nonexistent `postHooks` array. Bash creates the array due to how the append operator works, and **the hooks are never executed in any situation.**

### Expected behavior
Hooks should add themselves as phases in the proper way, either by [using `addEnvHooks`](https://nixos.org/manual/nixpkgs/unstable/#ssec-setup-hooks) or by appending to the correct phase array.

### Screenshots
N/A

### Additional context
A forum post: https://discourse.nixos.org/t/when-is-posthooks-used-in-a-derivation/6939

(Thank you to @frontear for helping me confirm this was an issue!)

### Affected packages
- [ ] `pkgs/applications/science/misc/root/setup-hook.sh`: @guitargeek @veprbl
- [ ] `pkgs/by-name/cm/cmake/setup-hook.sh`: @ttuegel @lnl7 @AndersonTorres
- [ ] `pkgs/desktops/lxqt/lxqt-build-tools/setup-hook.sh`: @NixOS/lxqt
- [ ] `pkgs/desktops/plasma-5/default.nix`: @ttuegel @nyanloutre
- [ ] `pkgs/development/compilers/swift/wrapper/setup-hook.sh`: @NixOS/swift
- [ ] `pkgs/development/libraries/aws-c-common/setup-hook.sh`: @orivej @r-burns
- [ ] `pkgs/development/libraries/kde-frameworks/default.nix`: @NixOS/qt-kde
- [ ] `pkgs/development/libraries/kde-frameworks/extra-cmake-modules/setup-hook.sh`: @NixOS/qt-kde
- [ ] `pkgs/development/libraries/memorymapping/setup-hook.sh`: @veprbl
- [ ] `pkgs/development/libraries/memstream/setup-hook.sh`: @veprbl
- [ ] `pkgs/development/libraries/physics/geant4/datasets-hook.sh`: @veprbl
- [ ] `pkgs/development/libraries/physics/lhapdf/pdfset-hook.sh`: @veprbl
- [ ] `pkgs/development/tools/ocaml/findlib/default.nix`: @maggesi @veprbl
- [ ] `pkgs/kde/frameworks/extra-cmake-modules/ecm-hook.sh`: @NixOS/qt-kde
- [ ] `pkgs/os-specific/linux/sgx/sdk/default.nix`: @phlip9 @sbellem @arcz @veehaitch

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.6.48, NixOS, 24.11 (Vicuna), 24.11.20240901.b833ff0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.18.5`
 - nixpkgs: `/nix/store/p2zlnhfbwx66hmp4l8m3qyyj3yrfr9zh-9qq0zf30wi74pz66rr05zmxq0nv17q1p-source`
```

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by Frontear** [comment]
While attempting a "fix" for the lxqt-build-tools, I noticed that the fix actually somehow god rid of the cmake flags. This immediately signals to me that somehow, `postHooks` _was_ in fact activating, though I cannot find **any** mention of it anywhere in nixpkgs besides the above package. This definitely seems like a documentation problem more than anything now.

**Comment by Frontear** [comment]
Please see my comment in my PR for further details. tl;dr it seems postHook and postHooks both work, the existence of postHooks is completely undocumented but it does work internally.
