### ISSUE TITLE
NixOS 24.11 - Feature Freeze & Release Blockers

### ISSUE THREAD

**Issue by RossComputerGuy** [NixOS/nixpkgs#344920]
Hello, this is your NixOS 24.11 ("*Vicuna*") release managers, [Tristan Ross](https://github.com/RossComputerGuy) & [Weijia Wang](https://github.com/wegank).

Today we're glad to announce the kickoff of the release schedule. Because of that, it's time to discuss the feature freeze. NixOS releases have had a history of being stable and reliable and we would like to continue that. I would like to also point out that if there's any issues with the aarch64 platforms, that we could get those fixed or any other improvements done.

Some important dates of concern:
- **2024-10-11**: Restrict breaking changes to [Release Critical Packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html)
- **2024-10-25**: Restrict all breaking changes: allow only non-breaking updates and Desktop Manager changes

Our full 24.11 release schedule is available here
- https://github.com/NixOS/nixpkgs/issues/339153

As of the time of posting this, we have a couple weeks before the release critical changes are restricted. If at all possible, let's get those done as soon as possible.

# Blockers

If you were pinged or know of any blocking issues for NixOS 24.11, please submit them in the issue tracker and place them into the [24.11 Blockers project](https://github.com/orgs/NixOS/projects/80/views/1).

# Check-in

Please comment your status quo and possible issues as soon as possible. We'll check teams once they have checked in.

If you think some subsystem, person or team should be added or removed from this list, update `maintainers/team-list.nix` in time before the next feature freeze announcement.

# Desktop environments

- [x] Cinnamon: @bobby285271 @mkg20001
- [x] DDE: @wineee
- [x] Enlightenment: @NixOS/enlightenment
- [x] GNOME: @NixOS/gnome @bobby285271 @dasj19
- [x] Lomiri: @OPNA2608
- [x] Lumina: @NixOS/lumina
- [x] LXQt: @NixOS/lxqt
- [x] MATE: @bobby285271 @johannesloetzsch @romildo
- [x] Pantheon: @NixOS/pantheon
- [x] Qt / KDE: @NixOS/qt-kde @ilya-fedin @K900 @LunNova @mjm @NickCao @SuperSandro2000
- [x] Xfce: @bobby285271 @romildo @muscaln

# Platforms

- [ ] Darwin: @NixOS/darwin-maintainers

# Languages ecosystem

- [x] BEAM: @NixOS/beam @minijackson
- [x] C: @matthewbauer @Mic92
- [x] Coq: @CohenCyril @Zimmi48 @siraben @vbgl @Alizter
- [x] Dhall: @Gabriella439 @ehmry
- [x] Go: @NixOS/golang
- [ ] Haskell: @NixOS/haskell
- [x] lisp: @NixOS/lisp @hraban
- [x] lua: @NixOS/lua
- [ ] Node.js: @winterqt
- [x] OCaml: @NixOS/ocaml
- [ ] Perl: @stigtsp @marcusramberg @zakame
- [ ] PHP: @NixOS/php @piotrkwiecinski
- [x] Python: @mweinelt @natsukium
- [x] R: @b-rodrigues @bcdarwin @jbedo @Kupac
- [x] Rust: @NixOS/rust
- [ ] Zig: @figsoda

# Compilers, build systems

- [ ] Bazel: @mboes @uri-canva @avdv @olebedev @groodt @aherrmann @ylecornec
- [ ] LLVM: @NixOS/llvm

# Programs

- [ ] CloudPosse: @dudymas
- [x] Geospatial: @NixOS/geospatial @autra @l0b0
- [ ] Lix ecosystem: @RaitoBezarius @Qyriad

# Modules

- [ ] ACME: @aanderse @arianvp @emilazy @flokli @m1cr0man
- [ ] systemd: @NixOS/systemd

# Core

- [ ] Docs: @NixOS/documentation-team
- [ ] Marketing: @garbas @tomberek
- [x] Module system: @infinisil @roberth
- [x] Nix/nix-cli ecosystem: @NixOS/nix-team
- [ ] NixOS tests: @tfc

# Everyone Else

@NixOS/nixpkgs-committers @NixOS/release-engineers

# Finally

No issue is too big or too small, but let's remember that we are all working on the project voluntarily in our free time here, so let's focus on issues that can be realistically addressed in the remaining time before the release.

We thank everyone for their contribution!

**Comment by RossComputerGuy** [comment]
More pings since GitHub limits the amount of pings, please refer to the original issue for the checkboxes

# Modules

- ACME: @arianvp @emilazy @flokli @m1cr0man

# Core

- Marketing: @garbas @tomberek
- Module system: @infinisil @roberth
- Nix/nix-cli ecosystem: @edolstra @grahamc @nbp

**Comment by K900** [comment]
Plasma is waiting for the staging-next cycle, and then the 6.2 release in two weeks (2024-10-08 target), the beta builds and is usable on https://github.com/NixOS/nixpkgs/pull/341487, there will probably need to be some last minute changes for the final release.

**Comment by emilazy** [comment]
The primary Darwin blocker is [Randy’s SDK rework](https://discourse.nixos.org/t/on-the-future-of-darwin-sdks-or-how-you-can-stop-worrying-and-put-the-sdk-in-build-inputs/50574), which is targeted for the next `staging` cycle and critical to the health of the platform. It will significantly reduce the burden of supporting macOS, both for the core Darwin maintainers and packagers of any software that works on it, and although it is mostly compatible, it still requires significant changes to the Darwin standard environment and some API deprecations. Missing 24.11 would be devastating for backports, but thankfully the work is on track and has already been very well‐tested, so I expect it to be merged relatively uneventfully.

**Comment by SigmaSquadron** [comment]
We're not here yet (needs #344314 which was only approved a few hours ago), but the Xen Hypervisor is as ready as it can be for 24.11. We are targeting further improvements for 25.05 and above. The only PRs that might happen for Xen are minor updates and security patches.

**Comment by NickCao** [comment]
> Plasma is waiting for the staging-next cycle, and then the 6.2 release in two weeks (2024-10-08 target), the beta builds and is usable on #341487, there will probably need to be some last minute changes for the final release.
> 
> Edit: Qt 6.7.3 also finally released today, I'll try to get it into this cycle.

Qt 6.8 is also targeting a 2024-10-08 release, I'd prefer getting that in.

**Comment by K900** [comment]
I would not want to risk a Qt bump in the last staging cycle of the release. We can get it in post release.

**Comment by jbedo** [comment]
For R a significant portion of the package tree is broken due to some packages explicitly enabling http support in libxml2 (notably gdal and libspatialite). The overriding results in multiple versions of libxml in the closure of some packages and causes subsequent loading issues. Not sure what the solution here is.

**Comment by mweinelt** [comment]
Python has done the necessary migration to the 3.12 release track early in the development cycle, so we don't have any blockers at this time.

**Comment by stigtsp** [comment]
Perl 5.40.0 is in staging-next at the moment. A mass update for perlPackages should begin soon, and would prefer to get that done for 24.11.

**Comment by ElvishJerricco** [comment]
This is not essential, but I've been hoping to get systemd initrd enabled by default for this release. Here's the blockers for that:

- https://github.com/NixOS/nixpkgs/issues/309190 It's still not known *why* this happens, but a fix is known. We need to put GDM on tty1, which requires `switch-to-configuration` changes to avoid its `Conflicts=getty@tty1.service` directive killing the desktop.
- https://github.com/NixOS/nixpkgs/issues/317901 I don't care too much about this, because bcachefs is experimental after all. But I do have a solution for it: https://github.com/ElvishJerricco/bcachefs-fstab-generator
- https://github.com/NixOS/nixpkgs/issues/250003 This is a slightly breaking change. The planned solution is to set the device timeout to infinite. This has not been done yet.
- We need to detect incompatible options and fallback to scripted initrd when they're used. This also has not been done yet, but it should be relatively easy. There aren't very many incompatible options.

Other than that, I think it's good to go. Please let me know if you have any other problems with it. I intend to fix the above issues in the next week or two.

We can delay this till after 24.11, which would make things easier. But that would be very disappointing IMO.

**Comment by happysalada** [comment]
No blockers in the beam ecosystem

**Comment by Mic92** [comment]
Blockers in C, are the mentioned macOS sdk updates. I changed the responsible people for the "nix-cli" to the Nix team, since I have been involved in that bit lately a bit. I don't think there are any blocker on that level. Rust also should be fine.

**Comment by Mic92** [comment]
I think we can remove the "Marketing" checkmark from the template. I don't think they do have any release blocker related items. Website updates are handled by NixOS release manager except for the final merge.

**Comment by hraban** [comment]
All quiet on the lisp front. 👍

**Comment by Gabriella439** [comment]
No blockers for Dhall

**Comment by wineee** [comment]
No blockers for DDE

**Comment by katexochen** [comment]
Go blockers (only common maintenance tasks, will be ready in-time):

- [ ] https://github.com/NixOS/nixpkgs/pull/342429 (in current staging-next)
- [ ] https://github.com/NixOS/nixpkgs/pull/344622 (against master)

**Comment by m1cr0man** [comment]
No ACME blockers, but we do have some PRs related to the test suite. To get [pebble up to 2.6.0](https://github.com/NixOS/nixpkgs/pull/331721) we needed to [change some of the assertions](https://github.com/NixOS/nixpkgs/pull/331721). I also have an open change which hopefully [makes the tests less flaky](https://github.com/NixOS/nixpkgs/pull/250260)

**Comment by siriobalmelli** [comment]
Foundationdb is currently still broken (https://github.com/NixOS/nixpkgs/issues/319537 - since 24.05).

I'd love some help getting this sorted and/or moving from foundation 7.1 to 7.3.

Happy to pitch in, just over my head and missing a bit of direction 🙏

**Comment by teto** [comment]
No lua blocker.

**Comment by reckenrode** [comment]
The Darwin rework is here:
- https://github.com/NixOS/nixpkgs/pull/346043

**Comment by fgaz** [comment]
If possible I'd like for Tcl to become a language ecosystem / package set before 24.11 to make backports easier:

* #344716

**Comment by imincik** [comment]
@NixOS/geospatial doesn't have any blockers.

Following PRs would be nice to have in 24.11:

* https://github.com/NixOS/nixpkgs/pull/342101

**Comment by vbgl** [comment]
No blocker for Coq.

No blocker for OCaml.

**Comment by romildo** [comment]
No block for Enlightenment, Lumina, and LXQt.

**Comment by thecaralice** [comment]
Would be nice to get #300532 merged since it apparently affects a lot of projects yet is stale for some reason.

**Comment by RossComputerGuy** [comment]
As per the release schedule, all [release critical packages](https://nixos.github.io/release-wiki/Release-Critical-Packages.html) are blocked.

**Comment by OPNA2608** [comment]
##### Lomiri DE

Should be fine. There'll be [another minor OTA release later this month](https://gitlab.com/ubports/development/project-management/-/issues/11) that might come with some more component bumps. Will check for relevant changes & bump/backport when it happens, not expecting anything serious though.

**Comment by K900** [comment]
Plasma 6.2 is good to go on master now, and given how long the staging cycle was, we also squeezed in Qt 6.8, which seems to be fine so far, and a big improvement on 6.7 in terms of Wayland stability. I think this was the right call after all.

**Comment by SigmaSquadron** [comment]
With #347810 being merged, the Xen Project Hypervisor is ready for 24.11. The current collectd PR, the documentation and the VM/stubdom builder are scheduled for 25.05.

**Comment by ulrikstrid** [comment]
> Plasma 6.2 is good to go on master now, and given how long the staging cycle was, we also squeezed in Qt 6.8, which seems to be fine so far, and a big improvement on 6.7 in terms of Wayland stability. I think this was the right call after all.

This broke packages relying on pyqt6, we have a interim-solution in master now but it could break any day since the package url isn't stable. If possible we should wait for a release of pyqt6 that is compatible and package that.

**Comment by K900** [comment]
We're not holding back a release for PyQt. They still have over a month, hopefully they get their stuff together.

**Comment by arianvp** [comment]
I would like to get https://github.com/NixOS/nixpkgs/pull/343939 in before the release.

**Comment by ulrikstrid** [comment]
> We're not holding back a release for PyQt. They still have over a month, hopefully they get their stuff together.

As long as there's a decision I don't mind, I'm not a stable-user anyway

**Comment by minijackson** [comment]
Can I ask for help getting #331750 reviewed / merged before the 25th? It already has two major bumps

**Comment by Eveeifyeve** [comment]
I mean nim is still a blocker. Unfortunately I made some mistakes in a pr that caused a brunch of issues like high cpu usage and etc. More about at issue #350913.

**Comment by Eveeifyeve** [comment]
> I mean nim is still a blocker. Unfortunately I made some mistakes in a pr that caused a brunch of issues like high cpu usage and etc. More about at issue #350913.

I am working a pr that will be finished asap.

**Comment by ehmry** [comment]
Nim has been taken care of.

**Comment by sternenseemann** [comment]
Regarding Ada, I've been working on updating all packages released by AdaCore to their 25.0.0 version: #352856. Unfortunately that causes quite a few undiagnosed regressions. Consequently, I don't think this is a good fit for 24.11.

What we could do for 24.11, is upgrading the default gnat version to 13 to match gcc: #352894.

**Comment by Artturin** [comment]
Misvimiumclick

**Comment by ShamrockLee** [comment]
I hope to bump `libchewing` onto a stable version (#314538). This package is the basis of Chewing Input Method on all IM frameworks and is crucial for zh-TW users.

**Comment by ShamrockLee** [comment]
The package `conan` currently builds on the `master` branch with the official binary substituter but fails some PyTest tests with the `--rebuild` flags.

Is it safe to introduce a change that would cause `conan` to rebuild during the ZHF period? (See also #354811 for the discussions.)

**Comment by RossComputerGuy** [comment]
We released! https://discourse.nixos.org/t/nixos-24-11-released/56811
