### ISSUE TITLE
Tracking Issue: Removing GHC 8.10

### ISSUE THREAD

**Issue by maralorn** [NixOS/nixpkgs#346214]
It is not yet clear, when we can or want to drop GHC 8.10, but there is the intention to do this if possible and the following things currently depend on GHC 8.10 and thus need to be dealt with first:

- [ ] Last ghc version for which there exists the old ghcjs is 8.10 (maintainer: obsidian systems) https://github.com/NixOS/nixpkgs/pull/422342
- Some elm packages still need 8.10 (maintainer: @turboMaCk )
  - [x] elmi-to-json #415911
  - [x]  elm-instrument https://github.com/NixOS/nixpkgs/pull/413234 
- [x] pakcs (maintainer: @t4ccer)
- [x] yi (no maintainers)
- [x] ~~hasura-graphql-engine (maintainer: @Lassulus)~~ (broken anyways)

GHC 8.10.7 (binary) is also used for bootstrapping other GHC versions:

- [ ] As boot compiler for GHC 9.0.2 https://github.com/NixOS/nixpkgs/pull/381265
- [x] As boot compiler for GHC 9.2.* (could be replaced by GHC 9.0.2)
- [x] As boot compiler for GHC 9.4.* (could be replaced by GHC 9.0.2, but *not* 9.2.*) #411397

That GHC 9.4 depends on 8.10.7 for bootstrapping is troublesome because:

- [ ] It is the latest GHC to support TemplateHaskell in `pkgsStatic`: https://github.com/NixOS/nixpkgs/issues/367686
- [ ] It is the latest GHC we can cross-compile which is interesting for bootstrapping a native GHC in the future (e.g. on `riscv64-linux`).

**Comment by t4ccer** [comment]
Moving pakcs is non-trivial because it doesn't build on mtl 2.3 even after bumping to 3.7.2. I'll try patching it later as it usually boils down to adding imports for reexports removed in mtl 2.3

**Comment by emilazy** [comment]
Copying what I said [on Matrix](https://matrix.to/#/!RbXGJhHMsnQcNIDFWN:nixos.org/$4fSMcBK9kyy69ZF8ydG7iMFxLhMXMTnHfJrFIaKeUZY?via=nixos.org&via=matrix.org&via=mozilla.org): `elm-instrument` and `elm-format` build on GHC 9.4 without modifications, and so pose no barrier to GHC 8.10 removal. (They would build with what looks like trivial import fixes on 9.6, too.)

`elmi-to-json` has dependencies that are broken on a newer GHC version, but there’s already an upstream issue about [known vulnerabilities in some of its dependencies](https://github.com/stoeffel/elmi-to-json/issues/48), so we probably shouldn’t be shipping it in its present state anyway (at least without `knownVulnerabilities`). I think it would be okay to expect someone to patch it for newer GHC versions and non‐vulnerable libraries or else remove it.

**Comment by turboMaCk** [comment]
elmi-to-json is library that is used by some nodejs dependecies, it's not useful by itself. We need to check which other packages would removal break. The known vulnerabilities are not that big deal because they do not have impact on security of elmi-to-json itself.

**Comment by emilazy** [comment]
If the package is important we could patch it to use libraries that work with the newer GHC (and send a PR as it seems the author would like help fixing such issues).

**Comment by turboMaCk** [comment]
I think it might not be that important anymore. I have a feeling that some downstream deps might even already moved away from using it. We need to check. In any case the package itself is not useful so we definitely should consider removing it if it doesn't break too much stuff. Otherwise I would provide patch upstream we can apply - in past I already provided some and upstream was fast to accept them.

**Comment by sternenseemann** [comment]
A more low hanging fruit in terms of GHC removals is probably GHC 9.0.2. I'm confident we could immediately remove it and we probably should do so immediately after the 24.11 release.

**Comment by sternenseemann** [comment]
<https://mail.haskell.org/pipermail/libraries/2024-October/031677.html>

**Comment by sternenseemann** [comment]
In the past two years, people have occasionally opened issues about ghcjs regressions (these happen inevitably because we can't test the full ghcjs on Hydra due to its close 4GB output size).

- https://github.com/NixOS/nixpkgs/issues/260271
- https://github.com/NixOS/nixpkgs/issues/376582

However, I haven't really been able to turn up a significant amount of projects that would suffer significantly. The Reflex/whatever it's called ecosystem heavily pins nixpkgs (maybe beyond what is reasonable), but it is also prevalent in other users, probably since ghcjs has to be manually compiled (e.g. dhall-lang.org, [miso](https://github.com/dmjio/miso), …). On balance, it seems justifiable to drop it, especially since the JS backend for GHC keeps improving (as does our support for it) and we don't really have active maintainers for it on the nixpkgs side.

**Comment by maralorn** [comment]
@sternenseemann That would be part of the deprecation policy I proposed. I can update and post it to discourse if you want. https://md.darmstadt.ccc.de/FZwe_M9GQwWVnYfO0U4qJA#

**Comment by maralorn** [comment]
Ah, well, there is a problem. I don’t think we announced deprecation in the 24.11 changelog, did we? Then maybe we shouldn’t announce the policy because we don’t intend to conform to it?

**Comment by alyssais** [comment]
25.05 is coming up — just mentioning in case anything is intended for that changelog :)
