### ISSUE TITLE
Remove archived python libraries

### ISSUE THREAD

**Issue by natsukium** [NixOS/nixpkgs#346385]
Steps to remove

1. Check if the package is a leaf. If it has no reverse dependencies, it should be removed. 
2. Check if other packages still really depend on the package. If not, it should be removed from the dependencies.
3. Check if the package follows current packaging standards.
see https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines-contributing-guidelines

- [ ] https://github.com/Azure/azure-functions-devops-build was archived at 2024-07-19T23:23:49Z
- [ ] https://github.com/Azure/msrestazure-for-python was archived at 2024-04-10T21:13:56Z
- [ ] https://github.com/AzureAD/azure-activedirectory-library-for-python was archived at 2023-09-29T17:12:43Z
- [ ] https://github.com/Google/google-reauth-python was archived at 2023-01-10T21:09:50Z
- [ ] https://github.com/NordicSemiconductor/pc-ble-driver-py was archived at 2024-02-19T07:41:41Z
- [ ] https://github.com/PokaInc/arnparse was archived at 2023-05-16T17:45:40Z
- [ ] https://github.com/PyCQA/pydocstyle was archived at 2023-11-03T22:30:55Z
- [ ] https://github.com/bdraco/aiolip was archived at 2021-12-06T01:30:05Z
- [ ] https://github.com/beeware/gbulb was archived at 2024-09-13T03:14:54Z
- [ ] https://github.com/codecov/codecov-python was archived at 2023-04-20T05:13:02Z
- [ ] https://github.com/core-api/python-client was archived at 2019-03-18T15:51:11Z
- [ ] https://github.com/core-api/python-coreschema was archived at 2019-03-18T15:52:07Z
- [ ] https://github.com/emersion/python-emailthreads was archived at 2024-05-17T08:48:30Z
- [ ] https://github.com/erdewit/nest_asyncio was archived at 2024-03-06T10:42:28Z
- [ ] https://github.com/frenck/python-ambee was archived at 2022-09-14T14:06:16Z
- [ ] https://github.com/gtaylor/python-colormath was archived at 2023-12-12T20:25:24Z
- [ ] https://github.com/hjacobs/python-clickclick was archived at 2020-10-03T20:35:14Z
- [ ] https://github.com/mapbox/mapbox-sdk-py was archived at 2022-08-02T05:47:06Z
- [ ] https://github.com/metachris/pdfx was archived at 2023-06-15T19:33:33Z
- [ ] https://github.com/monero-ecosystem/monero-python was archived at 2024-03-09T07:06:02Z
- [ ] https://github.com/mozilla-services/hawkauthlib was archived at 2023-06-01T11:16:50Z
- [ ] https://github.com/napari/magicgui was archived at 2022-11-11T16:46:50Z
- [ ] https://github.com/python-acoustics/python-acoustics was archived at 2024-02-07T08:01:48Z
- [ ] https://github.com/python-dugong/python-dugong was archived at 2022-05-02T15:58:27Z
- [ ] https://github.com/sassoftware/python-keyutils was archived at 2022-08-26T01:06:16Z

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by getchoo** [comment]
All leaf packages should have a PR now

**Comment by tomodachi94** [comment]
Just a note: Some packages simply moved their repositories elsewhere, as in #350156 or #342707.
