### ISSUE TITLE
CraftOS-PC plugins

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#346758]
This is an issue for tracking progress towards building CraftOS-PC's plugins reproducibly in Nixpkgs.

## Tasks
- [ ] Install craftos2-lua at `craftos2-liblua.so` instead of just `liblua.so`
   - This path is used in the packages maintained by upstream
   - Building the packages fails when the library is not at the correct path
- [ ] Install Lua headers
- [ ] Make a new attrset for CraftOS-PC plugins (probably `passthru.plugins`)
- [ ] Package the following plugins in their own derivations:
  - [ ] ccemux
  - [ ] computronics-tape
  - [ ] discord
  - [ ] glasses
  - [ ] joystick
  - [ ] periphemu_lua
  - [ ] sound
  - Other out-of-tree plugins, if they exist
