### ISSUE TITLE
Remove enum34

### ISSUE THREAD

**Issue by fabaff** [NixOS/nixpkgs#349607]
Remove `python312Packages.enum34`. 

https://pypi.org/project/enum34/ says:

> Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4

Possibly affected packages:

- [x] brotlipy: https://github.com/NixOS/nixpkgs/pull/349609
- [x] clikit: https://github.com/NixOS/nixpkgs/pull/349601
- [x] dragonfly: https://github.com/NixOS/nixpkgs/pull/349603
- [ ] enum-compat:
  - [x] libsoundtouch: https://github.com/NixOS/nixpkgs/pull/349616
  - [ ] enocean: https://github.com/NixOS/nixpkgs/pull/349763
  - [x] python-registry: https://github.com/NixOS/nixpkgs/pull/349849
  - [ ] i3: https://github.com/NixOS/nixpkgs/pull/350970
  - [x] hplip: https://github.com/NixOS/nixpkgs/pull/350778
- [x] fs: https://github.com/NixOS/nixpkgs/pull/349608
- [x] gin-config: https://github.com/NixOS/nixpkgs/pull/349602
- [x] grpcio: <s>https://github.com/NixOS/nixpkgs/pull/349727</s> https://github.com/NixOS/nixpkgs/pull/350432
- [x] numpy-stl: https://github.com/NixOS/nixpkgs/pull/349599
- [x] pypass: `enum34` is already being removed
- [x] pysc2: https://github.com/NixOS/nixpkgs/pull/350968
- [ ] scikits-odes: 
- [x] serpent: https://github.com/NixOS/nixpkgs/pull/349719
- [x] types-enum34: no dependency on `enum34`
- [x] hypothesis: #389263
- [ ] setools: https://github.com/NixOS/nixpkgs/pull/349733
- [ ] enum34: https://github.com/NixOS/nixpkgs/pull/349611

**Comment by bengsparks** [comment]
https://github.com/HypothesisWorks/hypothesis/pull/2282 removed hypothesis' dependency on `enum34` since v5.

**Comment by bengsparks** [comment]
Progress:
- [ ] enum-compat: #383874
    - [x] enocean: #382155
    - [x] i3altlayout: #382160
- [ ] enum34: #349611
    - [ ] setools: #383882
- [x] types-enum34: #382168

`scikits-odes` and `hypothesis` do not depend on any of the enum34-family packages
