### ISSUE TITLE
Many packages depend on `msrestazure` but don't actually need it

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#350657]
## Issue description

Many packages claim they depend on [the deprecated `msrestazure` package](https://github.com/Azure/msrestazure-for-python#disclaimer), without actually using it. Often, we simply forgot to remove the dependency when it was removed upstream. See the examples I added when creating this issue.

The goal is to eventually drop `msrestazure`.

Subset of #346385.

### Unassessed

- [ ] pkgs/by-name/az/azure-cli/extensions-manual.nix
- [ ] pkgs/by-name/az/azure-cli/python-packages.nix
- [ ] pkgs/development/python-modules/azure-containerregistry/default.nix
- [ ] pkgs/development/python-modules/azure-graphrbac/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-advisor/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-applicationinsights/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-authorization/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-batchai/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-cognitiveservices/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-commerce/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-consumption/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-containerinstance/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-datalake-analytics/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-datalake-store/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-datamigration/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-devspaces/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-devtestlabs/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-eventgrid/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-hanaonazure/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-iotcentral/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-iothubprovisioningservices/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-loganalytics/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-managedservices/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-managementgroups/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-managementpartner/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-marketplaceordering/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-notificationhubs/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-policyinsights/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-rdbms/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-scheduler/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-signalr/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-sql/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-sqlvirtualmachine/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-subscription/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-synapse/default.nix
- [ ] pkgs/development/python-modules/azure-mgmt-trafficmanager/default.nix

### Assessed - not needed by package

- [x] pkgs/development/python-modules/azure-mgmt-dns/default.nix
    - https://github.com/NixOS/nixpkgs/pull/350330
- [ ] pkgs/development/python-modules/azure-mgmt-relay/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/relay/azure-mgmt-relay/CHANGELOG.md?plain=1#L107-L109
- [ ] pkgs/development/python-modules/azure-mgmt-media/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/media/azure-mgmt-media/CHANGELOG.md#L144-L145
- [ ] pkgs/development/python-modules/azure-mgmt-reservations/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/reservations/azure-mgmt-reservations/CHANGELOG.md?plain=1#L113
- [x] pkgs/development/python-modules/azure-multiapi-storage/default.nix
    - No mentions of msrestazure in the codebase anywhere, might have never been necessary
- [ ] pkgs/development/python-modules/azure-mgmt-servicebus/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/servicebus/azure-mgmt-servicebus/CHANGELOG.md?plain=1#L127
- [ ] pkgs/development/python-modules/azure-mgmt-hdinsight/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/hdinsight/azure-mgmt-hdinsight/CHANGELOG.md?plain=1#L140
- [ ] pkgs/development/python-modules/azure-mgmt-logic/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/logic/azure-mgmt-logic/CHANGELOG.md?plain=1#L148-L151 and https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/logic/azure-mgmt-logic/CHANGELOG.md?plain=1#L38
- [ ] pkgs/development/python-modules/azure-mgmt-machinelearningcompute/default.nix
    - Source: https://github.com/Azure/azure-sdk-for-python/blob/f50c865e82e34fbe6738e20df149ea88f3c9e70c/sdk/machinelearning/azure-mgmt-machinelearningcompute/CHANGELOG.md?plain=1#L19
- [ ] pkgs/development/python-modules/azure-batch/default.nix
    - [No mentions in upstream](https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-python%20path%3Asdk%2Fbatch%2Fazure-batch%20msrestazure&type=code)

### Assessed - needed by package (take no action)
- [ ] pkgs/development/python-modules/azure-mgmt-common/default.nix
    - Might be optional?

### Done (dependency removed)
- [x] pkgs/by-name/pr/prowler/package.nix
    - Source: https://github.com/prowler-cloud/prowler/pull/3974
    - Fix: https://github.com/NixOS/nixpkgs/pull/351590

**Comment by tomodachi94** [comment]
cc msrestazure maintainer @bendlas
