### ISSUE TITLE
[tracking issue] Refactor docbook

### ISSUE THREAD

**Issue by AndersonTorres** [NixOS/nixpkgs#351040]
A tracking issue for migrating Docbook to by-name.

- [ ] https://github.com/NixOS/nixpkgs/pull/351039
- [ ] https://github.com/NixOS/nixpkgs/pull/350585
- [ ] https://github.com/NixOS/nixpkgs/pull/351036
- [ ] https://github.com/NixOS/nixpkgs/pull/351038

**Comment by AndersonTorres** [comment]
Closing in favor of  https://github.com/NixOS/nixpkgs/pull/351706
