### ISSUE TITLE
Documentation: github template for build failures could be more clear about getting `meta.maintainers`

### ISSUE THREAD

**Issue by tko** [NixOS/nixpkgs#351245]
## Problem

The template for reporting build failures asks to list people in `meta.maintainers`
```
<!--
Please @ people who are in the `meta.maintainers` list of the offending package or module.
If in doubt, check `git blame` for whoever last touched something.
-->
```

## Proposal

Please include a simple command to do so.

Preferably something slightly simpler than (I've no idea how to use `nix repl`, effectively or otherwise)
```
echo 'map (it: it.github) ${pkg}.meta.maintainers' | nix repl --expr 'import <nixpkgs>{}'
```

## Checklist

- [ ] checked [latest Nixpkgs manual] \([source][nixpkgs-source]) and [latest NixOS manual] \([source][nixos-source])
- [x] checked [open documentation issues] for possible duplicates
- [x] checked [open documentation pull requests] for possible solutions

[latest Nixpkgs manual]: https://nixos.org/manual/nixpkgs/unstable/
[latest NixOS manual]: https://nixos.org/manual/nixos/unstable/
[nixpkgs-source]: https://github.com/NixOS/nixpkgs/tree/master/doc
[nixos-source]: https://github.com/NixOS/nixpkgs/tree/master/nixos/doc/manual
[open documentation issues]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+label%3A%229.needs%3A+documentation%22
[open documentation pull requests]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+is%3Apr+label%3A%228.has%3A+documentation%22%2C%226.topic%3A+documentation%22

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by jackwilsdon** [comment]
Another option is:

```
nix eval nixpkgs#${pkg}.meta.maintainers --apply 'builtins.catAttrs "github"'
```
