### ISSUE TITLE
Remove Gradle 7 due to deprecation

### ISSUE THREAD

**Issue by tomodachi94** [NixOS/nixpkgs#358845]
It is reasonable to assume that Gradle 9 will release soon (likely within the next two release cycles). As Gradle 7 is now the oldest-supported version of Gradle, it will become EOL when this happens. We cannot reasonably support Gradle 7 once it goes completely end-of-life.

## How to help

[Below](#the-list) is a list of in-tree consumers.

For each:
* Check if it builds with the latest version of Gradle. 
  * If it does, update references from `gradle_7` to:
    * `gradle_8` (if it relies on features that will be removed in Gradle 9; there should be a warning in the build log if this is the case)
    * `gradle` (if it does not rely on features scheduled for removal).
  * If it doesn't build with a newer Gradle, attempt to write a patch. 
    * **Submit it upstream first**, especially if upstream is active; the idea is that the fix would be included in the next release of the software, making a special Nixpkgs patch unnecessary and overall contributing to the health of the ecosystem.
    * If upstream is unresponsive and hasn't merged the PR by the time Gradle 9 is released, apply the patch locally.

## The list

- [x] `freenet` (https://github.com/hyphanet/fred/pull/977)
    - [x] Patch submitted
    - [x] Released by upstream (`01499`)
    - [x] Updated locally (#368152)
- [x] `scenic-view` (https://github.com/JonathanGiles/scenic-view/pull/78)
    - [x] Patch submitted
    - [ ] Released by upstream
    - [x] Updated locally (https://github.com/NixOS/nixpkgs/pull/482815)
- [x] `keyspersecond` (https://github.com/RoanH/KeysPerSecond/commit/16fbf060948e822bbaccd96a270e33d829026c8c)
    - [x] Patch submitted
    - [ ] Released by upstream
    - [x] Updated locally (#430417)
- [x] `openjfx` (https://github.com/openjdk/jfx/pull/1257 and https://github.com/openjdk/jfx/pull/1559)
    - [x] Patch submitted
    - [x] Released by upstream (`24+18`)
    - [x] Updated locally (https://github.com/NixOS/nixpkgs/pull/477305)
- [x] `fastddsgen`
    - [x] Patch submitted (blocked by https://github.com/eProsima/IDL-Parser/pull/165)
    - [x] Released by upstream
    - [x] Updated locally
- [x] `freeplane` (https://github.com/freeplane/freeplane/commit/dc4421370c8e17b9a79f2218a579a1b8b7afd650 and https://github.com/freeplane/freeplane/commit/f0e7096783a7edd362f5eb8d1055e257f906f524)
    - [x] Patch submitted
    - [x] Released by upstream (`1.12.6`)
    - [x] Updated locally
- [x] `stirling-pdf` (https://github.com/Stirling-Tools/Stirling-PDF/commit/250c317155a4eca056c9113d0498a99d2f9aa32a)
    - [x] Patch submitted
    - [x] Released by upstream (`1.0.1`)
    - [x] Updated locally
- [x] `marytts`
    - [x] Patch submitted (https://github.com/marytts/marytts/pull/1120)
    - [ ] Released by upstream
    - [x] Updated locally (https://github.com/NixOS/nixpkgs/pull/430271)
- [x] `corretto`:
    - [x] 11
        - [ ] Patch submitted
        - [ ] Released by upstream
        - [x] Updated locally
    - [x] 17
        - [ ] Patch submitted
        - [ ] Released by upstream
        - [ ] Updated locally
    - [x] 21
        - [ ] Patch submitted
        - [ ] Released by upstream
        - [x] Updated locally

**Comment by tomodachi94** [comment]
[Gradle 9 will release in Q2 of 2025](https://gradle.org/whats-new/gradle-9/); consequently, Gradle 7 will be deprecated once 9 is released.

**Comment by tomodachi94** [comment]
I hope you'll pardon my meme...

https://gifdb.com/images/high/lizzo-its-about-damn-time-crx3v5w4zg8hpobn.webp

**Comment by tomodachi94** [comment]
That's all of them! Thanks to everyone who helped out. Last item is to drop gradle_7: https://github.com/NixOS/nixpkgs/pull/482816
