### ISSUE TITLE
Removing libsoup 2.4

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#360897]
Libsoup [2.4 ABI branch](https://gitlab.gnome.org/GNOME/libsoup/-/commits/libsoup-2-74/?ref_type=heads) has been unsupported for a while now and security issues are [popping up](https://github.com/NixOS/nixpkgs/pull/360878). We should work on getting rid of it.

# Plan

1. Rename `libsoup` to `libsoup_2_4`.

2. Walk though the packages still using the old version and replace it where possible.

    The problematic part is that in general, a program can only load one of the libraries or there will be symbol conflicts. So we need to make sure to replace it at the same time for all 

    - [ ] `dino` – supports libsoup 3 but also uses `libnice`, which transitively depends on old libsoup
    - [ ] `inkscape` – does not appear to be used
    - [ ] `libnice` – depends on 2.4 through `gnupg-igd-1_0`, there is a stale MR to bump so we might need to use libsoup do it locally like [Arch does](https://gitlab.archlinux.org/archlinux/packaging/packages/libnice/-/blob/77af8d1ab1202c76fdddb21dffe7d8320d783a82/PKGBUILD#L40)

3. Attempt to upgrade packages stuck with the old version upstream.

4. After a while, remove the stuck packages.

**Comment by tomodachi94** [comment]
`libnice` is unmaintained(!!). Pinging `dino` maintainers @qyliss and @tomfitzhenry so they're aware.

**Comment by alyssais** [comment]
I think the libnice MR probably needs to just be resubmitted by somebody else. It's a one character change.

**Comment by nyabinary** [comment]
> I think the libnice MR probably needs to just be resubmitted by somebody else. It's a one character change.

https://github.com/NixOS/nixpkgs/pull/395063 I just fetched the patch for now :P

**Comment by LordGrimmauld** [comment]
https://github.com/wxWidgets/wxWidgets/pull/23633
for `wxwidgets`, it seems it can build against `webkitgtk_4_1` which depends on `libsoup_3`
with https://github.com/NixOS/nixpkgs/pull/395063 that'd be almost all users of `libsoup_2_4`, no?

**Comment by LordGrimmauld** [comment]
`cinny-desktop` is currently working on an update: https://github.com/NixOS/nixpkgs/issues/360897 and https://github.com/cinnyapp/cinny-desktop/pull/429

transcaffeine is on it, see https://github.com/NixOS/nixpkgs/pull/387356#issuecomment-2703940078

**Comment by LordGrimmauld** [comment]
`cog` in nixpkgs is mostly unmaintained for the past 4 years, though it seems to no longer depend on webkitgtk at all since https://github.com/Igalia/cog/blob/f1435a2e180296a66dd2529cfa5900e712812ca4/NEWS#L161-L162

**Comment by LordGrimmauld** [comment]
https://github.com/NixOS/nixpkgs/blob/f675531bc7e6657c10a18b565cfebd8aa9e24c14/pkgs/by-name/en/en-croissant/package.nix#L53-L61
`en-croissant` is an absolute mess :/
However, once https://github.com/franciscoBSalgueiro/en-croissant/pull/407 hits release it can be updated trivially. An `-unstable` *might* make sense too, not sure.

**Comment by LordGrimmauld** [comment]
For restic browser, the relevant upstream PR is https://github.com/emuell/restic-browser/pull/139

**Comment by LordGrimmauld** [comment]
https://github.com/NixOS/nixpkgs/blob/f675531bc7e6657c10a18b565cfebd8aa9e24c14/pkgs/by-name/gu/gui-for-clash/package.nix#L94-L95
Uh, what the hell is this?? Why does this package depend on the libsoup_2_4 webkit, and then specifies libsoup_3???

**Comment by LordGrimmauld** [comment]
https://github.com/indigo-dc/oidc-agent/blob/4fb35a62b81abe9f542a7d6dd86fb022ab5c1073/Makefile#L192C11-L192C22
oidc-agent seems to have logic for `webkitgtk_4_1` but wiring that up to nix likely takes some work

**Comment by LordGrimmauld** [comment]
https://github.com/crosswire/xiphos/pull/1194
`xiphos` just needs an update to build with `webkitgtk_4_1`

**Comment by LordGrimmauld** [comment]
Prusa slicer seems to support webkitgtk_4_1 since https://github.com/prusa3d/PrusaSlicer/commit/a552b8fd07a2c16b854db6dd0611cc1ee38d32ff

**Comment by SuperSandro2000** [comment]
dino has an update at #398018

**Comment by LordGrimmauld** [comment]
Libmateweather is waiting for upstream, see https://github.com/mate-desktop/libmateweather/pull/133
This is ~50 dependents.

**Comment by LordGrimmauld** [comment]
Related: https://github.com/NixOS/nixpkgs/pull/395063#issuecomment-2800012149
there now is a branch to bundle all libsoup-related upgrades to not have inconsistent package versions

**Comment by LordGrimmauld** [comment]
https://gitlab.gnome.org/GNOME/libgdata/-/merge_requests/49
`libgdata` likely needs some more work upstream. The diff here is extremely large and not yet approved either.

**Comment by jtojnar** [comment]
`libgdata` is only used by `gvfsd-google` daemon which is a leaf program so it will not make anything crash. Likewise, other changes will not affect it since the only other libraries it links are [libgoa](https://gitlab.gnome.org/GNOME/gvfs/-/blob/6d14d850e99a3addf5b2641b7df9475f96bb396b/daemon/meson.build#L386) (which only links glib) and [libgvfsdaemon](https://gitlab.gnome.org/GNOME/gvfs/-/blob/6d14d850e99a3addf5b2641b7df9475f96bb396b/daemon/meson.build#L594) (which links [few other](https://gitlab.gnome.org/GNOME/gvfs/-/blob/6d14d850e99a3addf5b2641b7df9475f96bb396b/daemon/meson.build#L99-123) [safe libraries](https://gitlab.gnome.org/GNOME/gvfs/-/blob/6d14d850e99a3addf5b2641b7df9475f96bb396b/common/meson.build#L25-48)).

**Comment by chrisheib** [comment]
I'm not sure where the best place to ask this is. Asked it in the PR as well, later saw that one is already closed.

I got unexpectedly hit by this today on nixos unstable on rebuilding the config (no flakes, no home manager):
`error: Package ‘libsoup-2.74.3’ in /nix/store/n8dygvqyyysa9ymvz4fc08d0l3ks7nk6-nixos/nixos/pkgs/development/libraries/libsoup/default.nix:134 is marked as insecure, refusing to evaluate.`

I don't include any of the above mentioned packages directly, so I guess its a dependency of something. Is there an easy way to find out which of my included packages depends on it?

**Comment by gepbird** [comment]
@chrisheib yes, add `--show-trace` to the command you built your system with.

For testing it, I added `ario` package to my config which depends on `libsoup_2_4`, and I see that in the output:

```console
       … while evaluating derivation 'ario-1.6'
         whose name attribute is located at /nix/store/dr8qabarjnskcjrznp4nc07p5yzwjly5-source/pkgs/stdenv/generic/make-derivation.nix:482:13

       … while evaluating attribute 'buildInputs' of derivation 'ario-1.6'
         at /nix/store/dr8qabarjnskcjrznp4nc07p5yzwjly5-source/pkgs/stdenv/generic/make-derivation.nix:537:13:

<40 lines omitted>

       error: Package ‘libsoup-2.74.3’ in /nix/store/dr8qabarjnskcjrznp4nc07p5yzwjly5-source/pkgs/development/libraries/libsoup/default.nix:134 is marked as insecure, refusing to evaluate.
```

**Comment by heitorPB** [comment]
`darktable` depends on libsoup-2.74.3: https://github.com/NixOS/nixpkgs/issues/429268

`orca-slicer` depends on libsoup-2.74.3: https://github.com/NixOS/nixpkgs/issues/429433

**Comment by jtojnar** [comment]
In March 2026, new version of webkitgtk will drop support for [libsoup 2.4](https://discourse.gnome.org/t/webkitgtk-is-removing-support-for-libsoup-2/31873). This will result in removal of `webkitgtk_4_0`. Since we backport all webkitgtk releases to stable to get security fixes, we should drop drop the package before branch-off to avoid breakage.

**Comment by LordGrimmauld** [comment]
That is quite late of a find... You mind posting this in the release blockers thread and drafting up a drop PR? I can review, but don't have the capacity for such a large change atm

**Comment by greg-hellings** [comment]
restic-browser should be addressing its transitive dependency via #452158 with upgrade to webkit 4.1 dependency.

**Comment by whispersofthedawn** [comment]
i took a look through nixpkgs with copious usage of ripgrep (might've missed things, but i *think* this is representative) to figure out the current status of things. broadly categorizing packages:

semi-clear migration paths:
- [x] `ario`: leaf package. hasn't been updated in four years. however, it doesn't actually seem to depend on libsoup at all? debian removed the dependency as well. we should just be able to get rid of it. pr: #526209
- [ ] `hqplayerd`: leaf package, does have a nixos module. looking at their home page, it looks like they just released a version with a "New in-house implementation of UPnP 2.0 AV software stack to remove Rygel dependency", which sounds to me like we might be able to drop `hqplayerd.rygel` and the `gupnp` dependency with a 6.0 update. looks to me like a potentially workable migration path (though confusing since it's a binary-only release with no obvious building documentation).
  - maintainer cc: @lovesegfault. i've taken a stab at it, and it's not going super well since i don't have a license to the software and don't have a good enough idea of what it is to make sure nothing is broken. is there a chance you'd be able to take a look?
- [ ] `pragha`: leaf. hasn't been updated in four years, but it looks like the libsoup support is optional and defaults to off in Nixpkgs, so this shouldn't be a problem. probably just need to drop the feature flag.
- [x] `spice-up`: leaf package, hasn't been updated in four years. https://github.com/Philip-Scott/Spice-up/issues/328 indicates that this may not actually use libsoup at all, though, so there's a solid chance we can remove it. pr: #526089
- [x] `surf`: has one dependent (`surf-display`). uses libsoup 2.4 for the current version. there's an open build fix pr that migrates to `libsoup_3`, among other things. pr: #508345
- [ ] `xplorer`: leaf package, broken since webgtk_4_0 was dropped. however, seems like upstream has migrated to tauri v2 since (~~along with being an "ai file explorer" though soooo~~), so i *think* this should be okay to migrate.
  - i will not do the migration, though. i took a look and it's messy, and i don't care to put in the time for vibe coded ai-powered garbage. if someone wants to put in the effort, feel free. otherwise, i don't think we're losing much if we drop.

no obvious (to me) paths forward:
- [ ] `citrix_workspace{,_25_08_10,_26_01_0}`: leaves. wrapped binary with unclear dependencies (to me), so i can't tell if libsoup is hard-required. i assume this is a package folks are actively using.
  - maintainer cc: @flacks. do you know if this libsoup 2.4 dependency is a hard requirement?
  - dropping the dependency does lead to failures with auto-patchelf. urgh.

potential drops mby (or more generally, "things i think would be fine to yeet if it comes down to it"):
- [ ] `desktop-postflop`: leaf package. hasn't been updated in three years when the developer suspended work on it.
- [ ] `fondo`: leaf package. hasn't been updated in five years (https://github.com/calo001/fondo).
- [ ] `gamehub`: leaf package. hasn't been updated in years. broken since webkitgtk_4_0 was dropped. easy drop.
- [ ] `gssdp`: only in-tree dependents are `gupnp` and `hqplayerd`, see above and below. everything else is on `gssdp_1_6`.
- [ ] `gupnp`: only in-tree dependent is `hqplayerd`, see above. everything else is on `gupnp_1_6`.
- [ ] `haskellPackages.gi-soup2`: just bindings to libsoup 2.4. not super familiar with how haskell is handled in nixpkgs but seems like the only dependents are webkitgtk 4.0 related so I don't think this should cause breakage if it and its dependents were dropped.
- [ ] `haskellPackages.spike`: seems like a one-and-a-half decade old "experimental web browser" (https://github.com/Tener/spike). looks like an easy drop.
- [x] `libchamplain`: has support for building with both libsoup 2.4 and 3. can just drop support for the former and make it non-default. pr: #525672
- [ ] `libepc`: has been archived upstream, with no changes since 2020. has one in-tree dependent:
	- `glom`: also archived upstream, no changes since 2022. yay yippee. seems fine to kill.
- [x] `libgdata`: leaf package, has been archived upstream. with no dependents, seems like an easy drop. pr: #525685
- [x] `librest`: old version requires libsoup 2.4, but all in-tree dependents already use the newer version. pr: #525816
- [ ] `mouse-actions-gui`: leaf package, broken since webkitgtk_4_0 was dropped. hasn't migrated away from tauri v1 upstream, with no response to an issue from january: https://github.com/jersou/mouse-actions/issues/95. nothing done in Nixpkgs since. seems like an okay thing to drop if necessary.
- [ ] `squirreldisk`: leaf package, hasn't been updated in three years. *has* seen fixes in nixpkgs within the last year.
- [x] `uhttpmock`: `uhttpmock` is an old version of `uhttpmock_1_0`. it has a singular in-tree dependent, `libgdata`. as above, `libgdata` has been proposed for drop anyway, so this should be an easy drop/migration to new version after that. pr: #526054

so yeah. there are a few specific packages that present issues, but broadly speaking i personally think that most of the remaining dependents are not issues. seems like we can finally pull the trigger and get rid of this properly soon :D (i'm down to do some of the actual cleanup drop work when the time comes, if we'd like to go ahead with it)

**Comment by whispersofthedawn** [comment]
we've put up a tentative drop pr up at #529295 :3. see the description/commit messages there for our thoughts on the unchecked boxes above.
