### ISSUE TITLE
Report undeclared gio-unix-2.0 upstream

### ISSUE THREAD

**Issue by jtojnar** [NixOS/nixpkgs#36468]
The following projects fail to declare their dependency on `gio-unix-2.0` headers, which produces errors like the following:

```
src/gcal-shell-search-provider-generated.c:15:12: fatal error: gio/gunixfdlist.h: No such file or directory
 #  include <gio/gunixfdlist.h>
            ^~~~~~~~~~~~~~~~~~~
compilation terminated.

dbus-player.c:22:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
#include <gio/gdesktopappinfo.h>

../plugins/housekeeping/gsd-disk-space.c:32:10: fatal error: gio/gunixmounts.h: No such file or directory
 #include <gio/gunixmounts.h>
```

- [ ] pkgs/applications/audio/audio-recorder/default.nix https://bugs.launchpad.net/audio-recorder/+bug/1784622
- [x] pkgs/applications/backup/deja-dup/default.nix
- [x] pkgs/applications/misc/zathura/core/default.nix
- [x] pkgs/desktops/gnome-3/apps/gnome-calendar/default.nix https://gitlab.gnome.org/GNOME/gnome-calendar/issues/259
- [x] pkgs/desktops/gnome-3/apps/gnome-photos/default.nix
- [x] pkgs/desktops/gnome-3/apps/seahorse/default.nix https://gitlab.gnome.org/GNOME/seahorse/issues/8
- [x] pkgs/desktops/gnome-3/core/baobab/default.nix
- [ ] pkgs/desktops/gnome-3/core/evince/default.nix https://gitlab.gnome.org/GNOME/evince/issues/950
- [x] pkgs/desktops/gnome-3/core/gnome-calculator/default.nix
- [x] pkgs/desktops/gnome-3/core/gnome-desktop/default.nix https://gitlab.gnome.org/GNOME/gnome-desktop/issues/10
- [x] pkgs/desktops/gnome-3/core/gnome-settings-daemon/default.nix https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/16
- [x] pkgs/desktops/gnome-3/core/gnome-software/default.nix https://gitlab.gnome.org/GNOME/gnome-software/issues/320
- [x] pkgs/desktops/gnome-3/core/gnome-system-log/default.nix
- [x] pkgs/desktops/gnome-3/core/gnome-user-share/default.nix https://gitlab.gnome.org/GNOME/gnome-user-share/issues/1
- [x] pkgs/desktops/gnome-3/core/nautilus/default.nix https://gitlab.gnome.org/GNOME/nautilus/issues/287
- [x] pkgs/desktops/gnome-3/core/totem/default.nix https://gitlab.gnome.org/GNOME/totem/issues/246
- [ ] pkgs/desktops/mate/mate-applets/default.nix https://github.com/mate-desktop/mate-applets/issues/335
- [ ] pkgs/desktops/mate/mate-panel/default.nix https://github.com/mate-desktop/mate-panel/issues/852
- [x] pkgs/desktops/xfce/core/xfce4-power-manager.nix https://gitlab.xfce.org/xfce/xfce4-power-manager/-/issues/39
- [x] gnome-recipes https://gitlab.gnome.org/GNOME/recipes/issues/76
- [ ] pkgs/applications/editors/gnome-latex/default.nix https://gitlab.gnome.org/GNOME/gnome-latex/issues/63 
- [x] gnome-flashback https://gitlab.gnome.org/GNOME/gnome-flashback/issues/3
- [x] gnome-panel https://gitlab.gnome.org/GNOME/gnome-panel/issues/6
- [x] gnome-applets https://gitlab.gnome.org/GNOME/gnome-applets/issues/3

We should report it upstream so they can fix it. Try building the package without the hack to see the error.

**Comment by jtojnar** [comment]
Incorrect `poppler-glib` headers:

- [ ] pkgs/desktops/gnome-3/core/tracker-miners/default.nix https://bugzilla.gnome.org/show_bug.cgi?id=795573

**Comment by jtojnar** [comment]
All offenders are reported, now we wait.

**Comment by jtojnar** [comment]
- xfce4-14.exo https://bugzilla.xfce.org/show_bug.cgi?id=15825

**Comment by mkg20001** [comment]
(after merge)

- [ ] pkgs/desktops/cinnamon/cinnamon-screensaver
- [ ] pkgs/desktops/cinnamon/cinnamon-session
- [ ] pkgs/desktops/cinnamon/cinnamon-settings-daemon
- [ ] pkgs/desktops/cinnamon/cinnamon-nemo
- [ ] pkgs/desktops/cinnamon/xapps

**Comment by nh2** [comment]
I found in https://github.com/NixOS/nixpkgs/pull/77979#discussion_r368708826 how

```nix
{
  mesonFlags = [
    # TODO: https://github.com/NixOS/nixpkgs/issues/36468
    "-Dc_args=-I${glib.dev}/include/gio-unix-2.0"
  ];
}
```

can be used instead of `NIX_CFLAGS_COMPILE`, which I think is superior and we should switch to it for `meson` based builds because

* that way all parts of meson can see the flag, passing it to potentially more places than we do with our low-level hack
* the flag shows up in the build logs, making it clear what's happening

**Comment by worldofpeace** [comment]
> I found in [#77979 (comment)](https://github.com/NixOS/nixpkgs/pull/77979#discussion_r368708826) how
> 
> ```nix
> {
>   mesonFlags = [
>     # TODO: https://github.com/NixOS/nixpkgs/issues/36468
>     "-Dc_args=-I${glib.dev}/include/gio-unix-2.0"
>   ];
> }
> ```
> 
> can be used instead of `NIX_CFLAGS_COMPILE`, which I think is superior and we should switch to it for `meson` based builds because
> 
>     * that way all parts of meson can see the flag, passing it to potentially more places than we do with our low-level hack
> 
>     * the flag shows up in the build logs, making it clear what's happening

Thanks :heart:

**Comment by mwleeds** [comment]
This is fixed in GNOME Recipes now.

**Comment by masipcat** [comment]
- [ ] squeekboard https://source.puri.sm/Librem5/squeekboard/-/issues/201

**Comment by jtojnar** [comment]
Xfce-power-manager (https://gitlab.xfce.org/xfce/xfce4-power-manager/-/issues/39) has patch available: https://gitlab.xfce.org/xfce/xfce4-power-manager/-/commit/cbb3e82172ef520d520c4744447889767ea1c2b7

**Comment by rvl** [comment]
I submitted a patch upstream for [`pkgs/applications/window-managers/phosh/default.nix`](https://github.com/NixOS/nixpkgs/blob/4ec0020e841be6f186b712fd90e4cad5c40712e1/pkgs/applications/window-managers/phosh/default.nix#L96-L97): https://gitlab.gnome.org/World/Phosh/phosh/-/merge_requests/1363

**Comment by bobby285271** [comment]
With https://github.com/xfce-mirror/xfce4-pulseaudio-plugin/commit/a7eb9b9a43b4b1b3256a2999f276ce7d6b764ca0, https://github.com/xfce-mirror/exo/commit/6600467166621462717f996942d81051b8d96473, https://github.com/xfce-mirror/xfce4-notifyd/commit/307c8641b38f5161096d9886f1539b7f58b309c9, https://github.com/xfce-mirror/ristretto/commit/f7758e38b14ee4e124f38ddf56095e9fef91457b, https://github.com/xfce-mirror/xfce4-docklike-plugin/commit/867124d716c43bb1894ff69d57ee93474fae483b, https://github.com/xfce-mirror/xfce4-session/commit/a8ed1746fb4aeae6436b4c7b3a58d2926b7c4323 and #298614 all gio-unix-2.0 workarounds in Xfce are either upstreamed or cleaned up now.

**Comment by jtojnar** [comment]
Entangle: https://gitlab.com/entangle/entangle/-/merge_requests/61
