### ISSUE TITLE
Tracking issue: OneAPI

### ISSUE THREAD

**Issue by arunoruto** [NixOS/nixpkgs#367722]
### Tracking description

While the support for CUDA is quite good on nixpkgs and ROCm is [getting there](https://github.com/NixOS/nixpkgs/issues/197885), Intel's OneAPI is not entirely present. Like the tracking issue for ROCm, I wanted to have a list of packages contained in OneAPI's toolkits and track which are already packaged and still need to be.

#### Packages

- [x] Intel® oneAPI Level Zero ([code](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/le/level-zero/package.nix))
- [x] Intel® Video Processing Library ([VPL](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/vp/vpl-gpu-rt/package.nix))

##### [Base Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html?packages=oneapi-toolkit&oneapi-toolkit-os=linux&oneapi-lin=offline)

- [ ] Intel® oneAPI DPC++/C++ Compiler
  - #245031
- [ ] Intel® DPC++ Compatibility Tool
- [ ] Intel® Distribution for GDB*
- [ ] Intel® oneAPI DPC++ Library (oneDPL)
- [ ] Intel® oneAPI Threading Building Blocks (oneTBB)
- [x] Intel® oneAPI Math Kernel Library ([oneMKL](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/mk/mkl/package.nix))
- [x] Intel® oneAPI Deep Neural Network Library ([oneDNN](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/development/libraries/oneDNN/default.nix))
- [ ] Intel® oneAPI Data Analytics Library (oneDAL)
- [ ] Intel® oneAPI Collective Communications Library (oneCCL)
- [ ] Intel® Integrated Performance Primitives
- [ ] Intel® Cryptography Primitives Library
- [ ] Intel® Advisor
- [ ] Intel® VTune™ Profiler
  - #353528 

##### [HPC Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/hpc-toolkit-download.html?packages=hpc-toolkit&hpc-toolkit-os=linux&hpc-toolkit-lin=offline)

- [ ] Base Toolkit
- [ ] Intel® Fortran Compiler
- [ ] Intel® MPI Library

#### Config

- [ ] Like cudaSupport and rocmSupport, oneapiSupport could be provided to packages, which can have oneapi as an additional dependency, like pytorch, jaxlib, ...
- [ ] OneAPI team?

---

Add a :+1: [reaction] to [issues you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[issues you find important]: https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by aginiewicz** [comment]
Would love to see this happen. Will this include oneAPI runtime for CPU-only OpenCL? Looked at list of packages above, but cannot see one. Looking for something like this one – https://aur.archlinux.org/packages/intel-opencl-runtime – unless I'm not aware and this is already possible. What I looked at, is that intel-ocl works only on older CPUs (got Core Ultra, so no luck) and intel-compute-runtime only for GPUs (both integrated and discrete), and the CPU-only driver is distributed separately (https://www.intel.com/content/www/us/en/developer/articles/tool/opencl-drivers.html#cpu-section), but I cannot get it to show up on my machine.

**Comment by arunoruto** [comment]
> Would love to see this happen. Will this include oneAPI runtime for CPU-only OpenCL? Looked at list of packages above, but cannot see one. Looking for something like this one – https://aur.archlinux.org/packages/intel-opencl-runtime – unless I'm not aware and this is already possible. What I looked at, is that intel-ocl works only on older CPUs (got Core Ultra, so no luck) and intel-compute-runtime only for GPUs (both integrated and discrete), and the CPU-only driver is distributed separately (https://www.intel.com/content/www/us/en/developer/articles/tool/opencl-drivers.html#cpu-section), but I cannot get it to show up on my machine.

While it isn't a part of a toolkit mentioned above, it falls under the "oneAPI" branding. It seems there is not shell option for the new opencl runtime, so .deb or .rpm packages need to be used. I found out the link for the newest deb package: https://apt.repos.intel.com/oneapi/pool/main/intel-oneapi-runtime-opencl-2025.0.4-1519_amd64.deb
But packaging a deb package needs some understanding of the underlying structure, which I am still trying to familiarize with! And example is the [MKL](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/mk/mkl/package.nix) package. This doesn't mean that the opencl runtime will be the same, but it can happen.
According to the AUR link you sent, it depends on the basetoolkit, which needs to be provided for the runtime to work! While the whole basekit is probably not needed, it does not specify which packages are needed tho...

But I can add it to the list above, and maybe it can be tackled in the future!

**Comment by aginiewicz** [comment]
Wonderful, thanks! Will be keeping an eye on this tracking issue then! While I was an Arch Trusted User in the past and packaged a lot of stuff there, I'm still exploring nix, so won't be of much help currently, though might come back later, when I get accustomed to nix packaging

**Comment by eclairevoyant** [comment]
related: #74148

**Comment by kilyanni** [comment]
Base/HPC Toolkit got merged recently it seems: https://github.com/NixOS/nixpkgs/pull/448561

No wrapping for the compiler at the moment, see comments on https://github.com/NixOS/nixpkgs/pull/424900 for potential workarounds

Gonna see if I can wrangle `wrapCC` a bit for `icpx`

**Comment by KyleSanderson** [comment]
Size	2171.55 MB
Version	2026.0.0
Date	April 24, 2026
SHA384	b3931405eca08c75acffc3dd870f6f79c6acdc4bd4bb1438b2f3d71326ce45bf24f6169c3e8190072138cfb159d52e31
Intel® oneAPI Toolkit (version 2026.0.0) has been updated to include functional and security updates. Users should update to the latest version.

**Comment by kilyanni** [comment]
Seems like they've unified the base and HPC toolkits into just one
Would've been nice if they'd done that a year or two ago ^^'

Opened https://github.com/NixOS/nixpkgs/pull/516662

**Comment by retblast** [comment]
Offtopic, but, guys, thanks for your efforts. When this is done, we'll be able to have llama-cpp-sycl. Hopefully faster than vulkan haha.

**Comment by KyleSanderson** [comment]
> Offtopic, but, guys, thanks for your efforts. When this is done, we'll be able to have llama-cpp-sycl. Hopefully faster than vulkan haha.

It's not at this time, Intel's basically abandoned this backend and is focused on vulkan with llama. vLLM has dedicated engineers on it, but that's for their DC line. I have a very large build script to get all of this built, and add NPU support to the nixpkg with the driver, but it's all quite fiddly.

**Comment by retblast** [comment]
A shame and a great thing kind of at the same time, because they wasted effort, but at least Vulkan is general. Though, Pytorch/ComfyUI do not support Vulkan.

**Comment by eclairevoyant** [comment]
Also needs "Intel® Graphics Offline Compiler for OpenCL™ Code" (intel-ocloc)

**Comment by arunoruto** [comment]
> Intel® Graphics Offline Compiler for OpenCL

Got any link to where it can be downloaded? I did a quick search and couldn't find it. It seems like its bundled in another package?
