### ISSUE TITLE
Fix failing NixOS tests

### ISSUE THREAD

**Issue by xeji** [NixOS/nixpkgs#40257]
This is a tracking issue for fixing/improving tests in `nixos/tests` that have repeatedly failed on Hydra.
Some failures are likely caused by "real" underlying issues, others by broken or fragile test cases. I plan to investigate and try to fix them. Help is always welcome. Feel free to edit this list.

(nd = non-deterministic failure)

#### Fixed

(hopefully, for non-deterministic failures) 

- [x] `acme` (i686) #40410 
- [x] `atd` nd (unknown fix)
- [x] `bittorrent` 00aee56f3d6ce95b8c179b14654edb931bc91340
- [x] `blivet` disabled #45931m blivet version is ancient anyway
- [x] `cjdns` (i686) #40740 test was ok, service failed
- [x] `containers-imperative` (i686) 46874
- [x] `dhparams` (sporadic?) (unknown fix)
- [x] `dnscrypt-proxy` failed with apparmor errors #40801
- [x] `ec2-config` disabled, doesn't work in sandbox #46830 
- [x] `flatpak` (new, see #33371)
- [x] `gdk-pixbuf` (i686) #46916
- [x] `hardened` #40745
- [x] `hibernate` (i686) #46882
- [x] `home-assistant` #40735
- [x] `iftop` nd #41309
- [x] `installer.grub1`: test case looks ok, grub1 install broken, fixed in #46769
- [x] `kafka_{0_9,0_10,0_11,1_0}`: #40390 
- [x] `matrix-synapse` #45596
- [x] `mesos` #40373, fixed again in #45758 after a change in dockerTools broke it
- [x] `munin` (i686) munin build freezes, timeout. 3b336d0c180f8d6615c92695d446de59804baf47
- [x] `munin` nd (x86_64) #45622 
- [x] `mysql-backup` nd #40258
- [x] `mysql-replication` (i686) #40850
- [x] `networking.networkd.routes` #45649
- [x] `networking.networkd.virtual` #45649 
- [x] `networking.scripted.routes` #45649 
- [x] `networking.scripted.virtual` #45649 
- [x] `networking.networkd.macvlan` (nd?) 13c3986b7a7da4f29005349674b334b6b914a371
- [x] `nexus` - test exists but not run on hydra at all #40522
- [x] `nexus` (i686) #40743
- [x] `ostree` #46762
- [x] `plotinus` nd #40239 
- [x] `statsd` nd #40214 
- [x] `systemd` (since systemd 239 update) 03c1f567d59 (in staging)
- [x] `taskserver` eval error 7ac794f8780f4c35221763de6a425a07004515f2
- [x] `wordpress` 45582
- [x] `xautolock`, `xss-lock`: failed because `xlockmore` build output was empty, 2483720ad91cfaa278583ad4deea317dc2388319

#### Open

- [ ] `containers-restart_networking`
- [ ]  many `installer` tests fail occasionally, more so on i686

#### Not fixed, but good enough for now?

- [ ] `chromium`: nd, occasional timeouts
- [ ] `keymap.*`: nd - still fail occasionally but rarely after some improvements, need major redesign

**Comment by peterhoeg** [comment]
I'm sure @dotlambda is quite interested in the ```home-assistant``` tests

**Comment by jtojnar** [comment]
We also have a broken test currently blocking the [Flatpak pull request](https://github.com/NixOS/nixpkgs/pull/33371). If someone could take a look at it, it would be great.

**Comment by peterhoeg** [comment]
> so that it ignores "Timer git out of sync" errors

I get that error all the time here as well - I think having a list of errors to ignore is a perfectly reasonable thing to do.

**Comment by xeji** [comment]
@dotlambda I am experimenting with QEMU settings to see if giving the VM its own (non-real-time) clock can avoid the "Timer got out of sync" errors for Home Assistant, but I think we can't fully get rid of them.

**Comment by peterhoeg** [comment]
I don't think it's related to presence or absence of an RTC - it's simply a matter of HA not being able to process its events fast enough if the hardware is either under-powered or over-loaded (which I guess is technically the same thing).

**Comment by rvl** [comment]
Thanks for this effort @xeji. I wrote a non-deterministic test and would have fixed it - had hydra e-mailed me when it failed building the release-18.03 jobset. It was only by chance that I saw the PR.

**Comment by xeji** [comment]
We've made a lot of progress on the tests since this was opened. There are some open issues but I think this tracking issue has served its purpose, so I'll close it now.
