### ISSUE TITLE
mpd: add option to run as a systemd user service

### ISSUE THREAD

**Issue by emmanuelrosa** [NixOS/nixpkgs#41772]
## Issue description

As it stands, the NixOS MPD module runs MPD as a systemd system service. As such it expects that the MPD user account (mpd by default) has control over the audio device. This conflicts with PulseAudio when it's used as a systemd user service (the default configuration). 

The intent of this change is to extend the MPD module so that it can be configured to run as a systemd user service. The changes remain backwards-compatible so users can continue with a system-wide configuration or go with a per-user config.

## Example

I have a proof-of-concept of the modified module [here](https://gist.github.com/emmanuelrosa/352caf7de134b3f5a67697ecdb6d13f0) which I'm currently experimenting with. It can be used in `configuration.nix` as follows:

```
disabledModules = [ "services/audio/mpd.nix" ];

imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      (builtins.fetchurl https://gist.githubusercontent.com/emmanuelrosa/352caf7de134b3f5a67697ecdb6d13f0/raw/a11d4f66fe5329c9ef0285b066c34c8a3c01ba1d/mpd.nix)
    ];

services.mpd = {
      enable = true;
      systemWide = false; # Defaults to false to retain current functionality.
      musicDirectory = "~/music"; # Directories adjusted to use ~ which MPD expands to user's home directory
      playlistDirectory = "~/playlists";
      dataDir = "~/.mpd";

      extraConfig = ''
        audio_output {
          type "pulse"
          name "PulseAudio"
        }
      '';
  };
```

The result is MPD running within a user slice:

```
systemctl --user status

● nixos-laptop
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Sat 2018-06-09 15:28:34 EDT; 3h 6min ago
   CGroup: /user.slice/user-1000.slice/user@1000.service
           ├─mpd.service
           │ └─22074 /nix/store/jbp01j4ysxmsk249kqxdqqyikjixqxba-mpd-0.20.18/bin/mpd --no-daemon /nix/store/qd3ngnffsx20vsws9wr79id0h44p4b5v-mpd.conf
           ├─pulseaudio.service
           │ └─1296 /nix/store/0xy0hhnj6wlga7spqkb5h6c03y3234w7-pulseaudio-11.1/bin/pulseaudio --daemonize=no
           └─init.scope
             ├─1239 /nix/store/c5wlvh9g9xxh4wca6l1klj1clxifz9qh-systemd-238/lib/systemd/systemd --user
             └─1240 (sd-pam)
```

## TODOS

- [ ] Ability to use a different mpd.conf per user; Probably by providing a `configurationFile` option which overrides the other mpd.conf options and simply points to a file in the users home directory (ex. `~.config/mpd/mpd.conf`).
- [ ] See if it's possible to get realtime scheduling to work.
- [x] Add NixOS tests. Currently there aren't any. The different options make for numerous potential combinations; I'm to lazy to test all of them manually.

**Comment by jfly** [comment]
@emmanuelrosa did you ever add support for running mpd as a user service? It looks like https://github.com/NixOS/nixpkgs/pull/42118 just added tests in preparation for running it as a user service.

**Comment by emmanuelrosa** [comment]
Wow, I forgot all about this. Perhaps because I soon after stopped using MDP.

The implementation is still on Github: https://gist.githubusercontent.com/emmanuelrosa/352caf7de134b3f5a67697ecdb6d13f0/raw/a11d4f66fe5329c9ef0285b066c34c8a3c01ba1d/mpd.nix

**Comment by claes** [comment]
An alternative could be to let it talk to pulseaudio over the network. In the past I have used a config in mpd like

`      audio_output {
              type            "pulse"
              name            "pulseaudio"
              server          "127.0.0.1"
      }`
and then some config in /etc/pulse/default.pa to allow this access.
