### ISSUE TITLE
QtWebKit needs to be deprecated

### ISSUE THREAD

**Issue by veprbl** [NixOS/nixpkgs#53079]
QtWebKit was deprecated in Qt 5.6. We are now using an outdated unofficial port:

https://github.com/NixOS/nixpkgs/blob/b0705bcbcebfea359643112fd200b549035d9503/pkgs/development/libraries/qt-5/5.12/default.nix#L40-L49

In some cases, applications already provide support for using QtWebEngine instead, we just need to enable it. The advantage of using QtWebEngine is that it is supported by the Qt upstream.

This issue is to track progress (or lack thereof) in deprecation of QtWebKit.

Overview
========

Legend: ✔︎ - dependency can be removed, ✘ - no straightforward solution was found, **?** - dependency can be removed at a cost

* [x] apitrace - ✔︎ judging by upstream git master it doesn't need qtwebkit
* [ ] apmplanner2
* [x] bibletime - **#125162**
* [ ] blink - python
* [ ] cadence - python
* [x] calibre - **#79608** **#92118**
* [ ] calligra - #102490 **?** ["QWebPage needed for webpage plugin"] (https://github.com/KDE/calligra/blob/2c601b660e8845ca3ffeeb1509db386bfcddec70/CMakeLists.txt#L1023) 
* [ ] capybara-webkit - ruby
* [ ] cb2bib - ✔︎ https://www.molspaces.com/cb2bib/doc/overview/ Requirements: "QtWebKit or QtWebEngine library (optional) to compile cb2Bib Annote viewer"
* [ ] copyq - **?** https://github.com/hluk/CopyQ/issues/540 . Also in readme it says following about the dependencies: "Optionally QtWebKit (more advanced HTML rendering)"
* [ ] brewtarget - ✔︎ qtwebkit is not in the list of the dependencies
* [x] digikam - **#53083**
* [x] freecad - **#98845**
* [x] frescobaldi - **#76889**
* [x] ghostwriter - **6b73aa91e0438f5d84c1d4d1ff1e648b9f554d29**
* [ ] google-musicmanager - ✘ see comment below
* [x] golden-cheetah - **#76172**
* [ ] goldendict - ✘ https://github.com/goldendict/goldendict/issues/677
* kde
  * [ ] alkimia - **#201953**
  * [x] k3b - **#103164**
  * [x] kdenlive - 2ff2ef1a52acb7264f014e6f77bfe2c4776a78e4
  * [x] kdevelop5 - ✔︎ both QtWebKit and QtWebEngine are supported https://github.com/KDE/kdevelop/blob/5e17ba4cd7a50816825a279c70a6b1c64a701926/kdevplatform/documentation/CMakeLists.txt#L3-L16
  * [ ] kdewebkit - **#201953**
  * [ ] kmymoney - **#201953**
  * [ ] kreport - #102490 https://phabricator.kde.org/T3565
  * [ ] konqueror - #102490
  * [x] marble - **#94826**
  * [x] messagelib - c2366ae35036be6e1b26ec36ad6c9cf4d346ed27
  * [ ] rocs - #102490
* [ ] kexi - ✘ upstream task https://phabricator.kde.org/T10389
* [x] ksysguard, libksysguard - 505f0c2232b9b09b259e2c3279fd3c0d5a67cbfb
* [ ] lsd2dsl
* [ ] mendeley - ✔︎ our current expression depends on both qtwebkit and qtwebengine, AUR manages with qtwebengine only https://aur.archlinux.org/packages/mendeleydesktop/
* [x] merkaartor -  **#135925**
* [ ] mindforger - **#122476**
* [ ] minizincide - expression we have depends on both `qtwebengine` and `qtwebkit`
* [x] musescore - **#52835**
* [ ] mythtv - ✘ https://github.com/MythTV/mythtv/blob/master/mythtv/configure#L6526
* [x] nextcloud-client - **#75202**
* [ ] nixnote2 - ✔︎ should be already using QtWebEngine https://github.com/notepadqq/notepadqq/projects/1
* [x] nmapsi4 - **#59266**
* [x] notepadqq - ✔︎ should be using qtwebengine already https://github.com/notepadqq/notepadqq/blob/master/README.md#build-it-yourself
* [ ] oilrush
* [ ] openshot-qt - ✔︎ OpenShot/openshot-qt#3604
* [x] owncloud-client - **#75206**
* [x] p4v - **#110168**
* [ ] phantomjs2 - ✘ https://github.com/ariya/phantomjs/issues/14366
* [x] psi-plus - 8f5bafe599fff1917130d2fa8cc7080bfc44ed2e
* [x] rstudio - **#59512**
* [ ] shotcut - ✘ https://forum.shotcut.org/t/is-that-any-plan-for-porting-from-qt-webkit-to-qt-webengine/5816
* [ ] scudcloud - ✘ python, abandonware https://github.com/raelgc/scudcloud/issues/628
* [ ] sigil - ✘ no port to QtWebEngine so far
* [x] skrooge - **#55930**
* [ ] sleepyhead - ✔︎ very light use of QWebView can be fixed to use QtWebEngine with some simple patches from https://gitlab.com/sleepyhead/sleepyhead-code/merge_requests/21
* [ ] smtube - ✘ no traces of QtWebEngine support in svn trunk
* [ ] subsurface - **?**  "QtWebKit is needed, if you want to print"
* [x] supercollider - **#63812**
* [ ] swift-im - ✘ dependency on QtWebKit is mentioned in https://github.com/swift/swift/blob/master/README.md and https://wiki.xmpp.org/web/Summer_of_Code_2017#Design_a_Chat_View_Free_of_QtWebKit.2FQtWebEngine
* [ ] teamviewer - ✘ checked version 15.0.8397: still links to libQt5WebKitWidgets.so.5 libQt5WebKit.so.5
* [x] toggldesktop - **#54587**
* [ ] trojita - ✘ https://bugs.kde.org/show_bug.cgi?id=365299
* [ ] qlandkartegt - ✔︎
* [ ] qmc2 - ✘ no traces of QtWebEngine support in SVN trunk
* [x] qsyncthingtray - supports `qtwebkit` optionally
* [ ] qtwebkit-plugins
* [ ] quiterss - **?** migrate to https://github.com/QuiteRSS/quiterss2 ?
* [ ] wkhtmltopdf - ✘ https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3391, needs to be ported to qt5 though
* [x] yacas - **https://github.com/NixOS/nixpkgs/pull/147826**
* [x] zeal - ✔︎ https://github.com/zealdocs/zeal/pull/1125

How to help?
============

1. Take an open item from the list that doesn't have a comment, google "\<itemname\> qtwebengine" and "\<itemname\> qtwebkit". Report what you find (or add a comment if you can edit the post).
2. Take an open item from the list that does have a comment and ping a maintainer if the fix is possible. Alternatively try fixing it yourself.

**Comment by bhipple** [comment]
I don't think we'll be able to kill the dependency easily in `google-musicmanager`, since we're already on Google's latest release, which lists this as an explicit dependency:

```
$ curl http://dl.google.com/linux/musicmanager/deb/dists/stable/main/binary-amd64/Packages
Package: google-musicmanager-beta
Version: 1.0.467.4929-r0
Architecture: amd64
Maintainer: Google Music Team <googleplay-support-music@google.com>
Installed-Size: 16766
Pre-Depends: dpkg (>= 1.14.0)
Depends: libc6 (>= 2.16), libexpat1 (>= 2.0.1), libflac8 (>= 1.3.0), libgcc1 (>= 1:4.1.1), libidn11 (>= 1.13), libqt5core5a (>= 5.2.0), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5network5 (>= 5.0.2), libqt5webkit5, libqt5widgets5 (>= 5.2.0), libstdc++6 (>= 4.6), libvorbisfile3 (>= 1.1.2), xdg-utils (>= 1.0.2)
```

**Comment by KAMiKAZOW** [comment]
> We are now using an outdated unofficial port

Not unofficial – endorsed by Qt: https://code.qt.io/cgit/qt/qtwebkit.git/ And currently in the process of a massive overhaul thanks to Patreon funding.

**Comment by veprbl** [comment]
@KAMiKAZOW This is definitely a good news for qtwebkit and its users. However, we are using a specific 5.212-alpha version that is outdated and contains known CVE's. Looking at the repo at your link, it doesn't seem to contain any significant update to address those issues. I doubt anyone would endorse this software in its current state.

**Comment by KAMiKAZOW** [comment]
> Looking at the repo at your link, it doesn't seem to contain any significant update to address those issues.

The development happens here on Github. "My" link was solely a reference proving that it's not unofficial but instead adopted by upstream Qt.

As you can read under https://github.com/qtwebkit/qtwebkit/blob/qtwebkit-dev/ReadMe.md#this-repository-development the qtwebkit-dev branch is the update to current WebKit master.

**Comment by sikmir** [comment]
zeal ported to qtwebengine (https://github.com/zealdocs/zeal/pull/1125), not released yet.

**Comment by bachp** [comment]
Freecad will be ported with the 0.19 release https://github.com/FreeCAD/FreeCAD/commit/75fd7231e05be6a7fcd76cd2c00f9eda0bef2f28, not released yet

**Comment by bachp** [comment]
messagelib no longer depends on qtwebengine since https://github.com/NixOS/nixpkgs/commit/c2366ae35036be6e1b26ec36ad6c9cf4d346ed27

**Comment by gebner** [comment]
freecad no longer depends on qtwebkit since we switched to the 0.19 prerelease in #98845/#100972.

**Comment by jerith666** [comment]
The issue for OpenShot linked in the description is outdated; it's been superseded by https://github.com/OpenShot/openshot-qt/pull/3604.

**Comment by milahu** [comment]
> no straightforward solution was found

example: https://github.com/scrapinghub/splash/issues/349

`splash` is not in nixpkgs. its needed for the legacy project [portia](https://github.com/scrapinghub/portia) (a GUI for scrapy)

**Comment by impl** [comment]
p4v doesn't depend on qtwebkit since #110168.

**Comment by K900** [comment]
apitrace is done: #201032

**Comment by gador** [comment]
`teamviewer` builds and runs fine without `qtwebkit` in version 15.29.4
I cannot test the connectivity, though, since I don't have a teamviewer partner to test it with

**Comment by aidalgol** [comment]
@das-g How are you going with fixing the kmymoney build?  I'm hitting build errors in my attempts to build against `qtwebengine`.

**Comment by das-g** [comment]
@aidalgol working on it, should be ready in some minutes.

**Comment by das-g** [comment]
@aidalgol PR to switch kmymoney from qtwebkit to qtwebengine: https://github.com/NixOS/nixpkgs/pull/201953

**Comment by LunNova** [comment]
qgis depends on it and isn't in the main list.

Looks like it can build with QtWebEngine but won't work due to some bugs, see https://github.com/qgis/QGIS/commit/7c1d6165f127f682399f694d2a37377525eaba5d

**Comment by totoroot** [comment]
yacas does not rely on QtWebKit, since PR #147826 got merged.
I think we can tick its box :ballot_box_with_check:

**Comment by totoroot** [comment]
QLandkarte GT hasn't seen any updates since 2015 and can therefore probably be considered unmaintained/abandoned:
https://sourceforge.net/projects/qlandkartegt/

On the AUR (patches fetched from there) it has been unmaintained as well:
https://aur.archlinux.org/packages/qlandkartegt

I'd suggest changing the ✔︎ to a ✘ for its entry.

**Comment by totoroot** [comment]
copyq does not rely on QtWebKit, since PR https://github.com/NixOS/nixpkgs/pull/130670 got merged.
I think we can tick its box :ballot_box_with_check:

**Comment by totoroot** [comment]
Issue for a port from QtWebKit to QtWebEngine for `kexi` and `kreport` are still open:
[pkgs/development/libraries/kreport/](https://invent.kde.org/office/kexi/-/issues/79)

**Comment by K900** [comment]
Qtwebkit has been marked insecure since #201028. No point in trying to check every single box.

**Comment by totoroot** [comment]
Fantastic :sweat_smile: 
Thanks for the notice!
