### ISSUE TITLE
Add missing KDE applications

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nixpkgs#62168]
## Issue description

It would be good to package all of the KDE apps. Here is a list of a few that are missing in Nixpkgs. Feel free to add them!

- [x] analitza
- [ ] audiocd-kio
- [x] blinken
- [x] bomber
- [x] bovo
- [x] cantor
- [x] cervisia
- [x] granatier
- [x] juk
- [x] kaffeine
- [ ] kaidan
- [x] kalgebra
- [x] kalzium
- [x] kamera
- [x] kanagram
- [x] kapman
- [x] kapptemplate
- [x] katomic
- [x] kblackbox
- [x] kblocks
- [x] kbounce
- [x] kbreakout
- [x] kbruch
- [x] kcron
- [x] kdiamond
- [x] kfloppy
- [x] kfourinline
- [x] kgeography
- [x] kgoldrunner
- [x] khangman
- [x] kigo
- [x] killbots
- [x] kiriki
- [x] kiten
- [x] kjumpingcube
- [x] klettres
- [x] klickety
- [x] klines
- [x] kmag
- [x] kmahjongg
- [x] kmines
- [x] kmousetool
- [x] kmouth
- [x] knavalbattle
- [x] knetwalk
- [x] [kolf](https://github.com/NixOS/nixpkgs/pull/66933)
- [x] kollision
- [ ] kopete
- [x] kpat
- [x] kreversi
- [x] kshisen
- [x] ksirk
- [x] ksnakeduel
- [x] ksquares
- [x] kstars
- [x] ksudoku
- [x] kteatime
- [x] ktimer
- [x] ktuberling
- [x] kturtle
- [x] kubrick
- [x] kwave
- [x] kwordquiz
- [x] libkcompactdisc
- [x] lokalize
- [x] lskat
- [x] marknote
- [x] palapeli
- [x] parley
- [x] rocs
- [x] step
- [x] svgpart
- [x] sweeper
- [x] tellico
- [x] [umbrello](https://github.com/vcunat/nixpkgs/pull/new/p/umbrello)
- [ ] [vakzination](https://apps.kde.org/vakzination/)

### Steps to reproduce

Up to date list here: https://repology.org/projects/?inrepo=kde_neon_user_lts&notinrepo=nix_unstable

## Technical details

Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the
results.

**Comment by vcunat** [comment]
Originally it was stated as intentional that not everything is added, and the remaining packages were meant to be added on-demand.

I had a working expression for `umbrello` a few months ago, so I can find that if you like.  I ended up not using the app, after all.

**Comment by dtzWill** [comment]
Is this PR/list limited to those in `srcs.nix` (applications released together and probably more officially)?

If not, a few I've been meaning to package, if only to evaluate their state and such:

* [ ] kbibtex
* [ ] kxstitch
* [ ] kio-gdrive
* [ ] kronometer
.. maybe others, i'll follow up if I find where I put that last list... :)

**Comment by peterhoeg** [comment]
I packaged ```kronometer``` ages ago, so it's definitely already there.

**Comment by FeepingCreature** [comment]
I miss Minesweeper.

**Comment by toyo-chi** [comment]
+1 for Tellico, Kiten, KWave and KTeaTime!

**Comment by silverhook** [comment]
There seem to be missing plugins as well (e.g. I miss kdepim-addons).

As for apps themselves, I would add the following:

- kaidan

**Comment by papojari** [comment]
@matthewbauer kmag was added.

**Comment by peterhoeg** [comment]
Do we need/want to keep this open? It isn't really a goal in itself to add everything in. If/when something is needed it will be added anyway.

**Comment by solson** [comment]
What determines when something is needed? There's maybe a dozen things on this list I would love to see packaged as soon as possible (and I hope to find some time to do the packaging myself — this list would help me keep track of what's left unfinished).

**Comment by peterhoeg** [comment]
If it adds value to you and help you achieve your goals, by all means, leave it open.

**Comment by tobiasBora** [comment]
I'd also be interested by Kcron ;-) https://github.com/KDE/kcron

**Comment by peterhoeg** [comment]
Just to manage expectations - there are very few people who are looking around for unaddressed packaging requests. It's typically much more a case of "scratching your own itch". Your best bet is always to take a stab at packaging it yourself. Feel free to ping me in the PR.

**Comment by harrisonthorne** [comment]
palapeli has been merged today! #198396

**Comment by peterhoeg** [comment]
@harrisonthorne , I believe that was your first packaging contribution, so thank you for that and welcome onboard!

**Comment by hervyqa** [comment]
labplot & cantor was added. #179752

**Comment by Svenum** [comment]
I would like to see audiocd-kio to be added.

**Comment by eliandoran** [comment]
@dtzWill ,

I've just packaged `kxstitch`: https://github.com/NixOS/nixpkgs/pull/277909

**Comment by lomenzel** [comment]
Marknote is missing on the list 

https://apps.kde.org/marknote/

**Comment by ajs124** [comment]
See also https://github.com/NixOS/nixpkgs/issues/293966 for marknote

**Comment by thibaultmol** [comment]
seems like this list is also missing some others, for example kodaskanna.
it's mentioned in this file but i have no idea what this file is https://github.com/NixOS/nixpkgs/blob/bfa57fa30068cf7a07142c05235d5ae322f0d076/pkgs/kde/generated/projects.json#L3098

**Comment by thibaultmol** [comment]
Some other kde apps (some with lower usage, but still maintainted) that aren't in the list at the top:
- https://apps.kde.org/vakzination/
- https://apps.kde.org/ruqola/
- https://apps.kde.org/pikasso/
- https://apps.kde.org/rkward/
- https://apps.kde.org/liquidshell/
- https://apps.kde.org/ktechlab/
- https://apps.kde.org/kookbook/
- https://apps.kde.org/kolorfill/
- https://apps.kde.org/kodaskanna/
- https://apps.kde.org/kirogi/
- https://apps.kde.org/kexi-3.3/
- https://apps.kde.org/klimbgrades/
- https://apps.kde.org/kfloppy/
- https://apps.kde.org/khipu/
- https://apps.kde.org/kommit/
- https://apps.kde.org/qrca/
- https://apps.kde.org/amarok/
- https://apps.kde.org/atlantik/

**Comment by tomodachi94** [comment]
I updated the list with completed packages, and added some requests from comments here.

**Comment by thibaultmol** [comment]
@tomodachi94 could you add my list as well?
also karp has been added yesterday: https://github.com/NixOS/nixpkgs/issues/357680

**Comment by ZZBaron** [comment]
kaffeine has been removed "due to outdated KF5 dependencies" https://github.com/NixOS/nixpkgs/commit/ae09e3144ac9502e157d43197e3f7e1c0b2b5552
