### ISSUE TITLE
PyGTK deprecation tracking issue

### ISSUE THREAD

**Issue by worldofpeace** [NixOS/nixpkgs#75478]
#### Description
PyGTK is by all means a dead project.
It's unmaintained upstream and even the Gnome team for debian is aiming to have it completely gone in their distribution. It hasn't had a release since Gnome 3 in 2011. It uses python 2, soon to be EOL.

For PyGTK using projects, the migration process is to use GObject Introspection bindings and PyGObject. This usually entails a port to GTK 3 too.

This issue is to investigate what packages have been ported, have ports in progress, or are abandoned.

##### Requests to package maintainers
Please don't merge an expressions using PyGTK, it would be a disservice to this ongoing effort.
I expect to keep PyGTK around as long as we can try to patch it so it doesn't fail to build, and the most popular applications make their move as planned.
For background see https://github.com/NixOS/nixpkgs/pull/74282 and https://github.com/NixOS/nixpkgs/pull/74295.

##### Involving yourself
Please link a PR here, or provide information about a specific package/s.

##### Packages using pygtk

- [ ] [ocropus](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/ocropus/default.nix)

- [ ] [screenkey](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/screenkey/default.nix)
https://gitlab.com/wavexx/screenkey/issues/3

- [ ] [gpsd](https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/gpsd/default.nix)
https://github.com/NixOS/nixpkgs/issues/35604

- [ ] [solfege](https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/solfege/default.nix)

- [ ] [nicotine-plus](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/soulseek/nicotine-plus/default.nix)
https://github.com/Nicotine-Plus/nicotine-plus/issues/99

- [ ] [gimp](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/graphics/gimp/default.nix)

- [ ] [cherrytree](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/cherrytree/default.nix)

- [ ] [neap](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/neap/default.nix)

- [ ] [phwmon](https://github.com/NixOS/nixpkgs/blob/pkgs/applications/misc/phwmon/default.nix)

- [ ] [planner](https://github.com/NixOS/nixpkgs/blob/pkgs/applications/office/planner/default.nix)

- [ ] [chirp](https://github.com/NixOS/nixpkgs/blob/pkgs/applications/radio/chirp/default.nix)

- [ ] [gnuradio](https://github.com/NixOS/nixpkgs/blob/pkgs/applications/radio/gnuradio/default.nix)

- [ ] [rabbitvcs](https://github.com/NixOS/nixpkgs/blob/pkgs/applications/version-management/rabbitvcs/default.nix)

- [ ] [gnome_python_desktop](https://github.com/NixOS/nixpkgs/blob/pkgs/desktops/gnome-2/bindings/gnome-python-desktop/default.nix)

- [ ] [gnome_python](https://github.com/NixOS/nixpkgs/blob/pkgs/desktops/gnome-2/bindings/gnome-python/default.nix)

- [ ] [gnome2.vte](https://github.com/NixOS/nixpkgs/blob/pkgs/desktops/gnome-2/desktop/vte/default.nix)

- [ ] [keybinder](https://github.com/NixOS/nixpkgs/blob/pkgs/development/libraries/keybinder/default.nix)
Possible obsolete to keybinder3

- [ ] [pythonPackages.notify](https://github.com/NixOS/nixpkgs/blob/pkgs/development/python-modules/notify/default.nix)

- [ ] [pythonPackages.pygobject](https://github.com/NixOS/nixpkgs/blob/pkgs/development/python-modules/pygobject/default.nix) (this is the old version)

- [ ] [pythonPackages.pygtksourceview](https://github.com/NixOS/nixpkgs/blob/pkgs/development/python-modules/pygtksourceview/default.nix)

- [ ] [pythonPackages.pyspread](https://github.com/NixOS/nixpkgs/blob/pkgs/development/python-modules/pyspread/default.nix)

- [ ] [neard](https://github.com/NixOS/nixpkgs/blob/pkgs/servers/neard/default.nix)

- [ ] [escrotum](https://github.com/NixOS/nixpkgs/blob/pkgs/tools/graphics/escrotum/default.nix)

- [ ] [nmap](https://github.com/NixOS/nixpkgs/blob/pkgs/tools/security/nmap/default.nix) (optional)

- [ ] [claws-mail](https://github.com/NixOS/nixpkgs/blob/pkgs/applications/networking/mailreaders/claws-mail/default.nix) (optional)

**Comment by worldofpeace** [comment]
Perhaps have of these were cleaned in https://github.com/NixOS/nixpkgs/pull/74295.

**Comment by doronbehar** [comment]
A small note for GNUradio: Upstream released a while ago an update (we haven't packaged yet) that introduces incompatible API changes but it dropped the dependency in PyGTK and Qt4 (related: https://github.com/NixOS/nixpkgs/issues/33248). More details are covered at #82263 . Upstream still maintains a branch for users of the previous version.

I've been working (https://github.com/NixOS/nixpkgs/pull/84401) on making the build of our current version GNURadio more configurable and it should be possible to build the maintainence version without GUI support and hence without needing PyGTK (without needing python2 as well BTW) and still maintaining the reverse dependencies working.

**Comment by miniBill** [comment]
@worldofpeace nicotine+ has merged the py3 code and we are now shipping the updated version

**Comment by qweered** [comment]
Pygtk has been removed
