### ISSUE TITLE
All options should have types

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#76184]
**Describe the bug**

To make the usage of options and errors more clear, every option should have a type.
Currently, ~~more than 300 199 151 117 27 20~~ 18 options don't have a type.

**To Reproduce**
<details>

```nix
let
  config = { };
  pkgs = import ./. {};
  lib = import ./lib;

  scrubDerivations = namePrefix: pkgSet: lib.mapAttrs
    (name: value:
      let wholeName = "${namePrefix}.${name}"; in
      if lib.isAttrs value then
        scrubDerivations wholeName value
        // (lib.optionalAttrs (lib.isDerivation value) { outPath = "\${${wholeName}}"; })
      else value
    )
    pkgSet;

  scrubbedEval = lib.evalModules {
    modules = import ./nixos/modules/module-list.nix;
    specialArgs = {
      pkgs = scrubDerivations "pkgs" pkgs;
    };
  };

  manual = import ./nixos/doc/manual {
    inherit config pkgs;
    inherit (scrubbedEval) options;
    version = "master";
    revision = "master";
  };
in manual.optionsJSON
```

```bash
jsonFile="$(NIX_PATH='' nix-build types.nix)/share/doc/nixos/options.json"
jq -r 'to_entries[] | select(.value.type == "unspecified") | [ "`" + .key + "`", "[" + .value.declarations[0] + "](../blob/master/" + .value.declarations[0] + ")" ] | join(" - ")' < "${jsonFile}" | sed 's/^\(.*\)$/- [ ] \1/g'
```
</details>

**Expected behavior**

All options should have a type.

**Additional context**

Options without types:

- [x] `dysnomia.components` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.containers` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.extraContainerPaths` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.extraContainerProperties` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.extraModulePaths` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `dysnomia.properties` - [nixos/modules/services/misc/dysnomia.nix](../blob/master/nixos/modules/services/misc/dysnomia.nix) → #149416
- [x] `hardware.pcmcia.config` - [nixos/modules/hardware/pcmcia.nix](../blob/master/nixos/modules/hardware/pcmcia.nix) → #149415
- [x] `security.pam.loginLimits` - [nixos/modules/security/pam.nix](../blob/master/nixos/modules/security/pam.nix) → #149412 
- [x] `security.pam.services.<name>.limits` - [nixos/modules/security/pam.nix](../blob/master/nixos/modules/security/pam.nix) → #149412 
- [x] `services.hoogle.haskellPackages` - [nixos/modules/services/development/hoogle.nix](../blob/master/nixos/modules/services/development/hoogle.nix) → #149415
- [ ] `services.nsd.zones.<name>.children` - [nixos/modules/services/networking/nsd.nix](../blob/master/nixos/modules/services/networking/nsd.nix) → #149415
- [ ] `services.unbound.stateDir` - [nixos/modules/services/networking/unbound.nix](../blob/master/nixos/modules/services/networking/unbound.nix) → #141730
- [ ] `services.vsftpd.userlist` - [nixos/modules/services/networking/vsftpd.nix](../blob/master/nixos/modules/services/networking/vsftpd.nix) → #111441
- [ ] `services.xserver.displayManager.session` - [nixos/modules/services/x11/display-managers/default.nix](../blob/master/nixos/modules/services/x11/display-managers/default.nix) → #141760
- [x] `services.xserver.windowManager.xmonad.haskellPackages` - [nixos/modules/services/x11/window-managers/xmonad.nix](../blob/master/nixos/modules/services/x11/window-managers/xmonad.nix) → #149415
- [x] `specialisation.<name>.configuration` - [nixos/modules/system/activation/top-level.nix](../blob/master/nixos/modules/system/activation/top-level.nix) → #143207

**Comment by dasJ** [comment]
cc @ajs124 @Infinisil @Scriptkiddi @Ma27

**Comment by aanderse** [comment]
@dasJ great! Any plan of attack, or just track it here and people can chip away at it?

BTW - I noticed `services.wordpress.commonOptions` but no such option exists that I'm aware of.

**Comment by dasJ** [comment]
@aanderse I'd love to attack this somehow, but as I honestly don't have any idea what most modules do, I'm too afraid to break anything. I'd love people to chip away at it, and I'll try to do as much as I can.

As for the Wordpress options: I accidentially added our company modules into the list. I'm currently regenerating it ;)

**Comment by lourkeur** [comment]
I looked at some of those options to try and type them. I ran into an interesting situation with `services.tor.tsocks.config`: the implementation of the module sets this option by itself, which means that if the user uses it, NixOS does the default thing which appears to be to concatenate everything together without separators, in the style of `types.string`. (as opposed to `types.str` which cant be merged) I concluded that, if we want to put a type on such an option while preserving its behavior by oral contract, the deprecated `types.string` is what should be used. Of course every option should be looked at case-by-case. (Also I think the `tsocks` module should be nuked at some point.)

I'm working on my branch [here.](https://github.com/lourkeur/nixpkgs/tree/fix_76184) Do we want to centralize at least the trivial cases somewhere instead of opening loads of small PRs?

**Comment by dasJ** [comment]
@aanderse I finally regenerated the list and updated the command to make it usable for everyone

**Comment by dasJ** [comment]
@lourkeur Yeah, I think that some larger PRs (like #76551 which fixes all nagios options at once) would be a lot easier to merge.

**Comment by lourkeur** [comment]
Updated command: `curl -L https://hydra.nixos.org/job/nixos/trunk-combined/nixos.options/latest/download/1/options.json | jq -r 'to_entries[] | select(.value.type == "unspecified") | .key | "- [ ] " + .'`
result:
- [ ] boot.crashDump.reservedMemory
- [ ] boot.kernelPackages
- [ ] dysnomia.components
- [ ] dysnomia.containers
- [ ] dysnomia.extraContainerPaths
- [ ] dysnomia.extraContainerProperties
- [ ] dysnomia.extraModulePaths
- [ ] dysnomia.properties
- [ ] hardware.pcmcia.config
- [ ] networking.timeServers
- [ ] nix.registry.<name>.flake
- [ ] programs.cdemu.group
- [ ] programs.cdemu.gui
- [ ] programs.cdemu.image-analyzer
- [ ] security.pam.loginLimits
- [ ] security.pam.services.<name?>.limits
- [ ] services.activemq.configurationDir
- [ ] services.amule.dataDir
- [ ] services.amule.user
- [ ] services.autofs.timeout
- [ ] services.babeld.extraConfig
- [ ] services.bacula-dir.extraDirectorConfig
- [ ] services.bacula-dir.extraMessagesConfig
- [ ] services.bacula-dir.name
- [ ] services.bacula-dir.password
- [ ] services.bacula-fd.director.<name>.monitor
- [ ] services.bacula-fd.director.<name>.password
- [ ] services.bacula-fd.extraClientConfig
- [ ] services.bacula-fd.extraMessagesConfig
- [ ] services.bacula-fd.name
- [ ] services.bacula-sd.autochanger.<name>.changerCommand
- [ ] services.bacula-sd.autochanger.<name>.changerDevice
- [ ] services.bacula-sd.autochanger.<name>.devices
- [ ] services.bacula-sd.autochanger.<name>.extraAutochangerConfig
- [ ] services.bacula-sd.device.<name>.archiveDevice
- [ ] services.bacula-sd.device.<name>.extraDeviceConfig
- [ ] services.bacula-sd.device.<name>.mediaType
- [ ] services.bacula-sd.director.<name>.monitor
- [ ] services.bacula-sd.director.<name>.password
- [ ] services.bacula-sd.extraMessagesConfig
- [ ] services.bacula-sd.extraStorageConfig
- [ ] services.bacula-sd.name
- [ ] services.bind.blockedNetworks
- [ ] services.bind.cacheNetworks
- [ ] services.bind.forwarders
- [ ] services.bind.ipv4Only
- [ ] services.bind.zones
- [ ] services.bitlbee.extraDefaults
- [ ] services.bitlbee.extraSettings
- [ ] services.bitlbee.interface
- [ ] services.bitlbee.portNumber
- [ ] services.buildbot-master.pythonPackages
- [ ] services.cgminer.config
- [ ] services.cgminer.hardware
- [ ] services.cgminer.pools
- [ ] services.cgminer.user
- [ ] services.chrony.initstepslew
- [ ] services.chrony.servers
- [ ] services.cntlm.domain
- [ ] services.cntlm.noproxy
- [ ] services.cntlm.port
- [ ] services.cntlm.proxy
- [ ] services.cntlm.username
- [ ] services.compton
- [ ] services.consul.extraConfig
- [ ] services.deluge.openFilesLimit
- [ ] services.elasticsearch-curator.actionYAML
- [ ] services.felix.group
- [ ] services.felix.user
- [ ] services.firebird.baseDir
- [ ] services.firebird.port
- [ ] services.firebird.user
- [ ] services.flashpolicyd.policy
- [ ] services.fprot.updater.frequency
- [ ] services.fprot.updater.licenseKeyfile
- [ ] services.fprot.updater.productData
- [ ] services.gale.setuidWrapper
- [ ] services.gocd-agent.extraOptions
- [ ] services.gocd-agent.startupOptions
- [ ] services.gocd-server.extraGroups
- [ ] services.gocd-server.extraOptions
- [ ] services.gocd-server.startupOptions
- [ ] services.gogoclient.server
- [ ] services.gogoclient.username
- [ ] services.gvpe.configFile
- [ ] services.gvpe.configText
- [ ] services.gvpe.customIFSetup
- [ ] services.gvpe.ipAddress
- [ ] services.gvpe.nodename
- [ ] services.gvpe.subnet
- [ ] services.hadoop.coreSite
- [ ] services.hadoop.hdfsSite
- [ ] services.hadoop.mapredSite
- [ ] services.hadoop.yarnSite
- [ ] services.heyefi.cardMacaddress
- [ ] services.heyefi.uploadDir
- [ ] services.heyefi.uploadKey
- [ ] services.heyefi.user
- [ ] services.hoogle.haskellPackages
- [ ] services.hoogle.packages
- [ ] services.hostapd.interface
- [ ] services.ihaskell.extraPackages
- [ ] services.ircdHybrid.adminEmail
- [ ] services.ircdHybrid.certificate
- [ ] services.ircdHybrid.description
- [ ] services.ircdHybrid.extraIPs
- [ ] services.ircdHybrid.extraPort
- [ ] services.ircdHybrid.rsaKey
- [ ] services.ircdHybrid.serverName
- [ ] services.ircdHybrid.sid
- [ ] services.jboss.deployDir
- [ ] services.jboss.libUrl
- [ ] services.jboss.logDir
- [ ] services.jboss.serverDir
- [ ] services.jboss.tempDir
- [ ] services.jboss.user
- [ ] services.k3s.extraFlags
- [ ] services.lshd.hostKey
- [ ] services.lshd.interfaces
- [ ] services.lshd.loginShell
- [ ] services.lshd.portNumber
- [ ] services.lshd.srpKeyExchange
- [ ] services.lshd.subsystems
- [ ] services.mailpile.hostname
- [ ] services.mailpile.port
- [ ] services.mediatomb.group
- [ ] services.mediatomb.interface
- [ ] services.mediatomb.port
- [ ] services.mediatomb.user
- [ ] services.mediatomb.uuid
- [ ] services.mediawiki.name
- [ ] services.memcached.extraOptions
- [ ] services.memcached.listen
- [ ] services.memcached.maxConnections
- [ ] services.memcached.maxMemory
- [ ] services.memcached.port
- [ ] services.memcached.user
- [ ] services.mongodb.bind_ip
- [ ] services.mongodb.dbpath
- [ ] services.mongodb.extraConfig
- [ ] services.mongodb.pidFile
- [ ] services.mongodb.quiet
- [ ] services.mongodb.replSetName
- [ ] services.mongodb.user
- [ ] services.mysqlBackup.databases
- [ ] services.mysqlBackup.location
- [ ] services.mysqlBackup.singleTransaction
- [ ] services.mysqlBackup.user
- [ ] services.netatalk.homes.basedirRegex
- [ ] services.netatalk.homes.path
- [ ] services.netatalk.port
- [ ] services.netdata.python.extraPackages
- [ ] services.nginx.config
- [ ] services.nginx.logError
- [ ] services.nsd.zones.<name>.children
- [ ] services.ntp.servers
- [ ] services.oauth2_proxy.extraConfig
- [ ] services.octoprint.plugins
- [ ] services.openafsServer.advertisedAddresses
- [ ] services.postfix.dnsBlacklistOverrides
- [ ] services.postfix.transport
- [ ] services.postgresqlBackup.databases
- [ ] services.postgresqlBackup.location
- [ ] services.postgresqlBackup.startAt
- [ ] services.prayer.port
- [ ] services.quassel.dataDir
- [ ] services.quassel.interfaces
- [ ] services.quassel.portNumber
- [ ] services.quassel.user
- [ ] services.radvd.config
- [ ] services.redis.masterAuth
- [ ] services.redis.slaveOf
- [ ] services.resilio.sharedFolders
- [ ] services.rippled.extraConfig
- [ ] services.rsyncd.address
- [ ] services.sabnzbd.configFile
- [ ] services.sabnzbd.group
- [ ] services.sabnzbd.user
- [ ] services.shairport-sync.arguments
- [ ] services.shairport-sync.user
- [ ] services.supybot.extraPackages
- [ ] services.svnserve.svnBaseDir
- [ ] services.synergy.client.screenName
- [ ] services.synergy.client.serverAddress
- [ ] services.synergy.server.address
- [ ] services.synergy.server.configFile
- [ ] services.synergy.server.screenName
- [ ] services.timesyncd.servers
- [ ] services.tomcat.extraGroups
- [ ] services.unit.logDir
- [ ] services.unit.stateDir
- [ ] services.venus.feeds
- [ ] services.virtuoso.config
- [ ] services.virtuoso.dirsAllowed
- [ ] services.virtuoso.httpListenAddress
- [ ] services.virtuoso.listenAddress
- [ ] services.virtuoso.parameters
- [ ] services.vsftpd.userlist
- [ ] services.wakeonlan.interfaces
- [ ] services.weechat.binary
- [ ] services.xserver.desktopManager.gnome3.sessionPath
- [ ] services.xserver.desktopManager.pantheon.sessionPath
- [ ] services.xserver.displayManager.lightdm.greeters.gtk.cursorTheme.package
- [ ] services.xserver.displayManager.session
- [ ] services.xserver.serverFlagsSection
- [ ] services.xserver.useXFS
- [ ] services.xserver.windowManager.exwm.extraPackages
- [ ] services.xserver.windowManager.xmonad.extraPackages
- [ ] services.xserver.windowManager.xmonad.haskellPackages
- [ ] services.xtreemfs.dir.address
- [ ] services.xtreemfs.dir.httpPort
- [ ] services.xtreemfs.dir.port
- [ ] services.xtreemfs.dir.syncMode
- [ ] services.xtreemfs.dir.uuid
- [ ] services.xtreemfs.homeDir
- [ ] services.xtreemfs.mrc.address
- [ ] services.xtreemfs.mrc.httpPort
- [ ] services.xtreemfs.mrc.port
- [ ] services.xtreemfs.mrc.syncMode
- [ ] services.xtreemfs.mrc.uuid
- [ ] services.xtreemfs.osd.address
- [ ] services.xtreemfs.osd.httpPort
- [ ] services.xtreemfs.osd.port
- [ ] services.xtreemfs.osd.uuid
- [ ] services.yandex-disk.directory
- [ ] services.yandex-disk.user
- [ ] specialisation.<name>.configuration
- [ ] users.ldap.base
- [ ] users.ldap.server
- [ ] virtualisation.xen.bootParams
- [ ] virtualisation.xen.bridge.name
- [ ] virtualisation.xen.domain0MemorySize

That's good progress but it's not all done.

**Comment by lourkeur** [comment]
Related: #91813

**Comment by xaverdh** [comment]
was this closed intentionally or by accident?

**Comment by dasJ** [comment]
Thanks to some newfound motivation for this issue (and procrastination from my regular work :eyes:) I chose to redo my generation code (goes from master instead of the release branch now) and reopen this. Good news is that a lot of the items are already fixed so I'm going to just replace the list above.

**Comment by dasJ** [comment]
Probably cc @Infinisil do you have any idea why `services.compton` shows up here? It's `mkAliasOptionModule`'d to `services.picom` but the type does not seem to be properly applied (showing as `types.unspecified`).

**Comment by Infinisil** [comment]
@dasJ Isn't `types.unspecified` what your script looks for?

**Comment by dasJ** [comment]
Yes that's why I'm wondering. Shouldn't the type be the same as the type of `services.picom`? Or is the type implicit unspecified because it's not a real option?

**Comment by Infinisil** [comment]
Oh I see the problem: The `mkAliasOptionModule` code just tries to get the type from `options.services.picom.type`, which in this case doesn't exist, because `services.picom` isn't an option, it's just an attribute set of options.

**Comment by Infinisil** [comment]
@dasJ Fixing that in https://github.com/NixOS/nixpkgs/pull/110392 :)

**Comment by turboMaCk** [comment]
I think this change will have one downside. Some options might be taking function as an argument. In these cases the underlying implementation within module does the passing of value into this function. Many of these functions are not covered by test suite and will fail during rebuild of systems while not being fixable by users without defining overlays. I think errors like can happen way too easily. See for instance https://github.com/NixOS/nixpkgs/pull/111451#discussion_r567434993

I'm not saying that I'm strictly against these changes but I think we need to take this to account and try to minimize the risk of introducing similar regressions. putting runtime type checks on options is simply not like turning nix to statically typed language.

**Comment by Scriptkiddi** [comment]
> I think this change will have one downside. Some options might be taking function as an argument. In these cases the underlying implementation within module does the passing of value into this function. Many of these functions are not covered by test suite and will fail during rebuild of systems while not being fixable by users without defining overlays. I think errors like can happen way too easily. See for instance [#111451 (comment)](https://github.com/NixOS/nixpkgs/pull/111451#discussion_r567434993)
> 
> I'm not saying that I'm strictly against these changes but I think we need to take this to account and try to minimize the risk of introducing similar regressions. Putting runtime type checks on options is simply not like turning nix to statically typed language.

I actually have only encountered a handful of options like this, I reverted changes where I probably did the same error. Let's see what the solution for the xmonad issue is going to be an see if we can apply that to the last remaining options.

**Comment by Infinisil** [comment]
Still relevant, and my #132448 should help with this

**Comment by dasJ** [comment]
Done
