### ISSUE TITLE
Node2nix doesn't support the `nodejs-13_x` packageset

### ISSUE THREAD

**Issue by NinjaTrappeur** [NixOS/nixpkgs#78044]
**Describe the bug**
Node2nix doesn't support the `nodejs-13_x` packageset introduced by https://github.com/NixOS/nixpkgs/pull/71799. 

Currently, some manual intervention is required to update the nodejs packages  besides running `pkgs/development/node-packages/generate.sh`. See https://github.com/NixOS/nixpkgs/pull/78037/files

We need to update `node2nix` to handle this new packageset. This issue will be used to track the progress.

**TODO**

1. [x] Fix node2nix. (me) [PR opened](https://github.com/svanderburg/node2nix/pull/169)
2. [ ] ~Release a new node2nix version. (@svanderburg )~ Project unmaintained.
2. [x] Create a nix-community repo (@Mic92 )
3. [x] Release a new node2nix version (@Mic92 ) https://github.com/nix-community/node2nix/commit/25439feee8fdc1ac5604927b4284983088d0b3d3
4. [x] Update nixpkgs to use this newly released version.
5. [x] Re-Generate the `node-13_x` packageset. https://github.com/NixOS/nixpkgs/pull/82228

CC. @asymmetric @marsam @flokli

**Comment by Mic92** [comment]
We could fork node2nix to [nix-community](https://github.com/nix-community/] and applied the changes required. I am not overly familiar with nodejs and its ecosystem so.

**Comment by NinjaTrappeur** [comment]
Yes, I think it would make sense. 

I also think we mostly need somebody taking ownership of the nixpkgs nodejs packageset. I'm not really familiar with this environment nor up to this task.

If nobody shows up, maybe dropping the whole packageset from nixpkgs and rather use a per-software derivation fetching its own deps might make sense.

**Comment by Mic92** [comment]
No. I would not drop the whole package set. Having per-software derivations would add way to many generated node packages into nixpkgs since the node dependency graph are insanely large.

**Comment by asymmetric** [comment]
We could also fork it and find a maintainer after the fact, and in the meantime apply the patches that we know we need.

Or is there something to lose in doing that?

**Comment by Mic92** [comment]
@asymmetric No. Are you up for the task? You can ask @zimbatm on #nix-community regarding creating repositories in nix-community.

**Comment by Mic92** [comment]
I created the fork here: https://github.com/nix-community/node2nix

**Comment by NinjaTrappeur** [comment]
Just saw that, I updated the first post. Thanks!

I'm going to update nixpkgs with it now.

**Comment by Mic92** [comment]
@NinjaTrappeur I am already in the process of doing so. Someone also broke the update script, which I am about to fix.

**Comment by Mic92** [comment]
Here is the pull request: https://github.com/NixOS/nixpkgs/pull/82228

**Comment by asymmetric** [comment]
Is there anything left to do here?

**Comment by NinjaTrappeur** [comment]
Oops, I forgot to follow through this one.

The required changes have been merged to node2nix and a new 1.8.0
release has been issued. I just checked the current master, we the
various packageset have been regenerated.

We still did not adressed who/what(bot?) should be responsible to run
the generate.sh script periodically

That said, I think we're good for this issue. Closing.
