### ISSUE TITLE
FOSS music trackers packaging effort

### ISSUE THREAD

**Issue by fgaz** [NixOS/nixpkgs#81815]
I recently took an interest in the world of tracker music and discovered that there are _a lot_ of FOSS trackers, but that packages for them are scattered across distros (Debian has quite a lot though).

So i decided to package all of them for NixOS :D

This issue tracks ~my~our packaging effort. Suggestions are welcome!

In no particolar order (name - {**R**epology, **H**omepage, pull request #} - additional details):

* [x] `milkytracker` - was already in nixpkgs
  * [ ] add a .desktop file and an icon
* [x] `klystrack` - was already in nixpkgs
  * [ ] can't open files, needs update to master (maybe ask the dev for a release? Done. Release coming soon:tm:)
* [x] `schismtracker` - was already in nixpkgs
  * [ ] add a .desktop file and an icon
* [x] `pt2-clone` {[R](https://repology.org/project/pt2-clone/information) [H](https://16-bits.org/pt2.php) #80611}
  * [ ] add a .desktop file and an icon
  * [x] fix darwin https://hydra.nixos.org/build/114789300/nixlog/2/tail
* [x] `ft2-clone` {[R](https://repology.org/project/fasttracker2/information) [H](https://16-bits.org/ft2.php) #80612}
  * [ ] add a .desktop file and an icon
  * [x] fix [darwin](https://github.com/NixOS/nixpkgs/pull/102338#issuecomment-720084655): #108167
* [x] `goattracker` {[R](https://repology.org/project/goattracker/information) [H](https://cadaver.github.io/tools.html) #81025}
* [x] `gtultra` {[R](https://repology.org/project/gtultra/information) [H](https://github.com/jpage8580/GTUltra) #325277}
* [x] `bambootracker` {[R](https://repology.org/project/bambootracker/information) [H](https://github.com/rerrahkr/BambooTracker) #81840}
* [x] `soundtracker` {[R](https://repology.org/project/soundtracker/information) [H](http://www.soundtracker.org/) #82057}
* [x] `hivelytracker` {[R](https://repology.org/project/hivelytracker/information) [H](http://www.hivelytracker.co.uk/) #95797}
  * [ ] unbreak darwin (relevant comments in the init pr)
* [x] `cheesecutter` {[R](https://repology.org/project/cheesecutter/information) [H](https://github.com/theyamo/CheeseCutter) #82666} - ~waiting for #69144~
  * [ ] add a .desktop file and an icon
  * [x] Fix macOS build #97939
* [x] `littlegptracker` {[R](https://repology.org/project/littlegptracker/information) [H](http://www.littlegptracker.com) #91766} - official source at Mdashdotdashn's github
  * [x] fix darwin: https://github.com/NixOS/nixpkgs/pull/91766#issuecomment-688751821
  * [this fork](https://github.com/djdiskmachine/LittleGPTracker) has a more active maintainer
    * [ ] https://github.com/djdiskmachine/LittleGPTracker/issues/71
* [x]  `ptcollab` {- [H](https://yuxshao.github.io/ptcollab/) [#101446](https://github.com/NixOS/nixpkgs/pull/101446)}
* [x] `picoloop` {[R](https://repology.org/project/picoloop/information) [H](https://github.com/yoyz/picoloop) -}
  * [ ] needs a maintainer
* [x] `furnace` {[R](https://repology.org/project/furnace/information) [H](https://github.com/tildearrow/furnace) #158229}
* [ ] `tiatracker` {[R](https://repology.org/project/tiatracker/information) [H](https://bitbucket.org/kylearan/tiatracker/src/master/) #158645}
  * [ ] [tiatracker+ fork](https://bitbucket.org/rushjet1/tiatracker/) (what is the canonical alphanumeric name? tiatracker-plus? tiatrackerplus?)
* [ ] `zytrax` {[R](https://repology.org/project/zytrax/information) [H](http://zytrax.org/) -}
* [ ] `tutka` {[R](https://repology.org/project/tutka/information) [H](https://www.nongnu.org/tutka/) -}
* [ ] `buzztrax` {[R](https://repology.org/project/buzztrax/information) [H](https://buzztrax.org/) -}
* [ ] `protrekkr` {[R](https://repology.org/project/protrekkr/information) [H](https://github.com/falkTX/protrekkr) -} [a fork](https://pbat.ch/proj/protrekkr/), [another fork](https://github.com/hitchhikr/protrekkr)
* [ ] `tektracker`/`ttrk` {[R](https://repology.org/project/ttrk/information) [H](http://vektor.ca/audio/ttrk/) -} [fork](https://github.com/fundamental/ttrk), `attrk` is another fork
* [ ] `attrk` {- [H](http://www.lumanmagnum.net/physics/attrk/) -}
* [ ] `xybrid` {[R](https://repology.org/project/xybrid/information) [H](https://gitlab.com/zetaPRIME/xybrid/) -}
* [ ] `neil` (`-tracker`/`-sequencer`) {- [H](https://sites.google.com/site/neilsequencer/) -}
* [ ] `jacker` {[R](https://repology.org/project/jacker/information) [H](https://hg.sr.ht/~duangle/paniq_legacy/browse/default/jacker) -} [fork1](https://github.com/grejppi/jacker-fork) [fork2](https://github.com/harryhaaren/jacker)
* [ ] `cheesetracker` {[R](https://repology.org/project/cheesetracker/information) [H](http://cheesetracker.sourceforge.net/) -}
* [ ] Some stuff [here](https://www.ibiblio.org/pub/Linux/apps/sound/players/!INDEX.html) and [here](http://ftp.modland.com/pub/software/trackers/Linux/) maybe, like `funktrackergold`
* [ ] `shaketracker`? https://sourceforge.net/projects/cheesetronic/files/, http://www.shaltev.org/mvs/programming.html
* [ ] `adlibtracker2`? {[R](https://repology.org/project/adlibtracker2/information) [H](http://adlibtracker.net/) -}
* [ ] `frinika` {[R](https://repology.org/project/frinika/information) [H](http://www.frinika.com/) -}
* [ ] `radium` {[R](https://repology.org/project/radium/information) [H](http://users.notam02.no/~kjetism/radium/) -}
* [ ] `aldrin` {[R](https://repology.org/project/aldrin/information) [H](https://sourceforge.net/projects/aldrin/) -}
* [ ] `aube` {- [H](http://www.metadecks.org/software/aube/index.html) -}
* [ ] `maube` {- [H](http://www.vergenet.net/~conrad/maube/) -}
* [ ] `fmcomposer` {- [H](http://fmcomposer.org) -}
* [ ] `chibitracker` {- [H](https://sourceforge.net/projects/chibitracker.berlios/) -} [archived original homepage](https://web.archive.org/web/20120510050829/http://chibitracker.berlios.de/) [fork](https://github.com/reduz/chibitracker)
* [ ] `psytexx` {- [H](https://sourceforge.net/projects/psytexx/) -}
* [ ] `kmiditracker` https://web.archive.org/web/20080724082500/http://www.monasteriomono.org/programs/kmiditracker/
* [ ] `synergy-miditracker` {- [H](http://miditracker.org/) -}
* [ ] `fltracker` {- [H](http://fltracker.sourceforge.net/) -}
* [ ] `snestracker` {- [H](https://github.com/bazzinotti/snestracker) -}
* [ ] `1tracker` {- [H](http://shiru.untergrund.net/software.shtml) -}
* [ ] `bintracker` {- [H](https://bintracker.org/) -}
* [ ] `playerpro` {- [H](https://sourceforge.net/projects/playerpro/) -}
* [ ] `propulse` {- [H](https://github.com/hukkax/Propulse) -}
* [ ] `snibbetracker` {- [H](https://github.com/lundstroem/snibbetracker) -}
* [ ] `plebtracker` {- [H](https://github.com/danfrz/PLEBTracker) -}
* [ ] `psycle`/`qpsycle` {- [H](http://psycle.sourceforge.net/) -} https://psycle.fandom.com/wiki/Contributing_code#You_have_a_unix-based_OS
* [ ] `cobratracker` {- [H](https://github.com/kaadmy/cobratracker) -} [python3 fork](https://github.com/sonejostudios/cobratracker)
* [ ] `kunquat` {- [H](http://kunquat.org/) -}
* [ ] `tgtracker`/`tonal-glyph-tracker` {- [H](https://gitlab.com/tonal-glyph/tgtracker) -}
* [ ] `zeetracker` {- [H](https://github.com/DyzLecticus/Zeesoft/tree/master/ZeeTracker) -}
* [ ] `bassoontracker` {- [H](https://github.com/steffest/bassoontracker) -} js, but with no dependencies!
* [ ] `soundbox` {- [H](https://github.com/mbitsnbites/soundbox) -} js, but no dependencies!
* [ ] `teqqer` {- [H](https://github.com/fps/teqqer) -}
* [ ] `vht`/`valhalla-tracker`/`vahatraker` {- [H](https://github.com/rdybka/vht) -}
* [ ] `miditrk` {- [H](https://sourceforge.net/projects/miditrk/) -}
* [ ] `madtracker3` {- [H](https://github.com/MadTracker-FOSS/MadTracker3) -}
* [ ] `med` {- [H](https://github.com/suhr/med) -} the name "med" conflicts, use another
* [ ] `lebac` {- [H](https://github.com/qguv/lebac) -}
* [ ] `arkostracker` {- [H](http://www.julien-nevo.com/arkostracker/) -} plans to open source soon
* [ ]  `exotracker` {- [H](https://gitlab.com/exotracker/exotracker-cpp) -}
* [ ] `nesicide`/`qt-famitracker` {- [H](https://knob.phreneticappsllc.com/nesicide/) -}
* [ ] `prototracker` {- [H](https://github.com/kometbomb/prototracker) -}
* [ ] `prototracker-modular` {- [H](https://github.com/kometbomb/prototracker-modular) -}
* [ ] `prototracker-opll` {- [H](https://github.com/kometbomb/prototracker-opll) -}
* [x] ~~`beast` {[R](https://repology.org/project/beast/information) [H](https://beast.testbit.eu/) -} (not really a tracker, but still) was already in nixpkgs~~ removed due to difficulties in packaging the new electron interface

##### Related stuff which we could maybe package

* [ ] [adplug/adplay](https://adplug.github.io/)
* [ ] [resid](http://www.zimmers.net/anonftp/pub/cbm/crossplatform/emulators/resid/index.html)
* [ ] [MDAL](https://utz82.github.io/MDAL/)
* [ ] [oscilloscoper](https://github.com/kometbomb/oscilloscoper)
* [ ] it2play, ahx2play, ft2play: https://github.com/8bitbubsy?tab=repositories

There are definitely historical, long unmaintained, no longer used trackers in this list that probably belong to a NUR. Still, it'd be nice to have as much as possible in nixpkgs.

##### Resources

* http://battleofthebits.org/lyceum/View/tracker#Linux
* https://woolyss.com/tracking.php.html
* https://woolyss.com/tracking-trackers.php
* https://trackerbase.blogspot.com
* https://wiki.thingsandstuff.org/Tracker

**Comment by OPNA2608** [comment]
> - [ ] `bambootracker`

I have been sitting on a derivation for BambooTracker since the big Qt infrastructure awhile ago, been meaning to open a PR for it once the ever-approaching 0.4 release is out. I can open a PR for the current state later today, you can give it a look if you want.

> - [ ] `0cc-famitracker`

FT and any fork thereof is Windows-only, though some forks improve Wine support by alot. I don't think packaging Wine-based applications is something we do in nixpkgs.
In any case, you should give [j0CC-FamiTracker](https://github.com/jimbo1qaz/j0CC-FamiTracker) a look instead for your personal use.

Something that's missing from your list would be [CheeseCutter](https://github.com/theyamo/CheeseCutter), which is stuck waiting for GDC to get packaged (https://github.com/NixOS/nixpkgs/pull/69144 needs to get merged first) - I tried building it with the other Dlang compilers already in nixpkgs but it relies on GDC's support of legacy syntax to compile.

**Comment by deliciouslytyped** [comment]
Tangentially related, if anyone is interested in this issue, they may also be interested in the various JACK related issues.

**Comment by fgaz** [comment]
@OPNA2608 thanks for the interest! I added your prs and cheesecutter to the list

> FT and any fork thereof is Windows-only

oops, I thought I filtered out all of those, thanks

**Comment by OPNA2608** [comment]
> - [ ] `deflemask`?

While it's a very popular chiptune tracker, DefleMask is closed-source and far from FOSS-happy. [See the VICE emulator's Hall of Shame section on DefleMask & reSID.](https://vice-emu.pokefinder.org/index.php/Hall_of_Shame#Deflemask) The latest distributed non-reSID binary could be patched & wrapped but I get abit of a stomach ache thinking about it.

**Comment by fgaz** [comment]
That wasn't intended, thanks again for catching it! I removed it and added a bunch more from other repos and some nice resources I found ([1](http://battleofthebits.org/lyceum/View/tracker#Linux) [2](https://woolyss.com/tracking.php.html) [3](https://woolyss.com/tracking-trackers.php) [4](https://trackerbase.blogspot.com)).

37 trackers! That's a lot!

**Comment by OPNA2608** [comment]
> - [ ] `bambootracker`

Merged! Can finally be ticked off the list. :smile: 

---

- [ ] `snestracker` { - [H](https://github.com/bazzinotti/snestracker) -}

Quite new, and I'm talking to the dev about what can be done to improve packaging. It does some *awful* things:

- Compiling, including and unconditionally expecting `unrar` at runtime
- In-tree tools with unclear/conflicting licensing
- Some path detecting problems making it necessary for the binaries to reside in `$out/share/snestracker/`

Once these problems are solved, I plan to open a PR.

**Comment by fgaz** [comment]
Great! I Updated the list

> Compiling, including and unconditionally expecting unrar at runtime

ow. that's unfree... what does it need it for?
The project looks cool though

**Comment by OPNA2608** [comment]
Really only for convenience, apparently packs of SPC files (SNES music code) are usually in the RAR format. I have open issues for those problems:

- licensing: bazzinotti/snestracker#59
- path: bazzinotti/snestracker#60
- problems with our default hardening flags: bazzinotti/snestracker#68

**Comment by fgaz** [comment]
@OPNA2608 should I also ping you in my prs?

**Comment by OPNA2608** [comment]
Feel free to do so!

**Comment by OPNA2608** [comment]
Can you do me a favour and put

>   [ ] Fix macOS build

under CheeseCutter? I have been meaning to tackle that for awhile but never got around to test it properly and keep forgetting about it.

There's an updated commit on the repo that introduces Darwin-related compilation fixes and the SDL loading module requires some patching on our side to handle our non-standard path straight to the dylib, as opposed to an SDL.framework in the Library.

I'll ~~hopefully~~ remember it and make a PR later this week.

**Comment by fgaz** [comment]
Done!
I wonder if there's a way to let you edit the OP too

**Comment by OPNA2608** [comment]
I don't think there is.

For reference, a failed darwin evaluation on Hydra: https://hydra.nixos.org/build/126193708

**Comment by OPNA2608** [comment]
- [ ] `ptcollab` {- [H](https://yuxshao.github.io/ptcollab/) -}

Talked to the developer abit to fix some installation problems over at https://github.com/yuxshao/ptcollab/issues/3, will make a PR after testing the online part with some friends.

**Comment by fgaz** [comment]
Added to the list :+1:

**Comment by fgaz** [comment]
I found another great resource: https://wiki.thingsandstuff.org/Tracker

**Comment by dukzcry** [comment]
@OPNA2608 
I really liked BambooTracker for these features:
1) Modern interface
2) MIDI keyboard support and improvisation mode
3) FM synthesis
What other trackers with same features would you recommend? Except 3rd point of course, since its quite niche

**Comment by fgaz** [comment]
@dukzcry if I remember correctly, of those packaged soundtracker has the modern interface and midi support, and klystrack has all three but in limited form

**Comment by fgaz** [comment]
I merged all resources and there are ~60 entries now... There's a lot of cool stuff in there! (and also a fair amount of abandoned projects)

**Comment by OPNA2608** [comment]
- [ ] `exotracker` {- [H](https://gitlab.com/exotracker/exotracker-cpp) -}

---

> - [x] hivelytracker {R H #95797}
>   - [ ] unbreak darwin (relevant comments in the init pr)

I remembered this was still open. I hacked together a Darwin build, derivation needs cleanup & some more `lib.optional*` usage to not break Linux building. Has some problems like missing graphics on my end that may be a problem with my system, or with the packaging. But at least it builds & doesn't crash, so it's an improvement I guess? :sweat_smile:.

![Screenshot_macOS_2021-04-17_22:32:20](https://user-images.githubusercontent.com/23431373/115126076-d9bb2f00-9fcc-11eb-9746-273a425c5a7a.png)

Don't have the time rn to flip between machines and fix everything up, but I'll review a PR if you clean it up & CC me.

<details>
  <summary>Clickme for patch</summary>

```patch
@@ -3,6 +3,7
 , fetchFromGitHub
 , pkg-config
 , makeWrapper
+, xcbuildHook
 , SDL
 , SDL_image
 , SDL_ttf
@@ -24,34 +25,63 stdenv.mkDerivation rec {
   nativeBuildInputs = [
     pkg-config
     makeWrapper
-  ];
+  ]
+  ++ lib.optional stdenv.hostPlatform.isDarwin xcbuildHook;
 
   buildInputs = [
     SDL
     SDL_image
     SDL_ttf
-    gtk2
-    glib
+    # gtk2
+    # glib
   ];
 
-  makeFlags = [
-    "-C sdl"
-    "-f Makefile.linux"
-    PREFIX=$(out)"
-  ];
+  # makeFlags = [
+  #   "-C sdl"
+  #   "-f Makefile.linux"
+  #   PREFIX=$(out)"
+  # ];
 
   # TODO: try to exclude gtk and glib from darwin builds
   NIX_CFLAGS_COMPILE = [
-    "-I${SDL}/include/SDL"
+    "-I${SDL.dev}/include/SDL"
     "-I${SDL_image}/include/SDL"
     "-I${SDL_ttf}/include/SDL"
-    "-I${gtk2.dev}/include/gtk-2.0"
-    "-I${glib.dev}/include/glib-2.0"
+    # "-I${gtk2.dev}/include/gtk-2.0"
+    # "-I${glib.dev}/include/glib-2.0"
   ];
 
+  preBuild = ''
+    cd sdl/osx/xcode
+    # xcode project expects SDL Frameworks for linking, we only have dylibs
+    substituteInPlace Hivelytracker.xcodeproj/project.pbxproj \
+      --replace 'lastKnownFileType = wrapper.framework; name = SDL.framework; path = /Library/Frameworks/SDL.framework' 'lastKnownFileType = "compiled.mach-o.dylib"; name = libSDL.dylib; path = ${SDL}/lib/libSDL.dylib' \
+      --replace 'lastKnownFileType = wrapper.framework; name = SDL_image.framework; path = /Library/Frameworks/SDL_image.framework' 'lastKnownFileType = "compiled.mach-o.dylib"; name = libSDL_image.dylib; path = ${SDL_image}/lib/libSDL_image.dylib' \
+      --replace 'lastKnownFileType = wrapper.framework; name = SDL_ttf.framework; path = /Library/Frameworks/SDL_ttf.framework' 'lastKnownFileType = "compiled.mach-o.dylib"; name = libSDL_ttf.dylib; path = ${SDL_ttf}/lib/libSDL_ttf.dylib'
+    substituteInPlace ../../../hvl2wav/Makefile \
+      --replace 'gcc' '${stdenv.cc.targetPrefix}cc'
+  '';
+
   # Also build the hvl2wav tool
   postBuild = ''
-    make -C hvl2wav
+    make -C ../../../hvl2wav
+  '';
+
+  installPhase = lib.optionalString stdenv.hostPlatform.isDarwin ''
+    runHook preInstall
+    install -Dm755 Products/Release/Hivelytracker.app/Contents/MacOS/Hivelytracker $out/lib/Hivelytracker
+    cp -R Products/Release/Hivelytracker.app/Contents/Resources/* $out/lib/hivelytracker
+    # Crashes if fonts are not in ttf/ subdirectory
+    mkdir $out/lib/hivelytracker/ttf
+    mv $out/lib/hivelytracker/{*.,}ttf
+    mkdir $out/bin
+    runHook postInstall
   '';
 
   postInstall = ''
@@ -59,11 +89,11 @@ stdenv.mkDerivation rec {
     # Ideally we should patch the sources, but the program can't open
     # files passed as arguments anyway, so this works well enough until the
     # issue is fixed.
-    wrapProgram $out/bin/hivelytracker \
-      --run "cd $out/share/hivelytracker"
+    makeWrapper $out/lib/hivelytracker/Hivelytracker $out/bin/hivelytracker \
+      --run "cd $out/lib/hivelytracker"
 
     # Also install the hvl2wav tool
-    install -Dm755 hvl2wav/hvl2wav $out/bin/hvl2wav
+    install -Dm755 ../../../hvl2wav/hvl2wav $out/bin/hvl2wav
   '';
 
   meta = with lib; {
@@ -83,7 +113,6 @@ stdenv.mkDerivation rec {
     license = licenses.bsd3;
     platforms = platforms.all;
     maintainers = with maintainers; [ fgaz ];
-    broken = stdenv.isDarwin; # TODO: try to use xcbuild
   };
 }
```

</details>

---

> > FT and any fork thereof is Windows-only
> 
> oops, I thought I filtered out all of those, thanks

Actually, [nesicide](https://github.com/christopherpow/nesicide) includes a version of FamiTracker that's cross-platform, via an MFC-over-Qt compatibility layer. It [has](https://github.com/christopherpow/nesicide/issues/75#issuecomment-812541476) [some](https://github.com/christopherpow/nesicide/issues/74) [problems](https://github.com/christopherpow/nesicide/issues/73) but it can launch and produce some sound. I haven't tried packaging the whole IDE yet though.

![grafik](https://user-images.githubusercontent.com/23431373/115126353-bee9ba00-9fce-11eb-8a21-43ae43b016e2.png)

**Comment by OPNA2608** [comment]
I picked afew projects from the list that I've heard of before / seemed interesting and hacked-together overlays:

#### Chibitracker

Requires some patching to build for x86_64-linux, builds fine out-of-the-box for i686-linux (via `pkgsi686Linux.chibitracker`).

[package-chibitracker.txt](https://github.com/NixOS/nixpkgs/files/6695223/package-chibitracker.txt)

![grafik](https://user-images.githubusercontent.com/23431373/122936667-a05ac300-d371-11eb-8a53-78cb585b8a82.png)

i686 versions works mostly fine, only crashes when exiting. x86_64 can't load a module most of the time and crashes with a bus error. It's an interesting little project but it seems abandoned and abit broken, not sure if it makes sense to include this one.

#### AdlibTracker2

x86_64 support requires replacing x86-exclusive inline assembly with equivalent x86_64 assembly… :confused: 

[package-adlibtracker2.txt](https://github.com/NixOS/nixpkgs/files/6695228/package-adlibtracker2.txt)

Compiles on x86_64-linux but crashes immediately. This may be "normal" however because I heard that the AUR's package (which installs the prebuilt Linux version) also crashes for some people in a similar fashion. Not sure what's up with that.

```
  Sample buffer size: 1024 samples (requested 2048)
  Sampling rate: 49716 Hz (requested 49716)
Reading configuration file ... not found!
An unhandled exception occurred at $00000000004B200E:
EAccessViolation: Access violation
  $00000000004B200E
```

i686-linux doesn't build because i686 fpc fails to build for me. The project might still be active.

#### Arkostracker2

The project is still binary-only for now but I tried to package it regardless.

[package-arkostracker2.txt](https://github.com/NixOS/nixpkgs/files/6695244/package-arkostracker2.txt)

It "builds" but fails on me when it tries to draw via libGL. Maybe this works on an actual NixOS machine.

```
bt1cn@pcclu01:/dev/shm$ nixGL ./result/bin/ArkosTracker2 
./result/bin/ArkosTracker2() [0x7c8ce7]
./result/bin/ArkosTracker2() [0x70c009]
./result/bin/ArkosTracker2() [0x7bab0d]
/nix/store/sbbifs2ykc05inws26203h0xwcadnf0l-glibc-2.32-46/lib/libpthread.so.0(+0x13700) [0x7f17fd936700]
/nix/store/hpnazqkp4zbm2pkp1xj4whmld2zhwv0r-libglvnd-1.3.3/lib/libGLX.so.0(+0xa415) [0x7f17fd30b415]
/nix/store/hpnazqkp4zbm2pkp1xj4whmld2zhwv0r-libglvnd-1.3.3/lib/libGLX.so.0(glXChooseVisual+0x13) [0x7f17fd304633]
./result/bin/ArkosTracker2() [0xa67d16]
./result/bin/ArkosTracker2() [0x9620d7]
./result/bin/ArkosTracker2() [0x9a5147]
./result/bin/ArkosTracker2() [0x6c4f53]
./result/bin/ArkosTracker2() [0x70cf1b]
./result/bin/ArkosTracker2() [0x85984a]
./result/bin/ArkosTracker2() [0x4e8b1b]
/nix/store/sbbifs2ykc05inws26203h0xwcadnf0l-glibc-2.32-46/lib/libc.so.6(__libc_start_main+0xed) [0x7f17fd3c9ded]
./result/bin/ArkosTracker2() [0x4eace9]
/home/bt1cn/.nix-profile/bin/nixGL: line 6:  8477 Killed                  "$@"
```

Last release was on March 21, 2021 so it's very much in development still.

#### psycle

The `qpsycle` project isn't available on their SVN repository anymore. There is a new `cpsycle` rewrite that's in active development but it only has a build script for Windows. `psycle-core` etc are still available and buildable on Linux, albeit with some fixes.

[package-psycle.txt](https://github.com/NixOS/nixpkgs/files/6695245/package-psycle.txt)

This is only a command-line-only player however, and so far I've been unable to get any sound out of it. Psycle modules embed the names of the plugins they need… with a DLL extension. I don't know if that affects the plugin loading. I saw in strace that it also tries to find a config.xml at some point. ALSA also doesn't seem to work & causes an abortion.

#### 1tracker

I gave this a quick attempt. I think it's trying to test something by writing to the nix store at runtime - which obviously fails - so it instantly errors. I'll try to look into this more. I think it's still active.

[package-1tracker.txt](https://github.com/NixOS/nixpkgs/files/6695251/package-1tracker.txt)

(Excuse the monitor photo, any button press will close the window)
![IMG_20210622_134625](https://user-images.githubusercontent.com/23431373/122946458-a8b6fc00-d379-11eb-931b-cdc32a398e6d.jpg)

---

[ZorroTracker](https://github.com/ZorroTrackerDev/ZorroTracker) is a very new, WIP and active project (since there's some minor financial backing behind it) but it's Electron-based. I have no clue how to build that from source and gave up on it.

**Comment by fgaz** [comment]
Wow, nice job!

> AdlibTracker2

I also tried building it but gave up shortly after. Does the cross32 makefile help?

---

> 1tracker

I tried stracing it and it looks like it's missing some files: `$out/lib/1tracker/engines/{test.1te,list,hash}`.

If you add `test.1te` (even just by copying one of the other engines) it starts, but fails if you try to select a different engine.

If you write the list of engines in the `list` file, the selection works and you can make some sounds. I have yet to figure out the specific format though. I tried one filename per line and only the first entry seems to work.

I have no idea what the `hash` file does.

**Comment by OPNA2608** [comment]
>  okay, the cache files are a biit more complicated than I thought:

.1te files seem to be C/C++ source code, with a function `void Info(void)` that prints the title & about stuff from `list` (i.e. `ZX|1BIT|AntEater` etc). Maybe we could write a bash script that scans and collects the engines' filename, title and about texts to build the `list` file.

**Comment by fgaz** [comment]
> .1te files seem to be C/C++ source code

[angelscript](http://angelcode.com/angelscript/) actually! (which looks very nice, I might use it for some of my own projects...)
so we could use the `angelscript` package in nixpkgs to run them

**Comment by fgaz** [comment]
Though the best long-term solution is probably to ask the author to use XDG for cache and configuration (and maybe to pick up additional engines). Should we contact them?

**Comment by OPNA2608** [comment]
> [angelscript](http://angelcode.com/angelscript/) actually! (which looks very nice, I might use it for some of my own projects...)
> so we could use the `angelscript` package in nixpkgs to run them

I think devendoring angelscript would be a good idea if it's feasible, yeah.

> Should we contact them?

We can certainly ask! :smile: 

---

I patched in SDL_GetPrefPath and wrote a wrapper that copies the example cfg to the appropriate place if it's missing. It should work "from the store" now. LMK what you think.

[package-1tracker.txt](https://github.com/NixOS/nixpkgs/files/6702660/package-1tracker.txt)

**Comment by fgaz** [comment]
https://github.com/djdiskmachine/LittleGPTracker is a LGPT fork with a more active maintainer. I may switch the package to it if https://github.com/djdiskmachine/LittleGPTracker/issues/71 is resolved.

P.S.: wow, 2 years since the last tracker addition! Time flies! I need to finish that tiatracker pr...

**Comment by ScottFreeCode** [comment]
If I wanted to get QTFamitracker (or any other Linux-compatible Famitracker fork, if there are any) in, how involved is that likely to be? I've never packaged a QT app for Nix before, but I've done a little bit of C building in Nix and used to use C and C++ for whole projects back in the day (Nix can't be more of a slog than CMake's multiple steps and interminable build time).

**Comment by fgaz** [comment]
@ScottFreeCode  Qt isn't too bad, see [the relevant section in the manual](hhttps://nixos.org/manual/nixpkgs/unstable/index.html#sec-language-qt). `qmake` or `cmake` is used automatically if you put it in `nativeBuildInputs`.

**Comment by teesh3rt** [comment]
I do not know how to maintain a package, but I have packaged snibbe as my first derivation
[here it is i guess](https://github.com/teesh3rt/snibbenix)

**Comment by coderofsalvation** [comment]
+1 for adding more miditrackers to the repo (tutka, jacker, ttrk or attrk, fltracker, shaketracker)

Btw. 'player pro' would be so amazing to get up and running. I've tried to compile it 2 years ago I think [but gave up as I realized I had an old mac lying around]. It gained quite a cult-following ever since Aphex Twin released this video: https://www.youtube.com/watch?v=inUOTPt2mLk

**Comment by coderofsalvation** [comment]
another suggestion: drop ttrk in favor of attrk (reason: ttrk relies on OSS & /dev/midi* symlinks, while attrk is an updated version of ttrk relying on pure ALSA + various extra features/fixes)

**Comment by bandithedoge** [comment]
I've packaged Protrekkr (@hitchhikr fork) in my NUR repo: https://github.com/bandithedoge/nur-packages/blob/master/pkgs/protrekkr/default.nix. I'm happy to upstream this to nixpkgs if there is interest.

**Comment by coderofsalvation** [comment]
great news: someone nix-packaged tutka here: https://github.com/TheRedstoneDEV-DE/tutka-qt6

Tutka is quite an interesting and mature midi-tracker.
I really hope we can submit it to nixpkgs as currently there's no true MIDI tracker in there afaik ❤

**Comment by coderofsalvation** [comment]
> UPDATE: trying to nix-compile shaketracker:

https://github.com/coderofsalvation/shaketracker/commit/2e76698f31d5a7018cc82d62398db73d98670021

I got various old compiler shenanigans out of the way, unfortunately I got stuck on the gtk dependency, as mentioned in the README.md (Feel free to have a stab at it).
iirc shaketracker had an interesting unique concept of 'variables', so would be awesome to have as a nixpkg at some point:

![](https://dl.acm.org/cms/attachment/6ec80b08-a915-4357-a03a-05960d5dcc44/4349f4.jpg)

**Comment by fgaz** [comment]
> I plan on submitting my changes in that fork to upstream, so we wouldn't need to add a second package just for qt6 support.

that'd be ideal!

> Should I create a package.nix for the current upstream right now and submit it to nixpkgs or should I only start submitting it to nixpkgs once my changes have been accepted?

As you prefer

> I'm just a bit unsure since my last contribution to nixpkgs took quite a while (6 months) and I don't want to waste (a reviewers) time with a PR I'd have to change once upstream changes got approved

Usually the difficult part is getting the attention of a reviewer/committer. You can link your relevant PRs here and I'm sure they'll get merged quickly :)
