### ISSUE TITLE
Xpra tracking issue

### ISSUE THREAD

**Issue by mjlbach** [NixOS/nixpkgs#86164]
**Describe the problem** 

Xpra has been in various stages of broken on NixOS for awhile. There are several ongoing bugs which may be interrelated, and are actively in the process of being fixed.

Currently, xpra can be started locally with the flags 

```
xpra start --daemon=no --fake-xinerama=no.
```

**cc:**
@offlinehacker

**Unpatched fixes:**
* [ ] xpra cannot run in daemon mode
* [ ] xpra when launched remotely cannot be found on path

**Fixes with PR:**
* [ ] xpra cannot launch with fake xeinerama #85718 
* [x] xpra crashes due to Xorg failure #83853

**Comment by lourkeur** [comment]
wrt libfakeXinerama license  #43716, we're good thanks to 0bc74681221f3eeb616b0842c8ce6a49a8b

wrt libfakeXinerama phases #28910, I just tested and I think it's ok to just remove the line. Should I put that into my PR?

**Comment by mjlbach** [comment]
I think they need to update #43716 since it was out of date anyways... I'm not sure about the importance of #28910, but it seems like minor impact but good for compliance with other packages.

**Comment by lourkeur** [comment]
OK, good news: I was able to successfully `xpra start ssh://$server` by combining #87982 and #87985.

**Comment by mjlbach** [comment]
Perfect! I just unbroke pycuda in #88031, and it seems like nvenc might worth with xpra now

**Comment by mjlbach** [comment]
I updated the open issues, we should probably close all of the ones listed under "Open issues that should be closed." and merge #87985 and #88526. Almost there!

**Comment by mjlbach** [comment]
With #87985 merged, we should close #14540 #63631 #30822 #24652

**Comment by samueldr** [comment]
I have closed this particular set of issues. Thanks for your work :).
