### ISSUE TITLE
Move nss modules into NixOS modules

### ISSUE THREAD

**Issue by dasJ** [NixOS/nixpkgs#86350]
## Issue description

Since #85998 was merged, every NixOS module can add own modules into nsswitch.
This allows moving the items into their corresponding modules and clean up the nsswitch module.
edddc7c82a848f1b1f23344a338b5d56b38178c0 demonstrates this with sss.

Modules which are still mentioned in [nsswitch.nix](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/config/nsswitch.nix):
- [x] systemd (mymachines resolve myhostname systemd) @andir @edolstra  @flokli #86940
- [ ] avahi (mdns_minimal mdns) @WilliButz @ljani #87016
- [x] googleOsLogin (cache_oslogin oslogin) @flokli @aanderse #86409
- [ ] ldap (ldap) @aanderse @flokli #87016
- [ ] nsswins (nsswins) @bjornfor @Izorkin #87016

cc @ajs124

**Comment by flokli** [comment]
#87016 cleans up the rest of these modules.
