### ISSUE TITLE
Haskell: to-do list of potentially out-dated overrides

### ISSUE THREAD

**Issue by peti** [NixOS/nixpkgs#86500]
The [krank](http://hackage.haskell.org/package/krank) utility found the following references to closed Github issues in our Haskell override files. The fact that those bugs are closed upstream is an indication that we can probably remove the override, but that needs to be checked because upstream closes issues for all kinds of reasons, not all of them meaning that the issue was actually fixed. Furthermore, there appear to be some URLs to bugs that don't exist anymore (see end of this list).

Please, everyone, help fix these issues by checking some entries of that TODO list and, if applicable, create a pull-request to submit the fix. Then also please check the TODO entry here so that it won't be checked again by someone else.

Please submit your changes against the `haskell-updates` branch, not `master`. If you feel like it, please ping @peti and @nh2.

**Comment by peti** [comment]
## Overrides with closed issues attached

- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1037 https://github.com/haskell-servant/servant-auth/issues/113
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1061 https://github.com/haskell-hvr/hgettext/issues/14
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1085 https://github.com/ku-fpg/blank-canvas/issues/73
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1099 https://github.com/haskell/hoopl/issues/50
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1126 https://github.com/danfran/cabal-macosx/issues/13
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1129 https://github.com/DanielG/cabal-helper/issues/59
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1145 https://github.com/phadej/tdigest/issues/30
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1176 https://github.com/haskell/haddock/issues/979
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1224 https://github.com/erikd/hjsmin/issues/32
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1227 https://github.com/blamario/grampa/issues/19
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1269 https://github.com/Daniel-Diaz/HaTeX/issues/144
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L127 https://github.com/haskell/haddock/issues/979
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L132 https://github.com/haskell/vector/issues/47
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L133 https://github.com/haskell/vector/issues/138
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1386 https://github.com/bergmark/feed/issues/43
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L1416 https://github.com/phadej/binary-orphans/issues/45
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L169 https://github.com/jputcu/serialport/issues/25
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L187 https://github.com/decomputed/euler/issues/1
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L224 https://github.com/haskell-nix/hnix/issues/514
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L243 https://github.com/timjb/aeson-schema/issues/9
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L289 https://github.com/bsl/GLFW-b/issues/50
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L399 https://github.com/kim/snappy-framing/issues/3
- [ ] https://github.com/NixOS/nixpkgs/blob/4b942e88cb4907037912b63aa030169bca95bc5e/pkgs/development/haskell-modules/configuration-common.nix#L414 https://github.com/cgaebel/stm-conduit/issues/33

**Comment by cdepillabout** [comment]
> nixpkgs/pkgs/development/haskell-modules/configuration-nix.nix
> Line 685 in 4b942e8
> # https://github.com/spacchetti/spago/issues/510 
> purescript/spago#510

I'm not sure exactly what to do about this.

The upstream issue was closed because it is meant to work the way they have it working, so it is something we have to workaround in nixpkgs.  I think it is nice to have the issue linked there to give some context why we have to do this hacky thing.

Although if you'd like to remove the issue link, I'd be fine with that as well.  What we are doing should be explained in our code as well.

I checked this off, given that I think we should keep in the link, but if you want to keep it unchecked, please feel free to uncheck this.

**Comment by nh2** [comment]
@cdepillabout I think that is fine. The point of this effort is to find things that need to be done; this linked issue is only informational and nothing needs to be done, so checking it off is right.

In the future we probably want to use some textual marker to exclude this type of link from `krank`.

**Comment by Anton-Latukha** [comment]
* cross `hnix` https://github.com/NixOS/nixpkgs/pull/89513

Other packages from that PR seem not be mentioned here.

**Comment by Anton-Latukha** [comment]
* `statistics` is free from overrides: #91299

**Comment by Anton-Latukha** [comment]
The lot of linked reports and PRs are closed/merged, but Nixpkgs awaits on project release a package on Hackage.

So since those reports/PRs are solved, they should be replaced with relevant info.

So I adopted the message:

```
# 2020-06-22: NOTE: > 0.4.0 => rm Jailbreak
```

**Comment by nh2** [comment]
Probably still relevant given the many recent PRs.

**Comment by svmhdvn** [comment]
I'm happy to continue gradually working on this, I will be getting a little more time to put into this soon.

**Comment by Jake-Gillberg** [comment]
It looks like idris 1.3.3 is broken and needs an older version of megaparsec.

The issue referenced above: https://github.com/idris-lang/Idris-dev/issues/4826 is closed as "won't fix".

This override was removed in https://github.com/NixOS/nixpkgs/commit/4b2b6ce65e3894391ee6a42b40fe5b6016f1592f. I believe this broke the package.

Idris is failing to build with the message:
```
  Setup: Encountered missing or private dependencies:
  aeson >=0.6 && <1.5, haskeline ==0.7.*, megaparsec >=7.0.4 && <9
```
I tried fixing this package (https://github.com/Jake-Gillberg/nixpkgs/commit/5c63f2499e45bd6e8a0a8186edf6e699b5200484) by re-adding the relevant overrides, but it looks like specified megaparsec versions are not found.

I'd be happy to test and submit a working pull request if I could get some guidance on how to meet the listed megaparsec version.

**Comment by Anton-Latukha** [comment]
BTW. Stackage currently removed the upper bound on the `hnix-store-core` that is still unmaintained there. We by the team voted for removal, so it would happen eventually, https://github.com/commercialhaskell/stackage/issues/5872. I do not know their schedules & all procedure of how Nixpkgs inherits with LTS & Nightly presence. But boundary removal means that `hnix-store-core` hardcode version derivation overrides soon would be out-dated, which this thread is about.

**Comment by Anton-Latukha** [comment]
> I'm happy to continue gradually working on this, I will be getting a little more time to put into this soon.

You did great work, thank you.

**Comment by cdepillabout** [comment]
@Jake-Gillberg You can generate `megaparsec_8_0_0`  by adding a line to the following list:

https://github.com/NixOS/nixpkgs/blob/4dfe07dadac24ae00881b6ab808d8f3627340511/pkgs/development/haskell-modules/configuration-hackage2nix.yaml#L2705-L2726

If you send a PR to the `haskell-updates` branch adding this line and it is merged in, then the next time the re-generation script runs, it will create a `megaparsec_8_0_0` derivation for you.

Please feel free to open up an issue or PR to further discuss this.

**Comment by Anton-Latukha** [comment]
Stackage: `hnix-store-core`, which is in Nightly & LTS:

 `juhp` in https://github.com/commercialhaskell/stackage/issues/5872#issuecomment-783303809 
> I have blocked the package now.
> If you need action for LTS please open a separate issue for that as mentioned.

So the situation is changed for the package. Over time it would go through the process of a proper graceful removal, and `hnix` infrastructure would scale back to Hackage. So all of our "guilty as charged" overrides would be cleaned over the nearest time.

**Comment by cdepillabout** [comment]
@maralorn @sterfield @expipiplus1 Since none of us is really maintaining this list or this issue, how about just closing it out?

In theory I think something like this issue is a neat idea, but I don't think it makes sense to keep this issue open without anyone actually going through and keeping it up to date.

**Comment by maralorn** [comment]
I think we should in general strive for more hygiene like that, but it’s not very high priority and I guess we should run krank new and open a new issue anyways.

**Comment by maralorn** [comment]
Sorry for the noise @sterfield, we meant @sternenseemann.

**Comment by sternenseemann** [comment]
A regularly updated krank-based report is available at <https://krank.sterni.lv/mirror/nixpkgs/haskell-updates.html> now. Feel free to report any issues to me directly. Can't make any guarantees w.r.t. availabilty etc., obviously.
