### ISSUE TITLE
20.09 Release notes

### ISSUE THREAD

**Issue by jonringer** [NixOS/nixpkgs#95765]
This thread is for any release-worthy notes which may have not have made their way into https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2009.xml yet.

Please leave a summary and any relevant links to the items. I will try and go through them before the release to ensure the notes are in order.

List to make items easier to track:
- [x] Python35 was removed
- [x] Agda changes
- [x] Amdvlk can be added to `hardware.opengl.extraPackages`
- [x] Cinnamon desktop was added
- [x] Fontconfig was bumped, and reworked on NixOS
- [x]  Nvidia Optimus/Prime is fully usable now
- [ ]  Core changes (gcc, glibc, linux kernel, mesa, openssl) #101444
- [ ]  Desktop changes (plasma, kdeApplications, gnome, pantheon) #101444
  - [ ] Maybe include some others? (cinnamon, xfce, lxqt)? #101444 
- [ ] Capture signifcant changes https://github.com/NixOS/nixos-search/pull/206 #101444

**Comment by jonringer** [comment]
Python35 was removed https://github.com/NixOS/nixpkgs/pull/95305

**Comment by alexarice** [comment]
agda infrastructure was reworked quite heavily https://github.com/NixOS/nixpkgs/pull/76653 . This has some documentation but I'm not sure if it needs release notes as well.

**Comment by jonringer** [comment]
@alexarice I'm sure agda users would appreciate it

**Comment by alexarice** [comment]
@jonringer did you want me to make a pull request?

**Comment by jonringer** [comment]
@alexarice  That would be great :+1:, if you're feeling up to it

**Comment by alexarice** [comment]
@jonringer have no idea how to use docbook but I'll give it a go

**Comment by jonringer** [comment]
That makes two of us, but I wouldn't expect it would take very long to learn enough to create release notes. Plus there's already many commits which demonstrate how to do additions.

**Comment by danieldk** [comment]
I should probably add a blurb to *other notable changes* about the addition of part of the ROCm stack. @Flakebi do you think it is worthwhile adding something about amdvlk as well. If so, I could add an item summarizing all new features on the AMD GPU front.

**Comment by Flakebi** [comment]
A short mention that amdvlk can now be added to `hardware.opengl.extraPackages` is probably worth it. Thanks!

**Comment by worldofpeace** [comment]
We updated fontconfig https://github.com/NixOS/nixpkgs/pull/73795 and changed an integral way in how fontconfig is setup on nixos https://github.com/NixOS/nixpkgs/pull/95358. The latter PR isn't merged yet but I believe it's going to be.

**Comment by mkg20001** [comment]
If not already added, a note about cinnamon desktop 4.6 now being available

**Comment by jonringer** [comment]
Release notes are able to be added even after branch-off, however, they will need to follow backporting conventions and first be merged into master

**Comment by deliciouslytyped** [comment]
It's the source of this is not immediately clear, but if it's introduced in this release I think it warrants a note: https://github.com/NixOS/nixpkgs/issues/96753#issuecomment-696019991  "Deprecate boot.cleanTmpDir?"

(Maybe we should just start pasting the systemd release notes in the release too? :P)

**Comment by alexarice** [comment]
Not sure if this the right place to ask this as this isn't technically release notes but would be good to get #98084 merged and backported as it has fixes for agda part of the manual

**Comment by jonringer** [comment]
I plan to write the release notes this weekend.

Unpinning to give "spotlight" to release blocking discussion in #95475

**Comment by Jiehong** [comment]
- Some packages have changed names (ex: `source-han` fonts are no longer split by language).
- Emacs 25Packages dropped

Is there a migration guide/tool usually, or are people supposed to find out from the release note + updating their channel, and trying to build their environment manually?

**Comment by jonringer** [comment]
It should be available on the website, not sure in which way people typically consume the manual

**Comment by jtojnar** [comment]
Fontconfig in https://github.com/NixOS/nixpkgs/pull/100103

**Comment by copyread** [comment]
Nvidia Optimus/Prime is fully usable now, might be worth adding.

**Comment by worldofpeace** [comment]
> Nvidia Optimus/Prime is fully usable now, might be worth adding.

Could you link the PR that did this? (and maybe ping the author as well)

**Comment by copyread** [comment]
> > Nvidia Optimus/Prime is fully usable now, might be worth adding.
> 
> Could you link the PR that did this? (and maybe ping the author as well)

https://github.com/NixOS/nixpkgs/pull/66601

@eadwu

**Comment by jonringer** [comment]
all items have been marked as done

**Comment by worldofpeace** [comment]
Was plasma noted and notable updates?

**Comment by jonringer** [comment]
-_- you're right, we should have core and desktop changes like we had for 20.03
